### ISSUE TITLE
Suggestion: ahelping certain words smites you

### ISSUE THREAD

**Issue by AnthonyJNgo** [HippieStation/HippieStationdeprecated2020#10011]
If someone ahelps "@everyone, @anyadminname, @admin, etc." they should be smited and have their ahelp verb taken away for at least 5 minutes.

This will ensure that people do not use this for retarded reasons.

**Comment by ghost** [comment]
this sounds gay and antifun bruh

**Comment by bardofrage** [comment]
+1

**Comment by k-k-karma** [comment]
i'm the one who figured this out and told everyone but just punish them yourself.

**Comment by AnthonyJNgo** [comment]
If we were on to punish them ourselves then they probably wouldnt be pinging everyone. Implementing this is a deterrent to nerds. They know if they ping @everyone or any admins they will instantly get smited and have their ahelps muted for a few minutes. Guarantee people will stop pinging unless they have an actual ahelp that they truly believe they are justified in pinging for.

**Comment by DaydreamPuppeh** [comment]
-1 I actually enjoy the @everyone in ahelps. The @specificadmin can fuck right off though

**Comment by Maroonenahmoron** [comment]
If it’s something urgent like mass grief or the server lagging due to someone spamming something then it should be justified by pinging all online admins on discord

**Comment by AnthonyJNgo** [comment]
If it's justified then they'll ahelp it, and an admin will (hopefully) come on, heal them since it's a valid ahelp if needed and then take care of the issue.

The smite and temporary removal of ahelp function is just to prevent people from spamming or using @everyone for dumb reasons.

**Comment by ghost** [comment]
You should add a command in discord for smite, not instantly smite, because @everyone could be useful like DDOS, Mass grief or things like that.
