### ISSUE TITLE
Change Null_Crate cost to 10k

### ISSUE THREAD

**Issue by WarRage333** [HippieStation/HippieStationdeprecated2020#10024]
TG gutted every single way of obtaining money for cargo fast.

I legit never see people buy those.

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by Maroonenahmoron** [comment]
I don’t see any other way of getting them apart from the questionable department funding. +1

**Comment by AliiTea** [comment]
This good to do? I can probably have it done in minute or so on my phone.

**Comment by ghost** [comment]
this sounds cool
on another note,  we need more contraband crates.  and we also need a security contraband seller where security can sell weed and drugs and weapons,  while also taxing the department where they originate,  botany/service with no botanists.  is station budget divided into departmental budget or is it completely separate?  getting the department budget in debt should syphon funds from all other departments equally or maybe prioritizing research
