### ISSUE TITLE
move the suggestions back to the forum

### ISSUE THREAD

**Issue by geylard** [HippieStation/HippieStationdeprecated2020#10032]
[Title]: # Your feature needs to have a good title. If you want an object added, the object's name would be a good title, and such. Use common sense.
suck my dick
[Implementation]: # How should the feature work out? What exactly is it supposed to do, in your initial idea? If an item, can it be crafted/found/bought and for what?
add suggestion part of forum back, the github is shit for its purpose.
[Why]: # How does your feature improve the game anyhow? Why should it be added?
you fucking idiot coders have lost sight of what function a suggestion forum is supposed to do. bringing it here has lowered the ease of accessibility for your superior, the player and lowers overall forum activity. you added some fucking stupid +1 and -1 system to player suggestions, when suggestions are better as loose ideas since non-coders usually wouldn't have a full grasp on implementation. 
 you might not remember, but the point of the suggestion forum is to toss ideas around at the coders rather than write out all the details for a feature and either code it yourself or force a coder to make it to your specifications. you've even corrupted the minds of the idiot new players like the fucking idiot baby known as "hideandseek" who now only serves as one of the cushions in your padded hugbox room. this is what happens when we let coders be admins, death to carbonhell. 
[Resources]: # Eventual assets such as icons and sounds which you have and want to suggest related to this feature.
eat my ass
# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by WarRage333** [comment]
I ded

**Comment by AnthonyJNgo** [comment]
-1, poor formatting.

**Comment by geylard** [comment]
look at this fucking idiot metagrudging me in all my suggestions in a vain attempt to earn coder respect from the mouth breathing asstards known as 'coders', truly the biggest villain of all time.

**Comment by ExpAntique** [comment]
-1, learn how to use a fucking template autist

**Comment by yobob591** [comment]
-1 I dont like the forms as much as github

**Comment by Carbonhell** [comment]
This isn't even a github issue. Closing
