### ISSUE TITLE
Easier Access to Clown Planet as Clown

### ISSUE THREAD

**Issue by scythanic00** [HippieStation/HippieStationdeprecated2020#10076]
[Title]: Easier Access to Clown Planet as Clown

[Implementation]: Give the Clown a role-restricted teleporter location for the "Clown Planet"

[Why]: Considering the shortness of each round on hippie, its almost impossible to actually take the time and find the "Clown Planet" location, I'd think the clown role itself is slightly valueless and has no real end-game goal other than to prank those on the station, so giving the Clown a role restricted teleporter location, would not only add to the way they can play out their pranks, but also give a different way to play the role. This doesn't mean clown has access to the teleporter room itself however, which could add to clown stealing an ID, or pushing to gain access for it

[Resources]: # Perhaps an ID scanning feature for the teleporter screen, allowing new locations to be opened up for specific roles, not just the clown, in the future

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by k-k-karma** [comment]
clown planet doesnt exist

**Comment by Dinopeaks** [comment]
time to make one!

**Comment by ghost** [comment]
make it only work if a clown puts a hand tele in his ass and fart and its also one way

**Comment by yobob591** [comment]
I like it tbh

**Comment by ghost** [comment]
@k-k-karma isn't there a clown planet ruin that can spawn in space?

**Comment by Manly-Dwarf** [comment]
Clown Planet ruin mysteriously disappeared from spess.

**Comment by Manu9123** [comment]
Then make it appear bruv ur an big big big admin you can do whatever you want bruv

**Comment by DaydreamPuppeh** [comment]
Bring back clown planet. All there is is a crashed clown space ship
