### ISSUE TITLE
Minimum Job Fulfillment

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#10171]
[Title]: Minimum job fulfillment 

[Implementation]: Basically,  to ensure good functioning of the station even on lowpop,  make the round only start if there's a Chief Engineer (to set up power),  Captain and Head of Security (to set up an authority backbone and prevent rampant chaos and free for all theft,  that comes later when shit gets wild).  Possibly,  if the round fails to start up 3 times,  force players to play as the needed jobs. And the system is overriden if there's less than 3 players? 

[Why]: Would incentivise better game habits and prevent lowpop being so shitty it doesn't get to highpop

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by BlueNothing** [comment]
Or would that be yellow-tiding?

**Comment by AnthonyJNgo** [comment]
-1. Crewmembers already get more access when there's a skeleton crew. We shouldn't force players into the HoS/CE/Captain roles because if/when they perform poorly they'll end up banned, and it isn't really their fault if they didn't pick the job in the first place.

If everyone signs up as Botanists and no one has enough sense to break into engineering and set up solar panels or engine then that's on them.

**Comment by DaydreamPuppeh** [comment]
-1. That would be shite

**Comment by ghost** [comment]
I'd be up for rewarding players for doing their jobs but definitely not punishing them otherwise

**Comment by Maroonenahmoron** [comment]
> We shouldn't force players into the HoS/CE/Captain roles because if/when they perform poorly they'll end up banned, and it isn't really their fault if they didn't pick the job in the first place.

As much as an avid believer that engineers need to **engine**er, there can be no good in forcing them to play if they don't know what they're doing.

**Comment by BlueNothing** [comment]
Not least because it will summon the yellow tide.

**Comment by AnthonyJNgo** [comment]
@HideAndSeekLOGIC

Crew objectives, already headmin approved.

**Comment by yobob591** [comment]
Crew objectives dont do shit, we need e c o n o m y.

though we shouldnt be forcing people to play jobs either.
