### ISSUE TITLE
make pod person a selectable roundstart race

### ISSUE THREAD

**Issue by RafRoq** [HippieStation/HippieStationdeprecated2020#10191]
why not

**Comment by DaydreamPuppeh** [comment]
-1. Roundstart races should stay as aesthetic changes only.

**Comment by RafRoq** [comment]
> -1. Roundstart races should stay as aesthetic changes only.

cant moths fly without gravity ? @DaydreamPuppeh

**Comment by DaydreamPuppeh** [comment]
Nope. Thats only on tg

**Comment by AnthonyJNgo** [comment]
-1 aesthetic changes only.

**Comment by ghost** [comment]
-1

**Comment by Maroonenahmoron** [comment]
-1, they're pretty much immune to hunger.
