### ISSUE TITLE
Revert cloning

### ISSUE THREAD

**Issue by AnthonyJNgo** [HippieStation/HippieStationdeprecated2020#10232]
Recert TG's awful changes to cloning. It doesn't fit the server and it just seems like massive grudge code from upstream, because almost all votes there were against it.

**Comment by Manly-Dwarf** [comment]
No, the PR was right in trying to tackle pre-scanning and autocloning. That's why it was merged. The problem is that the PR sucked. Like most everything /tg/ does, it has good intentions but is implemented laughably poorly.
Do not revert the PR, change the PR.

**Comment by Carbonhell** [comment]
Can anyone give some more info instead of just "revert x" or "change x" ffs

**Comment by WarRage333** [comment]
@Carbonhell 
TG changed it so when autocloners get upgraded you can't self scan yourself and get cloned when you die.

Everyone in tg and all of us pretty much hated the change and shit on it.

**Comment by Maroonenahmoron** [comment]
I've been seeing a lot of people trying to clone others and fail due to new initialization issues, fix this for the love of cloning!

**Comment by AnthonyJNgo** [comment]
@carbonhell

Honestly, just the entire cloning PR reeks of grudge code. It's pointless, takes away from our experience, and isn't something that was really wanted here or at TG. Autocloning removed, prescan was supposedly messed with, and I believe how corpses, suicides, and brains interact with cloners was also changed. It is big lame.

**Comment by Maroonenahmoron** [comment]
Cloning’s fixed, we still need this?
