### ISSUE TITLE
Cloning changes were only partially ported, breaking cloning

### ISSUE THREAD

**Issue by 4dplanner** [HippieStation/HippieStationdeprecated2020#10321]
Assuming this is what https://github.com/tgstation/tgstation/issues/42150 was about.

In machinery/cloning.dm: 	return pod.growclone(R.fields["name"], R.fields["UI"], R.fields["SE"], R.fields["mind"], R.fields["last_death"], R.fields["mrace"], R.fields["features"], R.fields["factions"], R.fields["quirks"], R.fields["bank_account"]) 	

in machinery/computers/cloning.dm: /obj/machinery/clonepod/proc/growclone(ckey, clonename, ui, mutation_index, mindref, datum/species/mrace, list/features, factions, list/quirks, datum/bank_account/insurance)

These argument lists don't match up, causing initialisation failure every time.

**Comment by 4dplanner** [comment]
@yoyobatty

**Comment by k-k-karma** [comment]
oh my GOD
