### ISSUE TITLE
LCass shit broken

### ISSUE THREAD

**Issue by G-erma** [HippieStation/HippieStationdeprecated2020#10337]
Issue reported from  Round ID: 35876 (Hippie Station)

Reporting client version: 512

https://cdn.discordapp.com/attachments/499381510453854209/532718328574246932/Screenshot_124.png

reeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by yoyobatty** [comment]
Well, aware tgui has been compiled so it should be fixed.
