### ISSUE TITLE
Remove or make hidden "A Rather Large Emergency Shuttle"

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#10355]
It's fun while it lasted, but it's about time we packed this one up somehow. We removed the Daniel shuttle for a reason here and now there's an even worse one? Come on!

**Comment by DaydreamPuppeh** [comment]
+1

**Comment by TheMeatGod** [comment]
Sorry Karma, +1. Its funny but griefy

**Comment by mikolaj007** [comment]
make it so it can only be bought after emagging the comms console.
that way its an annoying shuttle, but also a thing for antags to assert dominance

**Comment by k-k-karma** [comment]
no

**Comment by AliiTea** [comment]
I think removing it is the best option

**Comment by AnthonyJNgo** [comment]
I'd be okay with it being emag only, +1. Seen way too many people die from just one grenade because they were all packed in this thing.

**Comment by Manu9123** [comment]
+1 if members can vote its an + for this REMOVE THAT FUCKING SHUTTLE HOW THE FUCK AM I SUPPOSED TO SNEAK ON IT AS AN CAT ??!?!

**Comment by Manu9123** [comment]
nerf Memendia

**Comment by yobob591** [comment]
+1 shuttle gay, bring back meteor shuttle, it was way more hilarious and way easier to avoid than this shit

**Comment by Higitus1** [comment]
+1. Meteor shuttle is better for sure

**Comment by AnthonyJNgo** [comment]
Removed already.

**Comment by AliiTea** [comment]
that took a long ass time to close this holy fuck

**Comment by ghost** [comment]
@Memendia I have many questions
