### ISSUE TITLE
New ban type Confirmed ??

### ISSUE THREAD

**Issue by Manu9123** [HippieStation/HippieStationdeprecated2020#10377]
Add an new ban type aka Pacify ban/pacifiedban Its the same to that staff you get in lavaland after destroying an legion faunas tendril The staff with one snake on it and attaches to your hand cant be taken off. But you can make it unpacifiable or You cant unpacify the guy/girl who got pacified banned cant hurt only hug cant do surgery its like catban but without arms but you aren't valid and like that shit

**Comment by k-k-karma** [comment]
that's retarded

**Comment by Manu9123** [comment]
Go away karma

**Comment by Manu9123** [comment]
Better removes those tickets karma ill come to your house and destroy your pc

**Comment by TheMeatGod** [comment]
This suggestion stole a chromosome from me

**Comment by Manu9123** [comment]
no

**Comment by mikolaj007** [comment]
what?
basically remove the persons arms?
just catban them. or ban them normally.

**Comment by BlueNothing** [comment]
Just wait until they learn toxins or unleash the Supermatter/Singulo. They can't shoot you the usual way. They can't stun you... but they can still blow you the fuck to smithereens, make everyone around them brain-dead from debraining smoke... etc, etc.

**Comment by Manu9123** [comment]
Damn mikolaj didn't understood it

**Comment by Manu9123** [comment]
I mean with arms but just pacified forever nothing hard

**Comment by DaydreamPuppeh** [comment]
This won't remove your catban

**Comment by AnthonyJNgo** [comment]
How about we modify catbans so they have no arms or legs. It's perfect, good idea @Manu9123

**Comment by Manu9123** [comment]
Yeah but without being valid eeks dee would be fun stuck in shuttle until someone comes with an wheelchair haha

**Comment by Manu9123** [comment]
AnthonyJNgo What about Making catbeast headless like they have to carry their head everytime now that's hardcore

**Comment by Carbonhell** [comment]
we don't need more snowflakey ban types
Denied
