### ISSUE TITLE
remove mindshielded people from becoming midround antag

### ISSUE THREAD

**Issue by mikolaj007** [HippieStation/HippieStationdeprecated2020#10411]
[Why]: because after killing cult with help from a dude who i had given armory equipment to, he became a traitor and killed me. this would ensure that any roundstart people who have been trusted to be mindshielded didnt suddenly turn their backs on everyone.

**Comment by ghost** [comment]
+1, I'm no expert but this definitely needs to be fixed

**Comment by Carbonhell** [comment]
Done in #10572
