### ISSUE TITLE
Photograph icon is invisible

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStation/HippieStationdeprecated2020#10430]
Issue reported from  Round ID: 36212 (Hippie Station)

Reporting client version: 512

![image](https://user-images.githubusercontent.com/3355198/51439369-1b0aea00-1cb1-11e9-9586-b12032a47a98.png)

**Comment by Maroonenahmoron** [comment]
Can confirm, sometimes it’s invisible other times it’s not. Don’t remember what makes it invisible, if any prerequisites are involved.

**Comment by JohnGinnane** [comment]
My photos had players on them I think

**Comment by yoyobatty** [comment]
Fixed and confirmed just now.
