### ISSUE TITLE
Floor Cluwne Breaks If you drag its victim away

### ISSUE THREAD

**Issue by fluffe9911** [HippieStation/HippieStationdeprecated2020#10447]
[Reproduction]: 
1. Get attacked by a floor cluwne
2. Have someone drag you away
3. Scream in horror as the floor cluwne now screams at you invisibly for the rest of your life

**Comment by k-k-karma** [comment]
is this reproduced on hippie code

**Comment by fluffe9911** [comment]
will double check but pretty sure yeah

huh apparantly this is a yogs problem seems im just a idiot sorry

**Comment by k-k-karma** [comment]
fix your yogs trash

**Comment by fluffe9911** [comment]
plan on it

**Comment by yoyobatty** [comment]
floor cluwne is hippie exclusive, so yog just took the code, like usual. This is probably just poor sanity and timer checks.

**Comment by Pyko1** [comment]
or is it the super secret hippie antitheft system in action? :3
