### ISSUE TITLE
The general liquids feedback report

### ISSUE THREAD

**Issue by GuyonBroadway** [HippieStation/HippieStationdeprecated2020#10462]
Put your liquid feedback here.

**Comment by Manly-Dwarf** [comment]
fix soundloops, they're annoying
make liquids actually spread a bit, right now there can be tiles with a shitton of liquids on them but the liquids aren't moving anywhere
pipes and plumbing systems maybe

**Comment by dingdog7** [comment]
make it so, liquids kill all humans instantly.

**Comment by ghost** [comment]
pipes/plumbing is planned

**Comment by DaydreamPuppeh** [comment]
Make it so the liquids actually evaporate under a threatening scrubber event

**Comment by ghost** [comment]
also i'm lowering the soundloops volume. alot.

**Comment by Manly-Dwarf** [comment]
obviously make it so smoke and vapor don't spread liquids

**Comment by Manly-Dwarf** [comment]
and reduce on the leftover chempiles

**Comment by dingdog7** [comment]
can u unban me pls

**Comment by ghost** [comment]
smoke/vapor should already be blacklisted from liquids i believe

**Comment by ghost** [comment]
Liquids were pretty good. The only quibbles I have are with liquids glitching into walls (and making permanent puddles inside them) and with the crew's inability to create drains. Which is good, since minor fixes will be enough.

**Comment by ghost** [comment]
@HideAndSeekLOGIC RPDs could make drains??? And autolathes could make drain frames

**Comment by AnthonyJNgo** [comment]
There is a liquids PR now, comment there.
