### ISSUE TITLE
Remake tts

### ISSUE THREAD

**Issue by Carbonhell** [HippieStation/HippieStationdeprecated2020#10482]
General board regarding the TTS remake through MaryTTS. Will be updated accordingly.

**Comment by Carbonhell** [comment]
So, readding TTS isn't easy and I cannot do it alone for sure, I've tried to use MaryTTS but i had problems querying the local HTTP server for the sound file. Not sure if it even worked or not since playing wav files is buggy on byond. Apparently MaryTTS supports outputting in ogg vorbis,but only on linux, but it still doesn't work, I'm waiting their answer here: https://github.com/marytts/marytts/issues
--nvm they answered, we need to do that SoX stuff and try again, maybe if someone else wants to attempt too it'd be nice
some dm code: https://github.com/Carbonhell/HippieStation/commit/8212cef0887e0fcb70433c77ffd13699c365da62

**Comment by Eagle-Eyess** [comment]
Pls +1
