### ISSUE TITLE
PAI Loudness booster (aka music maker) does not work.

### ISSUE THREAD

**Issue by VladinXXV** [HippieStation/HippieStationdeprecated2020#10494]
Issue reported from  Round ID: 36438 (Hippie Station)

Reporting client version: 512

So I started the round as AI. I was soon given law to kill myself. About an hour into the round, I became a pAI. I downloaded the loudness booster, and hit import song. It crashed. I tried clicking start a new song. Crashed again. I used up 35 points to download that if I'm not mistaken. And I couldn't play any music.

**Comment by k-k-karma** [comment]
try harder

**Comment by Manly-Dwarf** [comment]
try harder-er
