### ISSUE TITLE
Make micro/macro bomb implants able to be bought no matter the pop

### ISSUE THREAD

**Issue by Higitus1** [HippieStation/HippieStationdeprecated2020#10535]
[Implementation]: # same as before

[Why]: # because it was their before and I want to buy it no matter the pop

[Resources]: # same as before

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas! alright I PMed yoyo this time
@HippieStation/maintainers

**Comment by ghost** [comment]
I'm on the fence here, there's a reason for why lowpoppers can't have an instant suicide. That reason is because they're the only antag - when they blow themselves up on a whim, that's all the fun of the round gone.

**Comment by Eagle-Eyess** [comment]
If a tator wants to suicide on low pop he’s going to find other ways to do it anyway. I see no reason to not allow this. +1

**Comment by Manly-Dwarf** [comment]
+1

**Comment by AnthonyJNgo** [comment]
This was merged already.
