### ISSUE TITLE
Readd Micro/macrobomb implants (again)

### ISSUE THREAD

**Issue by Higitus1** [HippieStation/HippieStationdeprecated2020#10534]
[Implementation]: Same as before
[Why]: # Because it was there before and now its not

[Resources]: # Well it was in the game before, just use the previous assets

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas! ok, I pmed pyko on the fourms
@HippieStation/maintainers

**Comment by ghost** [comment]
While at it, I'd be up for a buff to both the micro and macro bombs. Considering that using either one costs non-negligible amounts of TC, literally gibs you and then destroys most of your items, it should at the very least put any adjacent people into red or crit.

**Comment by yoyobatty** [comment]
They are in the game...? You just can't buy em as traitor below a population or you need to be a nukie, I forget, but they're in the game.
