### ISSUE TITLE
Plasma flooding countermeasures

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#10573]
Whenever some rude dude comes onto the server and floods the station with plasma, the clean air verb sometimes won't cut it. That's because there's still plasma in the distribution pipes and until it's pumped/cleared out the plasma will continue to flood even with all the plasma removed from atmospherics/source.

I propose there should be a verb to remove plasma in piping systems or something like the plasma decontamination event to remove all plasma in the station's piping!

**Comment by ghost** [comment]
Have you tried varediting the pipe network to have 0 gases in it? I could work.

**Comment by Maroonenahmoron** [comment]
> 
> 
> Have you tried varediting the pipe network to have 0 gases in it? I could work.

Could you go through the process of doing this?

**Comment by yoyobatty** [comment]
There's a literal event called plasma decontamination, also I would not recommend mass var editting the air values of pipes

**Comment by k-k-karma** [comment]
i recommend mass var editing the air value of pipes
