### ISSUE TITLE
Augmenting a head removes teef and the dental surgery.

### ISSUE THREAD

**Issue by jediluke1999** [HippieStation/HippieStationdeprecated2020#10596]
[Round ID]: # 36760
[Client Version]: 512
[Reproduction]: # Augmenting your head removes your teeth and the option to perform a dental surgery on your mouth. To reproduce, simply augment your head and say something requiring the "S", "F", or "T" sound, among others.

**Comment by k-k-karma** [comment]
which robots have you seen that have teeth

**Comment by jediluke1999** [comment]
Without teeth, though, you can't speak properly, and might as well be mute trying to communicate in a lot of cases. In any case, it's not robot quite yet; you still have organic stuff such as the tongue, eyes, and ears.

**Comment by Higitus1** [comment]
Had this happen to me, was about to write a issue about it. Robots dont have teeth sure but when "ah shit we have nuke ops in arrivals" comes out as "Ah shhiph we have nughe opsh in arrivalsh" something needs to be done.

**Comment by Jujumatic** [comment]
*Feature*

**Comment by AnthonyJNgo** [comment]
Feature.
