### ISSUE TITLE
Graphic glitch (I downgraded the byond version to try to fix it didnt work)

### ISSUE THREAD

**Issue by AndrixBr** [HippieStation/HippieStationdeprecated2020#10621]
Issue reported from  Round ID: 36841 (Hippie Station)

Reporting client version: 512

http://prntscr.com/mj02y7

**Comment by yoyobatty** [comment]
What is your primary video card that you're using to run byond and it's client?

**Comment by Carbonhell** [comment]
Not a code issue, and the dude disappeared seems. Closing.
