### ISSUE TITLE
Steel Point syringes do not pierce spacesuits/syringe deflecting armor

### ISSUE THREAD

**Issue by G-erma** [HippieStation/HippieStationdeprecated2020#10631]
Issue reported from  Round ID: 36884 (Hippie Station)

Reporting client version: 512

Shooting some wearing say a Sec or Cap hardsuit with a Steel Point doesn't work when it should normally go through the armor (which is the whole point of the syringe)

**Comment by ghost** [comment]
I think steelpoints inject via hand while piercing inject via syringe gun. It also makes sense in terms of balance.

**Comment by k-k-karma** [comment]
good

**Comment by mikolaj007** [comment]
not a bug but a feature

**Comment by yoyobatty** [comment]
This isn't a big, but I think a feature that got silently removed by a grudge mapper.

**Comment by ghost** [comment]
Personally, I think hardsuits should counter something you can get at roundstart (considering that this something is pretty much an instant kill). So, closing.
