### ISSUE TITLE
Bone Hurting Juice (?) spamms "ouch oof my bones" which leads to IC mute

### ISSUE THREAD

**Issue by cris5311** [HippieStation/HippieStationdeprecated2020#10664]
[Round ID]: # 37041

[Reproduction]: # After a scrubberbacksurge i started saying "ouch oof my bones" (or something simmilar). This activated the anti spam filter which then muted me. I assume this was the bonehurtingjuice chemical, but i am not sure.

**Comment by GuyonBroadway** [comment]
Why do we even have ic mute?
