### ISSUE TITLE
Cook/Bartender CQC works everywhere

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#10676]
It's not just in the bar and kitchen area, it works all over the station and beyond. Are you guys trying to make them new sec or something?

**Comment by Manly-Dwarf** [comment]
I reported this to maintainers a while back, they refused to fix it.

**Comment by Carbonhell** [comment]
We don't refuse to fix bugs. It's just that everyone thinks someone else is gonna do it, probably.
