### ISSUE TITLE
Syndicate fire suit isn't space proof

### ISSUE THREAD

**Issue by daedsidog** [HippieStation/HippieStationdeprecated2020#10683]
"A less heavy, armored version of the common firesuit developed by a now-defunct, \
	Syndicate-affiliated collective with a penchant for arson. It offers complete fireproofing, \
	**spaceproofing**, the added bonus of not slowing the wearer while equipped and it fits into any backpack. \
	Comes in conspicuous red/orange colors. Helmet included."

If you use that suit in space, you will still freeze. Either edit the description or add space proofing.

**Comment by AnthonyJNgo** [comment]
Will take care of this.

**Comment by AnthonyJNgo** [comment]
PR opened.
