### ISSUE TITLE
Catbanned players spawn on the START SCREEN

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#10730]
I dunno if it's just when I am on, but anyone that is catbanned and tries to join the game spawns on the title screen. They aren't even a catbeast and can pretty much do nothing, all naked and yet still set to their character preferences.

**Comment by TheMeatGod** [comment]
Yeah this does happen

**Comment by ghost** [comment]
Not really an issue, just join after round start.

**Comment by TheMeatGod** [comment]
No, they should be able to load in normally as a cat

**Comment by Kmc2000** [comment]
good
