### ISSUE TITLE
Planters broken

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#10757]
[Round ID]: # 37331
[Round ID]: # 37331
[Round ID]: # 37331

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # Containers work on planters, but chemicals won't apply, regardless of usage.This includes plants (They are containers), and everything else.I believe it still works on lavaland planters, or at least this issue started about a day or two before, since it worked then.
EDIT:They do not work on either.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by ghost** [comment]
Essentially means that you cant do botany without some serious makeshifting, like spamming grass filled with chems.

**Comment by Jujumatic** [comment]
#10687 uBadush pls

**Comment by ghost** [comment]
Apparently, the merge he made works, the only thing the planters accept is 50 units of mutagen.

**Comment by Carbonhell** [comment]
Fixed, server was just not updated

**Comment by RafRoq** [comment]
I'm really sorry with the problem caused

**Comment by RafRoq** [comment]
Won't repeat

**Comment by Jujumatic** [comment]
It was my fault dw about it cause I thought it was ok lol
