### ISSUE TITLE
Curator language manipulation idea

### ISSUE THREAD

**Issue by Carbonhell** [HippieStation/HippieStationdeprecated2020#10780]
[Implementation]: Implementation consists in a new UI panel, either linked to a specific item or made as an innate ability curators get, which lets them create a new language or edit ones created by them. Editing a language allows you to set hardcoded rules (up to 200, as an example, could be even more if stuff doesn't start to lag) and a single default rule.
The hardcoded rules' syntax is actual word = foreign word:
Actual word is the word people who know that language will see in the chat;
Foreign word is the word people who do NOT know that language will see in the chat.
(Those do not have to necessarily be words, they can just be part of words, like you could translate all the t letters to d)
The default rule is a rule that will translate all words in words built by using a formula, given as input by the user, which acts as a filter the input words will pass before being outputted. For example, you could make each character shift by 1, so all As become Bs, and such.
Also the curator obviously needs to be able to teach the language to other people.
[Why]: Gives an actual use to the language system, independent from the RP level, transforming it in an actual game mechanic (people can try to decypher words if they understand/find out about the rules or the formula)

[Resources]: Check stuff like lisps, spurdo mask etc. The core of this idea is the use of replacetext, and saycode. Should not be too hard.

**Comment by Eagle-Eyess** [comment]
+1 sounds cool. Maybe also a new antag type that speaks in a coded language that the curator could decode to help a lot. Like how the chaplain helps a lot against cultists.
