### ISSUE TITLE
Make it so that walking of chem spills on the floor not apply if you are wearing shoes

### ISSUE THREAD

**Issue by Higitus1** [HippieStation/HippieStationdeprecated2020#10797]
Issue reported from  Round ID: 37521 (Hippie Station)

Reporting client version: 512

I just think that if you are wearing shoes the chem spills shouldn't apply, unless you are resting or being dragged face down into the spill.
That is all thanks for reading

**Comment by DeltaFire15** [comment]
White shoes completely negate it.
Other shoes reduce.
(As of now)

**Comment by RafRoq** [comment]
Bad idea would mega chempiles useless

**Comment by Jujumatic** [comment]
No thanks

**Comment by yoyobatty** [comment]
Again, white shoes, magboots and jackboots negate severely/completely.

**Comment by Dinopeaks** [comment]
W H I T E S H O E P O W E R G A M E

**Comment by yoyobatty** [comment]
This isn't an issue or really a suggestion since we already have something that does it.

**Comment by RafRoq** [comment]
Dude you can be immune to chem piles 1 minute into the round
