### ISSUE TITLE
Nerf syndicate operative shuttle turrets

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#10800]
They have ludicrous DPS and projectiles can bounce off walls, if the emergency shuttle is parked next to it there's very little chance or hope for survival for anyone who walks within its firing range. Needless to say, they can pierce through armor and kill anyone within seconds.

**Comment by RafRoq** [comment]
That's really easy to do, but do most people want this nerf?

**Comment by mikolaj007** [comment]
Yes
Walking around and getting stunned and killed automatically isnt funny

**Comment by Higitus1** [comment]
dont walk around in space

**Comment by mikolaj007** [comment]
The stun is beyond fucking op honestly
Get hit once and you die because you cant move
Just show up outside departures and you kill anyone that even comes nearby

**Comment by ghost** [comment]
@Higitus1 thanks for showing that you read nothing but the title of the thread

**Comment by Higitus1** [comment]
I aim to please

**Comment by TheMeatGod** [comment]
+1 nuke ops turrets are rediculous

**Comment by AnthonyJNgo** [comment]
-1, the turrets are meant to be OP because retards kept breaking into the shuttle.
