### ISSUE TITLE
Give more information about zombie infected patients

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#10862]
Whenever someone becomes infected by a zombie, there is currently no way of telling apart from just taking constant toxin damage over time. While that definitely says something is up, there's no second step towards figuring out what to do than just pumping them up with charcoal/antitox.

There needs to be health analyzer cue or message in the infected's chat that something is affecting the brain and that surgical removal should cure the problem.

**Comment by mikolaj007** [comment]
all that needs to be done is this line added:
if(M.getorgan(/obj/item/organ/zombie_infection))
	to_chat(user, "\t<span class='alert'>Subject appears to contain the zombie infection. Head surgery needed to remove.</span>")

but it needs to be in the middle of the proc to look properly. should i do a PR on tg?

**Comment by AnthonyJNgo** [comment]
There is a PR open for this, closing.
