### ISSUE TITLE
Epi is useless after recent nerf, dosnt even stabilize.

### ISSUE THREAD

**Issue by cris5311** [HippieStation/HippieStationdeprecated2020#10885]
For gods sake just put it like it was. it worked.

[Why]: It always was like that and now it is shit.

**Comment by GuyonBroadway** [comment]
Whaddya mean it doesn't stabilize? 

Sounds more like a bug.

**Comment by Jujumatic** [comment]
In the balance pr it said it's definitely supposed to stabilise... I'll see if I can pull it up

**Comment by Jujumatic** [comment]
#10841

**Comment by cris5311** [comment]
Its a bug then. Already had 2 patients die after i administered epi

**Comment by yoyobatty** [comment]
Not a bug, it adds the no crit trait which stops you from taking oxyloss, however it doesn't immediately heal oxyloss damage and it doesn't prevent stuff such as toxin or rads damage from killing them.
