### ISSUE TITLE
Lavaland podpeople need a guaranteed method of escaping 

### ISSUE THREAD

**Issue by Vagak** [HippieStation/HippieStationdeprecated2020#10972]
[Title]: The "Separated Chemicals" trait is gone so lavaland podpeople need a new method of escape feature request

[Implementation]: This can be solved in various ways.

1. Make it so cherry bomb seeds will spawn in the ship, 100% guaranteed. Right now it's only a small chance of it happening whenever the podpeople ship spawns in lavaland. (easiest method.)
2. Give the podpeople a pickaxe or some other method of destroying rocks
3. Make it possible to craft a pickaxe using metal and wood combined, which podpeople have access to if they know what they're doing
4. Create a plant with the express purpose of melting lavaland rocks

[Why]: Podpeople used to be able to escape using explosive nitromatoes. Since separated chemicals is gone, now they can't.

[Resources]: Implementation suggestion #3 will probably require sprites for pickaxe head and pickaxe handle, but that should be easy to do. Implementation #4 would require plant sprites. Easiest method probably is to just do #1 or #2.

**Comment by mikolaj007** [comment]
separated isnt gone. Just in strange seeds.

**Comment by DaydreamPuppeh** [comment]
Do podpeople have the resources to rely on rng for it?

**Comment by mikolaj007** [comment]
do they have watermelons and a biomass generator?

**Comment by RafRoq** [comment]
Separated isn't gone you can still get it in glow berries but with 10% chance

**Comment by ghost** [comment]
you can dig using metal rods

**Comment by ghost** [comment]
or add attracting gold grubs with thumpers and domesticating them dune sandworm style

**Comment by Eagle-Eyess** [comment]
Idk about this they are a ghost spawner so I see no reason for them to “escape” in the first place. They aren’t suppose to.

**Comment by AnthonyJNgo** [comment]
They do not need a **guaranteed** way to escape.
