### ISSUE TITLE
Add Tiny Fan In Lavaland Mining AirLocks 

### ISSUE THREAD

**Issue by DavidBlanc5** [HippieStation/HippieStationdeprecated2020#10977]
[Title]: Add A tiny fan on lavaland airlocks

[Implementation]: idk .

[Why]: Because if anyone opens The Airlocks and they lead outside they just vent the room the airlock is opened in.

[Resources]: use the tiny fan that stops gas movement

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by Eagle-Eyess** [comment]
-1 could just use an airlock room in mining like in escape, I thought there already was one in mining though.

**Comment by AnthonyJNgo** [comment]
Not really an issue, the main mining station is still pressurized and has atmos. It is a 2-3 tile space, just step into the next room.
