### ISSUE TITLE
Vampire Screech Didn't knock over clown in sleigh

### ISSUE THREAD

**Issue by carlopault** [HippieStation/HippieStationdeprecated2020#10984]
Issue reported from  Round ID: 38203 (Hippie Station)

Reporting client version: 512

I was getting killed by this clown that was riding a sleigh after I tried killing him, when he knocked me over I tried using my screech ability to knock him over, but it didnt work and I died.

**Comment by Jujumatic** [comment]
can we just remove vamps at this point lol

**Comment by yoyobatty** [comment]
They possibly had ear protection or the clown was technically in nullspace
