### ISSUE TITLE
remove avians

### ISSUE THREAD

**Issue by robloxgothgf** [HippieStation/HippieStationdeprecated2020#10983]
[Title]: # remove avians
[Implementation]: # They are literally furries that are allowed on hippie
[Why]: # removal of furries 

[Resources]: # https://github.com/HippieStation/HippieStation/blob/master/hippiestation/code/modules/mob/living/carbon/human/species_types/avians.dm fucking furfags

**Comment by yoyobatty** [comment]
But they're not furry, they're feathery

**Comment by Manly-Dwarf** [comment]
+1

**Comment by Eagle-Eyess** [comment]
-1 I’m biased

**Comment by cris5311** [comment]
Just make them Valid instad

**Comment by ghost** [comment]
how about,  because birds have brittle bones,  have avians take triple brute damage from any source?  Brittle bones.  And they always have firestacks on them,  so they burn forever until death,  due to oily feathers.

**Comment by mikolaj007** [comment]
-1 because im also biased

**Comment by Majick1** [comment]
+1, do lizards and moths too

**Comment by DaydreamPuppeh** [comment]
+1. Just moths and birds. Lizards are a classic sci fi race

**Comment by k-k-karma** [comment]
NO THEY FUCKING AREN'T

**Comment by ghost** [comment]
what the fuck @daydreampuppeh.
liggers must die but dont remove them really just make them get 1.5x burn
This has gone too far.
Laputan machine.

**Comment by Majick1** [comment]
No, no nerf short of total removal will make furries stop forcing their fetish on us

**Comment by mikolaj007** [comment]
Well, in that case i call for removal of farts, because thats fetish content

**Comment by cris5311** [comment]
Well Lizards are a clasical FANTASY race, but not a classical SciFi race

**Comment by AnthonyJNgo** [comment]
I need to know the enemy so I can destroy them.
