### ISSUE TITLE
Yang gang for a gang possibility.

### ISSUE THREAD

**Issue by JessHorserage** [HippieStation/HippieStationdeprecated2020#11175]
[Title]: # True democracy added into gang gamemode.

[Implementation]: # Add yang gang to gang

[Why]: # Decent meme

[Resources]: # Basically fuck all

**Comment by ghost** [comment]
gets 1000 credits on joining and has money guns and cyber ninja super nerfed exosuits and katanas

**Comment by mikolaj007** [comment]
nah, if yang gang is in play, literally everyone gets 1k at roundstart
