### ISSUE TITLE
Locker at Hotel is locked and unopenable by regular staff access

### ISSUE THREAD

**Issue by Punkinguy** [HippieStation/HippieStationdeprecated2020#11174]
This is at the kitchen of the hotel, the Meat fridge, and the Refridgerator, I had to get an admin to open them for me. and there is nothing even strong enough to brute the things open.

**Comment by AnthonyJNgo** [comment]
Yeah I forget why this isn't open, this is an easy fix too.

**Comment by Punkinguy** [comment]
@AnthonyJNgo bro please fix :mistake:

**Comment by AnthonyJNgo** [comment]
PR has been created.
