### ISSUE TITLE
space billboards patreon award idea

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#11191]
[Title]: space billboards patreon award

[Implementation]: https://docs.google.com/document/d/14uVRRqAAeXtmWc4EtEItiM6NxmajUQKIbQjBOsbSAF8/edit?usp=sharing

[Why]: # How does your feature improve the game anyhow? Why should it be added?

[Resources]: # Eventual assets such as icons and sounds which you have and want to suggest related to this feature.

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by Maroonenahmoron** [comment]
This doesn't look filled out properly
