### ISSUE TITLE
Instant blue alert when cult

### ISSUE THREAD

**Issue by Galardomond** [HippieStation/HippieStationdeprecated2020#11219]
Issue reported from  Round ID: 39041 (Hippie Station)

Reporting client version: 512

When roundtype is cult, the blue alert triggers ~2 seconds after roundstart, instead of ~30 seconds.
Using meta-knowledge, this gives away the roundytype.

**Comment by yoyobatty** [comment]
How often has this happened?

**Comment by Galardomond** [comment]
https://statbus.hippiestation.com/rounds/39288
Soooo just happend for wizzard. That would resolve the issue, if its not the same type always.
