### ISSUE TITLE
Holotool Welder Fail

### ISSUE THREAD

**Issue by VladinXXV** [HippieStation/HippieStationdeprecated2020#11233]
Issue reported from  Round ID: 39158 (Hippie Station)

Reporting client version: 512

So I was trying to use the holotool welder to remove the layer of plasteel covering a door, and it did not work. I tried using a real welder, and it worked. So I was on the right step, but the holotool welder did not work. Please fix this, as the holotool should be able to do what any tool can.

**Comment by ghost** [comment]
Not a holotool issue. Holotool works on anything that uses TOOL_WELDER.

**Comment by ghost** [comment]
Is it possible you were on harm intent?
