### ISSUE TITLE
Give wizards better objectives

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#11230]
At the moment, wizards have pitiful chores to complete. Kill one guy, leave on the shuttle. Maybe steal a plasma tank and wait until the round is over.

It's about time we gave them some better tasks... have them turn walls into doors, make crew members into a certain mob, use their abilities to level them up to a certain amount or have some thralls escape along with them!

At the moment, wizards just go around and effortlessly kill off crew members and being dead because you took a single fireball to the face or got turned into a brain with an **EI NATH** shouldn't have to be everyone's end because there's a lack of imagination to work with.

Encourage them to do more weird and zany stuff that no other antagonist can accomplish!

**Comment by k-k-karma** [comment]
godo idea

**Comment by ghost** [comment]
I agree, this is a very godo idea

**Comment by Majick1** [comment]
do wizards even have a hijack objective? seems that's how 90% of them play it even if they don't have a single kill objective.

**Comment by mikolaj007** [comment]
> 
> do wizards even have a hijack objective? seems that's how 90% of them play it even if they don't have a single kill objective.

yes they do, but only rarely
i think its just the joy of murderboning with the fact that stealth wiz is too easy to greentext as

**Comment by AnthonyJNgo** [comment]
This is a non-issue because if you are playing anything other than Badmin Gauntlet as wizard you don't deserve to have fun.
