### ISSUE TITLE
Unable to play music with "Play Internet Sound" admin command - again

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#11257]
A currently ongoing issue since about 24 hours ago, internet sounds are once again fucked.

_**Youtube-dl URL retrieval FAILED:**
WARNING: Assuming --restrict-filenames since file system encoding cannot encode all characters. Set the LC_ALL environment variable to fix this.
ERROR: nfYVR34DGtc: "token" parameter not in video info for unknown reason; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type youtube-dl -U to update. Be sure to call youtube-dl with the --verbose flag and include its complete output._

I've tried any and all YT links and nothing works. I don't want to cry again.

**Comment by Manly-Dwarf** [comment]
what you get for trying to play delfino airstrip

**Comment by AnthonyJNgo** [comment]
This was fixed.
