### ISSUE TITLE
Remove Atmospheric Technician

### ISSUE THREAD

**Issue by Zyzarda** [HippieStation/HippieStationdeprecated2020#11279]
[Title]: # Your feature needs to have a good title. If you want an object added, the object's name would be a good title, and such. Use common sense.

[Implementation]: Useless role

[Why]: # Engineers should have access to the entire engine, and atmospheric technicians are glorified assistants with a few powergame items.

[Resources]: # No

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by yoyobatty** [comment]
Same logic applies to chemists, Atmos is extension of engine just like chemistry is extension of medbay.

**Comment by ghost** [comment]
fuck off furry faggot

To be serious, I don't really know what you mean by 'the entire engine'. From memory, engineers should be able to access the entirety of the SM without any hindrances.

Plus, atmos techs fill in the firefighting role and the stopping-AI-from-plasmaflooding role pretty well.

**Comment by ghost** [comment]
fuck off furry faggot

atmos tech has its own niche

**Comment by Manly-Dwarf** [comment]
It actually is a pretty useless role, Chemistry fulfills a different job than Medical Doctors, but Atmospheric Technicians don't really have a job. "Firefighting" but most fires are caused by Atmos Techs themselves or the AI plasma flooding, which you can't fight off. Most people just pick it for the fireaxe and don't bother trying to do fusion, supermatter stuff, or the thermal engine.

**Comment by Maroonenahmoron** [comment]
Atmos techie is a job that is frankly never played out fully. People going around adjusting air alarms, setting up atmospherics with better piping and even installing sprinklers is a sight never or very rarely seen.

"atmospheric technicians are glorified assistants with a few powergame items"

+1

**Comment by Majick1** [comment]
-1 

Atmos has room to fill, even if a lot of people don't bother fucking with pipes or firefighting. Just remove the fireaxe if it's that big an issue

**Comment by cris5311** [comment]
-1

Athmos Tech has its uses

**Comment by AnthonyJNgo** [comment]
-1, Atmos tech has a role to play. The new economy will help push them to make sure the stations atmosphere is continuously pumping out oxygen also.
