### ISSUE TITLE
Fix clown shoes

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#11316]
If you have the waddling perk and remove the clown shoe's waddle dampeners/wear clown shoes, nothing happens. If you deactive the waddlers with waddling quirk enabled however, it completely removes your waddling quirk.

As a bonus, if you already have the waddling quirk and wear clown shoes, you should jumble all around the place and waddle like a waddlefucker.

**Comment by AnthonyJNgo** [comment]
This whole scenario makes sense to me. Waddle is a free perk iirc. If you waddle and you wear clown shoes you will waddle x2. If you toggle the waddle off you lose it forever.
