### ISSUE TITLE
Russian Surplus Crate always has items missing and sprites are missing

### ISSUE THREAD

**Issue by AyB0ss** [HippieStation/HippieStationdeprecated2020#11329]
Sorry no round ID I dont want to waste one reproducing this bug

![unknown](https://user-images.githubusercontent.com/26505685/57085639-86267c80-6cf4-11e9-960a-0a24d031ec6e.png)

[Reproduction]: Hack the supply console and order the Russian Surplus Crate, open it, it's likely missing both the guns, half the items don't have proper sprites

**Comment by AnthonyJNgo** [comment]
This needs to be verified. I'll do it later.

**Comment by yoyobatty** [comment]
Just tested and it appears to be fixed.
