### ISSUE TITLE
Weapon/tool that just delimbs, no brute/burn.

### ISSUE THREAD

**Issue by JessHorserage** [HippieStation/HippieStationdeprecated2020#11338]
Maybe like a late game rnd thingy, takes like 3-5 seconds to activate then boom, limb taken off quick and with low-no damage.

**Comment by mikolaj007** [comment]
Just use surgery

**Comment by ghost** [comment]
disembowelment is an instant kill

**Comment by Maroonenahmoron** [comment]
It should be a surgical table add-on that allows you to use an operating console, target a limb and a saw comes out to quickly cut off your selected limb

**Comment by Jujumatic** [comment]
inb4 instantly cutting heads off, making insta nuggets and disembowlment.

or instantly removing lungs so you can watch as they slowly and helplessly die, unable to say anything throughout the whole process.

that one is my favourite

**Comment by AnthonyJNgo** [comment]
This would be extremely overpowered, just use surgery or fight using a circular saw, sword, or anything sharp. Any weapon that could instantly delimb would be abused.
