### ISSUE TITLE
8TC Infiltator Tracker upgrade doesn't work

### ISSUE THREAD

**Issue by cris5311** [HippieStation/HippieStationdeprecated2020#11339]
[Round ID]: # 39585

[Reproduction]: The 8TC upgrade for the infiltrator tracker, dosnt show the Antique Lasergun, even tho it says it will track objectives.

**Comment by ghost** [comment]
It doesn't track items, it will track people though. Weird.

**Comment by Maroonenahmoron** [comment]
Where was the antique the whole time? Might of got spaced or maybe it doesn’t track while it’s in a display case

**Comment by ghost** [comment]
i can rework this a bit

**Comment by cris5311** [comment]
According to the admins it was on the captain, who was on the station
