### ISSUE TITLE
Disappearing Stunprod

### ISSUE THREAD

**Issue by MeraNoMi** [HippieStation/HippieStationdeprecated2020#11385]
Issue reported from  Round ID: 39764 (Hippie Station)

Reporting client version: 512
 
When creating a stunprod, upon attaching an igniter to a wired rod, the stunprod sprite disappears from the hands menu completely, however the sprite remains on the character model. Furthermore, the stunprod can still be used to prod people, as clicking with the supposedly empty hand shows the prod text, and if clicking where the sprite should be in the hand, the no battery text pops up. The stunprod can still be moved at this point to a container or your pockets, however it will cease to exist at that point even though it takes up a position in the container, and will be overwritten by any new item placed in the container afterwards, and it cannot be removed from the container. Also, if swapping hands, the stunprod will become unmoveable from the hand position outside of admin intervention, and nothing may be placed in said hand. If placed in a container, then emptying the container to the floor, the stunprod will also disappear.

**Comment by yoyobatty** [comment]
I secretly fixed this.
