### ISSUE TITLE
Gives the aux base back a public mining shuttle dock

### ISSUE THREAD

**Issue by Yokool** [HippieStation/HippieStationdeprecated2020#11423]
[Title]: # Gives the aux base back a public mining shuttle dock

[Why]: # Normal boxstation has a public mining shuttle dock. Meaning you can call the mining shuttle to the aux dock, if you send the aux base into lavaland first, but hippiestation has the aux base moved south and the public dock completely removed (not sure if intended, that's why I made this). Meaning you can't call it there anymore. Adding this would provide people a much more direct way to get to lavaland instead of going through cargo.

[Implementation]: # Once you send the aux base into lavaland, you can call the mining shuttle into the aux base dock.

[Resources]: # All the assets are in the game right now

**Comment by Majick1** [comment]
Not sure why you would need a second shuttle spot, if an assistant wants to go mining they can just job change with HoP

**Comment by Yokool** [comment]
What if the hop isn't there, or you don't want to go through the hassle of getting a job change. This could be a positive change.

It was already a thing previously that existed, I would like if this was added back.

**Comment by Yokool** [comment]
Oh, I failed to mention that the aux base has a landing dock when you send it into lavaland. Meaning you can travel between the public dock and the lavaland aux dock. Making lavaland bases more fun.

I am almost sure this was forgotten when someone mapped the aux base. Since the mining shuttle console is still there, but the port is missing. Meaning you can't call it there.

**Comment by ghost** [comment]
no, you're supposed to drop some kind of beacon that creates a landing dock area and you can land the mining shuttle there

**Comment by Yokool** [comment]
> no, you're supposed to drop some kind of beacon that creates a landing dock area and you can land the mining shuttle there

You are right, there is a beacon that you can plop down, but I explained it wrong.

This issue is revolving only around the public mining dock.


___________________
Okay I hope I can explain it right this time:

As far as I am aware, every original map like box station, meta station etc, has a public mining dock that you can use after you send the auxilary base to lavaland. It is located on the station taking place where the original auxilary base was. Hippiestation has it removed, but the shuttle console is there. Meaning it really has significant no use. You can still use the console, but there is no point as you can only send it to lavaland/aux base dock/cargo and not to the public base port.

I am sure this was not intentional, but forgotten. Because the mining console is there, serving no purpose.

**Comment by Majick1** [comment]
The other half of my question is why do we even need a public mining shuttle? No real benefit to it being working.

**Comment by Yokool** [comment]
Scientists/Roboticists have a much cleaner way of getting to stuff lavaland and working on the aux base/mining. I'm not saying it's for everyone since most people don't use the aux base, but I enjoy working on it.

**Comment by Yokool** [comment]
dumb phones and missclicks

**Comment by Yokool** [comment]
Ehhh you know what? When the shuttle lands it cuts through a part of the wall and after it leaves the wall is back again. (That is if you want the shuttle to land perfectly on the airlock).

The trouble makes it less worth it and people don't seem to insterested in this to bother with it.


Closing this
