### ISSUE TITLE
My Text is on top of each other and I think its a server side issue.

### ISSUE THREAD

**Issue by Helgraf95** [HippieStation/HippieStationdeprecated2020#11505]
[Round ID]: # Every Round After I did it, non specific, I can reproduce it.

[Reproduction]: # So there are these boxes in the top right of the chatbox right. I pressed the first one that lets you modify font size and line height right. Heres what I did.
1. Pressed First Box
2. Pressed Decrease Line Height
2.5. All my text is now on top of each other and i cant read any of them.
3. I press Increase line Height, (Does Nothing)
4. I try fix chat (Does Nothing)
4.5. Switched to Old chat so I can play the game
5. Suffer from text on top of each other.
6. Cleared Cache (Didn't Work)
7. Uninstalled and Reinstalled (Didn't Work)
8. Cried some more.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by AnthonyJNgo** [comment]
This is your client specifically, not server side. You need to clean all files related to Byond then do a fresh reinstall.
