### ISSUE TITLE
The Loudness Booster doesnt work for PAI

### ISSUE THREAD

**Issue by carlopault** [HippieStation/HippieStationdeprecated2020#11504]
Issue reported from  Round ID: 40120 (Hippie Station)

Reporting client version: 512

When I click the Loudness Booster in my software interface, 2 buttons appear, "choose instrument type" and "open synthesizer interface". Both of the buttons bring me to the same menu, the menu when you press Z while holding an instrument. If I try and click Import Song, the menu closes, the same thing happens with every other button too. All of it is borked.

**Comment by AnthonyJNgo** [comment]
I think this is a duplicate but I'll keep it open.
