### ISSUE TITLE
Xenobiology Shield Generator

### ISSUE THREAD

**Issue by MeraNoMi** [HippieStation/HippieStationdeprecated2020#11549]
[Round ID]: 40293
[Testmerges]:
[Reproduction]: In the xenobiology lab, if the engineers fail to set up power and the apc starts losing power, without fail every round the shield generators will cease to draw any power from the apc, as in they will say "The xenobiology shield wall generator needs to be powered by a wire!", and upon inspecting the wires coming from the apc with a multi-tool even if the apc has been recharged with an inducer, the wires will say "The cable is not powered.", yet they still power all of the other machines in the Xenobiology lab just fine.
[For Admins]:

**Comment by yoyobatty** [comment]
Requires power from the SMES, NOT THE APC. The APC is the area power controller which provides power to stuff such as airlocks, vents, doors, computers, machinery and lights. The SMES outputs to the red wires in maint.

**Comment by AnthonyJNgo** [comment]
This requires SMES power, this is not an issue.
