### ISSUE TITLE
Make chat toggable

### ISSUE THREAD

**Issue by xTrainx** [HippieStation/HippieStationdeprecated2020#11565]
[Title]: # toggable chat
[Implementation]: # so add a button to quickly toggle chat on and off, this would help in high action moments, since chat can be a bit overwhelmy, also because my game fucking freezes for like a minute whenever i get shotgunned until every pellet hitting me message is through, wich sucks

[Why] shotguns are my demise, and no one looks at chat during battle scenes

[Resources]: unnecesary

@HippieStation/maintainers

**Comment by cb583** [comment]
-1, I can see this becoming a problem as people will turn their chat off (especially new players) and just completely ignore what people are saying to them

**Comment by cb583** [comment]
Even though they do that anyway

**Comment by ExpAntique** [comment]
+1 maybe instead of turning chat off let you minimize, and put little discord like notifications on the side of your screen so people know they're being talked to and can maximize it again
