### ISSUE TITLE
Use welders to escape cable cuffs

### ISSUE THREAD

**Issue by ExpAntique** [HippieStation/HippieStationdeprecated2020#11591]
[Title]: # Lets people trapped in cable cuffs burn them off with a turned on welder

[Implementation]: # If someone is trapped in cable cuffs, they can use a turned on welder that is on the ground or in their inventory to slowly burn through the cable cuffs (but still taking half the time that it would take to struggle out of them), freeing them and dealing large amounts of burn damage to their arms. 
Minor ideas:

- could also be implemented with lighters, which would take more longer than welders
- more advanced welders with more precise flames could do less burn damage
- people who are cuffed could be given the ability to turn on welders and other items that are on the floor with their feet.

[Why]: # In the current game, once you're cuffed by someone, you're pretty dead or forced to put up with their bullshit for like an hour or until some other retard decides to free you. This would allow people who are resourceful and able to think on their feet another chance at freedom. 

[Resources]: # The one scene in breaking bad season 5

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by Manly-Dwarf** [comment]
Would not mind making cables less ridiculous, but it would be a huge change that could very easily piss everyone off. Said this before, but I wish the handcuff-removal progress saved, so if you had already gotten 30 out of 60 seconds done on removing handcuffs, but some jackwagon moves you, you'll only have to wait another 30 to remove them. And so on.

**Comment by ExpAntique** [comment]
>Said this before, but I wish the handcuff-removal progress saved, so if you had already gotten 30 out of 60 seconds done on removing handcuffs, but some jackwagon moves you, you'll only have to wait another 30 to remove them. And so on.
 
 This is how Dead By Daylight does it, and I think that system works pretty well.

 The main poin in adding interactions like this is so people who get cuffed aren’t forced to just sit on thier ass in some room in maint and wait to die. Many people literally ghost as soon as they get cuffed because they can do legit nothing to escape that situation.

 Another mechanic from DbD we could add is the ability to struggle out of a grab, stunning the person grabbing you and giving you a chance to run. It could either be a random chance or escape or a long progress bar. This would be good for those shitters that arrest someone and then drag them around for the whole game because they know they can’t break free

**Comment by AnthonyJNgo** [comment]
How would this work? If it is on the ground or in their bag how are they going to take it out of the bag or alternatively turn on a welder on the ground? There aren't welders just lying all over the station turned on. I would +1 new ways to uncuff, but this is unfeasible.

**Comment by ExpAntique** [comment]
>If it is on the ground or in their bag how are they going to take it out of the bag or alternatively turn on a welder on the ground?

>people who are cuffed could be given the ability to turn on welders and other items that are on the floor with their feet.

**Comment by ghost** [comment]
something like this should be given a try. generally being stunned and cuffed is a death sentence in this game

**Comment by ghost** [comment]
yeah like if there's a welder on the floor, you should be able to kick it for a chance of either turning it on, turning it on and burning your foot, or tossing it several tiles
