### ISSUE TITLE
Health sensor grenades in butts don't go off

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#11630]
exactly what the title says.

How to reproduce:  
1. put health sensor grenade in butt  
2. die  
3. be disappointed

**Comment by DaydreamPuppeh** [comment]
No more assblasting

**Comment by yoyobatty** [comment]
This is because it checks if the sensors location is a mob. If you went on view variable and check a butts location and then checked the health sensor and found its location was the butt and not the mob, you found your issue.

**Comment by ghost** [comment]
Doesn't it do a recursive loc check, @yoyobatty? Since it works in backpacks.

**Comment by AnthonyJNgo** [comment]
This is a duplicate issue.
