### ISSUE TITLE
Bring back autocloning

### ISSUE THREAD

**Issue by WarRage333** [HippieStation/HippieStationdeprecated2020#11662]
4d man grudge code tg big gay

**Comment by Majick1** [comment]
+1 pls

**Comment by Manly-Dwarf** [comment]
No, autocloning was a legitimately awful feature. If it comes back, I want changes to cloning.
It, like perfluorodecalin, was removed for a very good reason. It's a shame that they were too unoriginal to actually come up with a solid fix other than harsh grudgecode.

**Comment by Majick1** [comment]
What kind of changes do you have in mind?

**Comment by WarRage333** [comment]
Auto cloning usually means you lose all your equipment, and they grudge coded it because one guy had a massive hate boner for mining and them killing megafauna

**Comment by AnthonyJNgo** [comment]
+1, you get cloned with a bunch of defects anyways usually unless you upgrade it. We never had a huge issue with this to be honest.
