### ISSUE TITLE
Antag Systen Reworking

### ISSUE THREAD

**Issue by Mastergodown** [HippieStation/HippieStationdeprecated2020#11695]
I believe a new system should be added for antags, which has to do with the settings of players, basically, it would increase the chances of being an antag for people who have no settings in other antags, this would also be balanced because the people with more yes's would gain more chances of being an antag in general, but people with more no settings would have a higher chance of being an antag they prefer, the thing is, the people with more no settings would only get that bonus of rolls if the antag they prefer is selected for the round (I don't know much about how the antag rolling/selecting system works, so yall will have to discuss it yourselves.

I believe it would improve gameplay because it would allow the people who are centered around one antag to get it more, but the people who have more yes settings will gain more chances overall.

That's just my own idea though.

**Comment by AnthonyJNgo** [comment]
I believe suggestions should be put in the issue tracker where they belong, where every single resource we have regarding the github tells you to put ideas unless you are making a PR draft. Closed.
