### ISSUE TITLE
Avengers ERT to fight Thanos

### ISSUE THREAD

**Issue by sagaty13** [HippieStation/HippieStationdeprecated2020#11705]
Here's my ideas for a possible Avengers team to fight the mad gay titan that wins almost every round because ~shotguns~ nothing stops him.

### **Iron Man**

- Clock Cult Armor Spell or a big ass mech
- Arm Mounted Laser Implant from Cybersun Sponsorship Kit or a laser spell

### **Hulk**

- Hulk (orly?)
- purple athletic shorts for reasons
- I dunno man maybe Elite CQC

### **Thor**
This one would be mostly wizard and genetics stuff like

- Mjolnir + Recall spell
- Tesla Blast
- Shock Touch
- Insulated
- Lightning Bolt
- Throw Lightning 

### **Captain America**

- the Bananium Energy Shield is a blatant rip-off of Captain America shield.
- CQC

k I'm outta ideas
i'll smoke some weed to up my creativity cya later bye

**Comment by AnthonyJNgo** [comment]
Hi this is a suggestion, please make an issue post.

**Comment by ghost** [comment]
I've mostly coded this in

**Comment by sagaty13** [comment]
this is a issue post though
are you high?
