### ISSUE TITLE
Faster neck grab sleeper hold

### ISSUE THREAD

**Issue by sagaty13** [HippieStation/HippieStationdeprecated2020#11735]
Neck grabbing someone is already hard as fuck since its so easy to resist, but strangling is even worse. Give it a realistic approach (If they attempt to resist, they lose oxygen faster because they are wasting it struggling to fight back) or make it deal more damage.

**Comment by AnthonyJNgo** [comment]
This is supposed to be easy to resist out of, the point is you need to incapacitate your victim first.
