### ISSUE TITLE
Cult shard shenanigans

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#11758]
Issue reported from  Round ID: 40939 (Hippie Station)

Reporting client version: 512

If you shard a cultist shade with a purified shard (use a bible on a cultist shard so anyone can use it) and purify the shard with a bible, the shade inside/when released is still labeled as a cultist. Could this get cleaned up? Cultist shades shouldn't still be cultists after being forced inside of a purified shard, for confusion's sake.

**Comment by AnthonyJNgo** [comment]
What? Can't you just purify the shade directly by purifying his shard? Sounds like you're just containing the evil spirit inside a holy item, not purifying the spirit itself.
