### ISSUE TITLE
Chaplains are NOT restricted from being a vampire in traitor+vamp

### ISSUE THREAD

**Issue by NautilusViper** [HippieStation/HippieStationdeprecated2020#11762]
[Round ID]: #40989

[Reproduction]: Be Chaplain in the Traitor+Vamp gamemode and watch in awe as you're able to roll Vampire, burn in your own chapel and not be able to use any of your vampire abilities.

**Comment by sagaty13** [comment]
Chap vamp is intentional, fair and balanced

**Comment by NautilusViper** [comment]
> Chap vamp is intentional, fair and balanced

get mannitol
