### ISSUE TITLE
Suggestion: Hulk Rework

### ISSUE THREAD

**Issue by sagaty13** [HippieStation/HippieStationdeprecated2020#11770]
### [Implementation]: # 

**The main goal is to nerf some features while also giving him a few buffs to compensate and vice versa**

Well, here's my ideas

- Make it a toggleable power, like goon genetics.

- Transforming breaks you out of any restraints (grabs, handcuffs, buckles) and recovers from sleep and stuns

- You won't be able to wear backpacks and armor while transformed, and if you're wearing a jumpsuit it will tear apart, damaging the pockets

- You're slightly taller when transformed, so your hitbox is bigger

- Once you transform, you share the same protection against harm from diamond golems but your speed doesn't change

- Your punches are stronger but they never stun cause thats retarded and is probably what makes hulk so hated by many people. Instead you get more chances of pushing someone while disarming and your grabs are always aggressive

- You cannot get your limbs amputated while transformed

- To compensate your strength, you get moderate brain damage while transformed (enough to headbutt airlocks and lose dexterity to use most technology without the brain damage sentences being spammed all the time) + you can only speak short sentences (unintelligible speech)

- Not doing any attack for a few minutes will calm down the beast and revert the transformation leaving you vulnerable for a while

- Wizard Hulk doesn't get any changes since that'd probably break the mutate spell

If you guys feel like these changes are too OP, maybe turn them into a traitor item exclusive to geneticists?
A modified Hulk DNA injector, who knows

### [Why]: # 
Currently Hulk is used as an excuse to grief the station breaking into every high sec area to steal shit and bait someone into shooting you once with lethals to get an excuse for killing them, maybe with these modifications this playstyle evolves into something less annoying and more fun to fight as/against.

### [Resources]: # 
I can sprite the ragged jumpsuits

**Comment by lunaman22** [comment]
you're not allowed to kill people for lethaling you as hulk since that's the only way you can be stunned
some admins said so a while ago

**Comment by ghost** [comment]
@lunaman22 that's a fundamental hulk flaw

**Comment by lunaman22** [comment]
tbh this seems like a bad idea, just make rules addendum stating that hulks are valid if they're shitters
-1

**Comment by sagaty13** [comment]
so you're downvoting the entire idea because of this flaw
based
