### ISSUE TITLE
Sith Lord Telekinesis

### ISSUE THREAD

**Issue by sagaty13** [HippieStation/HippieStationdeprecated2020#11778]
### **[Title]: ** 
Sith lord TK

### **[Implementation]: ** 
Give the sith lord kit a improved TK that is capable of grabbing people and throwing 'em around just like the mech gravitational catapult

### **[Why]: ** 
its fun and fits the gimmick

**Comment by Maroonenahmoron** [comment]
It would be too easy to throw someone against a wall in a stunlock and slowly kill them while you hide around a corner

**Comment by Majick1** [comment]
Is there a way to have a line of sight check?
