### ISSUE TITLE
Negrol

### ISSUE THREAD

**Issue by sagaty13** [HippieStation/HippieStationdeprecated2020#11777]
a chem that transforms you into a nigga called Tyrone, gives you a rollie and a glock with negrol bullets that kills and spreads negrol just like romerol zombies but nigerians

**Comment by Manly-Dwarf** [comment]
unfunny

**Comment by Manly-Dwarf** [comment]
lean also already exists

**Comment by sagaty13** [comment]
ok

**Comment by sagaty13** [comment]
many people talked about negrol on ooc looks like they actually want it

**Comment by AnthonyJNgo** [comment]
Unfunny.
