### ISSUE TITLE
Crippled can't move inside mech

### ISSUE THREAD

**Issue by sagaty13** [HippieStation/HippieStationdeprecated2020#11776]
if you got no legs you can't move inside a mech 
meanwhile a fucking brain (MMI) can move it

**Comment by AnthonyJNgo** [comment]
The MMI is hooked up with wires and uses brain waves to interact with the mech, this makes sense. You have no legs, you can't use the controls, and your brain is in your head, not inside a machine that allows you to interact with robotic interfaces.
