### ISSUE TITLE
Riot Shotgun entirely silent?

### ISSUE THREAD

**Issue by FrancisYorkMorgan** [HippieStation/HippieStationdeprecated2020#11783]
Issue reported from  Round ID: 41257 (Hippie Station)

Reporting client version: 512

I grabbed a Riot shotgun from the armory, as per usual, as (Insert shotgun copypasta here). It has 0 noises now. Shooting, cocking, and reloading are all silent.

**Comment by AnthonyJNgo** [comment]
Should be resolved with the new sec overhaul.
