### ISSUE TITLE
riot shotgun sprite is horrible

### ISSUE THREAD

**Issue by Manly-Dwarf** [HippieStation/HippieStationdeprecated2020#11784]
[Round ID]: # (If you discovered this issue from playing HippieStation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://tools.hippiestation.com/stats/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)
upstream testmerge
[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)
look at riot shotgun

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)
fix it

**Comment by ghost** [comment]
upstream merge related. i'll dig the old riot shotgun sprite up later

**Comment by ghost** [comment]
fixed whenever testmerge is next updated
