### ISSUE TITLE
Door remotes are not working

### ISSUE THREAD

**Issue by sagaty13** [HippieStation/HippieStationdeprecated2020#11797]
Something broke them, they do not do anything when you click airlocks

**Comment by Majick1** [comment]
I had one work just yesterday, which remote and what mode were you in

**Comment by Majick1** [comment]
Just tested all door remotes on the current build, they all work in all 3 modes

**Comment by sagaty13** [comment]
I think it was just a bug on the round or something related to time dilation, I tested them again and yeah they are good but there was a round where I tried to set engineering to emergency access but for some reason it wasn't working on any airlock
