### ISSUE TITLE
Suggestion: rework tgui

### ISSUE THREAD

**Issue by Timmeye** [HippieStation/HippieStationdeprecated2020#11790]
Whenever I click on something like a cargo console or a atmospheric alarm my game lags like hell, if it was reworked to reduce lag that would be good.

**Comment by yoyobatty** [comment]
Honestly, the only thing that works is resetting your PC. Windows 10 can do that, I would suggest doing that.

**Comment by Timmeye** [comment]
> Honestly, the only thing that works is resetting your PC. Windows 10 can do that, I would suggest doing that.

I restarted my laptop and it still lags

**Comment by yoyobatty** [comment]
Nah, I mean you can actually "reset" your PC. It essentially reinstalls but keeps most of your files and programs.

**Comment by Timmeye** [comment]
> Nah, I mean you can actually "reset" your PC. It essentially reinstalls but keeps most of your files and programs.

So basically I actually reset my computer and the tgui seems to still be laggy but I can Friccing use the cargo console now so its better than before, thanks.

**Comment by yoyobatty** [comment]
It's the best working solution so far. That, and maybe upgrading cpu.
