### ISSUE TITLE
New, hippie station?

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#11799]
We need a new station of our own, rather than re-using Box or /tg/ stations.

**Comment by ghost** [comment]
I might not personally agree with it, but I do think completely removing cargo from the game is a pretty bold move.

**Comment by ghost** [comment]
I FORGOT ABOUT CARGO TOO AHHHHHHHHH

**Comment by ghost** [comment]
![Untitled](https://user-images.githubusercontent.com/25724666/60144393-b8fb6700-97b1-11e9-8393-39a482e88856.png)

Inspired by Defficiency

**Comment by Manly-Dwarf** [comment]
I like the bridge and HOP placement a lot, actually. Maybe space them out a bit so you can't just thermite from escape into hop or caps or whatever. The less thermite can be abused, the better. Like what Metastation does to prevent you from just instantly getting into the caps, the windows and space.
I'd like more deathtraps though. The more deathtraps the merrier.
You could fix both of these problems by adding airbridges, like Goon's cogmaps.

Huge maint box right above Security, too many maintboxes in general.. There's a lot of potential for maint to just go around the whole station and be a scary deathtrap but instead it's just like a speakeasy under the library and that's it.

Could be cool.

**Comment by Timmeye** [comment]
It would be cool to have a new map. ALSO PLEASE ADD A FUSION CHAMBER OR THERMOELECTRIC GENERATOR SINCE MOST MAPS DONT HAVE THEM! Edit: nice you have a fusion gen

**Comment by Timmeye** [comment]
on the map the maint above sec is VERY close to the AI core and if someone places a strong enough bomb they may be able to take down the ai but that probably wont happen.

**Comment by Timmeye** [comment]
In the science area where would you launch toxin bombs for science points because the AI is south of science and xenobio is on the left of science and north and east is the station

**Comment by Timmeye** [comment]
I might not personally agree with it, but I do think completely removing T-comms from the game is a pretty bold move.

**Comment by cris5311** [comment]
Why the fuck would you remove T-comms?

**Comment by ghost** [comment]
![Untitled](https://user-images.githubusercontent.com/25724666/60220455-988ce480-9865-11e9-83fb-abea89a7e7c7.png)

**Comment by Timmeye** [comment]
> Why the fuck would you remove T-comms?

Its simple you see this was steams plan all along he was going to add a secret antag that you can get so he removed T-comms as his MASTER PLANNNN!!!! (jk I think he just forgot)

**Comment by ghost** [comment]
yeah that new map design i just posted has tcomms as a part of aisat

**Comment by Timmeye** [comment]
> yeah that new map design i just posted has tcomms as a part of aisat

that image is smol, but ok

**Comment by NautilusViper** [comment]
not enough maint, more maint pls

**Comment by AnthonyJNgo** [comment]
There are new map PRs open, you can continue conversation on your PR.
