### ISSUE TITLE
Shia LaBeouf Cult

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#11791]
[Title]: # Shia LaBeouf Cult

[Implementation]: # basically shia labeouf goes around giving people wedgies on He Will Not Divide Us flags in order to turn them into libtards. i dunno what the end goal is

idea originally by NonCancerAlias

[Why]: # we need better gamemodes

[Resources]: # HWNDU flag

@HippieStation/designers

**Comment by Manly-Dwarf** [comment]
second worst suggestion since ass penguins

**Comment by ghost** [comment]
ass penguins were the pinnacle of feature suggestions

**Comment by LaggyAsBalls** [comment]
This wouldn't be a bad idea, you could create a sort of, political war (much like gangs) where every player has a political side and is only able to be seduced by one or two leader that is able to radicalize who co-side (Shia, Adolf etc) with the political belief assigned to them at round start. Flags, could represent this. My idea is sort of like, a mix between gangs, cult and nations.

**Comment by MaterialisticThings** [comment]
Great idea

**Comment by ExpAntique** [comment]
fucking terrible idea
