### ISSUE TITLE
Health sensor + Ignitor will not combine with grenade casing.

### ISSUE THREAD

**Issue by prinnygod** [HippieStation/HippieStationdeprecated2020#11804]
Issue reported from  Round ID: 41576 (Hippie Station)

Reporting client version: 512

A recent update seemed to have broken this combo. The health sensor combined with an igniter will not go into a grenade casing.

**Comment by WarRage333** [comment]
They changes how grenades are made you always add wire then attach the desired addon (health analyser voice etc) tho you have to edit the settings before attaching me thinks.

**Comment by ghost** [comment]
not a bug.

you have to put the wire in, then the beakers, then click the grenade in your hand, and attach the health sensor, sans igniter, to the sole wire.
