### ISSUE TITLE
Pip-Boy for Traitors

### ISSUE THREAD

**Issue by Manly-Dwarf** [HippieStation/HippieStationdeprecated2020#11801]
[Title]: # edasffhfah

[Implementation]: # Hfsdfadggh

[Why]: # 
![hey hideandseeklogic](https://user-images.githubusercontent.com/33744849/60145164-319efb00-9793-11e9-9491-9c62ed891d9f.png)
![if you're reading this](https://user-images.githubusercontent.com/33744849/60145166-34015500-9793-11e9-9461-08347976b0e8.png)
![you're smelly](https://user-images.githubusercontent.com/33744849/60145173-35cb1880-9793-11e9-81d5-6761848f4a20.png)

[Resources]: # Eventual assets such as icons and sounds which you have and want to suggest related to this feature.

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers 

add it basically

**Comment by Manly-Dwarf** [comment]
+1 +1 +1 headmin approved and gregg approved

**Comment by Manly-Dwarf** [comment]
for clarification since the designers wanted it, you select whether or not you want the Pip or PDA in your preferences like how you do with pen or headset
the pen and headset uplinks must die for this, it is a worthy sacrifice

**Comment by MaterialisticThings** [comment]
+1

**Comment by Dystarra** [comment]
+1,

**Comment by Majick1** [comment]
+1, kill the headset and keep the pen, more convenient

**Comment by Manly-Dwarf** [comment]
pen more like smen

**Comment by cris5311** [comment]
keep the fucking pen

**Comment by Manly-Dwarf** [comment]
it's time for the jedi to end, cris

**Comment by cris5311** [comment]
Just fucking kill the headset, the pen is life, the pen is balance, the pen is salvation.

**Comment by ExpAntique** [comment]
+1 only if it's called the syndi-lad and its uplink screen has vault boy wearing a syndi hardsuit

**Comment by Manly-Dwarf** [comment]
@ExpAntique I can call it the syndie-lad but unfortunately these sprites are still 32x32, unless you want the damn thing to be larger than a person, a vault boy is not possible.

Would be fucking badass as hell though.
