### ISSUE TITLE
Feature Request: "Plumber Hat" atmos traitor item

### ISSUE THREAD

**Issue by Majick1** [HippieStation/HippieStationdeprecated2020#11813]
[Implementation]: Wearing hat allows you to ventcrawl and a 2 square radius jump-stomp attack. Can be thrown at a player or non-sentinent mob not wearing any headgear to take control of them for a certain amount of time/distance. Missing drops the hat on the ground.

Also would be open to a green cap that allows you to interact with ghosts.

[Why]: More fun items

[Resources]: Needs red baseball cap sprite with a letter on it that isn't M.

**Comment by Manly-Dwarf** [comment]
Doesn't seem like a very atmos-tech styled item, plus atmos tech already has some traitor items.
I can probably code this though. I don't like the headgear possession part, it'd make it a pain in the ass to manage, but everything else is piss easy.

**Comment by Majick1** [comment]
We can trade out the hat possession for another gimmick, and it could also work for janitor, just thought atmos fit the plumber niche more and would give them a way to antag besides plasma flooding. Maybe using a backpack water tank that shoots 3-4 tile jets of whatever reagent is in them.

**Comment by Majick1** [comment]
Ideas so far from discussion

-spin attack (hits every adjacent square with punch damage, pushback?)
-backpack water tank that lifts you and wets every tile you pass until you choose to land/run out of water
-short jump 1-2 tiles ahead that does bonus damage for landing on someone's head (ideally not enough to crit/gib?)
-maybe janitor instead of Atmos, or let both have it

**Comment by ghost** [comment]
make it say YIPPEEE and YAHOOOOO every time u do the jump
