### ISSUE TITLE
Reduced cargo prices for materials

### ISSUE THREAD

**Issue by Timmeye** [HippieStation/HippieStationdeprecated2020#11816]
[Implementation]: # Cargo materials should be reduced by have or atleast a little bit

[Why]: # Hippie station is a server where you can choose to do your job or not and some miners don't mine or the station doesn't even have miners at all so it would be better for cargo be able to order them cheaply then having no ores at all.

**Comment by Maroonenahmoron** [comment]
Diamonds are easily the main issue here, half/quarter the price of them and the amount given in crates

**Comment by AnthonyJNgo** [comment]
There should be a way to get materials with no miners, but this is not the answer.

**Comment by ghost** [comment]
maintenance periodic random spawn, yield proportional to if theres any miners. no miners to maint ores. could also make the system add trash to given areas like hallways   ~~like lifeweb~~
