### ISSUE TITLE
Shotguns can't shoot.

### ISSUE THREAD

**Issue by Manly-Dwarf** [HippieStation/HippieStationdeprecated2020#11826]
[Round ID]: # (If you discovered this issue from playing HippieStation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://tools.hippiestation.com/stats/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)
Upstream Merge. I wish yoyobatty was around to properly revert the guncode.
[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)
Try to shoot shotgun or contender.
Become disappointed.
It seems to work fine with the riot shotgun, but not a double barreled shotgun or the contender.
[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)
STEAMPOOOORT

**Comment by ghost** [comment]
i used a combat shotty against thanos earlier

**Comment by Manly-Dwarf** [comment]
dumb dumb it's the double barrel and contender

**Comment by Gandalf2k15** [comment]
Double barrel seems fine and the G13 seems completely borked.

**Comment by ghost** [comment]
g13 is broken
