### ISSUE TITLE
Gyrojet pistol and all foam force weapon sprites are broken from the upstream merge.

### ISSUE THREAD

**Issue by cb583** [HippieStation/HippieStationdeprecated2020#11823]
Issue reported from  Round ID: 0 (Hippie Station)

Reporting client version: 512

**Comment by Gandalf2k15** [comment]
Also includes 
Proto SMG /proto
wt550 /wt550
Mini Uzi /mini_uzi
Tommygun /tommygun
AR /ar
Gyrojet /gyrojet

**Comment by AnthonyJNgo** [comment]
@steamport
