### ISSUE TITLE
New curator system

### ISSUE THREAD

**Issue by JF260** [HippieStation/HippieStationdeprecated2020#11827]
**[Title]**:  Crafting: A DIY Guide

**[Implementation]**:  Right off the bat, i'd like to say that while this is a suggestion, I plan to code it myself if noone else beats me to it. This is more of a way to see if you guys would like this idea, and get feedback on how to balance it. 
     So first, the curators item beacon thing would be removed. Not eradicated from the code, but only admin-spawnable.
     What would it be replaced by, you ask? "Crafting: A DIY Guide." A book by this title spawns in the curators backpack, and gives some flavor text on use. "It contains a multitude of blueprints for items ranging from the mundane to devices you don't even recognize."
     The book by itself is useless, but a new section will be added to the crafting menu. All items in the first implementation will already exist, but be otherwise uncraftable. They all require the DIY book as a tool, which only one of exists.
     To give you an idea of what kind of stuff will be available for crafting and the ingredients they'll take, i'll display a few items I plan to add that vary greatly in power and crafting difficulty.

Leather Jacket:
2 cloth
Black crayon
Crafting: A DIY Guide (All of the craftables require this, but i'll only list it here.)

Insulated gloves:
5 plastic
Duct tape

Multitool:
2 metal
5 cable coil
1 battery

Curator's whip:
10 cloth
Black crayon
Duct tape
30 cable coil

Null rod:
50 holy water
20 metal
20 wood
5 gold

Flash:
20 metal
30 cable
1 lightbulb

Book of smoke:
3 bluespace crystals
10 paper
Pen
Strange object

Edit: in response to feedback, I'm canning the syndie shit for now.

**[Why]**:  To be honest, the curators current gimmick isn't great. It's cool and all, but it doesn't provide what the curator really needs: something to do for the round. You can choose the gear, but unless you're actively seeking out combat, you're still just book guy for the rest of the round. Besides, this is really cool and easy to implement.
**[Resources]**:  The only new item in the first implement will be the DIY book, which is just a book, so no new textures.

@HippieStation/maintainers

**Comment by carlopault** [comment]
This sounds pretty not gay, I say do it

**Comment by ExpAntique** [comment]
this seems cool but idk how it really connects with the curator. if he got a gimmick I would rather it be centered around collecting and sharing information than just being a bootleg scientist.

**Comment by carlopault** [comment]
> this seems cool but idk how it really connects with the curator. if he got a gimmick I would rather it be centered around collecting and sharing information than just being a bootleg scientist.

The DIY book is a book and teaches the curator, and anyone who reads it how to do something (in this case, crafting), which is what a lot of books do.

**Comment by Maroonenahmoron** [comment]
The whole idea of a curator is redundant given hippie’s play style, an artisan however would work very well.

Have the artisan be able to craft items better or new items that look ghetto but work just as well or better than their counterparts. The book should have a crafting speed penalty to those who aren’t artisans to encourage crew members to ask artisans to make something meaningful, perhaps masterful.
