### ISSUE TITLE
Singulo/tesla don't charge SMESes so they eventually get loose also the report issue button doesnt do dick.

### ISSUE THREAD

**Issue by geylard** [HippieStation/HippieStationdeprecated2020#11835]
[Round ID]: # (If you discovered this issue from playing HippieStation hosted servers:) 41899
[Round ID]: # (**INCLUDE THE ROUND ID**) yes
[Round ID]: # (It can be found in the Status panel or retrieved from https://tools.hippiestation.com/stats/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

eat my ass, its the wiring merge probably

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

Wiring from the engines don't hook up properly to the engineering SMESes at roundstart so their SMES never gets charged so their emitters eventually run out of power and it gets loose.

the end

**Comment by AnthonyJNgo** [comment]
I think this was an issue with the powernet update where wires autoconnected, not sure if still a problem or not.

**Comment by Maroonenahmoron** [comment]
Need to confirm if singulo engine draws power from grid or the single SMES to the right of the PA area

**Comment by AnthonyJNgo** [comment]
Resolved in #12204
