### ISSUE TITLE
remove escape pods

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#11857]
remove escape pods, they're for nerds trying to get green text

**Comment by Gandalf2k15** [comment]
No what if the shuttle is bombed or departures is gone

**Comment by 88scheming88** [comment]
>shuttle maxcapped leaving only unpressurized tiles
>"lmao escape pods only for greentext"
dumpass

**Comment by Manly-Dwarf** [comment]
+1

**Comment by cb583** [comment]
+1

**Comment by DaydreamPuppeh** [comment]
They are also for the times that the stupid antag maxcaps the shuttle before leaving
