### ISSUE TITLE
Burning sepia slime extract doesn't work

### ISSUE THREAD

**Issue by theworldo** [HippieStation/HippieStationdeprecated2020#11860]
[Reproduction]: the camera you get that's supposed to stop time where you take the shot is just a normal camera

**Comment by WarRage333** [comment]
Sepia - Creates a rewind camera. The camera can take a picture of a target, who will then rewind to the original spot and health status 10 seconds later, twice in a row. Limbs lost those 10 seconds re-attach, and new ones fall off. Can not revive someone from death. This can heal simple animals and objects.

https://github.com/tgstation/tgstation/pull/42933

https://github.com/tgstation/tgstation/pull/43870

tg fun removal
