### ISSUE TITLE
make miners start out with plasma cutters

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#11862]
playing as miner takes too long with KAs, and start of round if there are more than one miner will sometimes start beatin eachother over the mech.

**Comment by Majick1** [comment]
You mean more than one mech? You do start with a coupon that gives you a free plasma cutter.

**Comment by ghost** [comment]
the coupon cutter only works on the mech, I mean make miners start out with handheld cutters

**Comment by WarRage333** [comment]
Should just be a mining vendor reward if no science bad reserach it for you

**Comment by Gandalf2k15** [comment]
I agree with this actually, they should.

**Comment by enthethan** [comment]
honestly with how short rounds are this seems like a good idea makes being able to get the science items locked behind materials not be unavailable until 20 minutes into the round
