### ISSUE TITLE
ED-209 recipe DRAGnet -> Taser

### ISSUE THREAD

**Issue by haj325** [HippieStation/HippieStationdeprecated2020#11863]
[Title]: # ED-209 recipe DRAGnet -> Taser

[Implementation]: # The DRAGnet is in too limited of supply to make EDs efficiently, the taser would fix this by allowing you to go to supply for more

[Why]: # The DRAGnet is in too limited of supply to make EDs efficiently; Half the time captain/HOS run off with the DRAGnets, if someone hasn't broken into armoury from space

[Resources]: # Taser

**Comment by AnthonyJNgo** [comment]
+1

**Comment by mikolaj007** [comment]
+1
wiki lists the required thing to be a taser not the dragnet
when did this get changed?
EDIT: im gonna do some testing

**Comment by AnthonyJNgo** [comment]
PR made, closing this suggestion now, discussion can take place on the PR.
