### ISSUE TITLE
Unable to see cultist assets as AI

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#11874]
Round ID: 42572

I was examining a pile of leftover remains from a guy who somehow burned themselves to death and noticed that there was a cultist dagger on the floor. But the sprite was completely missing.

I thought it was a bug for just the sake of someone saying it was a toy dagger, but I noticed weird stuff was happening in medbay and people were circled around someone incapacitated. Once again, I examined the area and there was a rune on it, completely invisible.

This made it hard to figure out what the fresh hell was going on the station

**Comment by Manly-Dwarf** [comment]
The cultists might have used an obscure rune.

**Comment by ghost** [comment]
there's actually code that prevents silicons from seeing runes.

not a bug.

**Comment by Manly-Dwarf** [comment]
that's stupid as hell

**Comment by Maroonenahmoron** [comment]
Then what about the dagger? That was invisible too. I'm going to run a few quick tests.

**Comment by Maroonenahmoron** [comment]
Yeah, dagger shows up as invisible for silicons.

Why is this even implemented?

**Comment by ghost** [comment]
epic teegee balancing i guess

**Comment by AnthonyJNgo** [comment]
Not a bug, it's a feature.
