### ISSUE TITLE
[SUGG] Make the Mr. Meeseeks Box a Wizard Item (once fixed)

### ISSUE THREAD

**Issue by carlopault** [HippieStation/HippieStationdeprecated2020#11879]
The Mr. Meeseeks Box seems pretty cool, you spawn (negotiable) 1 immortal servant, until its "task" is complete (The task is typed out by the wizard when a player accepts to be Mr. Meeseeks), whatever that may be, and then you can spawn another. What determines when its task is complete may be the very hard part though. I am thinking the amount of points it costs could be 5-6. 

EDIT: The longer the Mr. Meeseeks is alive, the more and more insane they will become

**Comment by ExpAntique** [comment]
determining whether or not the task is completed sounds like it would be an absolute bitch to code

**Comment by carlopault** [comment]
> determining whether or not the task is completed sounds like it would be an absolute bitch to code

I think the easiest way to do it would be to allow the player playing as Mr. Meeseeks to determine for themselves when the task is finished, and press a button to poof themselves once they know they are done. If they don't poof themselves when they know they are done they get bwoinked.
