### ISSUE TITLE
[Feature Request ] Chance to get a shrapnel stuck on your head when caught on a explosion blast

### ISSUE THREAD

**Issue by sagaty13** [HippieStation/HippieStationdeprecated2020#11886]
title.
i can sprite the shrapnel :^)
![iojq13mkyruy](https://user-images.githubusercontent.com/51382956/62151412-a1def600-b2d6-11e9-861f-73576d5fc991.jpg)

hippie station the phantom pain

**Comment by yoyobatty** [comment]
This is the most lazy suggestion ever, you even confused the bot because you formatted it so poorly...

**Comment by yoyobatty** [comment]
Also, you can get shrapnel stuck from random debris, I've seen it happen. Are you sure about this?

**Comment by sagaty13** [comment]
I know but there's no cool sprite

**Comment by TrickyDickRichard** [comment]
and the shrapnel you get from random debris is random debris, like a rod or something, and not a random piece of shrapnel like BOSS has

**Comment by sagaty13** [comment]
EXACTLY

**Comment by sagaty13** [comment]
Why did you close this
what the fuck is wrong with you
