### ISSUE TITLE
[BUG] Nanosuit 0 TC Used Round Report

### ISSUE THREAD

**Issue by carlopault** [HippieStation/HippieStationdeprecated2020#11884]
Issue reported from  Round ID: 42764 (Hippie Station)

Reporting client version: 512

Sometimes when I buy a nanosuit as traitor, when the round ends, it shows I used 0 TC

**Comment by ghost** [comment]
did you use the Syndie Lad?

**Comment by carlopault** [comment]
> did you use the Syndie Lad?

Yes

**Comment by TrickyDickRichard** [comment]
> > did you use the Syndie Lad?
> 
> Yes

what did it cost

**Comment by ghost** [comment]
bug is unrelated to nanosuits, it's a bug with all non-standard uplinks (infiltrator uplink implants, syndie-lad, etc)
