### ISSUE TITLE
Raise cult required population to 15

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#11916]
Since cultists require at least 9 followers to summon their main objective, can you expect everyone under 15 players to even stay alive before a conversion? Chances are people suicide early on or get into accidents that leave them stranded outside of the station, making the cult win condition nearly impossible unless new people join up on the station.

There's no use dragging out rounds because cultists can't physically find any more people to convert, give them a better chance with more people pooled up.

**Comment by AnthonyJNgo** [comment]
Cultists can sacrifice them to make shards anyhow.
