### ISSUE TITLE
Garrote is broken

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#11915]
Ok so basically the garrote has two crafting phases the crafting one and the one where you add the cable to finish but it requieres 20 pipe cleaner which the pipe cleaner stack limit is 15 therefore you can't craft it

**Comment by Maroonenahmoron** [comment]
Yeah, I can confirm this

**Comment by cb583** [comment]
https://github.com/HippieStation/HippieStation/pull/11901

Have no fear, for the fix is here
