### ISSUE TITLE
Nerf Ayys

### ISSUE THREAD

**Issue by cris5311** [HippieStation/HippieStationdeprecated2020#11928]
[Implementation]: Reduce stuntimes

[Why]: Ayys have some BS stuntimes. That works out for what they are suppost to do: abduct, test and release station crew. But they dont on hippie, they murderbone, murderbone and murderbone.

[Example]: One Ayy took out the whole escape shuttle with 6 guys with one stun thing, without even having to cuff or otherwise disable anyone they hit once. Then another Ayy came in and started killing everyone while being assisted by the other guy.

**Comment by AnthonyJNgo** [comment]
Ayys got a recent nerf
