### ISSUE TITLE
Ass penguins 

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#11939]
_The ass penguin, or Aptenodytes forsteri rectum, is quite a strange creature, mainly due to it's infamous reproductive method, which many say is even worse than that of the xenomorph. The only similarity of the ass penguin's reproductive cycle to any other penguin is that it hatches from an egg. Even the egg is strange, however. It is first vomited into the rectum of a human (or primate) after being attacked and incapacitated by an ass penguin that has reached sexual maturity. After the egg is inserted, the penguin spits up a rapidly hardening resin, which keeps the egg in place, and prevents large bouts of flatulence from possibly detaching the rectum from the body, or the egg from the rectum. Once the egg hatches, the newly born ass penguin feeds on nutrients from the intestines of the host, before causing extremely severe pain, often described as "living hell" and "AGGHGHHHH I WANNA DIE" by victims, causing incapacitation in 99.99% of victims, and unconsciousness in 45.73% of them. After this occurs, the ass penguin chick uses built up gases in the rectum and large intestine in order to explosively launch itself out of the anus, where it will quickly flee, grow up, and repeat the cycle._

@HippieStation/maintainers

**Comment by Manly-Dwarf** [comment]
no

**Comment by ghost** [comment]
yes

**Comment by SireTurret** [comment]
no

**Comment by ghost** [comment]
yes

**Comment by TrickyDickRichard** [comment]
no

**Comment by ghost** [comment]
yes
