### ISSUE TITLE
Nanosuit Induced Lag

### ISSUE THREAD

**Issue by carlopault** [HippieStation/HippieStationdeprecated2020#11948]
[Round ID]: All rounds

[Testmerges]: It isn't caused by a test merge

[Reproduction]: Every time I equip the nanosuit, my game lags noticeably more. The way I fix the lag is by relogging.

**Comment by yoyobatty** [comment]
Does the lag last indefinitely or just until you relog?

**Comment by carlopault** [comment]
> Does the lag last indefinitely or just until you relog?

It lasts indefinitely unless I relog.
