### ISSUE TITLE
Possible issue? (When AI is controlling a cyborg and that cyborg gets transformed into a lifeform, you are stuck as that.)

### ISSUE THREAD

**Issue by v4ltages** [HippieStation/HippieStationdeprecated2020#11964]
Issue reported from  Round ID: 43788 (Hippie Station)
Reporting client version: 512

[Reproduction]: Play as AI then switch to your cyborg. Have a wizard that can transform people. Have that wizard transform the cyborg into some sort of lifeform.

[Issue]: You are stuck as that lifeform and are unable to reenter the AI

[Expected outcome]: Once that cyborg gets transformed into a lifeform the AI will get kicked out back into the AI core and that transformed cyborg will go into a catatonic state.

**Comment by ghost** [comment]
I think this is an issue.

**Comment by AnthonyJNgo** [comment]
This is a feature, not an issue. This is like shunting you an APC and when the APC gets destroyed you can’t return to core. Think about it. AI moves to shell. She’ll gets turned into biological being. AI core may send the signal out to retrieve the AI, but there is no shell to respond to it, you’re a carbon based life form.
