### ISSUE TITLE
Chaplain able to become anti-chaplain antags (Vampire and Devil)

### ISSUE THREAD

**Issue by Rando848** [HippieStation/HippieStationdeprecated2020#11966]
[Round ID]: # 43795

[Reproduction]: # I believe this is caused by the newly merged DYNAMIC mode, as I was prompted upon spawning "It's your lucky day! Choose your fate!" or something along that line, and was presented with a menu to select Traitor, Vampire, Devil, and Hivemind. In the past, I have actually become a vampire as a chaplain as well. However, this oversight seems to be more on DYNAMIC mode, than it is the same issue as before. The problem is that Devils and Vampires are directly countered BY chaplains, thus, the most powerful tool is ONE OF THEM. The other problem is that chaplains begin with a genetic trait that makes them arcanically null, or, in laymen's terms, anti-magic. Magic does not affect them, and they are incapable of casting. This makes vampire and devil physically impossible to be played by chaplain, thus ruining their antag status, or killing them outright in the case of vampire. I cannot provide any suggestions as to how to fix this.

**Comment by Neotwr** [comment]
#12645
