### ISSUE TITLE
Using the "Black market multitool" in hand makes it invisible

### ISSUE THREAD

**Issue by ADepressedPyroshark** [HippieStation/HippieStationdeprecated2020#12003]
Issue reported from  Round ID: 44193 (Hippie Station)

Reporting client version: 512

Nothing

it turned invisible. its still in hand just no sprite. I think I dropped it which still had problems, and using it again made it dissapear. You can't hold anything in that hand until you drop it for some reason.

This is bad due to the fact that if there are no admins on you don't have a multitool.

Steps
1. Play as lifebringer
2. go to the toolbox.
3. Use the multitool in hand.

I had finished hacking the machines when this happened, so that could do something

**Comment by AnthonyJNgo** [comment]
Confirmed the issue and took a look at it, I'll probably be able to fix this later.

**Comment by AnthonyJNgo** [comment]
PR opened.
