### ISSUE TITLE
Augmenting with a cyborg head removes all teeth and gives them the speech modifier thingy. Yeah, that.

### ISSUE THREAD

**Issue by TheTrigg** [HippieStation/HippieStationdeprecated2020#12016]
[Round ID]: Not on hippie server.

[Testmerges]: None.

[Reproduction]: Just augment someone with a borg head. Yeah, that simple. Not sure if there are any specific conditions for it to happen. I'd test it myself right now, but... Can't, currently.

[For Admins]: Nothing.

**Comment by yoyobatty** [comment]
Probably something to do with initialization since teeth were recently re-added and TG done made a lot of changes to surgery/bodypart code, I'm going to investigate in that area.

**Comment by TheTrigg** [comment]
Awesome, glad I was able to be useful on my first issue.

What surprises me is just how this passed under the radar for this long. I guess no hippie powergamer scimen likes to make robocops.

So do I click close issue already or..?
