### ISSUE TITLE
Cockroaches perpetually trigger automated turrets.

### ISSUE THREAD

**Issue by TheTrigg** [HippieStation/HippieStationdeprecated2020#12021]
[Round ID]: Doesn't matter.

[Testmerges]: None.

[Reproduction]: Spawn cockroaches in front of a turret.

Yeah. A scrubber backpressure thing happened and I noticed some turrets (on stun mode if it matters) were trying to shoot some cockroaches, and failing miserably.

[Gif of it happening](https://i.imgur.com/EPUEN0k.gifv)

**Comment by Manly-Dwarf** [comment]
it's a FEATURE

**Comment by TheTrigg** [comment]
It's pretty hilarious, to be honest.

But I see how, in a very very precise turn of events, the "scrambled" turrets could save an antag in a pinch.
I personally vote to actually keep this.

**Comment by ghost** [comment]
I agree with Triggered, this can result in a bit of !!!FUN!!!

Also, if the cockroaches are a bother just use the lethal setting to get rid of them.

Closing because I don't think this needs to be fixed.
