### ISSUE TITLE
Dynamic gamemode sometimes spawns 1-man abductor teams

### ISSUE THREAD

**Issue by TheTrigg** [HippieStation/HippieStationdeprecated2020#12025]
[Round ID]: It was round #1665 on beat! station. Yyyeah. They're actually nice guys so if you ask nicely they may give you the logs.

[Reproduction]: Not sure. It was a low-med-ish pop round. There were many ghosts, not sure how many clicked the popup to be an abductor. People were dying left and right. I had to leave before the round ended so I don't even know what the threat value was.

This is probably gonna be another one to go unfixed until marked as stale and later on just closed due to lack of anyone trying to fix it. Eh. I'm just here to report it and say that it happened.

**Comment by Manly-Dwarf** [comment]
why are you reporting beatstation bugs here

**Comment by ghost** [comment]
I'd wait a few days for someone on hippie to chime in and say they had the same thing happen before closing this issue though.

**Comment by ghost** [comment]
can vouch for this occuring on hippie to me multiple times

**Comment by ghost** [comment]
i've seen this happen before. dunno why though.

**Comment by TheTrigg** [comment]
Ahem Dwarf, beatstation currently runs on hippiecode.

As for a possible cause, it may be the same reason why mid-round nuke ops sometimes spawn with only 1-2 operatives. I dunno, just a hunch. Not a big brained like you guys.

**Comment by diegoxt45** [comment]
beat!station is fucking godawful shittiest admins shittiest players ever fuckign annihilate this man from existance and let them drown in their feces and piss and cum fuck beat! and fuck everyone who plays there

**Comment by diegoxt45** [comment]
i got a  2 
day ban there they extended it to a perma because i argued with the admin that banned me on their discord

**Comment by diegoxt45** [comment]
they have a rule 0 that's basically an end all be all rule to ban you if they don't like you

**Comment by diegoxt45** [comment]
what i'm trying to say is, do not fix their problem EVER

**Comment by TheTrigg** [comment]
They're nice guys... But they hate shitters.

From your comments alone I can tell you fit in that category.

Plus, y'know, BRAZILIAN ONLY STATION.

**Comment by diegoxt45** [comment]
> They're nice guys... But they hate shitters.
> 
> From your comments alone I can tell you fit in that category.
> 
> Plus, y'know, BRAZILIAN ONLY STATION.

I AM BRAZILIIAN YOU GODDAMN MORON.
NICE GUYS???? BACK WHEN THEY USED PARACODE THEY SERVABANNED ON MY SECOND OFFENSE FOR 2 DAYS BECAUSE I ACCIDENTALLY HIT A GUY ON ASIMOV LIKE ONCE WITH A STUN BATON.

LIKE ALL OF THEIR ADMINS ARE CONDESCENDIGN PIECES OF SHIT, I GOT MUTED FOR A WEEK FOR  TYPING SOME RANDOM SHIT IN A CHAT WITH NO PRIOR OFFENSE, THEY ARE FUCKING WEEBS, THEY HAVE LIKE 3 DIFFERENT PORN CHANNELS, AND THEY GOT A STOCKHOLM SYNDROME COMMUNITY TOO AFRAID TO MOVE ON FROM THEIR SHITTY ADMINNING, FUCK EM

**Comment by diegoxt45** [comment]
> > They're nice guys... But they hate shitters.
> > From your comments alone I can tell you fit in that category.
> > Plus, y'know, BRAZILIAN ONLY STATION.
> 
> I AM BRAZILIIAN YOU GODDAMN MORON.
> NICE GUYS???? BACK WHEN THEY USED PARACODE THEY SERVABANNED ON MY SECOND OFFENSE FOR 2 DAYS BECAUSE I ACCIDENTALLY HIT A GUY ON ASIMOV LIKE ONCE WITH A STUN BATON.
> 
> LIKE ALL OF THEIR ADMINS ARE CONDESCENDIGN PIECES OF SHIT, I GOT MUTED FOR A WEEK FOR TYPING SOME RANDOM SHIT IN A CHAT WITH NO PRIOR OFFENSE, THEY ARE FUCKING WEEBS, THEY HAVE LIKE 3 DIFFERENT PORN CHANNELS, AND THEY GOT A STOCKHOLM SYNDROME COMMUNITY TOO AFRAID TO MOVE ON FROM THEIR SHITTY ADMINNING, FUCK EM

YOU KNOW WHAT MY FIRST OFFENSE WAS? 
I  GOT BANNED FOR 60 MINUTES FOR HITTING A MIME AS A CHAPLAIN LIKE FUCKING ONCE BACK WHEN I JUST STARTED PLAYING THE GODDAMN GAME

**Comment by diegoxt45** [comment]
> They're nice guys... But they hate shitters.
> 
> From your comments alone I can tell you fit in that category.
> 
> Plus, y'know, BRAZILIAN ONLY STATION.

they are TRASH, worst of the fucking worst, weebs furries and 13 year olds abusing power because they feel like it and people still play there because it's the only BR station that doens't have ERP, jesus christ....

**Comment by Majick1** [comment]
Dude code lmao

**Comment by AntonioAugustoPostTeicofski** [comment]
ronaldo moment

**Comment by mikolaj007** [comment]
lol @diegoxt45, can confirm this happened on hippie

**Comment by ghost** [comment]
I guess if we find a fix we need to direct commit to master to dab on beat!

**Comment by ghost** [comment]
i've took the liberty of hiding the BR rant from ya'll

**Comment by Nopm** [comment]
mfw all the shitters have gotten to the point of shit talking our server in Reddit and GitHub

Now on a more serious note, I observed this happening multiple times. I suppose I should mention I manually forced a midround injection a few of these times, but one man abductor teams still show up naturally on dynamic, as I've also witnessed.

**Comment by SireTurret** [comment]
The BRtide is real

**Comment by SireTurret** [comment]
> mfw all the shitters have gotten to the point of shit talking our server in Reddit and GitHub
> 
> Now on a more serious note, I observed this happening multiple times. I suppose I should mention I manually forced a midround injection a few of these times, but one man abductor teams still show up naturally on dynamic, as I've also witnessed.

It's okay if you don't like us, we don't like you either.

**Comment by Nopm** [comment]
Nah man, I'm talking about the idiot above who spammed and got their comments hidden, not Hippie.

**Comment by SireTurret** [comment]
> Nah man, I'm talking about the idiot above who spammed and got their comments hidden, not Hippie.

yeah don't mind him he's the one who tries to improve hippie by being a seethe

I'll look into the code if someone else didn't do that already

**Comment by SireTurret** [comment]
https://github.com/HippieStation/HippieStation/pull/12027

eat your greens

**Comment by ghost** [comment]
beestation is trash

**Comment by ghost** [comment]
Nobody even mentioned Bee, idiot
