### ISSUE TITLE
Abductor galvanizer glands are hilarious, but too much.

### ISSUE THREAD

**Issue by TheTrigg** [HippieStation/HippieStationdeprecated2020#12029]
For those who don't recall, the galvanizer gland makes the abductee periodically shit out baby slimes. We're talking groups of 4-5 slimes every couple of minutes or so, may be less.

Although it's hilarious to see the station absolutely filled to the brim with slimes, there are too many of them, and they don't stop coming. On the round I played, the station was basically out of fire extinguishers because of just one boi who kept shitting out slimes. It was the sole reason of a shuttle call.

Again, hilarious, but majorly disruptive, which isn't even the point of the abductor experiments "in lore".

Implementation: Just nerf the hell out of it. Double the time between slime spawns, and make it so it only spawns 1-2 of them, I dunno. Just don't remove it, because it's still funny to see the poor humans shitting out slimes like they ate taco bell.

**Comment by diegoxt45** [comment]
surprisingly a shit take from a BR, go figure.

**Comment by WarRage333** [comment]
The problem i have with this is you get so cucked by the every 30 second vomit stun when you make the slimes

**Comment by diegoxt45** [comment]
lol he's talking about fucking RP, no, get out.

**Comment by SireTurret** [comment]
Even though the only thing I agree with in this issue is that the 30 seconds vomit stun is dumb, other than that the gland is hillarious and should NEVER get removed.

Besides, don't you brazilians have your own github/coder team?

**Comment by diegoxt45** [comment]
> Even though the only thing I agree with in this issue is that the 30 seconds vomit stun is dumb, other than that the gland is hillarious and should NEVER get removed.
> 
> Besides, don't you brazilians have your own github/coder team?

they don't, they actually  can't code for shit

**Comment by TheTrigg** [comment]
> don't you brazilians have your own github/coder team?

From what I've heard, beat! ran a codebase of its own for a while. But there weren't enough coders or something, so they stopped maintaining it and instead started running the server off other codebases.

> the gland is hillarious and should NEVER get removed.

I agree. What I proposed was to just nerf the amount of slime spawns as their numbers quickly get out of hand for as long as the abductee is alive.

Edit: Learning how github quotes work. heh.

**Comment by TheTrigg** [comment]
(I must have been really sleepy to not notice that typo, jeez.)

**Comment by ghost** [comment]
I think it might be nice to nerf the vomit but the slimes thing just means you need to carry around a spare extinguisher
