### ISSUE TITLE
Turning yourself into a slimeperson gets rid of abductor glands

### ISSUE THREAD

**Issue by TheTrigg** [HippieStation/HippieStationdeprecated2020#12033]
Yup. Title pretty much says it all.

I gave a dude doing xenobiology a gland. When I later wanted to use the Mental Interface Device to control his mind, he had no gland, and I noticed he had turned himself into a slimeperson. Since I knew he was an admin, I asked and he said he didn't do any varedit shenanigans or anything. 

Reproduction: Give a man an abductor gland and give them slime mutation toxin. Then check if he still has it.

This probably happens for any species, not only to slimemen.

**Comment by SireTurret** [comment]
it's a feature, kid.

**Comment by TheTrigg** [comment]
wait what

why?

**Comment by diegoxt45** [comment]
> wait what
> 
> why?

because you're morphing your entire being into another species, why would the gland stay? :feelsoldman:

**Comment by ghost** [comment]
Feature, not a bug. I think I'll close this for now, reopen if this is a big issue.

**Comment by TheTrigg** [comment]
> because you're morphing your entire being into another species, why would the gland stay?

Because the gland is metallic and artificial, and thus could not be altered in any together through a biologically-based morphing process. At the very least, the body would dump it - So, drop it on the ground. Funny, weren't you the one trying to mock me for using "RP" as a type of argument?

> reopen if this is a big issue.

After some testing on my own, I will note that this happens for any species transformation and gets rid of almost every organ except robot limbs, cybernetic implants and vocal cords - There may be more. It gets rid of fucken CAT EARS, DUDE.

Does that make it enough of a big issue to reopen?

**Comment by SireTurret** [comment]
>it gets rid of fucken cat ears

Good.

**Comment by diegoxt45** [comment]
lol furry
