### ISSUE TITLE
Heads of staff and security officers can be traitors on dynamic

### ISSUE THREAD

**Issue by SireTurret** [HippieStation/HippieStationdeprecated2020#12047]
[Round ID]: Happened on a lot of rounds, can't really specify which.

[Testmerges]: none

[Reproduction]: All you need to have is a lowpop server which runs dynamic, and BANG! I recall the HoP getting selected for traitor, sec officers, even the warden. This shouldn't be a feature.

[For Admins]: how much tokens should we give for this anyway STEAMPOOOOOOORT

**Comment by diegoxt45** [comment]
HoP's being traitors is a FEATURE, sec officers being ins't, so.... STEAMPOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOORT

**Comment by ghost** [comment]
I think I can make a quick fix for this.

**Comment by AnthonyJNgo** [comment]
@steamp0rt

**Comment by ghost** [comment]
shouldn't be happening. dynamic modes set restricted/protected_roles

**Comment by Toxici11i** [comment]
This happened recently, clockcult was spawned during dynamic due to 3 threat level round, mindshielded people became culties.
