### ISSUE TITLE
deletes mothpeople

### ISSUE THREAD

**Issue by notoriousBIGGIOS** [HippieStation/HippieStationdeprecated2020#12089]
![GRIM](https://cdn.discordapp.com/emojis/460846086785990656.png?v=1)

**Comment by DON-KARMA** [comment]
agreed

**Comment by Saturniidae** [comment]
Do it and i quit hippie station and join  bbbbeee or TG or yog or scalie STATION!!!

hippie number 1 with moths and lamps

**Comment by DON-KARMA** [comment]
> Do it and i quit hippie station and join bbbbeee or TG or yog or scalie STATION!!!
> 
> hippie number 1 with moths and lamps

good, fuck off
