### ISSUE TITLE
Toxin burn chamber's igniters don't create sparks

### ISSUE THREAD

**Issue by TheTrigg** [HippieStation/HippieStationdeprecated2020#12113]
Happens in every map. Current workaround is to throw a lit welder into the chamber, but that's annoying.

Reproduction: Pretty self explanatory. Just click the button and watch in discontempt as you realize you can't make tritbombs anymore.

![5KWe96AATh](https://user-images.githubusercontent.com/36010999/65792928-21ecd500-e13b-11e9-86ac-69d7df7a2f46.gif)

**Comment by Neotwr** [comment]
has been fixed in #12100

**Comment by yoyobatty** [comment]
Next time put "closes:" and link this issue and it will auto close once merged.

**Comment by TheTrigg** [comment]
Awesome. Bombing time.
