### ISSUE TITLE
BIG PDA FUCKUP

### ISSUE THREAD

**Issue by Toxici11i** [HippieStation/HippieStationdeprecated2020#12148]
Relevant PR from beestation; https://github.com/BeeStation/BeeStation-Hornet/pull/214
[Round ID]: 45005 (If you discovered this issue from playing HippieStation hosted servers:)
[Round ID]: 45005(**INCLUDE THE ROUND ID**)
[Round ID]: 45005 (It can be found in the Status panel or retrieved from https://tools.hippiestation.com/stats/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)
Enter a spacebar as the PDA ringtone as a traitor to reset it if you mistyped your pda code, explode.
Can also be used to find out if people are traitors.
Obligatory FUCK from coders right here
[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by yoyobatty** [comment]
https://github.com/HippieStation/HippieStation/commit/8101a305b9e0ed03e40fc88d91af30c11838732a 

Already fixed.
