### ISSUE TITLE
Nanosuit is advertised as having emergency medical systems, but this is not the case

### ISSUE THREAD

**Issue by Toxici11i** [HippieStation/HippieStationdeprecated2020#12144]
[Round ID]: 44971 (If you discovered this issue from playing HippieStation hosted servers:)
[Round ID]: 44971 (**INCLUDE THE ROUND ID**)
[Round ID]: 44971 (It can be found in the Status panel or retrieved from https://tools.hippiestation.com/stats/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)
Be in nanosuit, get critted, wait for emergency medical systems but none come as you slowly suffocate to death

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by yoyobatty** [comment]
Yeah it's for when you get hit. The PR I have open for it allows emagging to auto detect low heath.
Not sure if there's an IC description describing it as having auto emergency medical systems.

**Comment by Toxici11i** [comment]
There is

**Comment by yoyobatty** [comment]
I've updated in my nanosuit emag PR.
