### ISSUE TITLE
Allow the crew to snap Thanos

### ISSUE THREAD

**Issue by sagattyy** [HippieStation/HippieStationdeprecated2020#12150]
I won't tell you guys how to steal the infinity gauntlet, but it is possible and I did it once
But I couldn't snap even though it had every stone. Make it so if a crew member steals the gauntlet he's able to dust Thanos and call it a day

**Comment by ghost** [comment]
it's pretty easy to figure out tbh

there's many ways to pull it off

**Comment by ghost** [comment]
but thanos has to be dead or very stupid for you to do it.

**Comment by sagattyy** [comment]
nah the Thanos I fought was quite smart but... 
![db3](https://user-images.githubusercontent.com/18473245/66247456-24c76700-e6f3-11e9-9b08-722d17a14d30.png)

**Comment by epicss13gamer** [comment]
The only way I can see it being done is by delimbing thanos of that gauntlet.

**Comment by AnthonyJNgo** [comment]
Crewmembers should not be able to snap tbh, way too ripe for abuse.
