### ISSUE TITLE
Ghosts can ctrl-click on the Autodoc IX and it BEEPS

### ISSUE THREAD

**Issue by TheTrigg** [HippieStation/HippieStationdeprecated2020#12176]
Reproduction: Have someone on an ongoing surgery inside it. Ctrl-click as a ghost. BEEP.
Now spam click. The little influence your vengeful spirit can exert on the material realm is able to deafen people through the fourth wall.

Now this.. This is power.

https://cdn.discordapp.com/attachments/404474216730066947/632393216288751616/life-is-pain.mp4

**Comment by ghost** [comment]
BEEP

**Comment by AnthonyJNgo** [comment]
@steamp0rt This is probably not intended, please fix.
