### ISSUE TITLE
small chance to send a ghost or two back to lobby

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#12172]
[Title]:  small chance to send a ghost or two back to lobby

[Implementation]: small chance to send a ghost or two back to lobby each half hour or so, to retain dead players better

[Why]: to retain dead players better. population retention boost

[Resources]: none

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by AnthonyJNgo** [comment]
No, we will be rolling out more ghost content anyways. This is just inviting meta and grief.
