### ISSUE TITLE
Fix Abductors being able to talk like humans

### ISSUE THREAD

**Issue by sagattyy** [HippieStation/HippieStationdeprecated2020#12179]
title

**Comment by Toxici11i** [comment]
this isnt an issue and more of a feature.
Ayys should be able to speak like humans for the bare basics of communication.

Also, this can be bypassed via surgery even if it was implemented

**Comment by mikolaj007** [comment]
no, that's a bug
+1

**Comment by Manly-Dwarf** [comment]
it's a bug

**Comment by sagattyy** [comment]
it is a bug, they have their own "language" that works like a internal radio or whatever that is

**Comment by ElephantSeal** [comment]
it's a bug
