### ISSUE TITLE
Stands of the same owner can attack each other

### ISSUE THREAD

**Issue by private-tristan** [HippieStation/HippieStationdeprecated2020#12177]
as said above, stands of the same owner can attack the other stands, causing damage to the master of the stands
[Round ID]: 45232
[Testmerges]:none
[Reproduction]:as a wizard, get 2+ stands and have them attack each other

**Comment by diegoxt45** [comment]
how do you even

**Comment by AnthonyJNgo** [comment]
This is possible yes, but the question is should we prevent this through code, or should we just ban the nerds if done maliciously?
