### ISSUE TITLE
some chem suggestions

### ISSUE THREAD

**Issue by constatinus** [HippieStation/HippieStationdeprecated2020#12184]
[Title]: Chemistry suggestions
[Implementation]: Remove bicardine, kelotane, and anti toxin. Set sal acid and oxondrolone to heal above 25, not 50. Make sodium thiopental to be craftable in the lcass chemistry, and maybe reduce its metab rate to 0.2
[Why]:  Okay,  kelotane and bicardine and anti toxin are eay too powerful for such a simple chem. Just rrmove them, we already have stryptic powder, silver sulfadizine and charcoal.
Sal acid and oxondrolone should be a worthy investment to heal not just above 50, but a solid 25.
We have lotsa toxins in the lcass chems but no safe knockout ones. Make sodium thiopental be craftable, and make it a very complex recipe.
[Resources]: # Eventual assets such as icons and sounds which you have and want to suggest related to this feature.

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by ghost** [comment]
how about no u faggot

**Comment by WarRage333** [comment]
Hey buddy i think you got the wrong door.

TG's two blocks down

**Comment by SireTurret** [comment]
You seem like you're trynna order us around to do stuff. No, that won't work.

Additionally, I'm 90% sure this is an attempt at trolling us. If it's not, you're dumb and should stop trying to make any balance changes, even if this isn't a PR.

**Comment by karmaisblackandbluepilled** [comment]
i wish i knew your ckey so I could ban you

**Comment by ghost** [comment]
Dumb fucking idiot
