### ISSUE TITLE
Fix SMES room wiring for singulo power

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#12195]
https://puu.sh/EuK4C/25b290509a.png

The wire going up from the lower-left contains power from singulo going upwards onto the rest of the station's power grid, they aren't connected to the terminals even though there is a node below the SMES!

https://puu.sh/EuJFH/4762e33679.png

The power from the singulo instead charges a single SMES before being distributed across the station. Pretty useless since the tesla can easily perform over 200kW.

Integrate power from singulo generation into SMES room or make another SMES room for singulo-based power. This is why singulo/tesla gets loose when you don't set up the engine ASAP.

**Comment by AnthonyJNgo** [comment]
I'll do this tomorrow.

**Comment by AnthonyJNgo** [comment]
Resolved in #12204
