### ISSUE TITLE
New Antag for Chef

### ISSUE THREAD

**Issue by MrHeroKong** [HippieStation/HippieStationdeprecated2020#12201]
Kinda like Dead by Daylight.

In this Game mode, which in my opinion is best chef-only, The Chef's Only Objective is to get a body on all of his meat spikes my thought, was you could have the station go into lock down, where nobody could leave until a certain amount of machines were activated. Then when all the machines are activated, the emergency shuttle is called.

I think it would be a fun game mode that doesn't necessarily end in murder bone. and while you would be immortal, it would be more like zombie/ling/revenant immortality, where you can be killed by the crew, but rather than having the possibility of being dragged of to the crematorium, or having your dust spread, you become ethereal, like a cloak (or just a ghost) giving the crew time to start up generators while you regenerate in the kitchen. You all probably think this game mode is broken and will be a complete sweep for the cook, but to counter that, I would add in that a competent grey tide could save the entire station. the kitchen would be effectively locked down for the entire round, but not the freezer, where his meat spikes are. So unless he is a gay baby and camps his spikes, it is relatively easy to reset him.

It would require spriting and coding (minor tweaks for the death re spawn, i would think you could just use the zombie system and teleport them to the kitchen, which would be impenetrable, and I would like input for the amount of time that the entity should be ethereal after defeat) for the entity and coding the machines, (could just use pacman sprites).

I think it would be fun, I don't know how well it would work in practice though.

**Comment by AnthonyJNgo** [comment]
You need to take this idea and flesh it out and detail it out properly in a google doc or similar form of documentation. We have too many ideas that are spitballed at the moment that will never be implemented because we are so backed up at the moment.
