### ISSUE TITLE
[SUGG] ingame suggestion form

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#12237]
[Title]: ingame suggestion form

[Implementation]: have a button you can press in game, over the verbs tab, like the Wiki, Rules, etc button, that pops up a screen that lets you write suggestions in there. possibly have a bot post  them on the github? or just send to discord

[Why]: the more convenient it is to suggest things the more the average person (without a github account) might be liable to suggest things. And possibly even become curious and implicate themselves in development.

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by AnthonyJNgo** [comment]
We have re-enabled suggestions on the forums which can be accessed at the click of the button, so this is no longer an issue.
