### ISSUE TITLE
Syndie Stone Bull Charge Can Insta-Crit Thanos

### ISSUE THREAD

**Issue by carlopault** [HippieStation/HippieStationdeprecated2020#12232]
[Round ID]: #45777

[Reproduction]: If Thanos is beside a wall and the Syndie Stone holder bull charges at Thanos and hits Thanos while bull charging towards the wall that Thanos is adjacent to, Thanos gets critted in 1 second.

**Comment by ghost** [comment]
It used to be this way no matter _where_ thanos was standing.
