### ISSUE TITLE
Replace rusty toolboxes with new ones I made

### ISSUE THREAD

**Issue by Punkinguy** [HippieStation/HippieStationdeprecated2020#12245]
[Title]: # Replace rusty toolboxes with new ones I made

[Implementation]: # its just sprite shit just replace it lmao

[Why]: # cause the old ones look like someone lightly sharted on them

[Resources]: # 
https://cdn.discordapp.com/attachments/330146795311071263/639796928699170817/storage.dmi
here's the storage sprite file with the old toolboxes I made

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by karmaisblackandbluepilled** [comment]
+1 king

**Comment by TrickyDickRichard** [comment]
yes

**Comment by AnthonyJNgo** [comment]
This was merged a while ago.
