### ISSUE TITLE
Remove the beehives in hydroponics / fix bees

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#12247]
If bees are trying to chase down and attack someone and they get stuck between a wall/glass, they can flood the MC and quite possibly crash the server.

https://puu.sh/EzWYS/4d9b71de24.png

I've witnessed it happen at hydroponics with someone just walking by, they were standing outside and a bunch of bees were pressed against a glass window. Had to remove all the bees and restart the MC before everything worked just fine again.

**Comment by AnthonyJNgo** [comment]
Will have a mapedit giving botany a bee room that will stop this issue.
