### ISSUE TITLE
Science research Revamp

### ISSUE THREAD

**Issue by Higitus1** [HippieStation/HippieStationdeprecated2020#12280]
[Title]: # Material research prime

[Implementation]: Remove the research points that tick up over time and have it all unlocked by default, in return all of the science sstuff is simply limited by the materials you can work it.

[Why]: # Its a waiting game and while I am sure it works for servers the last longer hippie station tends to go for the 30 min to 1 hour mark. By the time you start getting the good stuff the shuttle is called and you gotta abandon it. This is a problem on highpop or lowpop and I think having it limited to Materials would be a good way to speed things up.

[Resources]: # I dont think any spires are needed just a bunch of coding.

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by karmaisblackandbluepilled** [comment]
no because science is really strong.
the wait is a balancing mechanic
-1

**Comment by Higitus1** [comment]
wouldnt the wait be able to be balanced out my new material requirements

**Comment by TrickyDickRichard** [comment]
higher costs would make miners need to do even more mining when they barely even come back from lavaland in the first place, and you already have a good amount of plasma, uranium, silver, and gold on the station -1

**Comment by mkikt4743** [comment]
-1 powergamers will play sci even more, if you want points just stagger bomb size at toxins launch
