### ISSUE TITLE
increased lag in the last month or two

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#12347]
I've no idea why, but for the last month or so i get really high lag especially when pop rises over 15.

**Comment by yoyobatty** [comment]
That's not a very descriptive issue. Not even the label bot could post a label it was so vague.
Have you tried any troubleshooting like updating your byond client, clearing byond cache, using CCleaner to clean your registry and temp files? Updating IE, clearing IE cache, switching from wifi to ethernet? There's a lot of stuff you can try.
