### ISSUE TITLE
make catbeasts selectable as roundstart race (HARDMODE)

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#12358]

**Comment by ghost** [comment]
code it,  flux

**Comment by mkikt4743** [comment]
Is this just so dudes can setup conveyor belts into grilles because 'muh valid'? Catfaggot is a punishment, not a reward, why would anyone use this?

**Comment by GuyonBroadway** [comment]
The other issue is people keep using it for antag fishing so they can get killed every round when not antag and not be punished for it.

**Comment by Toxici11i** [comment]
> The other issue is people keep using it for antag fishing so they can get killed every round when not antag and not be punished for it.

this doesnt make sense in the context of antag fishing - being catbanned bans you from all antags, but if you get converted to gang etc, itll offer you to ghosts and if no ghosts, lets you keep it (iirc)

**Comment by enthethan** [comment]
> The other issue is people keep using it for antag fishing so they can get killed every round when not antag and not be punished for it.

Not viable anymore as if you do roll antag you have to deal with being a pacifist clumsy valid target

**Comment by carlopault** [comment]
-1 never

**Comment by AnthonyJNgo** [comment]
This is a punishment, not a reward.

**Comment by Toxici11i** [comment]
@AnthonyJNgo 
<@668552269939343362>
just like playing on hippie is a punishment, and not a reward
