### ISSUE TITLE
Hotkeys not working, even in hotkey mode

### ISSUE THREAD

**Issue by GlassFedDockterr** [HippieStation/HippieStationdeprecated2020#12405]
Issue reported from  Round ID: 47163 (Hippie Station)

Reporting client version: 512

**Comment by ghost** [comment]
1. Open prefs
2. Go to game preferences
3. Ensure Hotkey Mode is Hotkeys
4. Go to custom keybindings
5. Scroll down
6. Click [Reset to Default]
7. Save setup
