### ISSUE TITLE
Add a Wall-Mounted Defib to medical for public use

### ISSUE THREAD

**Issue by zipzipzapityzoo** [HippieStation/HippieStationdeprecated2020#12418]
[Implementation]:  Ideally all it would do is allow for non medical staff to have access to a defibrillator in emergencies.  It could even still be locked in the medical storage room if we care that much, although those windows break the moment someone needs a band-aid.

[Why]: There is a common theme of not being able to defib a dead player in time because medical is either awol, haven't unlocked the lockers, simply incompetent or some combination of the three. Cloning takes significantly longer on average to revive a dead player, and other methods generally aren't available unless you set it up prior.

**Comment by carlopault** [comment]
+1 yes, very good

**Comment by Timmeye** [comment]
PR already made for this

**Comment by Neotwr** [comment]
#12682
