### ISSUE TITLE
Rename AppleJack to Apple Cider

### ISSUE THREAD

**Issue by ElephantSeal** [HippieStation/HippieStationdeprecated2020#12428]
[Title]: Rename Applejack to Apple Cider
[Implementation]: Rename it in the code
[Why]: because leftover TG stuff that needs to be coded out for obvious reasons
[Resources]: Applejack Replaced with Apple Cider
![Bad](https://user-images.githubusercontent.com/42258707/70964737-f2bf7300-205a-11ea-9709-82f3b1ab61fe.PNG)

**Comment by TrickyDickRichard** [comment]
rename it to Austin's All-American Apple Cider

**Comment by ElephantSeal** [comment]
I'm okay with this too
