### ISSUE TITLE
add a dedicated spin button for revolvers and pistols 

### ISSUE THREAD

**Issue by diegoxt45** [HippieStation/HippieStationdeprecated2020#12424]
[Implementation]: alt-click a revolver/pistol or something to spin it. a message will show to everyone nearby how cool you are 

[Why]: cool

**Comment by ElephantSeal** [comment]
you don't even play anymore

**Comment by diegoxt45** [comment]
> you don't even play anymore

BYOND broke

also internet sucking major chode for the past 2 months

**Comment by mkikt4743** [comment]
Diego aren't you banned?

**Comment by diegoxt45** [comment]
> Diego aren't you banned?

no

**Comment by carlopault** [comment]
+1 I wanna be able to play russian roulette
