### ISSUE TITLE
Suggestion: Move nanites to medical department

### ISSUE THREAD

**Issue by TheTrigg** [HippieStation/HippieStationdeprecated2020#12487]
Title. Gives med doctors something else to do and frees up sci from not getting new features due to "bro don't give sci more shit they can robust with"

Move the nanite stuff to, say, the patient rooms. People only use them for erp and hiding while they buy shit from their uplink anyway.

Plus, nanites are kind of fitting for Med anyway, and they can combo with some virology symptoms.
Hell, when have _you_ seen the nano-symbiosis symptom been used? Chances are it's fucking never.

**Comment by mkikt4743** [comment]
+1 on all concepts, roboticist should have acsess so sci can have nanite research or just remove nanite research

**Comment by enthethan** [comment]
for sure,leave science with the option to research the boards though

**Comment by diegoxt45** [comment]
this is good because it fucks over science

**Comment by Xizebo** [comment]
Good idea, more power to medbay.

**Comment by ghost** [comment]
-1 makes no logical sense, it's just a "fuck science" idea

**Comment by ghost** [comment]
brilliant suggestion to be honest.  too many cool things concentrated in science, why not let medbay be cool too?

**Comment by MrEpicSax** [comment]
-1 I'm with steamp0rt on this one. Also, I agree that something could be done with the patient rooms and that medical can be improved. The rest of your suggestion can be addressed by a change in player mindset and practice imo. If you're staffing medical and want nanites just go over to science and build / access them yourself by  either asking for entry or breaking in. It's far more logical.

Alternatively both departments could have them. Then you'd just have to remind science to research them or break in and do it yourself.

**Comment by Toxici11i** [comment]
the fact medical is so useless doesnt mean you should chop up science to put it in medical, instead, focus on improving medical

**Comment by TheTrigg** [comment]
I guess the main point of my idea was to give sci less stuff.
They get Xenobiology, they get Toxins, they get Robotics, they get Circuits, AND they get Nanites. That's a lotta cool stuff for a single department. Sure, it can be a "fuck science" idea.
Instead of removing one of those features like the typical /TG/ approach, my idea was to move one of these to another department. I thought nanites to medbay was fitting enough.

Now:

> this makes no logical sense

I hope I just explained the logical sense behind it. Nanites are fitting for medbay as they can synergize with virology and can be managed by med doctors while not much is happening on the station.
Plus, the "public" nature of medbay serves as a good way/excuse to inject people with a public nanite chamber.
Example: Got an assistant in crit? Epi pen and heal them with the power of nanomachines. Just don't tell them that you can now shock them remotely whenever you want. Spicy.

Now, if you meant something more IC by "logical sense", nanites are a poweful tool for healing. Medbay could use them. Nuff' said?


> Don't chop up science to put it in medical

My suggestion both makes Medbay more interesting _and_ opens up room for more stuff destined toward the Science department without people complaining that they are too powerful.
That's two birds with one stone in my book.

**Comment by MrEpicSax** [comment]
> 
> 
> the fact medical is so useless doesnt mean you should chop up science to put it in medical, instead, focus on improving medical

^ also this

**Comment by Mastergodown** [comment]
Fuck no. Sure, science has all that shit, but let me ask you, how much of it do you see is used? Toxins is near never used, same goes with xenobiology, R&D is used for research but never construction because NO OREEEEEEEEEEEEEEEEES, same goes with robotics. Nobody uses them because they either cant use its cool function (R&D and Robotics) or its not interesting or very time wasting (Xenobiology, Toxins) or not many people use it becauses its hard to understand (Nanites, Circuits, Toxins also falls under this). And medicals job is HEALING people. Sure, nanites can do that, but thats one thing taken away from science that wasn't used much anyways, so fuck all that anyone in medical would use it. Also, do know that they have Virology and Genetics are very powerful already and some people ACTUALLY USE THEM. Stop taking shit away from Science, what we really need is a fucking way to independently get ores so that the cool shit can be used. -1, +1 if we get a way to get ores independently. "Get mining access" doesn't count.

**Comment by Mastergodown** [comment]
> +1 on all concepts, roboticist should have acsess so sci can have nanite research or just remove nanite research

Also fuck you. NANITES SHOULD NEVER GET REMOVED, NOT TAKING ACCOUNT FROM TAKING IT AWAY FROM SCI

**Comment by mkikt4743** [comment]
no like naite research on the RnD console

**Comment by mkikt4743** [comment]
I think it unlocks new programs for nanites, and I know I've seen it in console

**Comment by Mastergodown** [comment]
o ok

**Comment by TheTrigg** [comment]
> how much of it do you see is used?

Toxin bombs are made all the time. Xenobio is underrated and has been given some speed buffs kind of recently. (imo the slimes are cute and fun to work with) The no ores limitation for robotics and circuits' complexity gates are true, though.
Well, Xenobio can make some bare minimum amounts of a couple of resources but again, they're very small. (Hey, maybe if those were buffed sci wouldn't need to rely so much on the miners)
Stuff could be done to make them more used, but nothing is happening because again, people don't want sci to get more stuff. Kind of a loop in which nothing gets done, honestly.

> thats one thing taken away from science that wasn't used much anyways

Exactly! And they hopefully will be used much more and to their full potential once in medbay.

**Comment by Mastergodown** [comment]
If sci doesnt use nanites, medical wont either. Also coming from the fact that nanites have to be researched, lets not.
