### ISSUE TITLE
New Hydroponics Bee Backroom

### ISSUE THREAD

**Issue by carlopault** [HippieStation/HippieStationdeprecated2020#12528]
![image](https://user-images.githubusercontent.com/48893662/72194487-b7a32c00-33db-11ea-87d7-40a9e6d89b21.png)

Botany doesn't have any bees so why not give em some bees in this area in maintenance. I made a new maint door at the holodeck control room and removed the space windows so that maintenance corridors aren't blocked.

**Comment by FantasticFwoosh** [comment]
I can't see why the wall couldn't be collapsed and it be some minor area to raise livestock and store common cross department service supplies. Something more to do with livestock would be nice, maybe biogen-printable synthetic animals/cube printer or something to save a trip to cargo.

If you need a idea of cheap plants, you could put some starthistle seed packets around. [I saw to it personally](https://github.com/tgstation/tgstation/pull/27214) that they drop seeds without uprooting themselves if you needed to gather more with some relatively low maintenance so are ideal candidate for the bee enviroment.

**Comment by mkikt4743** [comment]
cool now ju8st make it so it can have public access for livestock

**Comment by MaterialisticThings** [comment]
Botany does have bees

**Comment by ghost** [comment]
> Botany doesn't have any bees

they do. they used to spawn with an apiary setup roundstart, but this was bad for obvious reasons, so now they just start with a bee crate in the locker room.

**Comment by ghost** [comment]
yeah collapse that wall boi why have 2 rooms next to each other, with purposes not that different and the same APC

**Comment by AnthonyJNgo** [comment]
@FantasticFwoosh Has the right idea here, botany should just be upgraded.

**Comment by Maroonenahmoron** [comment]
isn't multiple mobs that group up like bees moving against a wall/window still a possible server crasher?

**Comment by FantasticFwoosh** [comment]
> isn't multiple mobs that group up like bees moving against a wall/window still a possible server crasher?

Bees can be easily controlled by inserting less trays for them to hoard resources and keeping a lid on bee spawns by taking out bees periodically using the ohk fly-swatter. [Beeswarms](https://github.com/HippieStation/HippieStation/pull/7299) should mean they wouldnt collide to lag but a nuclear bee-killing option like gas or chemical pipe injectors of insecticide (gas, foam or liquid) could work instead.

**Comment by AnthonyJNgo** [comment]
I'm going to make a forum section for this, and you can discuss this on there.
