### ISSUE TITLE
Reduce Badmin Gauntlet Player Requirement + New Admin Verb to Disable Gauntlet

### ISSUE THREAD

**Issue by carlopault** [HippieStation/HippieStationdeprecated2020#12529]
1. Since when does Hippie Station get 27 whole players? Thanos rounds work fine at 18 living players and above. 

2. Add a way to allow admins to disable the purchasing of the Badmin Gauntlet on raginmages bus rounds.

**Comment by Manly-Dwarf** [comment]
-1 simply because the suggestion is made by carlospaul

**Comment by AnthonyJNgo** [comment]
+1 to the first idea

**Comment by AnthonyJNgo** [comment]
PR opened for issue.
