### ISSUE TITLE
Hacking the medbay ChemDrobes gives you a white screen when you try to use them

### ISSUE THREAD

**Issue by cb583** [HippieStation/HippieStationdeprecated2020#12672]
Issue reported from  Round ID: 49842 (Hippie Station)

Reporting client version: 513

**Comment by LuisReyesX** [comment]
This happens with i think all departamental clothes vendors, it happens when you hack contraband and they dont have any

**Comment by mkikt4743** [comment]
also happens with engi and sec, just pulse the turn green wire again

**Comment by AnthonyJNgo** [comment]
Hmmmmm.
