### ISSUE TITLE
Pull requests to port over

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#150]
- [ ] https://github.com/HippieStation/HippieStation13/pull/17
- [x] https://github.com/HippieStation/HippieStation13/pull/19
- [ ] https://github.com/HippieStation/HippieStation13/pull/22 + https://github.com/HippieStation/HippieStation13/pull/30 + https://github.com/HippieStation/HippieStation13/pull/170 + https://github.com/HippieStation/HippieStation13/pull/331
- [x] https://github.com/HippieStation/HippieStation13/pull/23
- [ ] https://github.com/HippieStation/HippieStation13/pull/40
- [ ] https://github.com/HippieStation/HippieStation13/pull/49
- [ ] https://github.com/HippieStation/HippieStation13/pull/64
- [ ] https://github.com/HippieStation/HippieStation13/pull/68
- [ ] https://github.com/HippieStation/HippieStation13/pull/73
- [ ] https://github.com/HippieStation/HippieStation13/pull/75
- [ ] https://github.com/HippieStation/HippieStation13/pull/91
- [ ] https://github.com/HippieStation/HippieStation13/pull/104
- [ ] https://github.com/HippieStation/HippieStation13/pull/106
- [ ] https://github.com/HippieStation/HippieStation13/pull/107
- [ ] https://github.com/HippieStation/HippieStation13/pull/116
- [ ] https://github.com/HippieStation/HippieStation13/pull/119
- [ ] https://github.com/HippieStation/HippieStation13/pull/131
- [x] https://github.com/HippieStation/HippieStation13/pull/133
- [ ] https://github.com/HippieStation/HippieStation13/pull/135
- [ ] https://github.com/HippieStation/HippieStation13/pull/144
- [x] https://github.com/HippieStation/HippieStation13/pull/160
- [ ] https://github.com/HippieStation/HippieStation13/pull/172
- [ ] https://github.com/HippieStation/HippieStation13/pull/173
- [x] https://github.com/HippieStation/HippieStation13/pull/182
- [ ] https://github.com/HippieStation/HippieStation13/pull/186
- [ ] https://github.com/HippieStation/HippieStation13/pull/188
- [ ] https://github.com/HippieStation/HippieStation13/pull/189
- [ ] https://github.com/HippieStation/HippieStation13/pull/191
- [ ] https://github.com/HippieStation/HippieStation13/pull/192
- [ ] https://github.com/HippieStation/HippieStation13/pull/193
- [ ] https://github.com/HippieStation/HippieStation13/pull/194
- [ ] https://github.com/HippieStation/HippieStation13/pull/196
- [ ] https://github.com/HippieStation/HippieStation13/pull/204
- [ ] https://github.com/HippieStation/HippieStation13/pull/207
- [ ] https://github.com/HippieStation/HippieStation13/pull/214
- [ ] https://github.com/HippieStation/HippieStation13/pull/221
- [ ] https://github.com/HippieStation/HippieStation13/pull/222
- [ ] https://github.com/HippieStation/HippieStation13/pull/223
- [ ] https://github.com/HippieStation/HippieStation13/pull/225
- [ ] https://github.com/HippieStation/HippieStation13/pull/230
- [ ] https://github.com/HippieStation/HippieStation13/pull/234
- [ ] https://github.com/HippieStation/HippieStation13/pull/236
- [ ] https://github.com/HippieStation/HippieStation13/pull/245
- [ ] https://github.com/HippieStation/HippieStation13/pull/248
- [ ] https://github.com/HippieStation/HippieStation13/pull/249
- [ ] https://github.com/HippieStation/HippieStation13/pull/252
- [ ] https://github.com/HippieStation/HippieStation13/pull/271
- [ ] https://github.com/HippieStation/HippieStation13/pull/291
- [ ] https://github.com/HippieStation/HippieStation13/pull/294
- [ ] https://github.com/HippieStation/HippieStation13/pull/300 + https://github.com/HippieStation/HippieStation13/pull/302
- [ ] https://github.com/HippieStation/HippieStation13/pull/313
- [ ] https://github.com/HippieStation/HippieStation13/pull/314
- [ ] https://github.com/HippieStation/HippieStation13/pull/315
- [ ] https://github.com/HippieStation/HippieStation13/pull/318
- [ ] https://github.com/HippieStation/HippieStation13/pull/319
- [ ] https://github.com/HippieStation/HippieStation13/pull/327
- [ ] https://github.com/HippieStation/HippieStation13/pull/328
- [ ] https://github.com/HippieStation/HippieStation13/pull/329
- [ ] https://github.com/HippieStation/HippieStation13/pull/340
- [ ] https://github.com/HippieStation/HippieStation13/pull/342
- [ ] AN ADMIN TICKET SYSTEM (https://github.com/HippieStation/HippieStation13/pull/343) maybe just use the Yog one?
- [ ] https://github.com/HippieStation/HippieStation13/pull/344
- [ ] https://github.com/HippieStation/HippieStation13/pull/352
- [ ] https://github.com/HippieStation/HippieStation13/pull/359
- [ ] https://github.com/HippieStation/HippieStation13/pull/365
- [ ] https://github.com/HippieStation/HippieStation13/pull/369
- [ ] https://github.com/HippieStation/HippieStation13/pull/371
- [ ] https://github.com/HippieStation/HippieStation13/pull/378
- [ ] https://github.com/HippieStation/HippieStation13/pull/383
- [ ] https://github.com/HippieStation/HippieStation13/pull/388
- [ ] https://github.com/HippieStation/HippieStation13/pull/390
- [ ] https://github.com/HippieStation/HippieStation13/pull/393
- [ ] https://github.com/HippieStation/HippieStation13/pull/394
- [ ] https://github.com/HippieStation/HippieStation13/pull/395
- [ ] https://github.com/HippieStation/HippieStation13/pull/396
- [x] https://github.com/HippieStation/HippieStation13/pull/397
- [ ] https://github.com/HippieStation/HippieStation13/pull/398
- [x] https://github.com/HippieStation/HippieStation13/pull/400
- [x] https://github.com/HippieStation/HippieStation13/pull/403
- [ ] https://github.com/HippieStation/HippieStation13/pull/411
- [ ] https://github.com/HippieStation/HippieStation13/pull/412
- [x] https://github.com/HippieStation/HippieStation13/pull/425
- [ ] https://github.com/HippieStation/HippieStation13/pull/426
- [ ] https://github.com/HippieStation/HippieStation13/pull/427
- [x] https://github.com/HippieStation/HippieStation13/pull/436
- [ ] https://github.com/HippieStation/HippieStation13/pull/440
- [ ] https://github.com/HippieStation/HippieStation13/pull/444
- [x] https://github.com/HippieStation/HippieStation13/pull/450
- [x] https://github.com/HippieStation/HippieStation13/pull/455

[find more here](https://github.com/HippieStation/HippieStation13/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Amerged)

**Comment by JamieH** [comment]
- [ ] https://github.com/HippieStation/HippieStation13/pull/17
- [ ] https://github.com/HippieStation/HippieStation13/pull/19
- [ ] https://github.com/HippieStation/HippieStation13/pull/22 + https://github.com/HippieStation/HippieStation13/pull/30 + https://github.com/HippieStation/HippieStation13/pull/170 + https://github.com/HippieStation/HippieStation13/pull/331
- [ ] https://github.com/HippieStation/HippieStation13/pull/23
- [ ] https://github.com/HippieStation/HippieStation13/pull/40
- [ ] https://github.com/HippieStation/HippieStation13/pull/49
- [ ] https://github.com/HippieStation/HippieStation13/pull/64
- [ ] https://github.com/HippieStation/HippieStation13/pull/68
- [ ] https://github.com/HippieStation/HippieStation13/pull/73
- [ ] https://github.com/HippieStation/HippieStation13/pull/75
- [ ] https://github.com/HippieStation/HippieStation13/pull/91
- [ ] https://github.com/HippieStation/HippieStation13/pull/104
- [ ] https://github.com/HippieStation/HippieStation13/pull/106
- [ ] https://github.com/HippieStation/HippieStation13/pull/107
- [ ] https://github.com/HippieStation/HippieStation13/pull/116
- [ ] https://github.com/HippieStation/HippieStation13/pull/119
- [ ] https://github.com/HippieStation/HippieStation13/pull/131
- [ ] https://github.com/HippieStation/HippieStation13/pull/133
- [ ] https://github.com/HippieStation/HippieStation13/pull/135
- [ ] https://github.com/HippieStation/HippieStation13/pull/144
- [ ] https://github.com/HippieStation/HippieStation13/pull/160
- [ ] https://github.com/HippieStation/HippieStation13/pull/172
- [ ] https://github.com/HippieStation/HippieStation13/pull/173
- [ ] https://github.com/HippieStation/HippieStation13/pull/182
- [ ] https://github.com/HippieStation/HippieStation13/pull/186
- [ ] https://github.com/HippieStation/HippieStation13/pull/188
- [ ] https://github.com/HippieStation/HippieStation13/pull/189
- [ ] https://github.com/HippieStation/HippieStation13/pull/191
- [ ] https://github.com/HippieStation/HippieStation13/pull/192
- [ ] https://github.com/HippieStation/HippieStation13/pull/193
- [ ] https://github.com/HippieStation/HippieStation13/pull/194
- [ ] https://github.com/HippieStation/HippieStation13/pull/196
- [ ] https://github.com/HippieStation/HippieStation13/pull/204
- [ ] https://github.com/HippieStation/HippieStation13/pull/207
- [ ] https://github.com/HippieStation/HippieStation13/pull/214
- [ ] https://github.com/HippieStation/HippieStation13/pull/221
- [ ] https://github.com/HippieStation/HippieStation13/pull/222
- [ ] https://github.com/HippieStation/HippieStation13/pull/223
- [ ] https://github.com/HippieStation/HippieStation13/pull/225
- [ ] https://github.com/HippieStation/HippieStation13/pull/230
- [ ] https://github.com/HippieStation/HippieStation13/pull/234
- [ ] https://github.com/HippieStation/HippieStation13/pull/236
- [ ] https://github.com/HippieStation/HippieStation13/pull/245
- [ ] https://github.com/HippieStation/HippieStation13/pull/248
- [ ] https://github.com/HippieStation/HippieStation13/pull/249
- [ ] https://github.com/HippieStation/HippieStation13/pull/252
- [ ] https://github.com/HippieStation/HippieStation13/pull/271
- [ ] https://github.com/HippieStation/HippieStation13/pull/291
- [ ] https://github.com/HippieStation/HippieStation13/pull/294
- [ ] https://github.com/HippieStation/HippieStation13/pull/300 + https://github.com/HippieStation/HippieStation13/pull/302
- [ ] https://github.com/HippieStation/HippieStation13/pull/313
- [ ] https://github.com/HippieStation/HippieStation13/pull/314
- [ ] https://github.com/HippieStation/HippieStation13/pull/315
- [ ] https://github.com/HippieStation/HippieStation13/pull/318
- [ ] https://github.com/HippieStation/HippieStation13/pull/319
- [ ] https://github.com/HippieStation/HippieStation13/pull/327
- [ ] https://github.com/HippieStation/HippieStation13/pull/328
- [ ] https://github.com/HippieStation/HippieStation13/pull/329
- [ ] https://github.com/HippieStation/HippieStation13/pull/340
- [ ] https://github.com/HippieStation/HippieStation13/pull/342
- [ ] AN ADMIN TICKET SYSTEM (https://github.com/HippieStation/HippieStation13/pull/343) maybe just use the Yog one?
- [ ] https://github.com/HippieStation/HippieStation13/pull/344
- [ ] https://github.com/HippieStation/HippieStation13/pull/352
- [ ] https://github.com/HippieStation/HippieStation13/pull/359
- [ ] https://github.com/HippieStation/HippieStation13/pull/365
- [ ] https://github.com/HippieStation/HippieStation13/pull/369
- [ ] https://github.com/HippieStation/HippieStation13/pull/371
- [ ] https://github.com/HippieStation/HippieStation13/pull/378
- [ ] https://github.com/HippieStation/HippieStation13/pull/383
- [ ] https://github.com/HippieStation/HippieStation13/pull/388
- [ ] https://github.com/HippieStation/HippieStation13/pull/390
- [ ] https://github.com/HippieStation/HippieStation13/pull/393
- [ ] https://github.com/HippieStation/HippieStation13/pull/394
- [ ] https://github.com/HippieStation/HippieStation13/pull/395
- [ ] https://github.com/HippieStation/HippieStation13/pull/396
- [ ] https://github.com/HippieStation/HippieStation13/pull/397
- [ ] https://github.com/HippieStation/HippieStation13/pull/398
- [ ] https://github.com/HippieStation/HippieStation13/pull/400
- [ ] https://github.com/HippieStation/HippieStation13/pull/403
- [ ] https://github.com/HippieStation/HippieStation13/pull/411
- [ ] https://github.com/HippieStation/HippieStation13/pull/412
- [ ] https://github.com/HippieStation/HippieStation13/pull/425
- [ ] https://github.com/HippieStation/HippieStation13/pull/426
- [ ] https://github.com/HippieStation/HippieStation13/pull/427
- [ ] https://github.com/HippieStation/HippieStation13/pull/436
- [ ] https://github.com/HippieStation/HippieStation13/pull/440
- [ ] https://github.com/HippieStation/HippieStation13/pull/444
- [ ] https://github.com/HippieStation/HippieStation13/pull/450
- [ ] https://github.com/HippieStation/HippieStation13/pull/455

**Comment by tortellinitony** [comment]
455 was already ported. As you can see, it is causing conflicts. Why was it ported? I don't know.
