### ISSUE TITLE
TG Balance is shit and stunprods cant fit in backpacks.

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#1632]
In-Game report from tfw:
Revision info: 

>General description of the issue
Stunprods are too big for backpacks.

>What you expected to happen
For me to be able to carry my well crafted stunprod in my trusty backpack.

>What actually happened
I cant carry my well crafted stunprod in my trusty backpack.

>Steps to reproduce if possible
Make a stunprod and try to put it in a backpack.

**Comment by tortellinitony** [comment]
Good balance IMO

**Comment by PopNotes** [comment]
Yeah, prods should be just like spears. Don't change this, it hurts greytiders and that's something we need.
