### ISSUE TITLE
The AI can start with the hacked syndie lawset.

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#1634]
In-Game report from tfw:
Revision info: 

>General description of the issue
Was chilling and just observing the round and suddenly I get an ahelp. This ahelp is from the AI asking about his lawset. I check his laws and it's the fucking hacked syndie lawset. The AI is not a traitor, malf, or whatever the fuck. He just started with those laws. So that's pretty dope. Also no his laws weren't changed I checked, ya bastards.

>What you expected to happen
The AI to start with a lawset that doesn't allow him to kill the whole station.

>What actually happened
The AI started with a lawset that allows him to kill the whole station.

>Steps to reproduce if possible
Play AI.

**Comment by Carbonhell** [comment]
Might be related to law config having laws like asimov set to 1 instead of 0

**Comment by ghost** [comment]
Configuration issue, @JamieH needs to look into this as the configuration repository does no longer update the game, closing this as it's not related to the codebase
