### ISSUE TITLE
EVERYONE CAN BE ANTAG

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#1657]
In-Game report from carbonhell:
Revision info: 

>General description of the issue
>security officer
>traitor
find the issue

>What you expected to happen
loyalty implant peeps shouldn't be able to be antag

>What actually happened
they are becoming antags

>Steps to reproduce if possible
spawn as antag with a loyalty implanted role, find out how wrong it is

**Comment by j-mie** [comment]
Fixed
