### ISSUE TITLE
"Old Man Yells At Hippie Staff" end-round soundfile is the tg version

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#1658]
In-Game report from arzion:
Revision info: 

>General description of the issue
It's the version where "hippie" is cut out of it

>What you expected to happen
Have "hippie" mentioned

>What actually happened
Did not mention "Hippie"

>Steps to reproduce if possible
Finish a round, roll chance of hearing that soundfile

**Comment by KayeArray** [comment]
/tg/ stole this and removed our name from it? for shame

**Comment by GuyonBroadway** [comment]
bug was fixed closin
