### ISSUE TITLE
Viro buttons broke

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#1673]
In-Game report from higitus:
Revision info: 

I was able to use the viro button at the start of the round but after a while they just up and broke and didnt work, not even the little flash animation when you click on them happend.

>What you expected to happen= the doors to open

>What actually happened= The doors didnt open

>Steps to reproduce if possible= I actually dont know, it seemed to happen randomly. But it might be due to me trying to press the button when a monkey was blocking one of the doors from shutting

**Comment by ghost** [comment]
Was virology powered properly? Did a mouse bite through the wire or something?

**Comment by Higitus1** [comment]
Yeah I think they were, all the machines were still working as well as the other doors, just not the doors that I needed to actually open to leave viro.
