### ISSUE TITLE
bottled water doesn't show up in cola vending machines

### ISSUE THREAD

**Issue by cacogen** [HippieStation/HippieStationdeprecated2020#1681]
#890 added bottled water to the cola vending machines (https://github.com/HippieStation/HippieStation/blob/900dc9a38907e1bace27c37017ea8097ef46eae3/code/game/machinery/vending.dm#L753) but it doesn't show up in the vending list for some reason

**Comment by j-mie** [comment]
I assume @tortellinitony needs to port this over to our vending.dm file
