### ISSUE TITLE
Cannot shorten sec shotguns

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#1683]
In-Game report from higitus:
Revision info: 

I am not sure if this is the same for all shotguns but the sec one that you used to be able to shorten is not longer shortenable

>be able to put it in my backpack

>I got rused

>use sawblade on a combat shotgun

**Comment by tortellinitony** [comment]
shortenable combat shotguns sounds dumb but idk

**Comment by ghost** [comment]
Not a bug, been like that for ages.
