### ISSUE TITLE
Public garden fruit and vegtables are "empty"

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#1740]
In-Game report from ugonsthemad:
Revision info: 

>General description of the issue
The vegtables and fruit in the public garden are empty and seem to contain no regeants.

>What you expected to happen
For the fruit and vegtables to have regeants and such.

>What actually happened
The fruit and vegtables had no nutrients or regeants.

>Steps to reproduce if possible

Go to public garden, eat fruit or vegtables, be sad.

**Comment by j-mie** [comment]
Just checked - they do have reagents.
