### ISSUE TITLE
Mounted Turret causes HUD to fuck up

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#1801]
In-Game report from popnotes:
Revision info: 

>General description of the issue
Sitting on a mounted turret causes your HUD to shift out of bounds

>What you expected to happen
Not that

>What actually happened
That

>Steps to reproduce if possible
Sit on a turret who fucking designed this form

**Comment by Higitus1** [comment]
I think thats a feature, but regardless if you get on at the same time as someone else you get bugged and can never interact with anything again since both your hands are taken up

**Comment by PopNotes** [comment]
It's a shit feature and needs to be removed

**Comment by lcass** [comment]
They are seriously buggy , if you are on one and someone else climbs on your hud fucks up permanently. Need to port over the code from the particle rifles to make them automatic instead of just stupid 50 rounds burst fire.
