### ISSUE TITLE
Framerate dies horribly after rejoining, goonchat maybe? to blame

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#1811]
In-Game report from popnotes:
Revision info: 

>General description of the issue
read issue name

>What you expected to happen
not that

>What actually happened
that

>Steps to reproduce if possible
jesus christ this form is awful

**Comment by KayeArray** [comment]
stop playing on a potato and upgrade to a jacket at least

**Comment by j-mie** [comment]
@PopNotes not enough info.

**Comment by KayeArray** [comment]
old
