### ISSUE TITLE
Mentors can respond to certain administative prompts.

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#1812]
In-Game report from guyonbroadway:
Revision info: 

>General description of the issue
Somone changed the station name via charter and I saw the admin ntofication and could respond to it and presumably smite or reject too.

>What you expected to happen
Get an error permissions denied.

>What actually happened
I could send messaged directly to the charter user.

>Steps to reproduce if possible
Go mentor, have someone use chater -->SMITE!!!

**Comment by PopNotes** [comment]
I think this has more to do with Mentors being given more powers in order to do their jobs better, still kind of odd to see it though

**Comment by tortellinitony** [comment]
no this was unintentional, I'll look into fixing it later

**Comment by GuyonBroadway** [comment]
I think its because the charter just checks if someone is on the admins list and not for admin priveledges. Which it didn't need to till we added mentors.
