### ISSUE TITLE
Cryo UI is broken

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#1814]
In-Game report from cacogen:
Revision info: 

When clicking on cryo tubes, instead of the regular UI displaying, you get this message: The requested interface (hippiecryo) was not found. Does it exist?

**Comment by cacogen** [comment]
Happens with vending UIs as well: 

The requested interface (vending) was not found. Does it exist?

**Comment by tortellinitony** [comment]
I cannot replicate this.

**Comment by ghost** [comment]
Unable to reproduce.

Please try the following and feel free to (re)open the issue if you an still (re)produce the issue.

- Clear your BYOND cache from the BYOND settings
- Make sure Internet Explorer is up-to-date, and installed

**Comment by cacogen** [comment]
Fixed itself shortly afterward. Not sure if it was on my end or not.
