### ISSUE TITLE
spaces at the beginning and end of spoken sentences

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#1815]
In-Game report from cacogen:
Revision info: 

e.g.
[Common] Tim Buckley  says, " YOU FOOL " 
Barb E. Cue  stammers, " Gang g-gan-n-n-ng-g "

**Comment by Carbonhell** [comment]
Braylon Kanaga says, "AAAAAAAAAAAAAAAAAAAAAAAAA"

Braylon Kanaga says, "B"

Braylon Kanaga says, "C"

Braylon Kanaga says, "D"
seems like it was fixed somehow by tg i guess
