### ISSUE TITLE
bird persons to be able to rly flap the wings

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#1824]
In-Game report from dukeduki:
Revision info: 

>General description of the issue
when you emote *flap, all you get is text saying 'Poly flaps his wings'

>What you expected to happen
to be able to have 'animation' of wing flaps like you been able to do with the griffon suit

>What actually happened
nothing yet

>Steps to reproduce if possible
i dunno lols

**Comment by PopNotes** [comment]
not an issue
