### ISSUE TITLE
Various QOL HonkBot changes

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#1826]
To make reviewing, and merging upstream changes easier, i think we should add this

- @HonkBot should automatically add a `https://github.com/HippieStation/HippieStation/edit/{BRANCH NAME}/hippiestation.dme?pr={PR URL}` URL to the body, or comments of the PR whenever there are DME changes.

- @HonkBot should automatically add a `https://github.com/HippieStation/HippieStation/edit/{BRANCH NAME}/{FILE}.{EXT}?pr={PR URL}` to the body, or comments of the PR for all files that contain merge errors

**Comment by j-mie** [comment]
I'd like to see HonkBot automatically mirroring changes from tgstation.dme to our dme.

I'd also like a way to trigger a remerge for trusted users.

Automatically prune old upstream branches

**Comment by ghost** [comment]
Jenkins should check to see if the modified files are checked in hippiestation.dme only because then the port doesn't actually do anything.

**Comment by j-mie** [comment]
Closed due to https://github.com/HippieStation/HippieStation/issues/2931
