### ISSUE TITLE
When the shuttle launches it has no atmosphere.

### ISSUE THREAD

**Issue by GuyonBroadway** [HippieStation/HippieStationdeprecated2020#1849]
The shuttle becomes a cold vacuum upon launching so anyone without a spacesuit will slowly die.

**Comment by Carbonhell** [comment]
is this for any shuttle or just for that autistic meteor shittle

**Comment by ghost** [comment]
A METEOR DOES NOT HAVE ATMOS, ITS A FEATURE YOU DOOFUS

**Comment by Carbonhell** [comment]
^
