### ISSUE TITLE
toxin_reagents.dm is mirrored.

### ISSUE THREAD

**Issue by j-mie** [HippieStation/HippieStationdeprecated2020#1859]
https://github.com/tortellinitony/HippieStation/blob/master/hippiestation/code/modules/reagents/chemistry/reagents/toxin_reagents.dm -- This doesn't require an entire file to be mirrored.

Already missing commits: https://github.com/tgstation/tgstation/blob/master/code/modules/reagents/chemistry/reagents/toxin_reagents.dm

We should probably document which files are mirrored in whole, and which ones are partial mirrors.

**Comment by tortellinitony** [comment]
not anymore
