### ISSUE TITLE
Pool controller braks if you user wirecutters to turn on the red light

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#1884]
In-Game report from higitus:
Revision info: 

>If you try hacking the water cooler and eventually turn on a red light, if you close the menu all ability to interact with it is gone, from a menu popping up to even screwing it back into place

>For me to see if I can turn to water to freezing

>It stright up became busted

>Try to hack it an turn on a red light, close the menu and you lose any abilty to interact with it

**Comment by tortellinitony** [comment]
I can't reproduce this
