### ISSUE TITLE
No revolver in Detectives locker

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#1885]
In-Game report from nokington:
Revision info: 

>General description of the issue
No revolver in the detectives locker on round start

>What you expected to happen
There to be a revolver in the detectives locker at round start

>What actually happened
No revolver in the detectives locker at round start

>Steps to reproduce if possible

Ready up as detective.
Start game.
Open locker.
No revolver.
Cry.

**Comment by Carbonhell** [comment]
It is in the holster, along with the two speedloaders.

**Comment by Nokington** [comment]
yep I just saw that. Thats dumb. close this
