### ISSUE TITLE
goonchat is bugge

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#1898]
In-Game report from direvictory:
Revision info: 

>General description of the issue
I join up, when I do, the chat tells me I am either afk, experiencing lag or the connection has closed. If this takes longer than 30 seconds, it will automatically reload a maximum of 5 times.
And never loads up or anything.

>What you expected to happen
For the chat to work so I can see retarded spessmen mumble

>What actually happened
Wasn't able to see or hear anything, people talking, examine text, nothing.

>Steps to reproduce if possible
Join up hippiestation or tgstation

**Comment by Carbonhell** [comment]
resolved in pm
