### ISSUE TITLE
Traitor frame cartridge bugged

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#1935]
In-Game report from mechknight:
Revision info: 

>General description of the issue
Doesnt work as intended, can eat all TC

>What you expected to happen
To add all tc to the other uplink.

>What actually happened
All the TC was gone.

>Steps to reproduce if possible
It will open like other traitor PDAs just fine. However the bug starts when you try to put new telecrystals into it. It accepts them but does not add them to the total. Worse yet, the code it gives you to unlock the PDA later is a randomized fake one that doesnt work. If you use the virus to unlock it again, all TC will be gone.

**Comment by Carbonhell** [comment]
I think that's how it was coded. Although we might just scrap the idea and recode it to be more aggressive,ie "hack" into the enemy uplink, or something?

**Comment by KayeArray** [comment]
upstream
