### ISSUE TITLE
JUMP BOOTS

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#1939]
In-Game report from twg1:
Revision info: 

>General description of the issue
Used boots to jump over lava, landed safely onto a platform with no lava on it, yet still got lit on fire and critted from lava

>What you expected to happen
Not to take any damage, and to jump over the lava?

>What actually happened

Got lit up and died critted
>Steps to reproduce if possible

jump boots, lava 3 or 4 space gap, dirt platform on other side.

**Comment by KayeArray** [comment]
likely upstream

**Comment by j-mie** [comment]
marked at /tg/ as WONTFIX https://github.com/tgstation/tgstation/issues/25858
