### ISSUE TITLE
pAI's uneffected by Ion guns

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#1940]
In-Game report from higitus:
Revision info: 

>To be hones this really seems like a small issue, but pAI's can be put into ED-209s and beepskys which are then inturn uneffected by Ion guns

>The ED-209 to short out and stop moving

>It ran at the speed of sound and resulted in a head dying

>Put a pAI in a robot and try to ion gun it

**Comment by Higitus1** [comment]
Nevermind I was wrong, it was a midround event and not a pAI
