### ISSUE TITLE
Meteor shuttle wouldn't leave station

### ISSUE THREAD

**Issue by cacogen** [HippieStation/HippieStationdeprecated2020#1987]
The heads of staff authorised it to leave early, but the timer was stuck at 10 seconds. Apparently the meteor shuttle is bugged. Round was http://tools.hippiestation.com/stats/round.php?round=20017

![](https://puu.sh/wnmyr/920bf62a76.png)

**Comment by Carbonhell** [comment]
Happened again, seems to be linked to the shuttle type, yep.

**Comment by Carbonhell** [comment]
i witnessed it departing, not sure if it was sheer luck of if it got actually fixed.

**Comment by Carbonhell** [comment]
Yep,got fixed seems
