### ISSUE TITLE
changeling shield doesn't block anything for shit

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#1991]
In-Game report from spacedong:
Revision info: 

>General description of the issue

changeling shield barely blocks anything
>What you expected to happen

expected to block disabler shots
>What actually happened
I didn't deflect any of them and I got instantly stunned

>Steps to reproduce if possible
use the changeling shield thinking its good but it doesnt block anything

**Comment by KayeArray** [comment]
intended

**Comment by KayeArray** [comment]
balancing issue
