### ISSUE TITLE
NUKE OPS NUKE IS RADIOACTIVE

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2049]
In-Game report from kiltinaction:
Revision info: 

>General description of the issue
the nuke missile on nuke ops shuttle is radioactive and can crit nukies before they arrive on station

>What you expected to happen
not to be killed by radiation on my ship

>What actually happened
Hair fell out and got toxin on nukie ship, collapsed.

>Steps to reproduce if possible
Sit on the shuttle within range of missile

**Comment by ghost** [comment]
The nuke is not radioactive, https://github.com/tgstation/tgstation/blob/868d374fab11f6544b8dba8b1e98e2c27ee94a81/code/game/gamemodes/nuclear/nuclearbomb.dm

**Comment by GuyonBroadway** [comment]
/tg/ are reporting the same issue

**Comment by tortellinitony** [comment]
the plutonium core is radioactive inside, this is a bug
