### ISSUE TITLE
Chat window doesn't report anything 

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2050]
In-Game report from miksaleks:
Revision info: 

>General description of the issue
chat window wont work, i dont know why

>What you expected to happen
for the chat to normaly open and i normaly play the game

>What actually happened
came in to the game got the following message :˝Loading... If this takes longer than 30 seconds, it will automatically reload a maximum of 5 times. if it still doesn't work, use the bug report button at the top right wondow.˝

>Steps to reproduce if possible

**Comment by goonchaterrorguy** [comment]
had the same problem, It's because you have a old version of Internet Explorer, you need IE 11, try to update, on win7 you need sp1 for it.

**Comment by ghost** [comment]
Update BYOND and clear your cache
