### ISSUE TITLE
People being ejected from cloning prematurely, making cloning pointless

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2116]
In-Game report from cacogen:
Revision info: 

This was an issue pre-rebase, the issue seems to be characters whispering automatically in the cloner due to brain damage and this causing them to whisper succumb. Basically means cloning is useless because there's a good chance you'll die before cloning is complete.

**Comment by cacogen** [comment]
Related to https://github.com/HippieStationCode/HippieStation13-2/issues/345

**Comment by GuyonBroadway** [comment]
fixed via https://github.com/HippieStation/HippieStation/pull/2213
