### ISSUE TITLE
Crew manifest blank in HoP PDA

### ISSUE THREAD

**Issue by cacogen** [HippieStation/HippieStationdeprecated2020#2117]
If you have the HoP's PDA cartridge you can access the crew manifest. However, recently it's been blank any time I've tried to access it.

![](https://puu.sh/wunOp/88e849d760.png)

**Comment by Carbonhell** [comment]
This is a weird one.. I've confirmed it happens with cap pda too, and probably all PDAs, especially when you use it the first time. It seems to be a reference error at runtime, probs not fixable(?), but removing the cartridge and putting it back in seems to help,most of the time.

**Comment by j-mie** [comment]
Works here.
