### ISSUE TITLE
Clicking on chest with wielded defib paddles not doing anything

### ISSUE THREAD

**Issue by cacogen** [HippieStation/HippieStationdeprecated2020#2118]
Might just be a problem on my end, wouldn't be the first time I've had a problem with clicks not registering repeatedly for one specific thing, but when I tried to defib multiple bodies after wielding the paddles and aiming for the chest nothing happened.

When this has been an issue on my end reconnecting has fixed it, but that didn't work in this case.

**Comment by Carbonhell** [comment]
it works for me, might've been lag,probably?

**Comment by Carbonhell** [comment]
cannot be reproduc'd
