### ISSUE TITLE
Antag readout not printing to chat after round end

### ISSUE THREAD

**Issue by cacogen** [HippieStation/HippieStationdeprecated2020#2119]
Multiple rounds in a row last night ended without the antags being printed to chat. Just had that blue message that tells you whether you survived and whether you were stranded or managed to escape or not.

**Comment by Carbonhell** [comment]
we'd need better info for this bug man, because i see rounds ending just fine normally so it means something specific in that round broke, atleast the gamemode smh

**Comment by j-mie** [comment]
a round ID would be great

**Comment by tortellinitony** [comment]
it was fixed yesterday
