### ISSUE TITLE
Bombs not killing? 

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2123]
In-Game report from minimike1220:
Revision info: 

>General description of the issue

I stood next to a maxcap, it exploded, I was not harmed in said explosion.
>What you expected to happen
I should die.

>What actually happened
I didn't get harmed.

>Steps to reproduce if possible

?

**Comment by KayeArray** [comment]
edgecase

**Comment by j-mie** [comment]
yeah, bombs are complex, this shouldn't happen but it can, bombs are handled by upstream tho and I think they're better since June.
