### ISSUE TITLE
BLOB JANICART BUG

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2124]
In-Game report from twg1:
Revision info: 

>General description of the issue
If you're on the janicart thing that you can drive around and the blob attacks you and breaks it, you are stuck on an "invisible" destroyed janicart essentially and you cant get off and cant move.

>What you expected to happen
be off the cart and move around and run from blob

>What actually happened
couldnt move at all, blob killed me, i got fucked.

>Steps to reproduce if possible

get on janicart, have blob break cart while you on it, done.

**Comment by KayeArray** [comment]
>vehicle code
