### ISSUE TITLE
C4, at least on walls, is invisible

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2140]
In-Game report from tfw:
Revision info: 

>General description of the issue
When a C4 charge is planted on a wall it is completely invisible. No indacator what so ever that there is C4 on said wall.

>What you expected to happen
To be able to see a C4 charge planted on a wall.

>What actually happened
I got gibbed by my own nuke op cause there was no possible way for me to tell that he had planted C4 without him telling me. Nothing in the chat and nothing on the walls.

>Steps to reproduce if possible
Obtain a C4 charge and plant it on a wall.

**Comment by KayeArray** [comment]
fixed

**Comment by j-mie** [comment]
Confirmed.
