### ISSUE TITLE
UI Disappearing

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2157]
In-Game report from garlicbread:
Revision info: 

>UI disappeared after being shocked, can only see hands and intent

>expect my UI to not disappear after being shocked

>1. Be moth
2. someone tries breaking into HOP
3. Get shocked from ages away as he throws knives into the grille
4. can't access my inventory

pls fix

**Comment by Carbonhell** [comment]
you sure you didn't accidentally press f12
