### ISSUE TITLE
Unable to chrono-teleport more than a tile away after teleporting once using the chrono suit.

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2189]
In-Game report from arzion:
Revision info: 

The "target display" will remain stuck on you possibly permanently after teleporting once. You can only teleport one tile at a time or no tile at all.

**Comment by KayeArray** [comment]
people use this thing?

**Comment by KayeArray** [comment]
adminbus shit and upstream
