### ISSUE TITLE
Rule Breaker, General Shitter - No staff was online to handle!

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2205]
In-Game report from chemicalpills5379:
Revision info: 

>General description of the issue
Shitcurity borg, angry from past life after dying - permabriggs four players for small stuff, blames and has no evidence for brigging three of them. (No admins were on.)

>What you expected to happen
Harm the player (OOC NAME: Koffheat) into crit, stabilise, go to medbay and heal him up, warn him not to be a bad boy, send him out on his way.

>What actually happened
I killed a player for being a complete shitter,(Trying to steal All-Access ID during HoS line, yelling at me to get it for him, aggressively shoving me on the counter and throwing me into the HoS twice) which was out of hand - but i did not plan to kill them (I put them in early crit, and dragged them to medbay; but he spoke during critical so he prematurely died.) and dragged them to medbay so I could stabilise him and heal. But the robotist took his dead corpse and borged him into a security borg - he then proceeded to be a shitcurity and brig me for killing 2 people, tresspassing, and assualt. (Only ever killed Hans Wurstenburg) He then goes and perma-brigs four people (Including me) for small stuff. Two of the prisoners died (pretty sure 3) from meteor event, sucking them out into space. 

>Steps to reproduce if possible
Those steps would be a lengthy list bruv.

**Comment by Carbonhell** [comment]
Umm the issue reporter is for code issues...this is meant to go on ban requests
