### ISSUE TITLE
Sprite stuck holding flamethrower

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2210]
In-Game report from kiltinaction:
Revision info: 

>General description of the issue
I made a flamethrower, picked it up, put it in my bag. However, my sprite is still showing a flamethrower in my hand. I is also visible for others.

>What you expected to happen
For the held flamethrower to not show once I put it away

>What actually happened
Flamethrower persists even when picking up other items

>Steps to reproduce if possible

make a flamethrower and pick it up. Science uniform in testing lab

**Comment by KayeArray** [comment]
seems to be a common issue with multiple inhands, likely upstream

**Comment by j-mie** [comment]
Seems to be fixed.
