### ISSUE TITLE
AI sets off AI chamber motion alarm

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2228]
In-Game report from bobotheepic:
Revision info: 

>General description of the issue
The motion alarm in the AI chamber is on forever if someone is playing AI

>What you expected to happen
Motion alarm to trigger when somebody enters the AI chamber

>What actually happened
Motion alarm stayed active the entire round despite the only entity in the room being AI

>Steps to reproduce if possible
Be AI

**Comment by KayeArray** [comment]
fixed
