### ISSUE TITLE
harvested limbplant seems to be missing a sprite

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2229]
In-Game report from donglesaurus:
Revision info: 

>General description of the issue
limbplant is invisible

>What you expected to happen
to see the flower on the ground

>What actually happened
its invisible

>Steps to reproduce if possible

harvest limbplant

**Comment by Spankmaster1066** [comment]
@tortellinitony this is possibly the same issue as my lean?
