### ISSUE TITLE
Emagged Holodeck doesnt worj

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2239]
In-Game report from spartyn:
Revision info: 

>General description of the issue
emagging the holodeck and using the unsafe simulations does nothing

>What you expected to happen
get dangerous simulations

>What actually happened
nothing

>Steps to reproduce if possible
emag holodeck, try using an unsafe sim

**Comment by KayeArray** [comment]
was (((fixed))) by /tg/
