### ISSUE TITLE
You can buy modules twice as pAI

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2252]
In-Game report from bobotheepic:
Revision info: 

>General description of the issue
Clicking a module's purchase button twice before it updates will buy it twice and consume twice the RAM cost

>What you expected to happen
One "Remote Signaller" to be bought for 5 RAM

>What actually happened
Two Remote Signallers were bought for 10 RAM

>Steps to reproduce if possible
Become PAI
Double-click a module for purchase

**Comment by KayeArray** [comment]
fixed
