### ISSUE TITLE
Vaccines for shuttle-ordered viruses are broken

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2297]
In-Game report from carbonhell:
Revision info: 

>General description of the issue
When healed myself of the virus and taken a blood sample, the "create vaccine" option pops up in the PANDEMIC but it results in an empty bottle

>What you expected to happen

>What actually happened

>Steps to reproduce if possible
order a virus, inject it in yourself, use whatever chem the analyzer says you to,take a blood sample once healed, inject in beaker and put beaker in PANDEMIC, try to make a vaccine bottle,fail

**Comment by KayeArray** [comment]
upstream and old
