### ISSUE TITLE
Emergency generator in ancient station is invisible.

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2322]
In-Game report from oprayx73:
Revision info: 

>General description of the issue
The emergency generator on the ancient station is invisible you cannot see it.

>What you expected to happen
It's usually visible.

>What actually happened
It's missing a sprite.

>Steps to reproduce if possible

Take the engineer ghostrole pod and walk in there. it's missing a sprite.
http://i.imgur.com/Z08vUu6.png

**Comment by KayeArray** [comment]
duplicate of #2399
