### ISSUE TITLE
Borgs are not targeted by nuke ops turrets on the shuttle/pod.

### ISSUE THREAD

**Issue by GuyonBroadway** [HippieStation/HippieStationdeprecated2020#2347]
I'm sure turrets used to shoot anything not syndicate. and it means a borg can just jimmy fiddle the nuke into the crematorium no worries whatsoever.

**Comment by j-mie** [comment]
Confirmed.

**Comment by KayeArray** [comment]
probably upstream

**Comment by Blute1** [comment]
was this ever fixed

**Comment by Carbonhell** [comment]
yes
