### ISSUE TITLE
Chem tanks do not work.

### ISSUE THREAD

**Issue by GuyonBroadway** [HippieStation/HippieStationdeprecated2020#2351]
You can't open up watertanks to refill them like you used to and while you CAN open chem tanks you cannot refill them at all.

**Comment by tortellinitony** [comment]
yes they do

**Comment by tortellinitony** [comment]
Change it so that

when you unscrew `container_type = OPENCONTAINER`
and when you screw it back on `container_type = DRAWABLE`

**Comment by KayeArray** [comment]
yeah it gay pls fix

**Comment by GuyonBroadway** [comment]
this issue was fixed
