### ISSUE TITLE
AI with loadout (clown mask, cane, laceup shoes, ect.) when hit by meteor (or other gib effect I assume) sprays gibs and loadout items.

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2361]
In-Game report from memerino:
Revision info: 

I play AI, and I get hit by meteor.

I die, or just get severe dents

I get severe dents, but a pile of organs appear infront of me and my items from my loadout

Become AI, Spawn meteor heading straight for your core, and profit.

**Comment by GuyonBroadway** [comment]
*Feature

**Comment by j-mie** [comment]
Yeah, that's pretty funny tbh, I don't mind keeping it.
