### ISSUE TITLE
Locked ockers can't be resisted out of while moving.

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2381]
In-Game report from popnotes:
Revision info: 

>General description of the issue
read the title my guy

>What you expected to happen
being able to resist out of the goddamn locker

>What actually happened
couldn't resist out of the goddamn locker

>Steps to reproduce if possible
have someone drag you around in a locked locker

**Comment by PopNotes** [comment]
locked ockers what am I fucking retarded

**Comment by PopNotes** [comment]
the answer is yes

**Comment by tortellinitony** [comment]
Not a bug
