### ISSUE TITLE
invisible generator

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2399]
In-Game report from spartyn:
Revision info: 

>General description of the issue
the generator on the abandoned station is invisible and cant be interacted with

>What you expected to happen
use and see the generator

>What actually happened
cant see it and its not functional

>Steps to reproduce if possible
go to the back up power room and the uranium generator is invisible

**Comment by TungstenOxide** [comment]
Where exactly is this generator? I found a dm file for it but I'm not finding a sprite called 'generator' or any variation thereof.

**Comment by j-mie** [comment]
(E) (C) (M) icon = /icon (hippiestation/icons/obj/power.dmi) 
(E) (C) (M) icon_state = "portgen0_0" 

@tortellinitony these are invisible.

**Comment by KayeArray** [comment]
what the fuck I thought I fixed this

**Comment by KayeArray** [comment]
Tony I unmirrored that file for a reason

**Comment by TungstenOxide** [comment]
@banthebantz you wanna take another swing at this one?

**Comment by KayeArray** [comment]
if this still isn't fixed tony hangs
