### ISSUE TITLE
When a mentor disconnects it shows "ADMIN LOG: Admin logout [ckey]/([mob_name])

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2454]
In-Game report from jambread:
Revision info: 

>General description of the issue
When a mentor disconnects it shows "ADMIN LOG: Admin logout [ckey]/([mob_name])

>What you expected to happen
Not to happen

>What actually happened
It happened

>Steps to reproduce if possible
Be admin, mentor disconnect, message shows.

**Comment by DinduStuffin** [comment]
If you take the magazine out of some of the other gang weapons they become totally invisible too -- mag and gun both.

I believe the vintage rifle or whatever it's called is where I first saw this. I think the issue is that sprites just aren't assigned correctly.

**Comment by j-mie** [comment]
still an issue.
