### ISSUE TITLE
Instruments of all kinds are not working.

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2514]
In-Game report from jediluke1999:
Revision info: 

Whether it be the cyborg module or instruments in-hand, they haven't been working for the past couple days. I've checked my preferences, and others don't seem to be able to hear any music playing aswell.

**Comment by GuyonBroadway** [comment]
Instruments runtime out the butt.

![image](https://user-images.githubusercontent.com/22083966/28629231-c73c3dea-721e-11e7-984b-10f4cd4500c0.png)

**Comment by KayeArray** [comment]
can confirm this is gay

**Comment by ghost** [comment]
https://github.com/HippieStation/HippieStation/pull/2520

**Comment by Pyko1** [comment]
For a moment i though this was an issue about instruments causing runtimes and falling out when you put them in your butt.

**Comment by GuyonBroadway** [comment]
I will make an item that causes you to fart and an runtime cat to be generated when you use it because it "runtimes out the butt"

**Comment by ghost** [comment]
fix merbged :-DDD
