### ISSUE TITLE
Holodeck Winter Wonderland Gives non-holo wood

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2528]
In-Game report from twg1:
Revision info: 

>General description of the issue
The tree in the holodeck when on winter wonderland gives real wood when chopped down

>What you expected to happen
I was a chaplain and used my chainsaw hand to chop down the tree, i expected the wood to be some fake when i left and disappear.

>What actually happened
The wood did not disappear and i could continually farm wood by re-setting it to winter wonderland

>Steps to reproduce if possible

Holodeck -> winter wonderland -> chop tree -> get wood

**Comment by KayeArray** [comment]
just becomes a fake wooden chair for me

**Comment by GuyonBroadway** [comment]
So if you were to use the winter wonderland wood to build a fake door off the holodeck would it be a real fake door?

**Comment by KayeArray** [comment]
but you don't get any wood because it just becomes a 'holo' chair that turns to nothing when broken.

**Comment by KayeArray** [comment]
weird upstream issue
