### ISSUE TITLE
Holodeck doesn't recover from advanced darkness

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2556]
In-Game report from bobotheepic:
Revision info: 

>General description of the issue
Holodeck stays in a state of advanced darkness after the event ends

>What you expected to happen
Holodeck becomes visible after advanced darkness

>What actually happened
Holodeck stays dark

>Steps to reproduce if possible
Toggle advanced darkness and watch the holodeck

**Comment by JohnGinnane** [comment]
why'd you close, this is actually an issue upstream

**Comment by Pyko1** [comment]
isnt it fixed on upstream?

**Comment by JohnGinnane** [comment]
no, i tested it on weekend and couldn't fix it myself ((

**Comment by Pyko1** [comment]
:O

**Comment by JohnGinnane** [comment]
No longer an issue as it was removed by #7392
