### ISSUE TITLE
Misinformation on antag objects

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2564]
In-Game report from longtittytyrone:
Revision info: 

>General description of the issue / Im tired of wasting an entire antag round because the syndie or what ever catalog for item tells me an antag item does something it doesnt

>What you expected to happen / The toy riot dart gun to know out imediately like it says in the syndie catalog desc

>What actually happened / the dart does minor stam damage less then 1 rubber bullet of a non lethal shotgun shell and the only way to knock someone out is hit them 6-7 times

>Steps to reproduce if possible / buy a toy riot dart gun in stealth section of traitor syndie catalog

**Comment by KayeArray** [comment]
lol
