### ISSUE TITLE
Butts Disappearing when farted off

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2610]
In-Game report from blakek2:
Revision info: 

>General description of the issue
At ~1:30 EST 7/31/17, asses did not appear at all when farted off of people.  

>What you expected to happen
An ass to be generated

>What actually happened
An ass was not generated

>Steps to reproduce if possible
Spam Ctrl+F to reproduce

**Comment by GuyonBroadway** [comment]
A fix has been deployed for this but it has not been patched to the server yet. Closing.
