### ISSUE TITLE
Mindbreaker toxin lasts literally forever

### ISSUE THREAD

**Issue by carlarc** [HippieStation/HippieStationdeprecated2020#2613]
[Note]: #21351 (<B>Please enter the `Round ID` from the `Status` panel if you can!</B> If you believe the issue to be caused by a testmerge, please report it in its relative PR thread. State what the issue is from a "whats wrong" prospective. Issue reports should clearly allow maintainers to understand whats wrong and how to test/reproduce if that is not obvious. Avoid ambiguity. Start your issue report below both of these lines (or remove them))
dunno wtf to do with that so im gonna keep it

so a  bunch of rounds ago this dickhead syringe gunned me with 30u of mindbreaker toxin. around like 10 minutes later i STILL was hallucinating. i checked with my health analyzer and i had no mindbreaker in my bloodstream. fix please

**Comment by DinduStuffin** [comment]
Just tested this on CC myself. He's right. Once mindbreaker makes you hallucinate, it never stops.
Not only that, but it doesn't seem to do anything in small doses like 5u.

http://i.imgur.com/dsbHZcb.png Proof. All 30u of Mindbreaker is out of my system but it's still flooding me with hallucinations.

**Comment by KayeArray** [comment]
upstream issue?

**Comment by KayeArray** [comment]
nope not a bug, hallucination stacks will remain in your system for a long time after the mindbreaker has left, the real solution would be to clamp the value so it can't stack too high.

sidenote: you're supposed to treat hallucinations with synaptizine or haloperidol.

**Comment by tortellinitony** [comment]
If this happens again check your hallucinations var and report it if it's zero
