### ISSUE TITLE
You can crawl in space

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2741]
In-Game report from twg1:
Revision info: 

>General description of the issue
When critted in space and on just space tiles you can still crawl.

>What you expected to happen
Not be able to move at all

>What actually happened
I could crawl in any direction i wanted

>Steps to reproduce if possible

Go to space, get critted, press a direction to crawl

**Comment by tortellinitony** [comment]
You can crawl if there is a structure nearby or if you have gravity.
