### ISSUE TITLE
Admin idiocy

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#2805]
In-Game report from kutanoid:
Revision info: 

>General description of the issue
A faggot called Arco Vaughn just cut my legs and tounge, just for fun and admins refuse to do anything.

>What you expected to happen
Ban this faggot

>What actually happened
Nothing, cos admins are lazy fucks.

>Steps to reproduce if possible

**Comment by ghost** [comment]
lel

**Comment by DinduStuffin** [comment]
can we permaban you already

**Comment by KayeArray** [comment]
ingame issue reports were a mistake

**Comment by Thelolswat** [comment]
this is the new ban request format

**Comment by PopNotes** [comment]
it's a hell of a lot better than the headache that is the forums

**Comment by ghost** [comment]
^

**Comment by Pyko1** [comment]
gib on initial spawn if ckey is  kutanoid should fix this issue, no more admin issues.
