### ISSUE TITLE
Compact Defib Issue

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#3026]
In-Game report from minimike1220:
Revision info: 

>General description of the issue
Paddles from one hand in the other still count in being in the other hand.

>What you expected to happen

My hand to be empty
>What actually happened
It counted an invisble object

>Steps to reproduce if possible

Switch paddles in hand.

**Comment by KayeArray** [comment]
what the fuck are you on about

**Comment by ghost** [comment]
Unable to replicate, not enough information, Closing it
