### ISSUE TITLE
Keep getting grey slimes from different slime extracts.

### ISSUE THREAD

**Issue by challade** [HippieStation/HippieStationdeprecated2020#3076]
Round id: 22370

I keep getting grey slimes every time I inject any slime extract with plasma. Tried it with a fresh slime extract from the processor and two from the slime fridge, they all give me grey slimes as if they're grey slime extract. 
The three extracts I used were: green, purple, orange.

Edit: Afterwards, the slime extracts become grey.

**Comment by TheSpartyn** [comment]
I've run into the same problem. It seems that every slime extract has the properties of grey extract, blood gives cubes, plasma gives grey slime. Also using water seems to spawn glass and reinforced class.

**Comment by GuyonBroadway** [comment]
I've tried to re-create this but with no luck.

**Comment by WarRage333** [comment]
Had same thing happen to me, i put in multiple types of slimes in the processor at once, and it was upgraded with pico and super matter bin if that changes anything.

**Comment by KayeArray** [comment]
can confirm

**Comment by GuyonBroadway** [comment]
I've no idea why it happens on live and not a locally run copy of the exact same codebase...

Might be an issue with the slime extractor being upgraded.

**Comment by TheSpartyn** [comment]
It doesn't, for like 5 rounds minimum I've had the same problem from round start. I've never tried it with an upgraded extractor.
