### ISSUE TITLE
About Space Law Book Redirecting Page

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#3077]
In-Game report from dongilardoni:
Revision info: 

>General description of the issue
The book that shows the space law in the station (one with red cover) does not redirect the link to Space Law in the wiki, instead it 404's. Please fix it.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Tzeentchian** [comment]
I wanted to report about the Space Law book redirecting to a 404 page instead of: https://wiki.hippiestation.com/index.php?title=Space_Law

I'll supply photos later if you want.

**Comment by Tzeentchian** [comment]
The book I'm referring

![image](https://user-images.githubusercontent.com/20891384/30030083-5ffcfa26-9194-11e7-899c-86906248b306.png)

The Book content

![image](https://user-images.githubusercontent.com/20891384/30030063-4fc56454-9194-11e7-9d80-2d4610b853e0.png)

As you can see, it gives 404.

**Comment by j-mie** [comment]
fixed
