### ISSUE TITLE
Cargo shuttle doesn't work

### ISSUE THREAD

**Issue by tortellinitony** [HippieStation/HippieStationdeprecated2020#3093]
When launched, timer stays at 00:00 and the shuttle sits there. Hyperspace bubbles keep doing the animation of appearing and disappearing over and over.

Does not occur on /tg/station. Hippie only issue!

**Comment by GuyonBroadway** [comment]
Testing this on a local server and I cannot reproduce the problem. Could it be due to a testmerge?

**Comment by KayeArray** [comment]
https://github.com/HippieStation/HippieStation/pull/3106

should've been fixed upstream

**Comment by j-mie** [comment]
Seems to be fixed.
