### ISSUE TITLE
There are no cameras in the Lcasschem lab  main area.

### ISSUE THREAD

**Issue by GuyonBroadway** [HippieStation/HippieStationdeprecated2020#3111]
The AI can't see the area with the chem dispenser/heater and all around there.

**Comment by TungstenOxide** [comment]
That seems like it might be intentional, but I'll look into it anyway. Can an admin or someone confirm or deny if it's a feature?

**Comment by j-mie** [comment]
This is not intentional, a fix would be great @TungstenOxide

**Comment by TungstenOxide** [comment]
Okay im taking a look now. Might be a while since I need to learn how to use the map editor.

**Comment by TungstenOxide** [comment]
Also, erm, where exactly is this?

I legit cannot find it.

**Comment by TungstenOxide** [comment]
Ugh, I'm sorry. I'm really not familiar with science. Do you want a camera [here?](https://imgur.com/a/1piKm) Or am I miles off?

A picture would help.

**Comment by GuyonBroadway** [comment]
The Chasschem lab is the "testing lab" on vanilla boxstation.

**Comment by TungstenOxide** [comment]
Oh I'm an idiot lmao

[this thing, right? One sec.](https://imgur.com/a/V2ONY)

**Comment by KayeArray** [comment]
fixed
