### ISSUE TITLE
Fastfood's New Holotool bug

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#3220]
In-Game report from memerino:
Revision info: 

>General description of the issue
Some of the features of the holotool, like the multitool or wirecutters just DON'T work

>What you expected to happen
I would screwdriver a door's maint panel open and hack it using the test light, then I would crowbar the door and be able to greytide medbay by bolting it open.

>What actually happened
I screwdriver the door's panel open, and when I use my multitool, it says 'You need a multitool!', when I have my holomultitool out. I go to use wirecutters, and it says 'You need wirecutters!'.

>Steps to reproduce if possible
Screwdriver a door's panel open with the holotool, and attempt to hack the door using the holotool. Sit in dissapointment as you get arrested for breaking and entering by shitcurity.

**Comment by j-mie** [comment]
Confirmed.

**Comment by ghost** [comment]
@MoreRobustThanYou

**Comment by ghost** [comment]
I don't care anymore. Remove it for all I fucking care.
