### ISSUE TITLE
Clothing tab in crafting menu doesn't show up

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#3227]
In-Game report from gorramswags:
Revision info: 

>General description of the issue
When using the crafting menu, the clothing tab button does not work.

>What you expected to happen
For the clothing tab to show when I clicked the "Clothing" button

>What actually happened
Nothing on the first click, but on the second click of the "Clothing" button, it takes it to the tab after the clothing tab. For instance, if you are on the weapons tab and click the clothing tab once, nothing happens. When you click it a second time, it takes you to the food tab.

>Steps to reproduce if possible
Open the crafting menu and click the clothing tab button a couple of times from both food and weapons tabs.

**Comment by TrickyDickRichard** [comment]
The round ID was: 22558.

**Comment by KayeArray** [comment]
cannot reproduce
