### ISSUE TITLE
Can't shovel lavaland turf for sand.

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#3257]
In-Game report from superbdingaling:
Revision info: 

>General description of the issue

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by GuyonBroadway** [comment]
Upstream issue IIRC.

**Comment by j-mie** [comment]
You get volcanic ash, I think this is correct.

**Comment by j-mie** [comment]
Upstream issue too: https://github.com/tgstation/tgstation/issues/30616
