### ISSUE TITLE
Flamethrower for nuke ops is bugged

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#3293]
In-Game report from alexmika:
Revision info: 

>General description of the issue
Even though the flamethrower is supposed to have a suit that can handle the heat of the weapon, you can't walk straight whenever you're on fire. It's really annoying.

>What you expected to happen
I should be able to be on fire and walk straight.

>What actually happened
I was forced to walk in a bunch of different directions, sort of like when you're really drunk in game.

>Steps to reproduce if possible
Set yourself on fire while wearing the suit and having internals equipped/turned on

**Comment by KayeArray** [comment]
???????????????

**Comment by KayeArray** [comment]
this makes no sense
