### ISSUE TITLE
Credits being siphoned pretty often

### ISSUE THREAD

**Issue by cacogen** [HippieStation/HippieStationdeprecated2020#33]
People are breaking into the vault and siphoning cargo's credits pretty much every high pop round. The money isn't even worth anything. It's just fun to do. It sucks if you're cargo though, especially because you don't have access to the vault and aren't allowed in the vault to replace them (I got permabrigged once trying to replace them -- admins said it was allowed).

I have a couple of suggestions for making this harder to do:
1. Strengthen the door. It's too weak to hacking and RCDs. 
2. Make the bank machine require access. This is probably easier than number 1 and won't affect antags tasked with stealing the nuke core.

first issue report btw and it's not even a bug (^:

**Comment by Iamgoofball** [comment]
Did you guys not port the reinforced doors?

**Comment by cacogen** [comment]
Hippie has them, but I think you can just weld them to access the wires.

**Comment by Iamgoofball** [comment]
yeah but it also takes a lot of time

just protect it with security more often

**Comment by GuyonBroadway** [comment]
>Hippie
>Good Security

Pick one, even if an officer is on the ball they will get mobbed by the five or six something greyshits after his ID and baton/taser like it's their god given right moments after stepping out of the brig.

**Comment by Iamgoofball** [comment]
Do you have admins?

**Comment by Iamgoofball** [comment]
you don't already let sec murderize greytiders?

**Comment by cacogen** [comment]
we're like SoS-era /tg/, we've yet to change from being biased against security to being biased toward it

**Comment by Iamgoofball** [comment]
Should unleash security

**Comment by ghost** [comment]
BRB, nerfing security.

**Comment by ghost** [comment]
Actually, @Iamgoofball , working on something that you may or may not find interesting regarding stuns. I can keep you posted if you like.

**Comment by ghost** [comment]
Please do not use github as a chatbox

**Comment by Iamgoofball** [comment]
8====D

**Comment by Carbonhell** [comment]
or make the vault protected with turrets?ai upload has them,why not vault too? with proximity sensors and all the stuff, perhaps warn on entry rather than on siphoning, but obviously make a way to cut the proxy sensors(something that requires time) so that you can go stealth

**Comment by Iamgoofball** [comment]
make security do their job

**Comment by ghost** [comment]
If the cameras aren't secure cameras in the vault then they should be.
An alert to the AI or to the cargo console about the credits being tampered with would be a better way to balance this. So we can have sec reacting to the incident rather than people just doing it and forcing someone to defend it.

**Comment by tortellinitony** [comment]
I don't know what the heck this means but I've not seen them siphoned once in the past few days
