### ISSUE TITLE
Silencers

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#3300]
In-Game report from pyko:
Revision info: 

You cant fit stetchkin pistol with silencer in your pocket, but you can attack a silencer on to it while it is in your pocket.

**Comment by ghost** [comment]
wtf does this mean

**Comment by ghost** [comment]
stetchkin fits in pocket
stetchkin with silencer does not

put silencer on stetchkin in pocket to get silenced stetchkin in pocket

**Comment by ghost** [comment]
@McBawbaggings not really a problem, since as soon as you take it out you can't put it back in

**Comment by GuyonBroadway** [comment]
This is an issue as old as silencers themselves and fixing it would requrie lots of snowfake code and would be terrible all around.

**Comment by Pyko1** [comment]
Would be a simple to make it so that you have to have the gun in your hand and the silencer on other when you apply it tho.

as technically it is a bug/oversight.

**Comment by ghost** [comment]
just have attachment code require the thing to be in hand, like seclites on a taser

**Comment by Pyko1** [comment]
Also the bug really makes the size increase with silencer pointless as it takes only 1 click to take the silencer off so you can pocket the gun again and then just reapply silencer.

**Comment by GuyonBroadway** [comment]
In any case its an upstream issue and you really report it to /tg/. 

If it were me, I'd just make is so silencers didn't increase the W_Class at all. Spending money on a silencer is tradeoff enough as is.

**Comment by Pyko1** [comment]
reported to tg
