### ISSUE TITLE
mob health display

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#3417]
In-Game report from pyko:
Revision info: 

Beings such as morphs dont ahve any kind of indicator how much health they have.

**Comment by ghost** [comment]
probably intentional to make it so they can't be seen as fakes without examines?

**Comment by Pyko1** [comment]
I mean the character it self should know if its hurt or not.

**Comment by ghost** [comment]
OH
don't you have mob health in percentage in the status tab?

**Comment by Pyko1** [comment]
prolly has but, should be somekind of visual hud indicator

**Comment by Pyko1** [comment]
I mean could make a generic percentage health bar for all mobs, that get replaced by the human/alien health thinggies when applicable.

**Comment by KayeArray** [comment]
suggestion not a bug
