### ISSUE TITLE
Laughter demon bug report

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#3427]
Round ID: 22817

My ckey: TheMr.FoX

I managed to become a laughter demon thanks to the wizard, but I quickly figured out that the Blood Crawl skill didn't work, so basically I couldn't appear from blood.

Admin Tomorrow1918 tried to help me out, I cleared my cache and rejoined, the admin re-gave me Blood crawl in an attempt to fix it but it still didn't work.

**Comment by mlgdatboi** [comment]
fixed
