### ISSUE TITLE
Life casschem cannot be created

### ISSUE THREAD

**Issue by Maxammus** [HippieStation/HippieStationdeprecated2020#3452]
Had all the right ingredients and had them properly bluespaced but nothing happened.  Added more, bluespaced again and still nothing.  Looking at the code it seems it has the same datum name and id as the normal life reagent which i assume is the cause:

HippieStation/code/modules/reagents/chemistry/recipes/others.dm:
```
/datum/chemical_reaction/life
	name = "Life"
	id = "life"
	required_reagents = list("strange_reagent" = 1, "synthflesh" = 1, "blood" = 1)
	required_temp = 374
```
 HippieStation/hippiestation/code/modules/reagents/chemistry/recipes/medicine.dm:
```
/datum/chemical_reaction/life
	name = "Liquid life"
	id = "life"
	results = list("life" = 2, "methpos" = 2)
	required_reagents = list("superzine" = 1, "virogone" = 1,"defib" = 1)
	bluespace_recipe = TRUE
```

**Comment by Pyko1** [comment]
yeah it gets redefined, should be an easy fix tho

**Comment by KayeArray** [comment]
damnable id conflicts
