### ISSUE TITLE
STEALTH DOESN'T WORK FOR DISEASES :(

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#3488]
In-Game report from fredericusshrex:
Revision info: 

>General description of the issue
I had a disease with stealth 8 that was visible on the PanDEMIC machine. According to Hippie's wiki, it should be invisible past stealth 4. It was not visible on HUDs, however. I infected a monkey extracted his blood and looked at it in a beaker, I was able to see the disease and its cure, which is exactly what I didn't want to happen. I expected that the blood from an infected monkey would have the disease be stealthy enough not to show up on PanDEMIC, I expected only the original version would be "visible" and display symptoms. Or at least cure. 

>What you expected to happen
My disease should have been invisible.

>What actually happened
It wasn't. So it sucked in every other way, and so it sucked. Inhibited my tator round.

>Steps to reproduce if possible
Make a 4 or greater stealth disease and try to see if an infected person's blood shows it.

**Comment by KayeArray** [comment]
duplicate of #3503
