### ISSUE TITLE
Vending machines are out of date

### ISSUE THREAD

**Issue by j-mie** [HippieStation/HippieStationdeprecated2020#3499]
This https://github.com/tgstation/tgstation/blob/master/code/game/machinery/vending.dm is very different to: https://github.com/HippieStation/HippieStation/blob/master/hippiestation/code/game/machinery/vending.dm / https://github.com/HippieStation/HippieStation/blob/master/hippiestation/code/game/machinery/vending_types.dm

We need to either:
A) Not mirror the entire file
B) Update our mirror

Why did we mirror this file?

**Comment by tortellinitony** [comment]
Doesn't look out of date to me?

**Comment by KayeArray** [comment]
fixed
