### ISSUE TITLE
Virology is broken (This should be my second report on virology)

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#3503]
In-Game report from fredericusshrex:
Revision info: 

>General description of the issue
Transmittability is broken. Wiki says 5+ is airborne, I had a disease with 8-9 transmission that was only spread on contact. I also made a report about how stealth is broken, fix that too.

>What you expected to happen
5+ transmission to actually be airborne.

>What actually happened
It wasn't.

>Steps to reproduce if possible
Make a disease with 6 transmission and witness the discrepancy between the statements on the wiki and the reality of the in game code. I think some coder nerfed viro, and perhaps not wanting to draw attention to it didn't change this on the wiki. 

Also, I cancelled the first attempt at making a second report about virology accidentally, if I submitted it as incomplete instead of cancelling it, that was also an accident, so sorry if that's the case.

**Comment by KayeArray** [comment]
no clue but this is almost 100% upstream
