### ISSUE TITLE
emergency oxygen tank suicide no longer gibs

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#3558]
In-Game report from robustandrun:
Revision info: 

>General description of the issue
i wanna explode upon suicide but cannot due to my fav suicide method being broken

>What you expected to happen
gibs errywhere

>What actually happened
gibs still inside corpse

>Steps to reproduce if possible
kys (w/ emergency oxgeny tank)

**Comment by Pyko1** [comment]
I recall that was removed on purpose so that its not so easy to gib yourself if you happen to hear cult wants to sacrafice you.

**Comment by ghost** [comment]
that sounds like an OOC offense if anything, similar to people who get cult converted that suicide instead of ghosting

**Comment by Pyko1** [comment]
https://github.com/tgstation/tgstation/pull/26597

If you really must, just fill up your tank.

**Comment by tortellinitony** [comment]
Fixed
