### ISSUE TITLE
Rubber Shot Bugged (Might have just been an issue with massive lag spike)

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#3669]
In-Game report from fredericknippleburger:
Revision info: 

>General description of the issue
Fired rubber shot at pursuer with barkeep shotgun, rubber shot stayed in a sphere one tile off of the gun and appeared for two seconds and then vanished.

>What you expected to happen
I expected the pursuer to be hit by at least one of the rubber shot bullets as it was close and narrow quarters.

>What actually happened
The shot appeared to freeze for two seconds in an orange sphere as I said and then vanish. As I said this might have just been how I percieved it due to lag but that's what I saw.

>Steps to reproduce if possible
Fire barkeeps shotgun with rubber shot in the lower area of the courtroom. It might not matter but I had three different death chems in me and did not die from them despite having 52% blood level, which is odd. The fact that I was taking no suffocation damage mixed with how the rubber shot acted makes me believe it was an odd glitch instead of just a lag issue.

**Comment by PopNotes** [comment]
This sounds like a problem with one of the controllers

**Comment by tortellinitony** [comment]
Cannot be reproduced, probably lag
