### ISSUE TITLE
Spawned as Space Hotel Security. The gun they get requires a mindshield implant, as it has the mindshield firing pin. Does not spawn with implant, nor can get implant on hotel anywhere?

### ISSUE THREAD

**Issue by PineappleWolf** [HippieStation/HippieStationdeprecated2020#3779]
Issue reported from Round ID: 23280 (Hippie Station)

[Directions]: # (Include the Round ID from the Status panel or retrieve it from https://atlantaned.space/newSS13tools/round.php ! If you believe the issue to be caused by a testmerge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead. Explain your issue in detail, including the steps to reproduce it.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by KayeArray** [comment]
duplicate of #4086
