### ISSUE TITLE
Stealthminning admins are still visible by ''who'' command

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#3825]
Issue reported from Round ID: 23335 (Hippie Station)

[Directions]: # As an admin, when you stealthmin, you still appear when a player types in the ''who'' command in the playerlist.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by KayeArray** [comment]
can confirm, lol silly mins trying to hide from me

**Comment by ghost** [comment]
admins BTFO

**Comment by ghost** [comment]
fixed
