### ISSUE TITLE
Head of Personnel isn't protected job for vampires.

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#3872]
This is inconsistent with every other gamemode.

**Comment by mlgdatboi** [comment]
its non implanted

**Comment by ghost** [comment]
https://github.com/HippieStation/HippieStation/blob/master/code/game/gamemodes/traitor/traitor.dm#L14
https://github.com/HippieStation/HippieStation/blob/master/code/game/gamemodes/changeling/changeling.dm#L21

https://github.com/HippieStation/HippieStation/blob/27e4596befb785dd2db7f75a7cd2a28f91cd8b68/code/modules/jobs/job_types/captain.dm#L101
