### ISSUE TITLE
Unable to recall the emergency shuttle

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#3880]
I don't know what else to say but any method of recalling the shuttle does not work. This includes so far; using the console, Cancel Shuttle verb and triggering CENTCOM RECALL (although classified message still shows on the consoles).

There is feedback that someone has recalled the shuttle but it doesn't actually happen. I'm not sure how this is happening but something needs to be done quick.

EDIT: My theory of this is that when the round starts, the shuttle crisis event triggers, somehow not calling the shuttle there and then but making all shuttles unrecoverable.

**Comment by GuyonBroadway** [comment]
if its the shuttle autocall system this may be an upstream issue. Will check

**Comment by JamieH** [comment]
cc @mrstonedone

**Comment by GuyonBroadway** [comment]
fixed upstream.
