### ISSUE TITLE
Toxins Mixing Room inner door won't open/pressurize

### ISSUE THREAD

**Issue by GallusMarcius** [HippieStation/HippieStationdeprecated2020#3941]
[Directions]: 23448

[For Admins]: At the end of the testing an admin removed the door so I could continue toxins, but that was after he himself (DinduStuffin) could not open the door either.

Basically the door will be stuck in a permanent pressurizing stage, and won't open. It is rather frustrating as it makes the whole toxins lab unusable for anything and makes antag bombing way more harder or costier on telecrystals.

**Comment by PopNotes** [comment]
This has been an issue for awhile now, it probably has something to do with the way depressurizing works in the first place

**Comment by GuyonBroadway** [comment]
Its also an upstream issue.

**Comment by Spacedong** [comment]
bug as old as time

**Comment by JohnGinnane** [comment]
This is fixed, I've had no issues in the last few days when playing toxins
