### ISSUE TITLE
Machines are borked 

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#3943]
In-Game report from dindustuffin:
Server info: 23448 (Hippie Station)

>General description of the issue
Biogenerators and autolathes (and probably more) are busted

>What you expected to happen
Them to accept their respective materials and actually work

>What actually happened
The autolathe took no metal, the biogenerator did literally nothing.

>Steps to reproduce if possible
Use them and see for yourself.

**Comment by KayeArray** [comment]
Still not sure what this is and if it's upstream or not

**Comment by ghost** [comment]
its upstream, blame @kevinz000
