### ISSUE TITLE
CR-20 SMG default 2 round burst does not fire

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4070]
In-Game report from fredericknippleburger:
Server info: 23571 (Hippie Station)

>General description of the issue
The default 2 round burst setting of the CR-20 SMG does not work. I noticed this a few rounds ago when I died from it when I tried to kill the captain as an op and thought I must've just accidentally removed the mag. I noticed it again as even the donk soft SMGs found on the syndi outpost don't fire on two round burst.

>What you expected to happen
I expected them to actually fire on two round burst as killing the captain in my op round would've won me the round.

>What actually happened
The SMG didn't fire or produce any message in the chat, I tested the donksoft on semi auto and it worked fine but I didn't test the standard CR-20 on semi-auto as I didn't notice the different setting the top left of the HUD.

>Steps to reproduce if possible
Take any CR-20, donksoft or real (donksoft from syndi outpost, CR-20 from op uplink) try to fire it without tampering with the magazine or the fire setting and see if it works on admin sandbox or something similar. I tampered with the donksoft SMG taking out the magazine and putting another in and it wouldn't fire on two round burst no matter what I did. The CR-20 firing only on semi auto is fine, but the issue is that semi auto isn't the default and you probably won't think to switch settings on it during a fight since they're at the top left of the screen and not just as simple as pressing x with a standard E gun.

**Comment by j-mie** [comment]
https://github.com/HippieStation/HippieStation/pull/4120
Likely fixed.
