### ISSUE TITLE
Clown stamps create invisible clown boxes

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4087]
In-Game report from arzion:
Server info: 23583 (Hippie Station)

>General description of the issue
Using the clown's stamp on cardboard creates invisible clown boxes

>What you expected to happen
Honestly, I am not sure. I am making this issue report on behalf of an user and I do not know how are honkbots actually supposed to be made

>What actually happened
Invisible clown boxes have been spawned

>Steps to reproduce if possible
Use clown stamp on cardboard to create invisible clown boxes

**Comment by j-mie** [comment]
@tortellinitony this needs to be fixed, we need to update the DMI....
