### ISSUE TITLE
Mech polits take damage instead of the mech.

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4156]
In-Game report from guyonbroadway:
Server info: 23654 (Hippie Station)

>General description of the issue
While piloting a mech the pilot takes damage instead of the mech itself.

>What you expected to happen
For the mech to take damage besides the pilot.

>What actually happened
I died and the mech was undamaged.

>Steps to reproduce if possible
Spawn neovgre, get in neovgre, shoot neovgre with lasers.

**Comment by GuyonBroadway** [comment]
This is actually an upstream issue. https://github.com/tgstation/tgstation/issues/31899
