### ISSUE TITLE
Can't build firefighter ripleys after securing the peripherals control modules

### ISSUE THREAD

**Issue by challade** [HippieStation/HippieStationdeprecated2020#4177]
round 23683

I was asking the mentors about it, but it seems the firefighters are bugged after securing the peripherals control module, you can't add metal, or plasteel, it's just dud.

**Comment by Pyko1** [comment]
Most likely TeeGee issue.

**Comment by xTrainx** [comment]
need to add powercell before the inner layer, added in tg pr #30942 https://github.com/tgstation/tgstation/pull/30942
