### ISSUE TITLE
Bolt cutters (the syndicate upgrade to wirecutters) are invisible

### ISSUE THREAD

**Issue by Vagak** [HippieStation/HippieStationdeprecated2020#4187]
Round ID: 23698 (I've seen this plenty of times before in previous rounds, so this is probably irrelevant)

The bolt cutters, when in inventory and when on the ground, are invisible. [As shown here.](https://i.imgur.com/03eBMM0.png)

Funnily enough, the icon shows when you examine it however. [As seen here.](https://i.imgur.com/0OFxccn.png)

**Comment by GuyonBroadway** [comment]
Seems like a spiriting issue to me, I'll take a look.

**Comment by JohnGinnane** [comment]
Looks like upstream issue: https://github.com/HippieStation/HippieStation/issues/4553

**Comment by Vagak** [comment]
This still is happening. I'd like to remind people of that.

**Comment by JohnGinnane** [comment]
Cool, I'll look at today
