### ISSUE TITLE
cant craft butt shoes

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4225]
In-Game report from eagleeyes1:
Server info: 23750 (Hippie Station)

>General description of the issue

cant craft butt shoes
>What you expected to happen

to craft butt shoes
>What actually happened

said i was missing a piece but i wasnt and the crafting menu was blue saying i had all the items
>Steps to reproduce if possible

place items on table. click craft on craft menu. in chat says cant craft missing items

**Comment by Spankmaster1066** [comment]
Ok, here's what I found. If you do it with the wirecutters in hand it will say "missing tool" but still produce the shoes. If you throw the wirecutters on the table, it works exactly as intended. This is more likely an issue with the table_crafting checks for tools than the butt_shoes themselves.

**Comment by KayeArray** [comment]
Yes, that's a tablecrafting thing not related to butt shoes.

Closing
