### ISSUE TITLE
Defaulting to human race each game

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4254]
In-Game report from kiltinaction:
Server info: 23791 (Hippie Station)

>General description of the issue
In preferences, I set up a moth character and saved it. Each next round, it defaults back to human unless changed every lobby. 

>What you expected to happen
To be moth

>What actually happened
I am human

>Steps to reproduce if possible
Set up moth character, play one game, ready up for 2nd game, be human

**Comment by praisenarsie** [comment]
@iamgoofball its a dream for you come true

**Comment by Iamgoofball** [comment]
fxgjhthrfd

**Comment by Blute1** [comment]
i dont remember this happening? can anyone else confirm?

**Comment by Blute1** [comment]
this was 18 days ago and doesnt seem to occur, perhaps this person forgot to set their preferences

**Comment by Carbonhell** [comment]
Cannot reproduce
