### ISSUE TITLE
Shapeshifting as vampire does not change race

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4277]
In-Game report from kiltinaction:
Server info: 23826 (Hippie Station)

>General description of the issue
As moth vampire, I shapeshifted, and only my name changed, my physical moth appearance did not.

>What you expected to happen
To change into a human?

>What actually happened
Only my name changed

>Steps to reproduce if possible
Be moth vampire, shapeshift.

**Comment by KayeArray** [comment]
Does anyone other than Amari want to touch this vampire code lol

**Comment by ghost** [comment]
this issue happens because Shapeshift only randomizes name/appearance, and moths aren't too unique in terms of appearance.

**Comment by Carbonhell** [comment]
Not a bug, intended behaviour.
