### ISSUE TITLE
You can't ignore mentors

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4288]
In-Game report from esumlogos:
Server info: 23851 (Hippie Station)

>General description of the issue
I wanted to ignore a mentor in OOC and it turns out they can't be ignored. This makes no sense.

>What you expected to happen
To never see messages from PopNotes again.

>What actually happened
I saw messages from him.

>Steps to reproduce if possible
Block PopNotes. Watch as something terrible happens when he logs in.

**Comment by PopNotes** [comment]
Baby bitch boy
