### ISSUE TITLE
Finished Garrote's are invisible.

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4315]
In-Game report from gradusnl:
Server info: 23860 (Hippie Station)

>General description of the issue
See the issue name.

>What you expected to happen
Visible garrote's

>What actually happened
Invisible garrote's, although the handles were visible before I finished crafting.

>Steps to reproduce if possible
Craft a garrote using the crafting menu, I made one using white wires and red wires.

**Comment by Blute1** [comment]
this was fixed by yours truly as well

**Comment by JohnGinnane** [comment]
Just tested this, seems to be working fine
