### ISSUE TITLE
IPC faces appear over headgear.

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4316]
![image](https://user-images.githubusercontent.com/15840795/32057926-9102d7d6-ba60-11e7-93c6-ffad23df2093.png)
Kinda a bit of a problem.

**Comment by JohnGinnane** [comment]
@McBawbaggings when you get a chance can you see if this is still an issue? I know @tortellinitony worked on IPC faces a little while ago
