### ISSUE TITLE
vamp revive doesn't take 1 min as the message says, seems to take up to 3

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4324]
In-Game report from carbonhell:
Server info: 23871 (Hippie Station)

>General description of the issue

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by TungstenOxide** [comment]
May have something to do with [this](https://github.com/HippieStation/HippieStation/blob/master/hippiestation/code/game/gamemodes/vampire/vampire_powers.dm)
addtimer(CALLBACK(src, .proc/revive, L), rand(600, 750))

Line 334

**Comment by Carbonhell** [comment]
https://github.com/HippieStation/HippieStation/blob/master/hippiestation/code/game/gamemodes/vampire/vampire_powers.dm#L334
what's the point of this rand,just remove it and put 600
