### ISSUE TITLE
Garrote sprite is invisble

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4333]
In-Game report from zack24:
Server info: 23895 (Hippie Station)

>Garrote sprite is invisble

>For the garrote to show up in my hand

>First time i did it i didnt know it was invisible

>Create garrote handles and finish it and you get a invisble sprite garrote

**Comment by Pyko1** [comment]
same as https://github.com/HippieStation/HippieStation/issues/4315
