### ISSUE TITLE
Odysseus cannot be built

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4335]
In-Game report from jujumatic:
Server info: 23898 (Hippie Station)

>The Odysseus cannot be built fully as, once the peripherals board is secured, metal sheets cannot be added in order to progress to the next step of building the exosuit.

>I expected to be able to add the 5 metal sheets in the same manner as say, adding a metal sheet to an exosuit to build an ED bot, where on a click the step would be completed and the sheets would be gone from my hand.

>Nothing happened, even after spam clicking the exosuit. I tried with plasteel, glass, reinforced glass and metal and none worked. I also quadruple checked that the peripherals board was secured, and even had someone else try to add the metal sheets, which still did not work.

>Build an Odysseus as according to the Hippie wiki, watch as you cannot progress past securing the peripherals board.

**Comment by praisenarsie** [comment]
https://github.com/HippieStation/HippieStation/issues/4177 is related.

**Comment by xTrainx** [comment]
ok so, i was code digging, and apparently, you now have to install a power cell before you put the inner metal layer, im not sure when this change happened tho, so is not a bug, it just an upstream change i belive

EDIT: it was changed in tg pr #30942 https://github.com/tgstation/tgstation/pull/30942

**Comment by Pyko1** [comment]
Most likely TeeGee issue.

**Comment by KayeArray** [comment]
people are retards
