### ISSUE TITLE
Honkbot dosn't work

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4357]
In-Game report from leonidzurnadzhi:
Server info: 23907 (Hippie Station)

>General description of the issue
I wanted to make honkbot so i wanted to try that out

>What you expected to happen
So i destroy box stamp it and i think wil come out clown box where i gotta put arms and stuff into it to make honkbot

>What actually happened
welp comes invisibile clown box witch is usefull because why? If you a traitor and you put it into your backpack you can put into clown box everything and nobody finds it hope you fix it

>Steps to reproduce if possible
welp simple destroy box and stamp it and comes out invisibile clown box on floor

**Comment by Pyko1** [comment]
same as https://github.com/HippieStation/HippieStation/issues/4087
