### ISSUE TITLE
I devours the mouse

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4360]
In-Game report from memerino:
Server info: 23912 (Hippie Station)

>General description of the issue
Misspell of 'Devour', so whenever I take a bite of something it says 'You unwillingly devours a bit of the mouse.' or something of similar sort

>What you expected to happen
I would eat a mouse as a shadowling and RP as a l_shadowling who eats people, nyaaa

>What actually happened
'You unwillingly devours a bit of the mouse.', my immersion was broken and I'm very angery

>Steps to reproduce if possible
Take a bite of delicious mouse, when in reality, you devours it. muh immurshunz

**Comment by KayeArray** [comment]
feature
