### ISSUE TITLE
zombies cant get hulk

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4363]
In-Game report from razorblaza:
Server info: 23916 (Hippie Station)

>General description of the issue
Zombies cant get hulk

>What you expected to happen
for me to become a zombie hulk with hulk powers

>What actually happened
i only got regen core

>Steps to reproduce if possible
get someone to sign a devil contract for infernal power as a hallooween zombie

**Comment by KayeArray** [comment]
no
