### ISSUE TITLE
Sarin still makes chempiles in the smoke machine.

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4383]
In-Game report from jujumatic:
Server info: 23941 (Hippie Station)

Notes on github said sarin has been tweaked so the smoke machine doesn't put chempiles of it. The station is still floodable with sarin chempile hell. WE WERE LIED TO. Reference: round #23941

**Comment by Pyko1** [comment]
https://github.com/HippieStation/HippieStation/pull/4368 was not merged
