### ISSUE TITLE
Dead cow doesn't show up in photo

### ISSUE THREAD

**Issue by RawrARawrz** [HippieStation/HippieStationdeprecated2020#4407]
Round 23955 whatever, this ruins my immersion fix it now.
![ss13 invisible cow hippie](https://user-images.githubusercontent.com/30274955/32152332-d00f2ae2-bcf9-11e7-9f96-3faccdd58d0c.png)

**Comment by ghost** [comment]
u sure that cow isn't a vampire?

**Comment by RawrARawrz** [comment]
Camera obscura my dude

**Comment by Spacedong** [comment]
x-files theme

**Comment by Spacedong** [comment]
we've had this bug for ages and nobody knows how to fix it tbh

**Comment by praisenarsie** [comment]
tg bug

**Comment by Pyko1** [comment]
Not a bug, the cow is actually a vampire

**Comment by KayeArray** [comment]
"The dark side of the Force is a pathway to many abilities some consider to be unnatural."

**Comment by Blute1** [comment]
its presumably a problem with overlays
