### ISSUE TITLE
Can't open ORM screen after I placed all my ore inside with minig satccel of holding

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4446]
In-Game report from mikleo:
Server info: 23998 (Hippie Station)

>General description of the issue
The requested interface (ore_redemption_machine) was not found. Does it exist?

>What you expected to happen
collect my points and ID

>What actually happened
screen won' open just dispalys the error" The requested interface (ore_redemption_machine) was not found. Does it exist?"

>Steps to reproduce if possible

Place Mining satchel of ohlding with ore inside

**Comment by GuyonBroadway** [comment]
fixed
