### ISSUE TITLE
Pocket Defib staying in hand

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4459]
In-Game report from vpickles:
Server info: 24000 (Hippie Station)

>General description of the issue
Invisble paddle rendered left hand unusable

>What you expected to happen
Fixing the bug, I guess. It's more a minor annoyance than a problem.

>What actually happened
when I used the pocket defib and put the paddle back onto it, i noticed i couldnt hold items in my left hand. My left hand was invisible however when i clicked on it, it dual wielded the paddle and I could use it to resurrect people however I could not put it down. When I placed the defib on the floor however the issue fixed itself. 

>Steps to reproduce if possible
Equip compact defib on the belt, proceed to use it on someone (it failed), and then put the paddles back on the defib.

**Comment by ghost** [comment]
can't you just click one hand, press HOME, click other, press HOME?

**Comment by Carbonhell** [comment]
Pretty sure it was fixed months ago by tg.
