### ISSUE TITLE
Ore redemption machine bugged

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4463]
In-Game report from hydracoop:
Server info: 24001 (Hippie Station)

>General description of the issue
Put in my ID into the ore redemption machine and it disappeared

>What you expected to happen
That my id would show?

>What actually happened
My id disappeared

>Steps to reproduce if possible

**Comment by Blute1** [comment]
this was fixed upstream))

**Comment by JohnGinnane** [comment]
Fixed by #4474 by the looks of it

**Comment by praisenarsie** [comment]
FIXED YET NEVER CLOSED, ISSUES EXIST MAINTAINERS!!!!!!!!!!!!
