### ISSUE TITLE
thermite not igniting

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4466]
In-Game report from kiltinaction:
Server info: 24004 (Hippie Station)

>General description of the issue
thermite won't ignite, not even with 50u used.

>What you expected to happen
a wall to ignite and burn

>What actually happened
i started slicing through the wall

>Steps to reproduce if possible
throw thermite on wall, try to ignite with welder

**Comment by praisenarsie** [comment]
upstream issue which was merged https://github.com/HippieStation/HippieStation/pull/4538

close the issue
