### ISSUE TITLE
Cleaver saw blood mechanic does not work

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4539]
In-Game report from warrage:
Server info: 24043 (Hippie Station)

>General description of the issue
Beastly bleed mechanic on the cleaver saw from the blood drunk miner does not work

>What you expected to happen
Should apply blood stacks over target sprite that pop dealing damage when filled

>What actually happened
Nothing happens.

>Steps to reproduce if possible
Attack anything with it.

**Comment by Carbonhell** [comment]
Seems to work correctly.
