### ISSUE TITLE
Garrote Sprites

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4547]
In-Game report from helgraf95:
Server info: 24057 (Hippie Station)

>General description of the issue
Garrotes have no sprites

>What you expected to happen
A garrote to have a sprite

>What actually happened
A garrote didn't have a sprite

>Steps to reproduce if possible
Make a garrote

**Comment by GuyonBroadway** [comment]
dupe of https://github.com/HippieStation/HippieStation/issues/4315
