### ISSUE TITLE
Bolt cutters are invisible

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4553]
In-Game report from vagak:
Server info: 24074 (Hippie Station)

>General description of the issue
Inside the syndicate suspicious looking toolbox, there are a pair of boltcutters, which are supposedly the syndicate version of the wirecutters. The icon for them is invisible.

>What you expected to happen
The bolt cutters to be visible.

>What actually happened
The bolt cutters are invisible. They can still be interacted with and used easily however, it's just they're a pain in the neck to know which slot they're in.

>Steps to reproduce if possible
It always happens on roundstart, inside any suspicious looking toolbox.

**Comment by tortellinitony** [comment]
#4187
