### ISSUE TITLE
Sprite error

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4571]
In-Game report from lopert12:
Server info: 24083 (Hippie Station)

>General description of the issue
There is no sprite for the shank but when you hold it you can still see a glass shard in your hand

>What you expected to happen
I expected to get a visible and normal shank

>What actually happened
When i created the shank i didnt see anything but i could hear the sound of walking on glass,when i right clicked i could see shank but there was no sprite for it and when i examined the shank it didnt look anything like one

>Steps to reproduce if possible
1.Create a shank
2.Profit

**Comment by Blute1** [comment]
this was fixed, close
