### ISSUE TITLE
[s] Serverside database issue allows you to see the current roundtype in Hippie Stats

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4613]
```<MrStonedOne> hippie's db has a bug that isn't making round end null, so its showing as having an end round time, and atl's site is assuming that means its safe to show```

FUCK FUCK!!! FIX DB ASAP!!!

**Comment by Spacedong** [comment]
this is jamie and admiral hippie's issue

**Comment by j-mie** [comment]
Fixed.

**Comment by ghost** [comment]
PHEW!
