### ISSUE TITLE
Devil round should not end on antagonist death

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#4642]
I have no idea how this is the case but devils with enough souls are able to revive themselves in a new body/location upon death.

Making the round end when they can clearly try again is very counter-unitive.

**Comment by Spacedong** [comment]
to my knowledge devil round doesnt end on antagonist death???

**Comment by ghost** [comment]
It does

**Comment by GuyonBroadway** [comment]
Same goes for vampires who are resurrecting.

**Comment by ghost** [comment]
take it upstream
