### ISSUE TITLE
The hotel from the spawner wiring 

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4651]
In-Game report from lewismaaate:
Server info: 24199 (Hippie Station)

>General description of the issue
spawned into the hotel through the spawner menu after dying and all the wiring was bugged out and none of it was connected. All wiring was just in single pieces covering half a tile.

>Steps to reproduce if possible
never seen this occur before so could just be an isolated incident

**Comment by xTrainx** [comment]
this actually is happening in all other generated places, including, most notable, the old cryogenic sleeper, wich makes you unable to wire the sm and generator, making that place useless, but all other generated places have their wiring wrong
