### ISSUE TITLE
Mining Ripley with 50% chance for plasma cutter

### ISSUE THREAD

**Issue by TheSpartyn** [HippieStation/HippieStationdeprecated2020#4685]
For some reason the mining ripley only spawns with a plasma cutter every other round, which is apparently intentional. Should make it spawn with it everytime so it's not a gamble every time you pick Shaft Miner.

**Comment by GuyonBroadway** [comment]
What with the new mining drill buffs it might come down to personal preference. Compromise, I make it never spawn but you can get one from the vendor using your mining round-start voucher?

**Comment by WarRage333** [comment]
The cutter is nearly always better, but yes please add it as a voucher or if thats 'too op', a reward from the mining vendor for 1k or 2k points

**Comment by TheSpartyn** [comment]
Actually yeah that'd be a great compromise, have it be a voucher option. Also, if it's not too much to ask, could you add a welding mask/goggles to the shuttle bay or mining camp too? Otherwise you'd have to run to RnD every round start to be able to repair the ripley.

**Comment by GuyonBroadway** [comment]
Well the area near the shuttle dock has a toolbox(and thus welder) and there is another toolbox on lavaland but I'll see to adding some welding goggles. 

Time was I always took the mining drone from the vendor as it came with an industrial welding tool, and back in the day the mining RIG suit gave welder protection, I'll see to changing it.

**Comment by TheSpartyn** [comment]
Yeah I know there's welders, but theres no protection. And same, I'd always grab the mine not just for the welder and goggles, but that won't be an option anymore.

Also might as well mention it now since its related. Mentioned mining Ripley also has a problem where it spawns ID locked, and I have no idea which ID works. This means you can't perform any maintenance on it because it requires ID access.

**Comment by GuyonBroadway** [comment]
Oh all mech by default (read: SHITCODE) need robotics access to do maint protocols and its annoyingly hard wired.

**Comment by TheSpartyn** [comment]
Blech. Give Miners robotics access lmao

Is there any solution for recovering a drained Ripley in lavaland then? Can't move, drag it, or replace the battery.

**Comment by GuyonBroadway** [comment]
If they could do maint protocols they could replace the cell. I'll see to changing that for miners, until then ask the HoP for robotics access.

**Comment by JohnMcLaime** [comment]
Iirc for the adjacent pickup of ores to work, ripley needs plasma cutter installed, otherwise without it you have to walk over every orepile to pick them up.

Also old hippie used to have buyable mechparts in miner vendor, for points. Those were mech teleporter and repair drone?

**Comment by GuyonBroadway** [comment]
The ore pickup is tied to the clamp, not the plasma cutter.

**Comment by JohnMcLaime** [comment]
Unless it was fixed recently, i am pretty much sure about what i said, that without plasma cutter it wouldnt pick up ADJACENT to the mech ores and clamp is present on all cargo's ripley spawns anyway so there was an issue. 

I was confused because of how pickup check works, Ores arent picked up if you drill them (oldhippie used to have that), you have to step back and forth to pick adjacent ores.

**Comment by TheSpartyn** [comment]
Did anything ever come of this?

**Comment by GuyonBroadway** [comment]
Its on my to-do list.
