### ISSUE TITLE
Chemical payloads / homemade big bombs are broke

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4691]
In-Game report from warrage:
Server info: 24260 (Hippie Station)

>General description of the issue
When making a bomb from a chemical payload + 10 plasteel bomb frame it does nothing when it goes off.

>What you expected to happen
Should mix the chemicals in the beakers and do a reaction.

>What actually happened
First i tried an 1200 unit emp that fizzled, then i went down a notch and used a simple 50/50 foam water combination it also fizzled doing nothing. 

>Steps to reproduce if possible

Make a chempayload from gibtonite, two granades and a matter bin add it to a bomb shell assembly (10 plasteel), put chemicals in beakers, put beakers in bombload, put bombload in the bomb shell, mend wires, screwdriver it up, and set a timer, wait it out and watch it sizzle.

Not sure if i'm doing something wrong or its just brok

**Comment by JohnGinnane** [comment]
Should be fixed by #4694
