### ISSUE TITLE
Grenades seem broken

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4692]
In-Game report from vpickles:
Server info: 24261 (Hippie Station)

>General description of the issue
Grenades do not detonate

>What you expected to happen
A fix 

>What actually happened
Yesterday custom mix grenades did not detonate but I put it down to me being a shit Chemist. I tried to use the cleaning grenades the Janitor spawns with today but they reacted the same way. 
After the timer runs out, the grenades just vanish without detonating.

>Steps to reproduce if possible
Throw a grenade

**Comment by JohnGinnane** [comment]
I wonder if this is upstream issue?

**Comment by KayeArray** [comment]
No it's an issue with chem splash code

**Comment by Pyko1** [comment]
mostlikely the same thing https://github.com/HippieStation/HippieStation/issues/4691

**Comment by JohnGinnane** [comment]
Should be fixed by #4694
