### ISSUE TITLE
Firey Fireaxe projectile starts where ever you click and always moves east

### ISSUE THREAD

**Issue by praisenarsie** [HippieStation/HippieStationdeprecated2020#4703]
poorest design choice @GuyonBroadway

**Comment by Blute1** [comment]
huh?????????????????????????????

**Comment by ghost** [comment]
the syndie fireaxe that shoots fire, spacedong

**Comment by Blute1** [comment]
when was that added

**Comment by JohnGinnane** [comment]
There seems to be a bigger issue:

![image](https://user-images.githubusercontent.com/3355198/33803714-2f5f4284-dd8e-11e7-9d29-acba1c3f4a59.png)

**Comment by JohnGinnane** [comment]
When I click somewhere it always moves the fire east for some reason

**Comment by JohnGinnane** [comment]
Also the fire doesn't go through windows, but you can click somewhere and it will start there and head east as above

**Comment by JohnGinnane** [comment]
@GuyonBroadway do you wanna look at this?

**Comment by Carbonhell** [comment]
Was fixed long ago it seems.
