### ISSUE TITLE
Tourettes stuns you whenever it triggers

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStation/HippieStationdeprecated2020#4706]
https://github.com/HippieStation/HippieStation/blob/229f7c8efab323a4b69e58233e16d75aa75cce2d/code/datums/mutations.dm#L321

I got hit with the twitching mutation and the tourettes mutation. It's pretty shit. I don't think we had a stun in oldcode either so perhaps we should remove it

**Comment by Blute1** [comment]
it has always stunned you, since 2015 I remember

**Comment by JohnGinnane** [comment]
Hm, well I think 20 seconds is a little over kill, perhaps maybe 1 second

**Comment by ghost** [comment]
yeah the stun's always been there
lowering it sounds fine, but it should still be largely detrimental overall to incentivize getting that cured ASAP

**Comment by ghost** [comment]
mutations should be bad though and it's been like this for ages
it's hard to fix by yourself so you needing help is fine, mechanics should encourage cooperation among staff.

**Comment by Arzion5** [comment]
I do agree that it needs to be removed or reduced. It's a shit stun.

**Comment by ghost** [comment]
ye exactly thats what im saying
like it shouldnt be 1 second but a solid 20 seconds of staring at your screen sounds awful too tho

**Comment by Arzion5** [comment]
Going to make a PR that reduces the stun to about 5 seconds.

**Comment by JohnGinnane** [comment]
@Arzion5 when pls)
