### ISSUE TITLE
I CANT CLICK OB PEOPLE WHEN THEYRE LYING DOWN

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4734]
In-Game report from spankmaster:
Server info: 24304 (Hippie Station)

>IF I STUN SOMEONE I CANT INTERACT WITH THEM OR CLICK ON THEM

>CLICKJ

>COULDNT CLICK
>STUN SOMEONE AND TRY TO HIT THEM , THIS SHIT IS RUINING MY FUCKIN ROUNDS

**Comment by PopNotes** [comment]
lmao owned

**Comment by GuyonBroadway** [comment]
What is yer byond version? What is yer Internext Explorer version? When was the last time you updated windows?

**Comment by Blute1** [comment]
this bug is a duplicate of #4572

**Comment by Spankmaster1066** [comment]
We need to fix this bullshit, I can't count on two hands the number of times I've just barely managed to get a stun off on someone who is attacking me and find myself unable to interact with their body at all, standing there like a dipshit with my weapon in hand clicking frantically until my opponent stands back up, knocks me over, and rapes my soul physically.

**Comment by Carbonhell** [comment]
As dong said,duplicated. The other one is explained better,closing this
