### ISSUE TITLE
WEW XD MISSING SPRITES

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4835]
In-Game report from sherifftubbynips:
Server info: 24421 (Hippie Station)

>General description of the issue
Bolt cutters aint got no sprite

>What you expected to happen
Bolt cutters to have sprites

>What actually happened
NO SPRITES >:(

>Steps to reproduce if possible
Add sprites

**Comment by xTrainx** [comment]
it has a spire but for some reason it appears invisible

**Comment by tortellinitony** [comment]
#4187
