### ISSUE TITLE
whiteship nav console dun broke

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4848]
In-Game report from captainruddy:
Server info: 24437 (Hippie Station)

>General description of the issue
whiteship nav console dont work

>What you expected to happen
it to work

>What actually happened
it dident

>Steps to reproduce if possible
try to click on the fucker, gud ol TG not coding right

**Comment by praisenarsie** [comment]
upstream iss, needs more info
