### ISSUE TITLE
Lightly Fried Moth heads have no model/sprite

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4883]
In-Game report from critiasblue:
Server info: 24462 (Hippie Station)

>General description of the issue
Some dude fried a moth head and I took it out of the frier

>What you expected to happen
A moth head to come out

>What actually happened
Invisble moth head that I couldn't find

>Steps to reproduce if possible
Fry a moth's head for 1 second and take it out

**Comment by tortellinitony** [comment]
Issue with all heads

**Comment by Carbonhell** [comment]
Works.
