### ISSUE TITLE
Cryo bug

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4888]
In-Game report from bubberduckydducker:
Server info: 24473 (Hippie Station)

So i was in cryo healing myself, and then i scanned myself with a health analyzer and realized i have 500u of cryoxadone in my system, i don't think this shit is normal, i mean that literally came from a 30u beaker of it, anyway i think you can reproduce this bug by simply going on it with any chem and coming out with a massive amount of it in your system in the cryo pods, ples fix :(((

**Comment by WarRage333** [comment]
Intended behavior

**Comment by Carbonhell** [comment]
Wtf it is not intended

**Comment by Carbonhell** [comment]
Resolved long ago.
