### ISSUE TITLE
Cant spraycan paint the H.E.C.K. suit.

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4889]
In-Game report from warrage:
Server info: 24475 (Hippie Station)

>General description of the issue
You used to be able to paint the heck suit any color using the spray can

>What you expected to happen
You cant

>What actually happened
Game became literally unplayable

>Steps to reproduce if possible
Git spray can, take cap off, (SELECT COLOR OPTIONAL), click the suit / head and cry

**Comment by praisenarsie** [comment]
@xdtm

**Comment by WarRage333** [comment]
Somehow it works again

**Comment by praisenarsie** [comment]
??

**Comment by WarRage333** [comment]
I could not paint the thing twice this week (out of like 11~ times), seems absolutely random.
