### ISSUE TITLE
THINGS THAT NEED TO BE REWRITTEN

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4925]
- [ ] Mentor system. Right now, mentors are buggy subtypes of admins that cause many problems... like #4903

- [ ] Shadowling antag. They need to use antag datums.

**Comment by GuyonBroadway** [comment]
Didn't you make shadowlings? And Vamps for that matter?

**Comment by ghost** [comment]
yes and yes
