### ISSUE TITLE
Ore redemption machine issue

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4952]
In-Game report from mediphious:
Server info: 24543 (Hippie Station)

>General description of the issue
Apparently it's clientside for some reason. But after moving the redemption machine to lavaland I'm unable to actually access the popup menu

>What you expected to happen
Insert ore, insert ID, receive points

>What actually happened
Insert card. no menu. Lost access until another miner could pull it out for me

>Steps to reproduce if possible
No idea.

**Comment by xTrainx** [comment]
you can fix it by screwing it open and close

**Comment by Carbonhell** [comment]
Its a general issue related to tgui,the answer up here,or just reconnecting,works. Afaik it is not fixable,closing
