### ISSUE TITLE
Communications console disappeared after I repaired it's broken glass

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4953]
In-Game report from tonytalent:
Server info: 24543 (Hippie Station)

>General description of the issue

>What you expected to happen
fix the comms console after it's screen was shattered

>What actually happened
when i screwdrived the repaired glass I put in, it simply disappeared. It's not just invisible cause right click shows nothing, so it's literally gone.

>Steps to reproduce if possible

**Comment by praisenarsie** [comment]
upstream issue, see referenced issue ^

**Comment by JohnGinnane** [comment]
Fixed by #4968
