### ISSUE TITLE
drifting in space in crit counts as crawling and saps your health

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4955]
In-Game report from cacogen:
Server info: 24544 (Hippie Station)

**Comment by praisenarsie** [comment]
why doesn't hippie use tg softcrit crawling

**Comment by JohnGinnane** [comment]
@praisenarsie does /tg/ have softcrit crawling???

**Comment by Carbonhell** [comment]
i think this got fixed?

**Comment by Carbonhell** [comment]
someone check
