### ISSUE TITLE
Pirate Ship navigation view fucks up screen zoom

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4956]
In-Game report from spankmaster:
Server info: 24544 (Hippie Station)

>If you use the navigation computer for the pirate ship, you screen becomes extremely zoomed out and there's tons of black space

>useable camrea

>was NOT

>use the pirate ship

maybe just add a proc when disengaging from pirate console that resets zoom?

**Comment by Carbonhell** [comment]
Should have been fixed a long time ago
