### ISSUE TITLE
Vanishing Robotics R&D Console

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4958]
In-Game report from kittykathy:
Server info: 24546 (Hippie Station)

>General description of the issue
Robotics R&D Console and the one in the E.X.P.E.R.I-MENTOR room can't be constructed on the last step to complete it the whole console just vanishes. This may affect the Core RD Console too but that was not tested to be the case.

>What you expected to happen
The console would not dissapear and instead be constructed.

>What actually happened
It vanished on completion of the last step.

>Steps to reproduce if possible
Try to construct a Robotics R&D Console watch as it vanishes on completing the last step.

**Comment by dreamcrab** [comment]
this actually happens with every console iirc
