### ISSUE TITLE
Brass Chairs have no sprites

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4964]
In-Game report from critiasblue:
Server info: 24552 (Hippie Station)

>General description of the issue
Brass chairs have no sprite, making them invisible

>What you expected to happen
I built a brass chair out of brass and expected a chair to appear

>What actually happened
No chair appeared and I had to right click the ground to see if it appeared

>Steps to reproduce if possible
Make a brass chair

**Comment by JohnGinnane** [comment]
We're currently override the chair icon with our own but this file doesn't have brass chairs so I'm looking into a workaround
