### ISSUE TITLE
RnD not working, devices do not link

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4974]
In-Game report from kiltinaction:
Server info: 24568 (Hippie Station)

>General description of the issue
As much as I despise the new RnD, it's FUCKED because the protolathe and circuit imprinter are not linked and will not link even from the menu. Not even when deconstructed and built again

>What you expected to happen
protolathe to be link or linkable

>What actually happened
can't be linked

>Steps to reproduce if possible
try to use protolathe from RnD console

**Comment by GuyonBroadway** [comment]
You don't use the protolathe from the R&D console anymore you just click the protolathe itself, not messing around with linked/unlinked devices just click and dun.
