### ISSUE TITLE
ULTRA AC2 LMG mech attchement is mis-named in research as PACIFIER

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4989]
In-Game report from warrage:
Server info: 24591 (Hippie Station)

>General description of the issue
Title, 

>What you expected to happen
To not be wrong

>What actually happened
https://i.imgur.com/B86x5AI.png

>Steps to reproduce if possible
Do rnd until you get to this point

**Comment by GuyonBroadway** [comment]
Upstream issue, everyone go beat up kevinz

**Comment by praisenarsie** [comment]
p sure this got fixed

**Comment by praisenarsie** [comment]
yup got fixed
