### ISSUE TITLE
Crossbow pinning

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#4998]
In-Game report from romathebest:
Server info: 24601 (Hippie Station)

>General description of the issue
Pinned a guy to the wall with crossbow, his sprite properly reflected that but he could still freely move. 
>What you expected to happen

He has  the metal rod embedded in his left arm! It has pinned him down to the reinforced wall! 
>What actually happened

Bug
>Steps to reproduce if possible
I shot from south to north, they got pinned to north wall of hop's line, shot at flat angle.

**Comment by KayeArray** [comment]
@JohnGinnane

**Comment by JohnGinnane** [comment]
Interesting

**Comment by JohnMcLaime** [comment]
Yeah examining still said that they were pinned to reinforced wall, while they were running around.

**Comment by JohnMcLaime** [comment]
Strange, other time it properly  worked in same area too.

**Comment by JohnMcLaime** [comment]
It seems to work/bug out randomly

**Comment by JohnGinnane** [comment]
That makes it a bit more difficult to fix, because it's hard to recreate then. I wonder if it maybe fell out or something, we'll have to see if it happens again and if so, under what circumstances
