### ISSUE TITLE
Swagile AutoAdmin is broken

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5031]
In-Game report from milliardomarquise:
Server info: 24635 (Hippie Station)

>General description of the issue
Without enough time left for the shuttle to be recalled, I pushed over and took the shield of a security officer, and then again pushed and took their taser from them after they whipped it out and shot at me twice with it.  Another sec intervened, and I was cuffed.  This shitcurity officer, Meme Boy, proceeded to beat me and cause me to start bleeding out, then took me into the virology monkey pen and bolt the door, and then cut all of the wires to break it.  When I Ahelped and explained this to your Botmin, Swagile, I was catbanned for "banbaiting"

>What you expected to happen
I expected the shitcurity to be sec banned for murderboning crew without a valid reason.

>What actually happened
I was catbanned for "banbaiting" by your botmin, Swagile.

>Steps to reproduce if possible

Ahelp with Swagile alone on.

**Comment by Swagile** [comment]
> reporting an administrative issue on github

    o          k
