### ISSUE TITLE
Cargo export not working properly

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5066]
In-Game report from romathebest:
Server info: 24677 (Hippie Station)

>General description of the issue
Tried to export 30 plasma sheets and a bunch of tech on a tech disk, left them on a floor at first try, got nothing. Second try, loaded 10 plasma in a crate and techdisk with more tech, only got 500 points for crate itself, nothing for the contents

>What you expected to happen
$$$$$$$$$$

>What actually happened
Disappointment

>Steps to reproduce if possible

See above
This has happened before too (since last month at least), getting money from exporting ores is inconsistent.

**Comment by ghost** [comment]
Exporting minerals has been removed from the game

**Comment by praisenarsie** [comment]
because kor sucks

**Comment by JohnMcLaime** [comment]
What about tech disks though, technology has this 	export_price = 10000, so you ignored half of the issue, fag.

**Comment by ghost** [comment]
Exporting of tech has been changed significantly since the techweb change, I'd suggest you try it again and open a new issue if it persists

**Comment by praisenarsie** [comment]
afaik there is a pr open upstream fixing tech disks unless i misread something
