### ISSUE TITLE
Warnings for ashstorms in lavaland are gone.

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5071]
In-Game report from milliardomarquise:
Server info: 24682 (Hippie Station)

>General description of the issue

Warnings for ashstorms in lavaland are gone.  The only warning you get is when it begins.
>What you expected to happen

Some warning prior to the actual ash storm.
>What actually happened
There is no warning now.

>Steps to reproduce if possible

Stay at lavaland awhile and wait for an ash storm.

**Comment by Carbonhell** [comment]
Most likely fixed by tg times ago, it works now
