### ISSUE TITLE
Search function does not work in the circuit imprinter

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5088]
In-Game report from jujumatic:
Server info: 24702 (Hippie Station)

>Search option does nothing when you type in anything

>Tried searching for circuits for the communications items e.g. bus mainframe

>Nothing happened on a search

>Go to the circuit imprinter in RnD and try to search for an item that's already developed. Search function is not broken for the protolathe by the way

**Comment by Carbonhell** [comment]
? It does,i literally use it daily
Needs testing?

**Comment by Carbonhell** [comment]
Resolved long ago
