### ISSUE TITLE
ejecting a beaker from a chem dispenser drops it under the dispenser

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5089]
In-Game report from dankmem:
Server info: 24703 (Hippie Station)

when you eject the beaker from the machine it drops below the machine so you need to alt-click or right click out from under it

**Comment by Blute1** [comment]
happens with the  cryo tubes too

**Comment by JohnGinnane** [comment]
Still happening, I suspect upstream but will have to test, should be easy to fix (if there's a move-to-top proc)

**Comment by JohnGinnane** [comment]
Just tested this and it's fixed already
