### ISSUE TITLE
A certain tile affiliated "Special friend" has issues when trying to "hug" people on the shuttle or centcom

### ISSUE THREAD

**Issue by GuyonBroadway** [HippieStation/HippieStationdeprecated2020#5110]
Basically if a "special friend" comes to visit the station and chooses to "play" with someone and the emergency shuttle leaves when they finally decide to "move in for the hug" they end up teleporting back to the station after jumping out to surprise their target and the target never get "their hug" they then teleport back to the target to try again after a while and teleport back to the station and the target remains forever unhugged.

**Comment by ghost** [comment]
what?

**Comment by GuyonBroadway** [comment]
Ask banthebantz for more information.

**Comment by KayeArray** [comment]
Do you mean if the person is on the emergency shuttle? Because he's not supposed to leave the Z level.

**Comment by WarRage333** [comment]
I'm having some noxstation tier ptsd from the old woody npc from those quotations

**Comment by GuyonBroadway** [comment]
If the "Friend" is on the shuttle following his "buddy" when the shuttle launches he stays on the shuttle till he tries to "hug" someone.

**Comment by Blute1** [comment]
I understand what he's saying, but I think he had a fucking stroke writing this

**Comment by Carbonhell** [comment]
What.
