### ISSUE TITLE
HippieStation fork is code-searchable

### ISSUE THREAD

**Issue by Partheo** [HippieStation/HippieStationdeprecated2020#5112]
Steps to reproduce:
-Go to https://github.com/HippieStation/HippieStation
-Type word into search bar, such as `singularity`
-Press enter
-Browse results

Expectation:
-No results.
![image](https://user-images.githubusercontent.com/10659549/33360227-e0b250ae-d4a0-11e7-963b-76f70dbec908.png)

Result:
-Actual search results
![image](https://user-images.githubusercontent.com/10659549/33360240-f25e3494-d4a0-11e7-938e-7b088aded14e.png)

---

By default, forked repos aren't code-searchable. How do you guys do it?

**Comment by ghost** [comment]
I'd suggest you contact github support for questions like these, as we can't really answer this, i think it has to do with the popularity of a forked project, and once it reaches that threshold it'll be searchable

**Comment by praisenarsie** [comment]
my only guess is hippie gained 10000 commits

**Comment by ghost** [comment]
IIRC, jamie contacted Github support and asked

**Comment by Arzion5** [comment]
From what I've heard, the fork has been approved to be searchable

**Comment by Partheo** [comment]
Thanks folks! And sorry for the useless issue.
