### ISSUE TITLE
The "proto-kinetic crusher" doesn't show up on your character's back when it is equipped on the back slot

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5142]
In-Game report from expensiveantique:
Server info: 24806 (Hippie Station)

>General description of the issue
When equipping the crusher on your back, there is no crusher on your character's back

>What you expected to happen
A protokinetic to be tied to my character's back, similar to pickaxe and shotgun

>What actually happened
No sprite showed up, and my back appeared as if nothing was equipped in it

>Steps to reproduce if possible
Get Proto-kinetic crusher
Equip in "back" slot

**Comment by Carbonhell** [comment]
Works.
