### ISSUE TITLE
Thrown Glass Shard Bug

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5185]
In-Game report from jackattack41498:
Server info: 24862 (Hippie Station)

>General description of the issue
A glass shard was thrown at my character and it hit at least 7 times rather than once.

>What you expected to happen
The glass shard hit once

>What actually happened
The glass shard hit more than seven times

>Steps to reproduce if possible
Unknown. Likely has to do with the movement of the target, though there could be other factors at play

**Comment by praisenarsie** [comment]
whooooooooooooooooooooooooooooooooo touched throwcode

**Comment by JohnGinnane** [comment]
Would be a good idea to try and recreate this and maybe ask the player if it's happened again

**Comment by KittyKathy** [comment]
Not a bug, this was likely one of those integrated circuits machines that throws one item several times at close range.
I have one such machine design and it does exactly what this issue reports describes.

**Comment by Jujumatic** [comment]
It's a thing that happens when you put in a bunch of "thrower" circuits into an assembly and hook it up to something that constantly activates them like a ticker. Essentially it causes as many hits to a person or thing as there are thrower circuits e.g. 7 throwers result in 7 hits, 9 throwers result in 9 hits etc

**Comment by ghost** [comment]
@jujumatic why are you letting that shit out,  faggot?  this is why you don't let the unballdropped learn the good shit

**Comment by KayeArray** [comment]
everyone already knows lmao

**Comment by Jujumatic** [comment]
Yeah everyone already knew this anyway so it's not like it matters anyway. It doesn't take a genius to figure it out in fact for a retard like you to be able to figure it out, that means anyone else could too

**Comment by ghost** [comment]
Upstream issue

**Comment by JohnGinnane** [comment]
@Chnkr perhaps we should fix it?
