### ISSUE TITLE
Mech drill not working

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5196]
In-Game report from kiltinaction:
Server info: 24880 (Hippie Station)

>General description of the issue
APLU Miner drill does not drill rock, it says 'starts to drill the rock, but never actually does it.

>What you expected to happen
rock to be drilled

>What actually happened
nothing, no porgress bar

>Steps to reproduce if possible
get in miner mech, try to mine

**Comment by WarRage333** [comment]
Some tiles work some do not its really strange

**Comment by praisenarsie** [comment]
https://github.com/HippieStation/HippieStation/issues/5234 is possibly related.

**Comment by GuyonBroadway** [comment]
fukken fixeds
