### ISSUE TITLE
Emagged Limb Grower does not have armblades.

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5227]
In-Game report from warrage:
Server info: 24922 (Hippie Station)

>General description of the issue
Title

>What you expected to happen
Should be able to print armblades from an emagged limb grower.

>What actually happened
When you emag it, special tab pop us where i assume the arm blade should be located, upon entering this tab you will find its empty.

>Steps to reproduce if possible

^step above

**Comment by GuyonBroadway** [comment]
It needs some R&D to work
