### ISSUE TITLE
Plants in escape enclosure should be replaced

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStation/HippieStationdeprecated2020#5231]
Last night I saw that we still have those old plants in the little enclosure where the cow is kept. We should remove these and maybe put some more of the new plants in their place. This means players don't have to *pray* to Gods to remove them because as far as I know they have to be deleted

**Comment by ghost** [comment]
They work just fine

**Comment by Pyko1** [comment]
Replaced by new potted plants?
I mean there is grass soil and everything in there.

**Comment by Pyko1** [comment]
or what?

**Comment by JohnGinnane** [comment]
Yeah replaced by the new potted plants. I don't know what they're called but there is/was static bushes

**Comment by Pyko1** [comment]
Why tho there is soil for plants, no need to pot em?

**Comment by Pyko1** [comment]
even tho, could improve the static plants so you can still run behind them but not pick em up.

**Comment by JohnGinnane** [comment]
It was because they weren't (easily?) destructable, so if wanted to renovate escape you generally had to pray to get them removed. With the new potted plants I thought it makes sense to replace any old static plants with these new ones. But yeah it would be neat if there was an anchored version of the potted plant. Maybe even make all growable plants do this (looking at greytide botany and permabrig garden)

**Comment by praisenarsie** [comment]
yeah i reported the baaad plant deconstruction upstream like weeks ago

**Comment by JohnGinnane** [comment]
Looks like they're just really really strong. To give you an idea, windows are 25, blob core is 500. The default max_integrity is 300:

https://github.com/HippieStation/HippieStation/blob/625ee0c45583e0a8d0a4917afad1368172f1c4d0/code/game/objects/structures/flora.dm#L134

https://github.com/HippieStation/HippieStation/blob/2b6b60b8970210408d1c565c79acb6322441a2a9/code/game/objects/structures.dm#L4

**Comment by JohnGinnane** [comment]
why :(
