### ISSUE TITLE
lagging

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5276]
In-Game report from bobjaybob:
Server info: 24969 (Hippie Station)

ok so i keep lagging ,i know this a server issue that admnis still dealing with,the game keep freezing and i keep getting 800-1400 mps.

i really hope that the lagging issue will be solved,for that many players keep talking about how they lagg alot,

thank you

**Comment by ghost** [comment]
this

**Comment by praisenarsie** [comment]
lol
