### ISSUE TITLE
Dental Implant surgery still fails

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5300]
In-Game report from kittykathy:
Server info: 24989 (Hippie Station)

>General description of the issue
The inserting pill step of dental surgery fails and does damage but still fails to implant the pill when it should be implanted.

You begin to wedge HP pill in Jayda Mcintosh's mouth...
You succeed... just about!
It's still in my hand and not implanted when it should be.
Still does the damage too.

>What you expected to happen
On fail it should do the damage and implant the pill.

>What actually happened
It did the damage and did not implant the pill. It also ended the surgery as if it was implanted.

>Steps to reproduce if possible
1.Do dental implant surgery until the pill wedging part.
2.Fail the pill wedging part and take damage.
3.Find out you took that damage for no reason and have to start over again.
4.Also stand and wonder why surgery tools from the holodeck do damage.

**Comment by JohnGinnane** [comment]
Probably my fault, will have to look into this

**Comment by JohnGinnane** [comment]
I STILL HAVENT FIXED THIS MY BAD

**Comment by WarRage333** [comment]
STILL HAPPENENG on all surgeries that require the part of adding or removing a thing.
