### ISSUE TITLE
Mining with pickaxes, or exosuit drills on rocks containing ores doesn't work

### ISSUE THREAD

**Issue by Vagak** [HippieStation/HippieStationdeprecated2020#5302]
Round IDs shown in the webms provided, if they're necessary. I've encountered this more than once in one round.

Video example:
https://lambda.sx/VKS.webm
Basically, it briefly pops up with the progress bar but instantly cancels.

Also, supposedly after attempting this, you won't be able to dig the ground for volcano ash afterwards.
https://lambda.sx/0MB.webm
You can vaguely hear the shovel sound as I'm spam-clicking in this video.

I've also experienced this while being a miner in a ripley. Directly mining a rock containing a ore doesn't work, but mining any rocks without ores beside the ore does work.

You can only mine with resonators and kinetic accelerators because of this bug.

**Comment by Carbonhell** [comment]
Fixed long ago seems,unless there's some special case that triggers it. Report it again if it happens, right now it works just fine.
