### ISSUE TITLE
Cyborg hotkeys 1,2,3 doesn't work at all - clicking the equipment doesn't work either

### ISSUE THREAD

**Issue by Vagak** [HippieStation/HippieStationdeprecated2020#5303]
Video example doesn't show my keypresses, but I can assure you I'm trying them alongside trying to click them with my mouse.
https://lambda.sx/o01.webm

So far, I have only encountered this once. I don't know if this is explicitly a problem with the default cyborg module or it's a problem with all cyborgs. This being broken basically makes cyborging a whole lot more annoying. You have to press X to cycle through your equipment, and you can't deselect your equipment at all for interacting with APCs and airlocks unless you remove all your equipment first.

If I decide to play cyborg again, I'll probably get more footage of this if I encounter this twice at all. It'd otherwise be nice if this can be tested for reproducing at all.

**Comment by ghost** [comment]
Update to 512 latest

**Comment by Manly-Dwarf** [comment]
I am updated to 512 and this problem is still around.

**Comment by praisenarsie** [comment]
@ninjanomnom 🕵️

**Comment by JohnGinnane** [comment]
@Kawaii-Big-Boss is this still an issue now?

**Comment by ninjanomnom** [comment]
This is fixed on tg's end so you probably don't have this anymore

**Comment by Carbonhell** [comment]
Thank you.
