### ISSUE TITLE
Mining is broken again.

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5307]
In-Game report from milliardomarquise:
Server info: 25006 (Hippie Station)

>General description of the issue

Can't mine tiles with ore in them, again.  This was already fixed once, why'd you break it again?
>What you expected to happen

To be able to mine ore tiles with a pickaxe or ripley.
>What actually happened
Nothing, you cant' mine tiles with ore in them now.

>Steps to reproduce if possible

Go mining.

**Comment by praisenarsie** [comment]
#5196 #5234 is related

**Comment by GuyonBroadway** [comment]
was fixed.
