### ISSUE TITLE
Clicking a sprite has a chance of clicking the floor under it instead

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5325]
In-Game report from mechknight:
Server info: 25017 (Hippie Station)

>General description of the issue
When clicking a sprite, say yourself or another person, it will click the floor instead. When using say a health analyzer on myself, half the time it will end up used on the floor. Or when trying to shoot someone on the ground with lazers, it will pass right by them, since you're clicking the floor.

>What you expected to happen
To click the actual sprite

>What actually happened
It clicks the floor

>Steps to reproduce if possible
Take a health analyzer, walk around and analyze yourself.

**Comment by GuyonBroadway** [comment]
Analysing the floor is a clown clumsiness thing and lasers passing over downed people is intended.
