### ISSUE TITLE
Forcing game modes does not work anymore (ADMIN)

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5336]
You can't force game modes anymore in the lobby before the round starts.

**Comment by JohnGinnane** [comment]
upstream issue?

**Comment by JohnGinnane** [comment]
Also how do you force gamemodes so I can test this

**Comment by Pyko1** [comment]
Admin -> Game Panel -> Change Game Mode / (Force Secret Mode)

**Comment by ghost** [comment]
bump

**Comment by Cyberboss** [comment]
is this upstream or not?

**Comment by ghost** [comment]
I'll have to dig trough logs, suspect it's some fuckery with perms

**Comment by ghost** [comment]
appreciate it fellas

**Comment by Carbonhell** [comment]
Confirmed. It doesn't seems to be a permission issue, it might be upstream.

**Comment by ghost** [comment]
Please fix

**Comment by Cyberboss** [comment]
I've checked this multiple times, it definitely works on /tg/ or i'd be getting hell for it

**Comment by JohnGinnane** [comment]
@Carbonhell is this still broke?

**Comment by Carbonhell** [comment]
Probably still broken, this is high priority cmon guys

**Comment by Pyko1** [comment]
was working like a month or so ago when someone had forgotten the server on extended.

**Comment by Carbonhell** [comment]
This probably only affect secret force gamemode.

**Comment by Pyko1** [comment]
failed to force secret gamemode , but it was due to not enough players for the mode

**Comment by Carbonhell** [comment]
problem is that sometimes it just silently ignores your input and picks a random mode

**Comment by Carbonhell** [comment]
magically fixed itself
