### ISSUE TITLE
Mysterious Boat, no longer floats

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5352]
In-Game report from hentaisatan:
Server info: 25069 (Hippie Station)

>tried using mysterious boat. Died due to lava poisoning

>Be able to sail the lava seas

>I burned to a crisp 

>Get mysterious boat, put in lava, hop on, watch the fireworks.

**Comment by praisenarsie** [comment]
upstream tissue

**Comment by Carbonhell** [comment]
Should be fixed in #5979
