### ISSUE TITLE
The ? href in who command doesn't work for gameadmins

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5401]
In-Game report from carbonhell:
Server info: 25137 (Hippie Station)

>General description of the issue
I clicked who, clicked the ? next to a guy, and it told me i had no authorization key or some shit

>What you expected to happen
Player info should have displayed in chat

>What actually happened
ADMIN LOG: CarbonHell/(Tyson Richards) clicked an href with no authorization key!

>Steps to reproduce if possible
Be GA, click who, click a ?, profit

**Comment by Cyberboss** [comment]
Upstream issue

**Comment by ghost** [comment]
downstream issue

**Comment by ghost** [comment]
our `who` is modified ;-)
