### ISSUE TITLE
Airlock Sprites & Locker Sprites

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5409]
The airlocks for the general access hallways are a default green, revert to original.
Our locker sprites were changed, revert to original.

**Comment by ghost** [comment]
get used to it, these sprites are better

**Comment by ghost** [comment]
get used to this
**unzips dick**

**Comment by ghost** [comment]
I agree, this needs to be changed

**Comment by ghost** [comment]
@Chnkr you always hate new sprites

**Comment by ghost** [comment]
+1 change this

**Comment by Blute1** [comment]
+1

**Comment by praisenarsie** [comment]
because hippie isn't 3/4 you mong
