### ISSUE TITLE
Thermals/Vampire

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5417]
In-Game report from doxdd:
Server info: 25150 (Hippie Station)

>General description of the issue
Vampires/thermals are broken, in the sense that instead of showing people through walls they just make basically everything look pitch black.

>What you expected to happen
Expected to see normally and through walls.

>What actually happened
Couldn't see fucking shit and stumbled around like a blind man.

>Steps to reproduce if possible
Wear thermals/become vampire

**Comment by ghost** [comment]
thermals are broken, we know

**Comment by ghost** [comment]
Dupe of https://github.com/tgstation/tgstation/issues/33409

**Comment by Carbonhell** [comment]
Fixed in #5685
