### ISSUE TITLE
Gluttony's Blessing

### ISSUE THREAD

**Issue by Danielle-Robinson** [HippieStation/HippieStationdeprecated2020#5420]
ID: 25161

Issue: Well, I injected myself with the gluttony's blessing. 
A couple seconds later, I was made a fucked-up morph, which was invisible and could attack, and couldn't be fixed with admin variables.

**Comment by Koffheatalt** [comment]
that's the whole fucking purpose of gluttony's blessing???????????????
i dont see the problem
