### ISSUE TITLE
Slime Management Console Crashes SS13

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5503]
In-Game report from expensiveantique:
Server info: 25271 (Hippie Station)

>General description of the issue
If I open the slime manangement console, my game crashes

>What you expected to happen
The slime management screen to open

>What actually happened
My game crashes and i have to rejoin the server

>Steps to reproduce if possible

Click on slime management console

**Comment by ghost** [comment]
known byond bug

**Comment by JohnMcLaime** [comment]
Same shit with console whch lets you place pirate ship, a month ago or when they were added, i was pirate 2 times and it worked fine, last week i got to be pirate again, using the console would crash/freeze my game if i held the cursor over hud button, long enough for tooltip to appear or it would just crash aftet 5-10 seconds of moving the ship landing zone.

**Comment by praisenarsie** [comment]
known and we can't do much about it, tg will probably find a fix eventually.
