### ISSUE TITLE
Roundstart clumsyness for batons.

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5509]
In-Game report from romathebest:
Server info: 25281 (Hippie Station)

>General description of the issue
>Be rd roundstart
>Try to stun something
>You accidentally hit yourself with the stungun! 

Same shit happened to ce, less than 5 min into the round. This issue has been going on for multiple rounds. Guns work fine though.

>What you expected to happen
To not have this shit

>What actually happened
You accidentally hit yourself with the stungun! 
You accidentally hit yourself with the stungun! You accidentally hit yourself with the stungun! You accidentally hit yourself with the stungun! You accidentally hit yourself with the stungun! You accidentally hit yourself with the stungun! You accidentally hit yourself with the stungun! You accidentally hit yourself with the stungun! You accidentally hit yourself with the stungun! 

>Steps to reproduce if possible
Try hitting something with a baton/stungun.

#killamari

**Comment by praisenarsie** [comment]
upstream issue that should've been merged/fixed by now? will doublecheck in a bit

**Comment by praisenarsie** [comment]
t'was fixed
