### ISSUE TITLE
There is an outdated protolathe board in Tech Storage.

### ISSUE THREAD

**Issue by praisenarsie** [HippieStation/HippieStationdeprecated2020#5537]
![2017-12-22_14-04-56](https://user-images.githubusercontent.com/31222036/34300720-422a69b0-e721-11e7-8a55-8f3393842ace.png)

**Comment by Jujumatic** [comment]
NO WAIT STOP ITS JUST A PRANK BRO

**Comment by praisenarsie** [comment]
shut up you dumb powergamer

**Comment by Jujumatic** [comment]
NEVER REEEEEEEEEEEEEE

**Comment by WarRage333** [comment]
keep it like that the new rnd system sucks when you cant make everything at rnd

**Comment by JohnMcLaime** [comment]
Keep it, sec doesnt even have a protolathe, they need to take the board from hos's locker and build it.

**Comment by Carbonhell** [comment]
Remove it and put a normal sec protolathe in security.

**Comment by WarRage333** [comment]
DO NOT TACH MY SPHAGET

if you do this which will kill rnd fully at least put an extra science protolathe in secure storage.

**Comment by 2Dollarbill** [comment]
If it's the old Science Protolathe and it functionally works, don't see a reason for it to be removed.

**Comment by JohnMcLaime** [comment]
It works, it doesnt have a department lock, so you can get all items once researched.

**Comment by Pyko1** [comment]
is prolly gone on my mirror map fix, since i updated the boards available.

**Comment by xTrainx** [comment]
Fuck

**Comment by GuyonBroadway** [comment]
I might just add an omnilathe to R&D

**Comment by Pyko1** [comment]
cant they like print boards for other lathes already?

**Comment by GuyonBroadway** [comment]
Not that I know of

**Comment by xTrainx** [comment]
Cant print any kind of protolathe
