### ISSUE TITLE
stuck to the wall

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5546]
In-Game report from theflyingbananagaming:
Server info: 25326 (Hippie Station)

>General description of the issue
when i got shot with a crossbow against a wall and got pinned against it, the rod fell out and i couldn't move and nothing worked to get me un-stuck

>What you expected to happen
that it would free me when the rod fell out

>What actually happened
i got stuck and couldn't move

>Steps to reproduce if possible

step 1# shoot someone with a crossbow against a wall. step 2# remove the rod or let it fall out step .3# get stuck

**Comment by praisenarsie** [comment]
@JohnGinnane JOOOOOOOOOHN

**Comment by JohnGinnane** [comment]
Just tested this and it happened on the first go

![image](https://user-images.githubusercontent.com/3355198/34313144-23d185da-e761-11e7-9c18-8557eddd4e15.png)

**Comment by JohnMcLaime** [comment]
WALL STUCK

**Comment by ghost** [comment]
PLEASE
I BEG YOU
WE'RE DEAD
YOU'RE G-GENUINE DICKSUCKER

**Comment by JohnGinnane** [comment]
fixed in https://github.com/HippieStation/HippieStation/pull/5556 )
