### ISSUE TITLE
Construction button does not work properly

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5563]
In-Game report from kutanoid:
Server info: 25375 (Hippie Station)

>General description of the issue
Playe cannot reopen construction menu. It happened everytime, after player used construction menu just once and then closed it. However, rejoin fix the problem, it is a higly disturbing to rejoin a server, just to construct anything through this UI

>What you expected to happen
I can reopen construction menu anytime, without any issues

>What actually happened
I cannot reopen construction menu

>Steps to reproduce if possible

Log in to the server
Pick any materials require to construct
Construct any item by construction menu
Quit construction menu and try to open it again

**Comment by JohnMcLaime** [comment]
Happened to me with ling emporium menu, to fix it you need to fully reconnect.
Sometimes happens with crafting menu and other tg ui menus, happened often for me with canister menus.
Tg ui is overrated crap, it wasnt worth their effort.
Fuck tg.

**Comment by Carbonhell** [comment]
Hasn't happened anymore, closing
