### ISSUE TITLE
MMI in Mechs

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5583]
In-Game report from bardofrage:
Server info: 25415 (Hippie Station)

When an MMI is put into a mech, moving will let the MMI "Climb out" which puts them in a sort of headbug state where they are pulled out of thed mech whenever they try to move, and even if they are picked up from beneath the mech they still see from the perspective of it.

When this happened, the mech in question was an odysseus and I was the MMI.

I'd imagine you can recreate these steps by putting an active MMI into a mech

**Comment by JohnGinnane** [comment]
Can confirm, I seen this happen the other day, trying to put MMI into mech but it keeping "falling out" after he moved one tile

**Comment by Carbonhell** [comment]
Not sure what's the current status with MMIs in mechs aside from the fact they're /tg/ stuff. Requires reproducing to see if the bug still happens.

**Comment by WarRage333** [comment]
Fixed

**Comment by AnthonyJNgo** [comment]
This should be closed.
