### ISSUE TITLE
spamming shutters to open/close will spam their sound

### ISSUE THREAD

**Issue by praisenarsie** [HippieStation/HippieStationdeprecated2020#5586]
https://youtu.be/mfgXQMhpbmE

**Comment by Carbonhell** [comment]
Confirmed,still happening

**Comment by AnthonyJNgo** [comment]
This is still an issue, checked it the other day. I'm pretty sure just adding a 2-3 second delay after the sound is played before it is played again will resolve it.

**Comment by Jujumatic** [comment]
1 line change or so, a $1 bounty most likely

**Comment by praisenarsie** [comment]
$100*

**Comment by Jujumatic** [comment]
go back to whatever bastard hole you came from

**Comment by Carbonhell** [comment]
Fixed in #11169
Thanks yoyo
