### ISSUE TITLE
You cant reserach gravity catapult for mechs in the new rnd system

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5617]
In-Game report from warrage:
Server info: 25484 (Hippie Station)

>General description of the issue
Autistic tg coders left it out or maybe even worse locked it behind an insane RnD wall (i didn't get to it in 1 hour THANKS 2400 research points per minute!!!)

>What you expected to happen
fuck everything 

>What actually happened
tg balance can go eat a shit

>Steps to reproduce if possible
try to research the grav catapult with the new rnd system

**Comment by JohnMcLaime** [comment]
oh right my nigga catacuck is missing and i havent noticed it

**Comment by WarRage333** [comment]
Fixed
