### ISSUE TITLE
cluwne/cat bans

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5621]
In-Game report from glordqtinkle:
Server info: 25487 (Hippie Station)

>General description of the issue

cant apply cat/cluwne ban
also cluwnebans instantly kill whoever is cluwned whenever they spawn.
>What you expected to happen
go away normies

>What actually happened
get out get out get out

>Steps to reproduce if possible
reeeeeeeeeeeeeeeeee

**Comment by Manly-Dwarf** [comment]
Cluwnebans instantly kill whoever is cluwned thanks to the fact that the idiots over at the Upstream Merge forgot that Brain Trauma is entirely incompatible with our code.
