### ISSUE TITLE
I f#%&d up the log

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5631]
In-Game report from sunkship203:
Server info: 25493 (Hippie Station)

>General description of the issue
I messed log line height.

>What you expected to happen
give some space between text lines.

>What actually happened
im too stupid to make a single click lmao

>Steps to reproduce if possible
don't, but please tell me how to reset log.

**Comment by Carbonhell** [comment]
What?
Doesnt seems to be a code issue,closing
