### ISSUE TITLE
autolathe makes cargo lose power when fed items to recycle

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5644]
In-Game report from adeptmechanicus:
Server info: 25505 (Hippie Station)

>General description of the issue
put 50 sheets of metal in, made 10 shotgun shells, put 3 shells in, cargo power went out. happened multiple times over multiple rounds, cargo APC shows 0 power.

>What you expected to happen
to actualyl recycle my shit

>What actually happened
the cargo APC lost power totally

>Steps to reproduce if possible

try to recycle shit

**Comment by JohnMcLaime** [comment]
That used to happen when you put raw ore in a protolathe, but they removed that feature. I thought it was balancing decision,

**Comment by Pyko1** [comment]
fixed in https://github.com/HippieStation/HippieStation/pull/6035
