### ISSUE TITLE
Mentor Permissions

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5653]
In-Game report from bardofrage:
Server info: 25523 (Hippie Station)

Mentors can aghost, f6 and open player pannel to see antags as well as PM people

**Comment by ghost** [comment]
WTF

**Comment by dankess13** [comment]
can confirm, only me and bard are aware of this at the time of this report

**Comment by Blute1** [comment]
where were u when mentors had all admin perms thanks tg

**Comment by bardofrage** [comment]
Yeah, I made this report. No beuno

**Comment by ghost** [comment]
Mentors are basically glorified admins, closing this issue since we are removing all mentors and rewriting the system after new years.
