### ISSUE TITLE
Limb loss leaves hand sprite.

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5672]
In-Game report from milliardomarquise:
Server info: 25551 (Hippie Station)

>General description of the issue
Losing your arms leaves bloody little red hand stumps for your sprite, not that you can do anything with them.

>What you expected to happen
If I lose my arm, I should lose the hand that was attached to it as well.

>What actually happened
I have ghostly floating hands next to my body.

>Steps to reproduce if possible
Take captains sword, aim at arm, strip nekkid.

**Comment by praisenarsie** [comment]
known and requires respriting everything or some dumb shit like that
