### ISSUE TITLE
Blood Brother

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5683]
In-Game report from doxdd:
Server info: 25562 (Hippie Station)

>General description of the issue
If you don't qualify for any jobs you wanted, however get the blood brother antag status, you're able to pick any jobs, even ones that aren't normally able to be antagonist such as sec/HoS/Captain, and retain your antagonist status.

>What you expected to happen
Just wanted to play the game and either get the job I wanted, get antagonist and a random job, both of those, or stay in the lobby.

>What actually happened
I didn't get put in the game, but was a blood brother antagonist.

>Steps to reproduce if possible
All jobs to never on a server with one/two players since blood brother is a team antagonist, return to lobby if the job isn't available, and blood brother as the only possible gamemode. It should either put you as a random job as blood brother, /should/, but from what I've seen it instead keeps you at the main menu with the antagonist status.

**Comment by JohnMcLaime** [comment]
You are russian too right?

**Comment by Carbonhell** [comment]
Gamemode was disabled so this does not matter anymore.
