### ISSUE TITLE
Traitor Clowns still shoot themselves

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5700]
In-Game report from glordqtinkle:
Server info: 25624 (Hippie Station)

>General description of the issue
Clown shot himself in the foot with the ebow. This is most likely due to that bugfix relating to everyone being clumsy.

**Comment by GuyonBroadway** [comment]
This has actually been a thing since before then.

**Comment by JohnGinnane** [comment]
Should we remove the clumsy trait if clown is antag? Kinda makes it the same level of difficulty as other players, where as now it's more interesting if the clown manages to complete his objectives with his.. limited capabilities

**Comment by Jujumatic** [comment]
to be fair you can do some super quick genetics to make yourself not clumsy but i guess that's not the point here. i thought people liked playing traitor clown because of the challenge it brings, though

**Comment by JohnGinnane** [comment]
yeah I would think the same, I'd say this is intended (i.e we don't want remove clumsy from tator clown)
