### ISSUE TITLE
Dissapearing wall griders

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5709]
In-Game report from wouju:
Server info: 25627 (Hippie Station)

Medbay was blown up and there were wall griders where the walls used to be

I expected to finish the walls by adding plating so i can clone people without them being instantly killed due to lack of O2 and pressure

Wall griders dissaper when i "finished" adding plating, just poof! I asked Adminhelp to help me out, the admin tried the same but the wall griders dissapeared, told me to Report the issue which i am doing right now.

PS: It also happened to other griders in medbay

**Comment by GuyonBroadway** [comment]
Known bug, fixed by a mirror.

**Comment by JohnGinnane** [comment]
@GuyonBroadway https://www.youtube.com/watch?v=8ElaXDNqrlM
