### ISSUE TITLE
input gets stuck

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5726]
In-Game report from carbonhell:
Server info: 25651 (Hippie Station)

input randomly gets stuck,so my char keeps going in a direction without me being able to stop it,gotta relog to fix it

**Comment by Pyko1** [comment]
Are you sure that the gravity generator was not offline? :3

**Comment by Carbonhell** [comment]
yeah man, it wasn't that. it was like me walking into a direction,except the fact i wasn't holding that key

**Comment by praisenarsie** [comment]
@Carbonhell did you switch hotkeys via TAB while moving, if so that's known and can't be fixed

**Comment by Carbonhell** [comment]
>cant be fixed
:Doubt:

**Comment by praisenarsie** [comment]
![](http://i.imgur.com/IKpgPyD.png)

## IT CAN'T BE FIXED, I'M TELLING YA

**Comment by praisenarsie** [comment]
well probably it can but ninja needs to get off the toilet and make hotkeys better

**Comment by Carbonhell** [comment]
Seems to have been fixed somewhat. Hasn't happened to me in ages.
