### ISSUE TITLE
Toxins vent pump doesn't work

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5757]
In-Game report from johnfg:
Server info: 25698 (Hippie Station)

>General description of the issue
\>be me
\>try to make bomb
\>vent doesn't succ the good shit out of chamber

>What you expected to happen
vent in mixing room to suck out hot sticky plasma

>What actually happened
nothing it just kind fucked off

>Steps to reproduce if possible
put stuff in, and then try pull it out

**Comment by praisenarsie** [comment]
upstream tissue afaik

**Comment by JohnGinnane** [comment]
This is fixed
