### ISSUE TITLE
Sheet stacking broke

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5795]
In-Game report from carbonhell:
Server info: 25754 (Hippie Station)

>General description of the issue
When trying to divide sheets, it keeps saying "your x stack now contains y+1 x bars"

>What you expected to happen
to get 1 sheet from my 15 sheets of metal

>What actually happened
it said my stack now contained 16 sheets of metal

>Steps to reproduce if possible
have any kind of sheet in a hand, use the other hand on it

**Comment by WarRage333** [comment]
It does not actually add an extra sheet it just says so, but yeah its really annoying you cant unstack things.

**Comment by Carbonhell** [comment]
@JohnGinnane was this caused by your pr at tg? If yes any news?

**Comment by JohnGinnane** [comment]
Yeah I fixed this upstream a while ago
