### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5799]
In-Game report from lordquailius:
Server info: 25759 (Hippie Station)

>General description of the issue
Viruses don't work on nonhumans (except monkeys).

>What you expected to happen
I injected myself as a lizard person with a virus about 50 times, sprayed myself with blood, and stood in the blood for 5 minutes. I also tried to inject a moth person with a virus as well. I expected both of us to get the virus.

>What actually happened
The virus doesn't manifest in liggers or moths, but manifests instantly in humans and monkeys.

>Steps to reproduce if possible
Make an entirely beneficial virus (blue on the medical hud) and try to inject it into different races to see if it ever manifests.

**Comment by Carbonhell** [comment]
needs testing

**Comment by Jujumatic** [comment]
Monkeys cough and collapse when infected by viruses, needs verifying

**Comment by AnthonyJNgo** [comment]
This could be seen as a racial feature, honestly.
