### ISSUE TITLE
Moths have bright white 1x1px eyes.

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5839]
![image](https://user-images.githubusercontent.com/15840795/34801758-401432e6-f662-11e7-802b-e59cc02ef64a.png)

This isn't normal moth behvaiour.

**Comment by praisenarsie** [comment]
does it show up ingame too, the char preview might be wrong

**Comment by ghost** [comment]
didn't try, will test in a bit

**Comment by ghost** [comment]
yeah it's fucked up ingame too

**Comment by tortellinitony** [comment]
flies have the same problem

**Comment by Carbonhell** [comment]
this was fixed long ago
