### ISSUE TITLE
Gluttony's Blessing

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5864]
In-Game report from lordquailius:
Server info: 25814 (Hippie Station)

>General description of the issue
Gluttony's Blessing doesn't work on non humans

>What you expected to happen
I expected to turn into a green blob creature like what usually happens when you inject Gluttony's Blessing

>What actually happened
Jack diddly fucking squat

>Steps to reproduce if possible
Inject self as a non human (ligger, moth, what the fuck ever)

**Comment by Carbonhell** [comment]
confirmed, the disease itself can't be given to anyone for some reason. Upstream issue?

**Comment by Carbonhell** [comment]
Confirmed to be fixed.
