### ISSUE TITLE
Stun Batons don't get drained by the Ion Rifle

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5910]
In-Game report from popotongue:
Server info: 25855 (Hippie Station)

>Stun batons don't get drained from the ion rifle

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by JohnGinnane** [comment]
Seems a few items might not be drained by Ion rifle

**Comment by Carbonhell** [comment]
Now it does, maybe not too much,just 10% per emp. But anyway, that's not an issue, so this is fixed
