### ISSUE TITLE
CANT EQUIP CLOAKS GAME UNPLAYALBE

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5915]
In-Game report from warrage:
Server info: 25863 (Hippie Station)

>General description of the issue

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Pyko1** [comment]
did you try backpack slot?

**Comment by WarRage333** [comment]
yeah it goes into the backpack slot, why did it move from neck its a dead feature now not like really anyone used it

**Comment by DaydreamPuppeh** [comment]
It moved because now it is a backpack with slots
