### ISSUE TITLE
Who command duplicating some entries

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5916]
In-Game report from carbonhell:
Server info: 25871 (Hippie Station)

>General description of the issue
Used who and noticed there's a guy listed two times,even after repeated calling of said command (VPickles)

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by JohnGinnane** [comment]
I'll have a look at the who command and maybe make it sorted by alpha

**Comment by JohnGinnane** [comment]
@Carbonhell has this happened since? I checked who code and it looks like it already sorts by alpha

**Comment by Carbonhell** [comment]
Fixed long time ago
