### ISSUE TITLE
Booze-o-mat

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5920]
In-Game report from glordqtinkle:
Server info: 25873 (Hippie Station)

>General description of the issue
Sprite broken rending the machine unable to be interacted with.
https://cdn.discordapp.com/attachments/276481746189680640/401965770453549057/unknown.png

**Comment by praisenarsie** [comment]
@tortellinitony p sure you did something with this

**Comment by GuyonBroadway** [comment]
Dupe of :https://github.com/HippieStation/HippieStation/issues/5912
