### ISSUE TITLE
Recycler duplicating brain from MMI

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5924]
In-Game report from kopoba:
Server info: 25876 (Hippie Station)

>So i was MMI and some faggot flush me in disposal i make my whole way to recycle machine. when i arrived recycler sucked me and spits out leaving my brain unedrneth and mmi still was with brain.

>Dunno maybe nothing

>Recycler duplicat brain from MMI

>Step to reproduce
1. start round as borg
2. captain condom
3. somone blow you up with rnd console
4. CE condome flush you as MMI to disposal
5. No gravity/comms due tesla loose you make whole way to disposal room with recycle
6. Ping for help watching you in mmi and your brain under recycler

**Comment by kopoba** [comment]
https://i.imgur.com/R5zT52z.gif

**Comment by tortellinitony** [comment]
Confirmed
