### ISSUE TITLE
SO MUCH LAG I CANT PLAFHERIOPGHR

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5925]
In-Game report from multipleshoe:
Server info: 25876 (Hippie Station)

>General description of the issue
Theres so much lag! I cant play! It freezes every two seconds!

>What you expected to happen
NOT LAG

>What actually happened
LAG

>Steps to reproduce if possible

JOIN GAM WITH DECenT CONNECTION

**Comment by GuyonBroadway** [comment]
Known issue and its not a code issue.
