### ISSUE TITLE
Voice of god does not work

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#5954]
In-Game report from warrage:
Server info: 25908 (Hippie Station)

>General description of the issue
Voice of god upon speaking certian words should force people to do actions

>What you expected to happen

^^
>What actually happened
You just speark gibberish like usual but its not BIG TEXT nor does force people to do stuff

>Steps to reproduce if possible

Surgery divine vocal cords into your mouth instead of a tounge.

**Comment by WarRage333** [comment]
Seems to be fixed

**Comment by Carbonhell** [comment]
Thank you for telling us!
