### ISSUE TITLE
spray cans broken?

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6005]
In-Game report from pyko:
Server info: 25963 (Hippie Station)

could not see my sprays on walls.

**Comment by Pyko1** [comment]
seems to work on floors tho but leaves **CHEMPILES**

**Comment by Carbonhell** [comment]
https://github.com/tgstation/tgstation/pull/39369

**Comment by Carbonhell** [comment]
Confirmed to be still broken. Although gang ones work. Should be as easy as moving my code up to all graffitis.
