### ISSUE TITLE
The detective's revolver is stupidly over powered

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6040]
In-Game report from vpickles:
Server info: 25982 (Hippie Station)

>General description of the issue
The detective's gun is far too strong now that it has been buffed

>What you expected to happen
One bullet = Stun

>What actually happened
One bullet = Crit

>Steps to reproduce if possible
Shoot someone in the head with the revolver

**Comment by Manly-Dwarf** [comment]
The Detective's revolver hasn't been touched in a long time. What?
