### ISSUE TITLE
loop in bar

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6072]
In-Game report from aidong:
Server info: 25998 (Hippie Station)

>General description of the issue 
a player by the name old man has made a bar trap that involves a chute that traps people in a loop.

>What you expected to happen
Him to let many people out

>What actually happened
He did not let anybody out.

>Steps to reproduce if possible

Ban people who make endless chute loop traps

**Comment by Carbonhell** [comment]
Not an issue...
