### ISSUE TITLE
inconsistent reee

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6118]
In-Game report from glordqtinkle:
Server info: 26033 (Hippie Station)

>General description of the issue
ion gun destroys the charge of batons and tazer guns but not actual tazers? reeeeeeeeeeeeeeeee

>What you expected to happen
REEEEEEe

>What actually happened
REEEEEEEEEEEEEEEE

>Steps to reproduce if possible

REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by GuyonBroadway** [comment]
What the fuck do you mean by "actual tasers"

**Comment by geylard** [comment]
stun guns you big bully

**Comment by JohnMcLaime** [comment]
It barely affects stunbatons too.

**Comment by JohnGinnane** [comment]
Duplicate of #5910
