### ISSUE TITLE
Can't remove pictures from news casters once you put htem in

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6119]
In-Game report from higitus:
Server info: 26038 (Hippie Station)

>say you write a story with a picture, well if you want to write another story on that same machine you cant remove the picture. So you need to find a new one.

>Repeated use of a newscaster

>Ran around the station looking for new ones

>Be a news man

**Comment by Carbonhell** [comment]
still happening

**Comment by Carbonhell** [comment]
It...sorta works?It's true you cannot "remove" a picture, but on inserting it just scans it,it doesn't take it from your hand. You can scan another one even with one already loaded in,no runtimes and everything works. I'd say it works.
