### ISSUE TITLE
Power Disconnected in Science's new "Circuit Lab" and rad equipment locker spawns on a wall

### ISSUE THREAD

**Issue by neetdev** [HippieStation/HippieStationdeprecated2020#6227]
[Round ID]: Every round

[Reproduction]: Go to science in the room just east of the chem lab where the autolathe is and you'll see the APC is not connected to the grid, which makes the room's power go down very early into the round.

There is also a yellow radiation equipment locker that spawns on the south wall of the chemistry room west of the circuit lab.

**Comment by Pyko1** [comment]
prolly missed out something when i copypasted the areas around from box to hippie.

**Comment by Pyko1** [comment]
checking/fixing as right now

**Comment by Pyko1** [comment]
fix created
