### ISSUE TITLE
Inspect rectum cavity

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6268]
In-Game report from longtittytyrone:
Server info: 26174 (Hippie Station)

>General description of the issue
wont work no good 

>What you expected to happen

fit nukie disc in my booty
>What actually happened

booty too tight?
>Steps to reproduce if possible

click on booty with no clothes on in the help intent

**Comment by WarRage333** [comment]
didn't use grab intent

it works
