### ISSUE TITLE
new player options still open after round started

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6282]
In-Game report from endaru:
Server info: 26206 (Hippie Station)

>General description of the issue
I pressed ready when the crew spawned now the start menu shows is just staying on the screen thinking i didint press the ready buton

>What you expected to happen

to just disaper of my screen the menu

>Steps to reproduce if possible

click ready when the round is about to start

**Comment by Carbonhell** [comment]
Probably an isolated incident, it doesn't happen right now.
