### ISSUE TITLE
vampire bug

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6289]
In-Game report from endaru:
Server info: 26213 (Hippie Station)

>General description of the issue
i cant hipnotise it says it recharging but is not recharging i hit it twice as a with no blood

**Comment by Carbonhell** [comment]
@steamp0rt

**Comment by ghost** [comment]
I'd need this to be reproduced

**Comment by Carbonhell** [comment]
Cannot reproduce
