### ISSUE TITLE
Cavity implants

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6321]
In-Game report from pyko:
Server info: 26237 (Hippie Station)

You drape the surgical drapes over Admin's chest to prepare for a cavity implant.
You begin to make an incision in Admin's chest...
You succeed.
You begin to clamp bleeders in Admin's chest...
You succeed... just about!
Admin screams!
You begin to retract the skin in Admin's chest...
You succeed... just about!
Admin screams!
You begin to make an incision in Admin's chest...
You succeed.
You begin to insert the bomb payload into Admin's chest...
You succeed... just about!
Admin screams!

Yet the bomb core just remains in my hand, unimplanted.
But the surgery has already proceeded to next step.

**Comment by Pyko1** [comment]
seems to work with normal surgery, maybe the issue is in the "You succeed... just about!" part.

**Comment by WarRage333** [comment]
https://github.com/HippieStation/HippieStation/issues/5300 

JohnGinnane commented 22 days ago
I STILL HAVENT FIXED THIS MY BAD

**Comment by JohnGinnane** [comment]
🤔🔫
