### ISSUE TITLE
Invisible vent in incinerator room,turbine section(which should be a scrubber)

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6367]
In-Game report from carbonhell:
Server info: 26287 (Hippie Station)

>General description of the issue
There is an invisible vent on the right of the igniter

>What you expected to happen
There should be a scrubber, not an invisible vent

>What actually happened
invisible vent

>Steps to reproduce if possible
use your goddamn eyes wtf

**Comment by JohnGinnane** [comment]
Caused by https://github.com/HippieStation/HippieStation/pull/4904 I suspect

EDIT: nevermind

**Comment by JohnGinnane** [comment]
@tortellinitony from what I can see we're still using tg icons for vents, is that intentional?

**Comment by Dinopeaks** [comment]
all is fine here this is fixed 
i did not have to touch it this one is all good
