### ISSUE TITLE
low pressure indicator wont go away

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6375]
In-Game report from friedsnow:
Server info: 26291 (Hippie Station)

>General description of the issue

the low pressure wont go away even if im in spess suit or in a normal pressure
>What you expected to happen

>What actually happened

>Steps to reproduce if possible

dunno

**Comment by Carbonhell** [comment]
Should be fixed, I haven't noticed it recently.
