### ISSUE TITLE
Spamming last resort as a ligger too fast break the game

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6376]
In-Game report from warrage:
Server info: 26293 (Hippie Station)

>General description of the issue
Somehow managed to use last resort twice

>What you expected to happen
Turn into a headslug and do stuff

>What actually happened
Turned into a headslug for a nanosecond and then swapped to another headslug that didn't spawn in the game world and the screen was black, upon ghosting i was in the arrival shuttle as a ghost

>Steps to reproduce if possible
Somehow use lest resort twice really fast

**Comment by JohnMcLaime** [comment]
Why this doesnt have yes/no prompt anyway?

**Comment by WarRage333** [comment]
It does

i think
