### ISSUE TITLE
Injecting power cell doesn't change syinge back to "DRAW" mode

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6378]
In-Game report from johnfg:
Server info: 26296 (Hippie Station)

>General description of the issue
When you inject a power cell with something using a syringe, the syringe remains in "INJECT" mode

>What you expected to happen
The syringe to reset back to "DRAW" mode

>What actually happened
The syringe remained in "INJECT" mode even though it was empty

>Steps to reproduce if possible
Draw liquid into syringe until full, click on power cell with syringe

**Comment by JohnGinnane** [comment]
Just tested this and it's fixed
