### ISSUE TITLE
If you emag a borg while they have modules enabled they need to disable them even though they appear empty

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6397]
In-Game report from johnfg:
Server info: 26321 (Hippie Station)

When a borg is emagged and they have some modules already enabled, these module slots are shown to be disabled but they are still occupied. To fix this you need to select that slot (1, 2, or 3) and then hit "Store"

**Comment by JohnGinnane** [comment]
Need to see if this is upstream or no
