### ISSUE TITLE
Mirror Map Fixes to OUR Version of Boxstation

### ISSUE THREAD

**Issue by tortellinitony** [HippieStation/HippieStationdeprecated2020#6415]
- [ ] #6387 
- [ ] #6344 
- [ ] #6298 
- [ ] #6297 
- [ ] #6293 
- [ ] #6229 
- [x] #6437 
- [ ] #6506 
- [ ] #6471 

Also Centcom
- [ ] #6306

**Comment by JohnGinnane** [comment]
\>#6437

how about no please
