### ISSUE TITLE
Mindslaved people doesnt show at end of round report

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6523]
In-Game report from enukar:
Server info: 26486 (Hippie Station)

>General description of the issue
When you mindslave someone the person doesnt appear as mindslaved and everyone gets salty calling self-antagging and shit. 

>What you expected to happen
Report should show for minor mindslave the date of when he was slaved and when it weared off like

The others were:
Marco polo mindslaved (12:23 - 12:38) that way you can tell if the person was self-antagging after that time. 

>What actually happened
Mindslaved people doesnt show. 

>Steps to reproduce if possible
Mindslave someone, make them kill people, end the round, watch them get salty and try to report him.

**Comment by Carbonhell** [comment]
I think this issue is related to temp antags not showing up. Admins can indeed check this with logs, and if you adminhelp when something happens instead of waiting till round end,they can easily give you the answer. I don't think this really deserves to be fixed. Closing.
