### ISSUE TITLE
Random teleporter satellite ruins

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6536]
In-Game report from enukar:
Server info: 26503 (Hippie Station)

>General description of the issue
There is a missing ingredient for the teleport to work.

>What you expected to happen
Using the teleporter to go somewhere you need to. 

>What actually happened
I wasnt able to finish the teleporter computer, it's missing glass for the screen. You can get reinforced glass but doesnt work for the computer. It has to be normal glass. 

>Steps to reproduce if possible
Find the teleporter > try to make it work

**Comment by AnthonyJNgo** [comment]
+1 Placing a few sheets of glass near the ruins would resolve this. Will check it out tonight.

This is resolved in #10071

**Comment by xTrainx** [comment]
@k-k-karma @yoyobatty needs closing, the space teleporter have 2 shard of glass and a firethingy that you can use to fix the 2 glass for the computer

**Comment by yoyobatty** [comment]
Yep just weld the shards of glass
