### ISSUE TITLE
Apprentice contracts from wizard not working

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6570]
In-Game report from enukar:
Server info: 26560 (Hippie Station)

>General description of the issue
I rolled wizard and tried to let people have some fun, spent 4 of my 10 points to get 2 contracts, when the signed them and asked for powers, the smoke from the contract being made happened, but they didnt get wizard clothes or powers or anything.

>What you expected to happen
They actually getting the powers you select from the contract. 

>What actually happened
They werent even considered wizards or had any kind of hud saying they were wizards like the actual wizard does. The contracts did nothing. 

>Steps to reproduce if possible

Make someone sign an apprentice contract
See how it does nothing but let out some smoke

**Comment by WarRage333** [comment]
Fixed
