### ISSUE TITLE
warden didnt start implanted

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6589]
In-Game report from kendrickorium:
Server info: 26582 (Hippie Station)

warden didnt start implanted, literally arrived right after me (HOS) 
i was implanted

the ERT that showed up wasnt implanted either

warden was not antag or anything like that

**Comment by JohnGinnane** [comment]
Joining after roundstart:
![image](https://user-images.githubusercontent.com/3355198/37873893-1299b2f6-301d-11e8-9af0-18bb1c54d30a.png)

Joining on roundstart:
![image](https://user-images.githubusercontent.com/3355198/37873906-65ba4b94-301d-11e8-9c62-bb8f29af8a50.png)

**Comment by JohnGinnane** [comment]
https://github.com/HippieStation/HippieStation/blob/6cc7f3329505a5748bd61765bbab020a772eebce/code/modules/jobs/job_types/security.dm#L114
