### ISSUE TITLE
Can't use dead chat after dying as revenant

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6595]
In-Game report from dyl000:
Server info: 26583 (Hippie Station)

>General description of the issue
After dying as a rev and having my dust incinterated I was unable to use deadchat, I tried reconnecting, and closing out of the game but I still couldn't use

>What you expected to happen
I expected to be able to use deadchat

>What actually happened
I couldn't use deadchat

>Steps to reproduce if possible

step 1. Be rev
step 2. Die
step 3. Have dust be destroyed
step 4. Die of loneliness

**Comment by Carbonhell** [comment]
Has been fixed time ago.
