### ISSUE TITLE
Hippie Station tiles are missing textures

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6692]
In-Game report from johnfg:
Server info: 26677 (Hippie Station)

>General description of the issue
When you place a tile down where the "Hippie Station" tiles are normally, there is no texture

>What you expected to happen
See "Hippie Station"

>What actually happened
Black and purple checkered sqaures

>Steps to reproduce if possible
Welderbomb bridge, put tile down where "Hippie Station" normally is

**Comment by JohnGinnane** [comment]
![image](https://user-images.githubusercontent.com/3355198/36344309-5319dba4-1410-11e8-9075-af9fa3885197.png)

**Comment by praisenarsie** [comment]
make it an overlay or decal

**Comment by Carbonhell** [comment]
still happening,fuck sakes

**Comment by GuyonBroadway** [comment]
Why the fuck is this the case, didn't we fix this? I remember us fixing this.

**Comment by Carbonhell** [comment]
just checked it ingame, dunno but it should be trivial to fix

**Comment by xTrainx** [comment]
actually, in the map file, the sprites are there, but once loaded they lose the path to the icon for some reason
