### ISSUE TITLE
Screwdriver eye damage only healed by surgery

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6716]
In-Game report from jujumatic:
Server info: 26708 (Hippie Station)

>Eye damage from being stabbed in the eye with a screwdriver can only be healed by surgery

>Eye damage would be healed with oculine, or sensory restoration as I had that virus with me as well

>I stayed blind forever until I did self-surgery, and became fine as normal

>Stab thyself in the eyes with a screwdriver and drink oculine/use the sensory heal symptom from a virus. It will not heal any eye damage, not even damage that results only in nearsightedness instead of total blindness.

**Comment by AnthonyJNgo** [comment]
+1 this is weird, if it's still an issue. Only thing I can think of off the top of my head is that it's two different damage types.

Edit: just tested and this is not an issue. Screwdriver damage to eyes is repaired.
