### ISSUE TITLE
Trying to put spray bottle into science backpack causes spray to be used

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6717]
In-Game report from jujumatic:
Server info: 26708 (Hippie Station)

>The spray bottle is used on your tile if you try and place it into a science backpack that is full

>The backpack full message would appear

>The backpack full message appeared and the spray was used on my tile... causing me to burn horribly

>Get a spray bottle and try to place it into a science backpack that is full - use super dangerous chems for added fun and suicide

**Comment by JohnGinnane** [comment]
Confirmed but also a duplicate of #6715
