### ISSUE TITLE
Mouse icon constantly blinking

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6752]
In-Game report from spankmaster:
Server info: 26733 (Hippie Station)

>General description of the issue
Mouse in-game is constantly flipping back forth between a loading icon, annoying and hurts eyes.

>What you expected to happen

>What actually happened

>Steps to reproduce if possible
Apparently coupea gets it too, I'm on win10. No idea what's causing this or if it is related to the game, but if it is would be nice to fix it

**Comment by Carbonhell** [comment]
That's when it's downloading resources. It gets fixed once the download ends, nothing we can do.
