### ISSUE TITLE
gold slime extract, no mobs respawn

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6762]
In-Game report from rapidgokhandrum:
Server info: 26766 (Hippie Station)

>General description of the issue
gold slime extracts injected with plasma does not spawn random agressive mobs, the extract just disappear after getting injected with plasma. i did not try the same thing with blood, cuz my plan was to spawn rabid mobs in order to create chaos in the station, when i left the extract on the ground after the injection, it just disappears without any mobs.

>What you expected to happen
when injected with plasma, it should spawn rabid random mobs

>What actually happened
gold slime extract disappeared. (should check the same thing with blood too, however that was not a part of my plan so i did not try it)

>Steps to reproduce if possible
get an extract of gold slime, inject it with plasma and watch it disappear. really frustrating for a xenobiology player.

**Comment by WarRage333** [comment]
It works when you hold it. I was wondering why my cores didn't go off when i left them on the floor.

**Comment by WarRage333** [comment]
Fixed

**Comment by AnthonyJNgo** [comment]
Tested and can confirm this is resolved.
