### ISSUE TITLE
dark blue slime extracts

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6781]
In-Game report from rapidgokhandrum:
Server info: 26775 (Hippie Station)

>General description of the issue
they dont release freon (or n2) gas when injected with plasma, they just disappear after getting injected just like gold slime extracts

>What you expected to happen
release freezing n2 gas

>What actually happened
extract disappears, no gas

>Steps to reproduce if possible

inject plasma to dark blue slime extract

**Comment by AnthonyJNgo** [comment]
I'm 95% sure this has been fixed already and is no longer an issue. I'll double check tonight and if it is will edit this comment.

Edit: this is still an issue

**Comment by Jujumatic** [comment]
Easy fix expect $1 bounty

**Comment by AnthonyJNgo** [comment]
$2 bounty, headmin approved.
