### ISSUE TITLE
Minor issue with ghost spirte

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6807]
In-Game report from dyl000:
Server info: 26825 (Hippie Station)

>General description of the issue

Dying as Ian doesn't make my sprite a dog
>What you expected to happen

To be a ghost pupper
>What actually happened
was normal ghost

>Steps to reproduce if possible

>Be Ian
>Die
>=(

**Comment by tortellinitony** [comment]
Not an issue
