### ISSUE TITLE
uh the doors from shuttle to station dont work

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6828]
In-Game report from noncanceralias:
Server info: 8 ([HippieStationEU]: NOW 100% MORE EUROPE! (ENGLISH SERVER, LOW PING, LOW-RP, UNOFFICIAL WAY BETTER THOUGH))

>General description of the issue

>What you expected to happen

>What actually happened

>Steps to reproduce if possible

**Comment by Pyko1** [comment]
welp, is this even issue on hippiestation?

**Comment by Carbonhell** [comment]
goddamn..

**Comment by ghost** [comment]
wait did they seriously not change any config settings at all??

**Comment by Carbonhell** [comment]
a+
