### ISSUE TITLE
Tech disks arent worth anything?

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6829]
In-Game report from dyl000:
Server info: 26855 (Hippie Station)

>General description of the issue
Sold tech disk, got no money

>What you expected to happen

expected lots of money
>What actually happened

got no money
>Steps to reproduce if possible

1. get shit tons of tech onto a disk
2. Place disk onto shuttle in crate
3. Cry because disk gave no money like it is supossed to

**Comment by Carbonhell** [comment]
Not a bug
