### ISSUE TITLE
Blastco needs to be removed

### ISSUE THREAD

**Issue by tortellinitony** [HippieStation/HippieStationdeprecated2020#6902]
Since we are no longer using our own Centcom it needs to be removed from the Operative uplink and have the extra code removed.

**Comment by Manly-Dwarf** [comment]
We could probably re-code it to spawn a crate full of the blastco gear.

**Comment by GuyonBroadway** [comment]
We're only not using our own centcom due to nobody bothering to map it yet.

**Comment by tortellinitony** [comment]
ok we're gonna re add it maybe ill map it later
