### ISSUE TITLE
dark blue slime extract

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6918]
In-Game report from rapidgokhandrum:
Server info: 27000 (Hippie Station)

>General description of the issue

it doesnt release cold gas like it did before
>What you expected to happen

it should release something like freon when injected with plasma but it does not
>What actually happened
it just disappears

>Steps to reproduce if possible

**Comment by Carbonhell** [comment]
Duplicate of #6781
