### ISSUE TITLE
Bad upstream merge - Skeletons are once again immune to space, syringes, and bruise packs/ointment.

### ISSUE THREAD

**Issue by Manly-Dwarf** [HippieStation/HippieStationdeprecated2020#6963]
[Round ID]: ???
[Testmerges]: It was caused by an upstream merge most likely.

[Reproduction]: Play as a skeleton.

[For Admins]: fix dis

Roundstart Skeletons are back to being lichwiz-type skeletons. Fix this.

**Comment by praisenarsie** [comment]
who care

**Comment by Manly-Dwarf** [comment]
>overpowered roundstart race with no downsides
"who care"
you gay

**Comment by GuyonBroadway** [comment]
Hippie mandate, if its roundstart selectable, its functionally identical to humans.

**Comment by kopoba** [comment]
> Hippie mandate, if its roundstart selectable, its functionally identical to humans.
No its not.

**Comment by GuyonBroadway** [comment]
Thats how the headmins decided it should be, anything otherwise is unintended behaviour.

**Comment by kopoba** [comment]
It a bug. Now roundstart selectable skele is REAL skely that dont get damage from fire/vacuum/chems/dont need eat/breath.

**Comment by tortellinitony** [comment]
This was caused due to the species traits being moved to `inherent_traits`

**Comment by JohnGinnane** [comment]
Fixed by https://github.com/HippieStation/HippieStation/pull/7161
