### ISSUE TITLE
Wizard spellbook doesn't say if a spell requires the staff or not

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#6964]
In-Game report from kendrickorium:
Server info: 27062 (Hippie Station)

cant use hardly anything without a staff, says nothing in book description

**Comment by Manly-Dwarf** [comment]
There's giant bold text that tells you "USE A STAFF RETARD" upon spawning as a wizard.

**Comment by GuyonBroadway** [comment]
You could still put "Requires a staff" and "Does not require a staff" into the spell description.

**Comment by Manly-Dwarf** [comment]
I could. But if you can't read bold text saying "USE A STAFF" then I don't think I can be blamed here.

It's like if a traitor complained that they had no traitor weapons because they didn't read their uplink code.

**Comment by GuyonBroadway** [comment]
this is more like if the spell;s in the book didn't tell you if they were robeless or not.

**Comment by Manly-Dwarf** [comment]
you do that
![smug_high-res](https://user-images.githubusercontent.com/33744849/37442128-02e3ff5a-27db-11e8-906b-130af3bd440d.png)

**Comment by GuyonBroadway** [comment]
tsk tsk, shirking the responsibilities of yer own code there lad? I thought you were supposed to be better at this than I was.

**Comment by Manly-Dwarf** [comment]
I don't dirty my hands with filthy bugfixes.

but yeah sure I'll look into fixing this

**Comment by GuyonBroadway** [comment]
Maybe if yer code wasn't doo doo to begin with you wouldn't HAVE to.

**Comment by Manly-Dwarf** [comment]
You know what? If you're so much better at coding it, why don't you just fix the bug? Rewrite the whole damn thing, in fact.
Prove that you're so much better.

You won't, though.
![soy](https://user-images.githubusercontent.com/33744849/37442239-7fc2b2aa-27db-11e8-8511-76fe09a6cb5b.gif)

**Comment by GuyonBroadway** [comment]
And neither will you...

**Comment by Manly-Dwarf** [comment]
Yeah. I already did, no need to do it twice.

I see that you have given up, though. You are forever Lesser Guyon.
![guyon](https://user-images.githubusercontent.com/33744849/37442267-ad67d5be-27db-11e8-97ef-2d3359aae485.png)
^ superior
  |
  |

**Comment by JohnGinnane** [comment]
I have made this mistake recently as well. Sometimes more warnings are good so I will look into this this weekend hopefully

**Comment by Carbonhell** [comment]
I thought if it needed the garb it also needed the staff and viceversa, but this isn't necessarily true. Confirmed, requires an entry in the spellbook to say it needs the staff or not
