### ISSUE TITLE
FLASHBANGS

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7006]
In-Game report from kendrickorium:
Server info: 27137 (Hippie Station)

>wearing sec hud and bowmans, still got stunned by flashbangs, was not on it

**Comment by JohnGinnane** [comment]
This happens to me too

**Comment by Carbonhell** [comment]
Tested and it doesn't happen,you only get stunned if you are on it and that's wanted behaviour.
