### ISSUE TITLE
Armstrong style doesn't work on non-human targets

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7042]
In-Game report from subs455:
Server info: 27182 (Hippie Station)

>General description of the issue
Arm Strong style doesn't seem to work with non-human NPCs.

>What you expected to happen
I was fighting clown SNPCs and armstrong style doesn't seem to work on them.

>What actually happened
Armstrong combos did not work at all and nearly got me killed

>Steps to reproduce if possible
Know Armstrong Style and attack a SNPC that's not human.

**Comment by Manly-Dwarf** [comment]
Weren't SNPCs removed entirely?
Regardless, this is not a bug. Martial Arts in its entirety only works on humans.

**Comment by Carbonhell** [comment]
I think all martial arts only work on humans, so it's not really a bug.
