### ISSUE TITLE
 Theatre Air Alarm is in a door 

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7043]
In-Game report from dinopeaks:
Server info: 27183 (Hippie Station)

>General description of the issue  Theatre Air Alarm is in the door to back stage 

>What you expected to happen move it to a wall

>What actually happened opened a door and it is there 

>Steps to reproduce if possible just open the back stage door

**Comment by JohnGinnane** [comment]
@Pyko1 do you know if this was fixed in latest map update?

**Comment by Pyko1** [comment]
I haven't touched it at least

**Comment by Dinopeaks** [comment]
will be fixed very soon

**Comment by Dinopeaks** [comment]
fixed with my PR
