### ISSUE TITLE
Crew monitor not working.

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7062]
In-Game report from kingelij:
Server info: 27211 (Hippie Station)

(playing as Ai) When i open the crew monitor, either by the Ai button, or the console itself, it gives me this message "The requested interface (crew) was not found. Does it exist?"

**Comment by JohnGinnane** [comment]
I think this might be fixed with rebuild of tgui, but tg did remove the crew monitor map I believe
