### ISSUE TITLE
Catbeasts don't turn into zombies

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7065]
In-Game report from bluscout78:
Server info: 27213 (Hippie Station)

>General description of the issue
Catbeasts don't turn into zombies when they're killed by one.

>What you expected to happen
I get killed by a zombie, I expect to become a zombie.

>What actually happened
I stayed a catbeast, and I was revived back to full health as a non-zombie.

>Steps to reproduce if possible
Become a catbeast, get zombified.

**Comment by praisenarsie** [comment]
you mean tajaran?

**Comment by Manly-Dwarf** [comment]
No, we mean catbeast.

**Comment by AnthonyJNgo** [comment]
-1

I wouldn't even say this is an issue to be honest. Catbeasts don't get to be antag or harm others. Being a helpless cat east in a storm of zombified crewmembers sounds fitting.

**Comment by DaydreamPuppeh** [comment]
-1
