### ISSUE TITLE
rnd console item producing

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7096]
In-Game report from rapidgokhandrum:
Server info: 27264 (Hippie Station)

>General description of the issue
when i click the items in the illegal node, they are not being produced, i have the mats, chemicals, protolathe upgraded and everything

>What you expected to happen

it should produce some cool shit
>What actually happened

nothing
>Steps to reproduce if possible

try illegal node and click on ebow over there, wont construct

**Comment by kopoba** [comment]
last time some dude help me to fix illegal node he says that i must click 0 points item in my uplink to fix it i managed to produce energy crosbow but not sure was it on sec protolathe or not. Maybe it was a prank.

**Comment by WarRage333** [comment]
Fixed

**Comment by AnthonyJNgo** [comment]
This should be closed.
