### ISSUE TITLE
Firing a glock 17 causes the game to crash

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7098]
In-Game report from bartels:
Server info: 27273 (Hippie Station)

Noticed this a bunch of times, peoples games crash when they shoot a glock 17 or are near someone who shoots one.

**Comment by GuyonBroadway** [comment]
JEEBUS DUCKS!!

**Comment by JohnGinnane** [comment]
Gonna test this now

**Comment by JohnGinnane** [comment]
I updated my fork, recompiled, started server, fired glock and it crashed immediately

I added `to_chat(firer, "hello")` to the `fire()` proc for 9mm, compiled, started server, fired glock and it worked fine

I undid above, etc. etc, fired glock and it still worked fine

**Comment by JohnGinnane** [comment]
Before any changes:
![image](https://user-images.githubusercontent.com/3355198/37408438-040718dc-2794-11e8-8f02-5395ea2488da.png)

With changes:
![image](https://user-images.githubusercontent.com/3355198/37408446-0a6cefee-2794-11e8-8d7f-a65826bd5dbf.png)
![image](https://user-images.githubusercontent.com/3355198/37408455-0d2fc008-2794-11e8-8e3f-1db6909f91cf.png)

**Comment by praisenarsie** [comment]
holy shit i want to absolutely murder who made it so you can report through honkbot because IT DOESN'T INCLUDE THE FUCKING REVISION AND VERSION.

anyway pinging @mrstonedone because this is an interesting crash issue, bartels runs 512.1412 or 1413 but he's pretty sure it's 1412

**Comment by JohnGinnane** [comment]
I was also running 512.1413 and it crashed, but after making a chance, compiling, running, and then reverting that change, it didn't crash so I wonder if it's related to resources maybe?

**Comment by JohnGinnane** [comment]
@tortellinitony pointed out the glock is the only weapon to use a list for the `fire_sound`:

![image](https://user-images.githubusercontent.com/3355198/37416357-70ff3c1a-27a5-11e8-8ccf-ba32f3fa1d92.png)

**Comment by JohnMcLaime** [comment]
Huh, today i was murderboning with glock and fired it few hundred times but it crashed only once for me after i shot a watertank in my line of sight, it crashed right when watertank ruptured (also noticed that other guy got a crash, since he was brainded when i connected back. I am running 512.1414

**Comment by praisenarsie** [comment]
>byond
