### ISSUE TITLE
Rapid Pipe Dispenser not showing disposal pipes

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7111]
In-Game report from gradusnl:
Server info: 27316 (Hippie Station)

>General description of the issue
Instead of disposal pipes it is showing transit tubes

>What you expected to happen
Dispense disposal pipes.

>What actually happened
Nothing.

>Steps to reproduce if possible
Guess.

**Comment by JohnGinnane** [comment]
Just tested on /tg/, it's upstream so I will fix there

**Comment by JohnGinnane** [comment]
just tested, not upstream issue
