### ISSUE TITLE
Chem dispensers sprite disappears when you screwdriver it.

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7144]
In-Game report from warrage:
Server info: 27348 (Hippie Station)

>General description of the issue
Chem dispenser disappears when you screwdriver it to apply new parts with rpd / remove parts by hand.

It comes back after you screwdriver it again.

You can still upgrade it by alt clicking the tile and using rpd on the 'floor menu' where its located

>Steps to reproduce if possible

heres the pr that did stuff to it
https://github.com/HippieStation/HippieStation/pull/7137

**Comment by JohnGinnane** [comment]
Just tested this on live and by the looks of it we're using the tg icon and everything works

![image](https://user-images.githubusercontent.com/3355198/37873825-dd26a65c-301b-11e8-8163-1ba9488a132f.png)
