### ISSUE TITLE
Protolathe Crafting seems to be broken

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7152]
In-Game report from vagak:
Server info: 27370 (Hippie Station)

>General description of the issue
I'm a golem fiddling with the protolathe. The protolathe seems to be consuming way much more materials than what's listed and everything.

Here's a webm of what's going on.
https://lambda.sx/Nn2.webm

>What you expected to happen
To be able to craft what I need.

>What actually happened
Everything is actually more expensive than what's suggested.

>Steps to reproduce if possible
Check out a protolathe, specifically one that the golems receive and go from there.

**Comment by Pyko1** [comment]
you don't have the 250 gold needed to make it.
