### ISSUE TITLE
The dead can clap

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStation/HippieStationdeprecated2020#7159]
Just noticed when testing my guillotine that you can still hear clapping from people who are dead

Caused by #7145

**Comment by JohnGinnane** [comment]
Looking at some other `run_emote` code it seems like you need to do `. = ..()` then check `if (.)` so I'll fix this later

**Comment by ghost** [comment]
I hear dead people.

**Comment by JohnGinnane** [comment]
Fixed by https://github.com/tgstation/tgstation/pull/36540
