### ISSUE TITLE
CMO does not get the brainwashing disk

### ISSUE THREAD

**Issue by TheOmn1** [HippieStation/HippieStationdeprecated2020#7185]
I don't know the round but I've posted this in disc around February third.

Traitor CMO does not have the brainwashing disk in his uplink. His ordinary inferior doctors who have to answer to him however, do have the brainwashing disk in their uplink (if they are a traitor)

I was told this is probably because CMO isn't included in the role list for the disk as MDs are.

**Comment by ghost** [comment]
I'll try to fix this

**Comment by JohnGinnane** [comment]
Fixed by #7494
