### ISSUE TITLE
fuckn extinguishers no longer damage slime

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7190]
In-Game report from glordqtinkle:
Server info: 27403 (Hippie Station)

>General description of the issue
WHATS UP WITH THAAAAAAAAAAAAAAAAT

>What you expected to happen
WHAT IS THE DEAL

>What actually happened
WITH

>Steps to reproduce if possible
THAAAAAAAAAAAAAAAAAAAAAAAAAT

**Comment by praisenarsie** [comment]
is this a result of chempiles

**Comment by GuyonBroadway** [comment]
Nah I think its a thing on tg too.

**Comment by geylard** [comment]
oh, extinguishers no longer chill things. slimes are pretty much unkillable now though.

**Comment by Jujumatic** [comment]
Fixing it in #7336 

Though it seems monkey cubes won't expand with the fire extinguisher either. wtf

**Comment by JohnGinnane** [comment]
This is caused by us adding in cryogenic_fluid

**Comment by JohnGinnane** [comment]
Related to https://github.com/HippieStation/HippieStation/issues/7347

**Comment by JohnGinnane** [comment]
Fixed by https://github.com/HippieStation/HippieStation/pull/7616
