### ISSUE TITLE
DOORS

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7231]
In-Game report from kendrickorium:
Server info: 27460 (Hippie Station)

FIX THE FUCKING DOOR SOUNDS HOLY FUCK 

FUCK /TG/

**Comment by GuyonBroadway** [comment]
It's like people don't understand when we say "we know"

**Comment by JohnGinnane** [comment]
It might be an idea to put up a warning or MOTD so when you join it can say "WE KNOW DOOR SOUNDS HAVE CHANGED"
