### ISSUE TITLE
Upgrading the RnD protolathe with manipulators makes the price of things go up instead of down

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7260]
In-Game report from warrage:
Server info: 27493 (Hippie Station)

>General description of the issue
FUCK

>What you expected to happen
SHIET

>What actually happened
This acutally does not happen on TG something didn't get merged or some shit i dont knowwwwwww

>Steps to reproduce if possible

FFFFFUUUUUUCKKKKKKKK

**Comment by Jalleo** [comment]
Apparently it did occur and there is/was a fix PR by Kevin so you just need to search the history of PR's. Good luck
