### ISSUE TITLE
RDM

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7324]
In-Game report from sickmick:
Server info: 27576 (Hippie Station)

>General description of the issue
A guy named Gomrund and Darcey Winton rushed into chemistry, ( I was the chemist, I didnt even leave the are once so I had nothing to do with them ), Gomrund whipped a taser out and stunned me while Darcey decapped me without saying a word. The fuckers thought that I was a traitor but they were wrong. They shat on my round for nothing. I want them to get punished.

>What you expected to happen
I expected to do my job without getting RDM'd.
>What actually happened
I got decapped for no reason.

**Comment by KayeArray** [comment]
honkbot issue reports were a mistake
