### ISSUE TITLE
Monkey cubes not expanding with fire extinguishers

### ISSUE THREAD

**Issue by Jujumatic** [HippieStation/HippieStationdeprecated2020#7347]
Found during testing for my PR to fix fire extinguishers not damaging slimes correctly, monkey cubes do not create monkeys or react at all to water in any way. Probably a result of the TG Menace messing with the water code. This may also be happening to dehydrated carps.

The expand proc is working correctly as you can still activate the cube by forcing the proc with admin powa, so it's probably the water being fucked up or something.

**Comment by WarRage333** [comment]
Carps worked fine last time i sprayed water from a bottle, i just assumed the monkey cube thing was a nerf from tg since they had a problem with people spamming million of monkies in botany

**Comment by Jujumatic** [comment]
Problem is monkey cubes don't expand at all, not even when it's just 1 of them. Which I'm pretty sure is not intended when the expand code is still there

**Comment by JohnGinnane** [comment]
This is caused by us adding in cryogenic_fluid

**Comment by JohnGinnane** [comment]
Related to https://github.com/HippieStation/HippieStation/issues/7190

**Comment by JohnGinnane** [comment]
Fixed by https://github.com/HippieStation/HippieStation/pull/7616
