### ISSUE TITLE
Possible bug with cult pylons

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7385]
In-Game report from spankmaster:
Server info: 27638 (Hippie Station)

>As a cultist in crit, crawled up to a pylon and didn't receive any healing

>Healing

>no healing

>crit yourself as cultist near pylon. May have been something else causing me not to be healed.

**Comment by AnthonyJNgo** [comment]
I believe the healing is very slow. Will attempt to reproduce tonight.

**Comment by AnthonyJNgo** [comment]
Cult pylons do in fact heal you, even if you are crit. You may have been too far from it, crawling right next to it does wonders and brought me from near death crit to full health.
