### ISSUE TITLE
Mutating to aliens via alien mutation toxins does not give you the alien hivemind organ so you can't communicate

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7449]
In-Game report from warrage:
Server info: 27712 (Hippie Station)

>General description of the issue
Mutating to aliens via alien mutation toxins does not give you the alien hivemind organ so you can't communicate

>What you expected to happen
Be able to use the alien hivemind

>What actually happened
You dont have one

>Steps to reproduce if possible
Get turned into an ayylmao via strange seeds or scrubbers event

**Comment by WarRage333** [comment]
The organ is there but you cant use it.

**Comment by Jujumatic** [comment]
just checked the ayylmao code, it seems you can only communicate if you are an ayy and you have antagonist status. i guess this was overlooked. will push a fix shortly if everything goes well

**Comment by Jujumatic** [comment]
Will be fixed in #7543

**Comment by AnthonyJNgo** [comment]
The fix for this has been merged already.
