### ISSUE TITLE
TANK TRANSFER VALVES/BOMBS ARE NOT WORKING PROPERLY

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7450]
In-Game report from bubberduckydducker:
Server info: 27713 (Hippie Station)

>General description of the issue
I tried to make a bomb via normal methods AKA toxins lab, made sure the bomb mix was working fine

>What you expected to happen
i expected a maxcap, because it was just pure superheated plasma, and super cooled oxygen

>What actually happened
a fucking weak pissy explosion was met with suprise

>Steps to reproduce if possible
now this shouldn't be a problem if you were an admin and just made an explosion via magic but if you were a normal person trying to make a bomb then you would find some difficulty due to this shitty fucking piss explosion you always end up with, regardless the method you use.

**Comment by Pyko1** [comment]
you sure you didn't fuck up somehow?

**Comment by praisenarsie** [comment]
can we remove honkbot reports

**Comment by JohnGinnane** [comment]
no

**Comment by JohnGinnane** [comment]
https://streamable.com/0l1zw

just tested and it works fine using the following https://tgstation13.org/wiki/Guide_to_toxins
