### ISSUE TITLE
The dead cought

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7464]
In-Game report from warrage:
Server info: 27739 (Hippie Station)

>General description of the issue
 COUGH COUGH COUGH

>What you expected to happen
IT NEVER STOPS

>What actually happened
GOD HELP US ALL

>Steps to reproduce if possible
disease that has cought, people die etc

**Comment by WarRage333** [comment]
COUGH*

you dont even need a head to do it when dead

**Comment by JohnGinnane** [comment]
yeah I was playing during that round and oh boy were there a lot of coughing

**Comment by JohnGinnane** [comment]
not an upstream issue
