### ISSUE TITLE
Talking in soft crit no longer makes you whisper

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7497]
In-Game report from johnfg:
Server info: 27777 (Hippie Station)

Possibly something we didn't port from old code but would be nice to have again

**Comment by tortellinitony** [comment]
You have to use the whisper verb. We could fix this so it automatically makes you talk, but IDK

**Comment by JohnGinnane** [comment]
That's what I'm gonna do because you can't use the say verb anyway so it's more convenient
