### ISSUE TITLE
(Upstream) Put the circuit component movement buttons on the left

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7513]
In-Game report from johnfg:
Server info: 27816 (Hippie Station)

Something I might do upstream, having the controls (move up, down, to top, to bottom) on the left makes sense because they'll all line up, rather than be at the end of a varying length item

**Comment by JohnGinnane** [comment]
This was done upstream and I believe done in a mirrored PR
