### ISSUE TITLE
Activated holotool can't be inserted into backpack

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7518]
In-Game report from glordqtinkle:
Server info: 27822 (Hippie Station)

>General description of the issue
Any form of the activated holotool can't be inserted into the backpack, but can be inserted into a toolbelt belt or dropped. Message you get is, "the holo-screwdriver is stuck to your hand, you can't put it in the satchel!" Kind of a problem when you can't deactivate its form.

**Comment by JohnGinnane** [comment]
I will test this with my fix #7522

**Comment by Carbonhell** [comment]
I doubt that pr fixes it. Needs to be looked into.

**Comment by ghost** [comment]
Close this. @yoyobatty

Fixed since my refactor.
