### ISSUE TITLE
Minor map issues

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStation/HippieStationdeprecated2020#7541]
I noticed two areas on the map where items are inaccessible due to other items blocking them in (screenshots to follow later):

In Science chem lab where the freezer, heater, and pipes are, there's a blue toolbox on the table. However in order to get to the toolbox you need to drag a cannister out of the way. (Suggestion: Maybe move the toolbox or adjust the layout of the cannisters and tables so we don't have tables being hidden behind cannisters

Similarly, in cargo there's a medkit on the table at the end but there's a crate shoved in the corner so you need to move that to get to the medkit. (Suggestion: Move the crate somewhere so it's not blocking the table at all)

**Comment by Dinopeaks** [comment]
is it needed? or should i move it to warehouse 
edit: nevermind

**Comment by Dinopeaks** [comment]
both of this are done look for my PR for the changes

**Comment by Dinopeaks** [comment]
fixed in my PR
