### ISSUE TITLE
Should be able to wear a belt if you're not wearing a suit

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStation/HippieStationdeprecated2020#7542]
it doesn't make a lot of sense that someone without any clothes on can't wear a belt

**Comment by JohnGinnane** [comment]
was this actually a /tg/ change though?

**Comment by ghost** [comment]
no but i blame /tg/ for everything that goes wrong in ss13 and in my life

**Comment by Pyko1** [comment]
yes and no really

**Comment by Pyko1** [comment]
at some point they changed it, and it got changed on reabase

**Comment by Pyko1** [comment]
so blame /tg/

**Comment by Carbonhell** [comment]
this is a suggestion,not a bug
