### ISSUE TITLE
Races have different food prefs and Lizards can speak draconic

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7557]
[Round ID]: # (If you discovered this issue from playing HippieStation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://tools.hippiestation.com/stats/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)
![image](https://user-images.githubusercontent.com/15840795/38883703-a3185e90-4265-11e8-978c-c14612a7e15a.png)
![image](https://user-images.githubusercontent.com/15840795/38883707-a6eefaec-4265-11e8-98e5-170bd189cde5.png)
![image](https://user-images.githubusercontent.com/15840795/38883714-a98f3ef6-4265-11e8-9498-066647b68d8c.png)

**Comment by ghost** [comment]
Forgot to mention the lizards speaking draconic thing.
![image](https://user-images.githubusercontent.com/15840795/38884008-5a4eb212-4266-11e8-9038-4240849c610b.png)

**Comment by Jujumatic** [comment]
not a F E A T U R E?

it looks like it could be a pretty cool one

**Comment by ghost** [comment]
roundstart races shouldn't be different from humans functionally, been a design choice of hippie for ages, it's an oversight from upstream /tg/

**Comment by Jujumatic** [comment]
ah

SO WE DO LIKE COMMUNISM BUT FOR ROUNDSTART RACES

**Comment by ghost** [comment]
Lizards also have different heatmods and coldmods from moths and humans

**Comment by Pyko1** [comment]
something bypassing our race changes?

**Comment by ghost** [comment]
seems to be

**Comment by Pyko1** [comment]
oh wait my mistake

**Comment by Pyko1** [comment]
thought that by not having `inherent_biotypes = list(MOB_ORGANIC, MOB_HUMANOID, MOB_REPTILE)` it would inherit it from human.

But, i have to actually override the actual /tg/ file instead

**Comment by Pyko1** [comment]
even tho, I assume its pretty fluff seeing that we have had it for month or 2

**Comment by ghost** [comment]
it's annoying being non-human lizard and getting sick from eating anything mostly, lizards take less cold damage and more heat damage, and having access to a sekrit club language if it becomes meta would be further annoying
