### ISSUE TITLE
medhud should show if defibs would revive someone

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStation/HippieStationdeprecated2020#7562]
to encourage usage of defibs over cloning we should have medhud tell you if a dead person can be defibbed or not, maybe something we can put upstream

**Comment by ghost** [comment]
wtf i was thinking about defibs 10 minutes ago

I was thinking of changing the patient rooms into a defibbing station room. Where you have a table and a monitor kinda like surgery. The monitor would tell you the death time of someone and if they could be revived and with roughly how much brain damage

**Comment by JohnGinnane** [comment]
that sounds nice but idk if it would be used, but then again patient rooms aren't even used atm so :man_shrugging:

**Comment by ghost** [comment]
the advantage is that medical players who like to play EMT don't deprive medical of defib units, primarily

**Comment by Pyko1** [comment]
I wish there were some nerfed 1 hit wall defibs on medbay. Usually i waste all the time trying to get someone to open the locker containing defibs.

**Comment by Carbonhell** [comment]
Not an issue. Anyway, i saw a PR that does that made recently.
