### ISSUE TITLE
Clogged vents event causes screen issue

### ISSUE THREAD

**Issue by ShroudedCorpse** [HippieStation/HippieStationdeprecated2020#7602]
[Round ID]: # (If you discovered this issue from playing HippieStation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (it restarted so i can't see https://tools.hippiestation.com/stats/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Reproduction]: Happened after i got exposed to the black foam/liquid in the event then someone dragged me. Looks like this: http://prntscr.com/jmd6w0

[For Admins]: # (no idea what this is

**Comment by JohnGinnane** [comment]
Did rejoining/closing and reopening work?

**Comment by ShroudedCorpse** [comment]
Didn't check but it ruined the rest of the round fixed itself when the round ended and went back to the menu also i wasn't blind.

**Comment by praisenarsie** [comment]
possibly skewium

**Comment by AnthonyJNgo** [comment]
This should be reproduced and tested or closed.

**Comment by Jujumatic** [comment]
Needs reproducing

**Comment by AnthonyJNgo** [comment]
Has not been reproduced in over a year, closing.
