### ISSUE TITLE
Various races have no sprite/are currently invisible

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#7605]
Simply put, right now the following races do not appear visible apart from their underwear, eyes or worn objects;

- Avians
- IPCs
- Catbeasts

Since avians are a roundstart race it can be easily abused so people can do nasty shenanigans by running around naked without being able to be seen.

**Comment by Kendrickorium55** [comment]
commandokioshi has constantly been abusing this

**Comment by ghost** [comment]
big ladle larry!

**Comment by Dinopeaks** [comment]
I have been forcing humanizing on anyone abusing this but it be nice if we could fix this
