### ISSUE TITLE
RPD images are missing

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#7606]
While it's completely possible to use a RPD (Rapid Piping Device), the missing images for the direction/sprite of the pipe makes it more difficult to use.

https://puu.sh/AtIQR/fea7e8889c.png

All images for direction previews are currently gone.

**Comment by Cyprex** [comment]
Are you on IE8/9 (Windows XP or wine). See https://github.com/tgstation/tgstation/issues/37828.
Fixed by https://github.com/tgstation/tgstation/pull/37905.

**Comment by JohnGinnane** [comment]
@Maroonenahmoron when you get a chance can you check this again to see if it's still happening?

**Comment by Maroonenahmoron** [comment]
Seems like it got patched up
