### ISSUE TITLE
BRROOO farts are silent they have no sound

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7611]
[Round ID]: # (If you discovered this issue from playing HippieStation hosted servers:) yes
[Round ID]: # (**INCLUDE THE ROUND ID**) 28820
[Round ID]: # (It can be found in the Status panel or retrieved from https://tools.hippiestation.com/stats/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.) no

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.) try to fart and its soundless

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.) no

**Comment by praisenarsie** [comment]
@GuyonBroadway

**Comment by GuyonBroadway** [comment]
It's due to something in the reindex screams/farts code that causes the first set to be blank and I have no idea why. You can confirm this by shoving an item in your ass and farting works again.
