### ISSUE TITLE
Removing custom forge chem floor tiles makes space tiles.

### ISSUE THREAD

**Issue by WarRage333** [HippieStation/HippieStationdeprecated2020#7675]
[Round ID]: # 2195

[Testmerges]: # Revision: 44f0798ed20f10b2af88e4916feb0ebc5e7c4186  

[Reproduction]: # Putting down a custom chem floor tile (from the forge) then crowbaring it off, makes empty space, no rods just empty space that vent the room.

(I only tried synthflesh tiles but i assume all others will do the same)

unrelated note ingame reporter does not seem to work

https://i.imgur.com/oj4v474.png

**Comment by WarRage333** [comment]
Not sure what to put under testmerges section so i just copy pasted what i got from the ooc thingy

**Comment by AnthonyJNgo** [comment]
Afaik forge is broken so this should be closed since it is a non-issue. In the future if the forge is fixed and this isn't resolved, looks like when the tile is crowbared pff it just deletes everything under it in the space.

**Comment by AnthonyJNgo** [comment]
When its crowbared up it's probably deleting everything underneath it or just spawning space tile. Should be easy fix

**Comment by yoyobatty** [comment]
That's the theory I'm going to go with, I'll investigate.
