### ISSUE TITLE
Removing your heart no longer gives you heart attacks

### ISSUE THREAD

**Issue by Jujumatic** [HippieStation/HippieStationdeprecated2020#7692]
[Round ID]: # 29154

Yeah removing your heart doesn't give you heart attacks for some reason. Hmm.

**Comment by ghost** [comment]
How could you even live ?

**Comment by JohnGinnane** [comment]
@Jujumatic I think the point of a heart is that it's working overtime rather than stopping (i.e. not existing) also how are you even alive if you have no heart?

**Comment by Jujumatic** [comment]
You don't die when you remove your heart lol and you become completely immune to heart attacks, you take out your heart and you're fine

???????

**Comment by ghost** [comment]
Wait, wait, how do you remove your heart ? surgery ?

**Comment by Jujumatic** [comment]
yup

**Comment by ghost** [comment]
what is the state on the right side of your heart 100% or dead ?

**Comment by Jujumatic** [comment]
you stay at full health but if you put your heart back in then you get the heart attack and die

**Comment by ghost** [comment]
i thinki it cause to a "refresh" of the heart that are just not working

**Comment by Carbonhell** [comment]
Fixed seems. Removing a heart instantly sends you in coma and slowly kills you.
