### ISSUE TITLE
Corazone doesn't work at all

### ISSUE THREAD

**Issue by Jujumatic** [HippieStation/HippieStationdeprecated2020#7694]
[Round ID]: # 29154

Yeah so I drank some corazone and removed my liver (corazone is supposed to stop liver failure) and it didn't work, I checked code as well and it turns out all the corazone code got removed (except for the recipe itself).

Nice.

**Comment by Carbonhell** [comment]
lol confirmed

**Comment by Carbonhell** [comment]
um wait what, corazone is for the heart,not for the liver,isn't it? also the code seems ok,this needs testing.

**Comment by AnthonyJNgo** [comment]
Will test tonight and edit this comment.

**Comment by Jujumatic** [comment]
Fixed by tg like 1 year later lol
