### ISSUE TITLE
Randomly getting automuted by the auto mute system (maybe because voice of god?)

### ISSUE THREAD

**Issue by WarRage333** [HippieStation/HippieStationdeprecated2020#7708]
[Round ID]: # 29171

[Reproduction]: # I replaced my tongue with voice of god, and later in the round after using a few voice of god emotes i started seeing this in chart 

''You are nearing the spam filter limit for identical messages.''

while nothing was appearing in chat. I got muted after this.

**Comment by AnthonyJNgo** [comment]
This should be tested. Were you using the same emote repeatedly? That would probably be what it was.

**Comment by WarRage333** [comment]
This is old and didn't happen ever since.

No emotes or anything were used

**Comment by AnthonyJNgo** [comment]
Weird. This should be closed then until it actually reproduces itself.
