### ISSUE TITLE
Give logs for people changing labels on canisters

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#7867]
If we have someone who goes around and changes labels for canisters and it ends up getting the crew killed because an air canister was a plasma one, there's no logging for it.

**Comment by ghost** [comment]
fingerprints
you have to activate the canister without any gas inside before you can change the label and it will put prints on it

**Comment by JohnGinnane** [comment]
@McBawbaggings link to this? From what I can see the ui_act doesn't add fingerprints when you re-label a cannister

**Comment by JohnGinnane** [comment]
https://github.com/HippieStation/HippieStation/blob/dc285deb9ce2a6c503ba8bdbe81f9625f346860d/code/modules/atmospherics/machinery/portable/canister.dm#L389

**Comment by ghost** [comment]
https://github.com/HippieStation/HippieStation/blob/dc285deb9ce2a6c503ba8bdbe81f9625f346860d/code/modules/atmospherics/machinery/portable/canister.dm#L385
will be handled in super

**Comment by ghost** [comment]
infact:
https://github.com/HippieStation/HippieStation/blob/d0c853cfe3e70dcd83108c76fa41f1a12f979459/code/game/machinery/_machinery.dm#L241

**Comment by Carbonhell** [comment]
Also href logs log this already

**Comment by Jujumatic** [comment]
Is this still an issue or what

**Comment by AnthonyJNgo** [comment]
If HREF logs log this already then this is not an issue.

**Comment by AnthonyJNgo** [comment]
You know what, I don't see the harm in having this logged twice anyways because I have seen a few admins having issues with this lately.
