### ISSUE TITLE
Fix these circuits

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#7871]
[Round ID]: # betwenn 29400 and 2914

[Reproduction]: # Get a integrated hypo-injector that is in a drone (circuitry) and make him inject you, if you remove the power cell it's gonna continue to inject you.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by Jujumatic** [comment]
May be outdated by now, needs verification

**Comment by AnthonyJNgo** [comment]
This is a year old and has not been reproduced, going to close.
