### ISSUE TITLE
Removing arms from infectious zombies does not remove claws

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#7889]
[Round ID]: 29453

The process is simple; if you remove the arms from a clawed zombie in any way they can still use their hands to claw other people.

I believe this has been around for some time now and nobody has raised the issue, so here you go lads.

**Comment by GuyonBroadway** [comment]
its cus they biting you. also this is a tg level issue.

**Comment by AnthonyJNgo** [comment]
+1 removing the arms from zombies should change the attack message to bites, hitting them in the face repeatedly should remove their teeth and render them harmless. This shouldn't be too difficult.

**Comment by AnthonyJNgo** [comment]
Having both arms removed as a zombie stops you from attacking. Attempting to do so displays the message, "you look at your arms and sigh." This should be closed.
