### ISSUE TITLE
Body temperature will not rise as ashwalker

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#7937]
[Round ID]: 29581

I was an ashwalker fella wearing a hardsuit and someone started shooting me with freeze beams from a watcher projector. As soon as they noticed I wasn't their intended target, they did whatever they can to warm me up and fight through to shitloads of burn damage I was going through;

- Force-feeding me coffee.
- Taking me to a warm area.
- Taking my hardsuit off.
- Placing me under a shower on the hot setting.
- Using a survival injector.

None of these raised by body temperature from absolute 0 and I pretty much succumbed after a while, I know this because I checked my temperature during revival attempts and when I died.

Edit; turns out that watcher projectors might be overpoweringly bugged

**Comment by WarRage333** [comment]
Its just the projector nothing to do with race
