### ISSUE TITLE
Warden exosuit slot broken

### ISSUE THREAD

**Issue by bardofrage** [HippieStation/HippieStationdeprecated2020#7986]
Issue reported from  Round ID: 29667 (Hippie Station)

Reporting client version: 512

[Round ID]: # (If you discovered this issue from playing HippieStation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://tools.hippiestation.com/stats/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

When using the wardens starting vest, nothing can be put into the exosuit slot.

**Comment by bardofrage** [comment]
This also applies to the HoS' leather suit

**Comment by Carbonhell** [comment]
Fixed!
