### ISSUE TITLE
xenobioglogy broken

### ISSUE THREAD

**Issue by geylard** [HippieStation/HippieStationdeprecated2020#8067]
Issue reported from  Round ID: 29827 (Hippie Station)

Reporting client version: 512

xenogroligy console is filled with static, especially around the 2 middle cages regardless of camera status. needs you to use the console more than once for it to start happening.

**Comment by Carbonhell** [comment]
Most likely due to the byond version we are using

**Comment by geylard** [comment]
which is hwat

**Comment by Carbonhell** [comment]
does this still happen

**Comment by geylard** [comment]
yesrh

**Comment by Carbonhell** [comment]
Update byond. Confirmed to be a byond beta bug.
