### ISSUE TITLE
Firefighter Ripley Chassis Bug

### ISSUE THREAD

**Issue by challade** [HippieStation/HippieStationdeprecated2020#8111]
Issue reported from  Round ID: 29880 (Hippie Station)

Reporting client version: 512

While building a firefighter Ripley there's an issue where you can't wrench the Ripley after adding the last 10 plasteel needed. This leaves you with an unfinished Ripley and wasted material. 

Note: I was using this guide- https://tgstation13.org/wiki/Guide_to_robotics#Firefighter_APLU

The problem happens at step 18, you can add the plasteel but it ends there.

**Comment by yoyobatty** [comment]
Are you sure you're adding enough? You might have to click it a second time, to add the 3rd layer of armour.

**Comment by challade** [comment]
Absolutely positive, it says that I add the external armor but I can't interact with it with the wrench.

**Comment by GuyonBroadway** [comment]
Did you remember to add a battery?

**Comment by challade** [comment]
Yeah, look at the little guide I posted, I did everything up until step 19, it won't wrench together, everything prior works. no other tool works on it, it's stuck, unless Hippie has a specific obscure step to connecting the outer armor plate to the chasis, it's bugged.

**Comment by yoyobatty** [comment]
You either need to add more plasteel again or add regular metal.

**Comment by JohnGinnane** [comment]
Gonna look this up and see if I can recreate cause I had issues recently building a mech using the ingame guide

**Comment by JohnGinnane** [comment]
@challade I just went through it using your guide and didn't have any problems. I created Firefighter chassis and RIPLEY parts and followed those steps. Is still happening on the server?

**Comment by yoyobatty** [comment]
I've seen them build it in game numerous times, so I don't the glitch prevented it from being built but the step was not correct and they found a solution. They're just reporting that the wiki steps might be wrong.
