### ISSUE TITLE
People can spam authorise/repeal on shuttle console

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStation/HippieStationdeprecated2020#8211]
Not so much a bug but an oversight. I think maybe we can shock someone who has authorised and repealed more than 5 times in quick succession (i.e. 10 seconds). For lore it can be "preventative measure to stop syndicates from brute-forcing an early launch"

**Comment by JohnGinnane** [comment]
Suggestion by Carbon: Add a delay between actions

I might make a 10 second delay between repealing and authorising

**Comment by ghost** [comment]
would be better upstream?
