### ISSUE TITLE
IV drips are broken

### ISSUE THREAD

**Issue by DaydreamPuppeh** [HippieStation/HippieStationdeprecated2020#8236]
Issue reported from  Round ID: 30045 (Hippie Station)

Reporting client version: 512

Tried to place a blood bag on the IV drip. No matter which one I used, I just ended up hitting it with the bag.

**Comment by yoyobatty** [comment]
This has been found out to be a byond related issue by tg.

**Comment by yoyobatty** [comment]
What beta are you using?
