### ISSUE TITLE
Exosuit Equipment is Broken

### ISSUE THREAD

**Issue by DaydreamPuppeh** [HippieStation/HippieStationdeprecated2020#8255]
Issue reported from  Round ID: 30071 (Hippie Station)

Reporting client version: 512

In a firefighter APLU, you cannot use any equipment. This includes stuff like the drill, clamp, and the plasma cutter.

**Comment by DaydreamPuppeh** [comment]
Forgot to mention that I was an MMI in a mech.

**Comment by WarRage333** [comment]
Tied to being an mmi probably a known bug since its been like that for past 2 years

**Comment by WarRage333** [comment]
Fixed
