### ISSUE TITLE
Disposals bin doesn't stay powered off when you manually turn it off

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStation/HippieStationdeprecated2020#8301]
Possibly upstream issue, need to test but when you turn off the power on a bin, andput something inside, it turns back on and you can't keep it off

**Comment by Pyko1** [comment]
I recall it only works if you turn it off while its charging.

**Comment by JohnGinnane** [comment]
Ah okay, should still be able to turn it off to stop it automatically flushing

**Comment by AnthonyJNgo** [comment]
Probably a line of code that calls a proc that activates it when items are placed inside. Should be as simple as adding a check to see if it is currently on or off. If off then it does nothing.

**Comment by Jujumatic** [comment]
Is this still an issue?

**Comment by AnthonyJNgo** [comment]
It's not an issue, just flush and turn it off.
