### ISSUE TITLE
prefabs circuit disappeared

### ISSUE THREAD

**Issue by Carbonhell** [HippieStation/HippieStationdeprecated2020#8306]
Issue reported from  Round ID: 30144 (Hippie Station)

Reporting client version: 512

where did they go reeeeeEE

**Comment by yoyobatty** [comment]
Did a circuit PR remove them by accidental autism?

**Comment by Carbonhell** [comment]
Maybe, i think it is just a matter of readding some hooks

**Comment by Carbonhell** [comment]
somehow i had an aneurysm and just assumed they were merged here when in fact i coded them on tg and they were denied
something's wrong with me
anyway https://github.com/tgstation/tgstation/pull/36573
