### ISSUE TITLE
Picking up two emagged potted plants changes your player model to a potted plant forever

### ISSUE THREAD

**Issue by Eagle-Eyess** [HippieStation/HippieStationdeprecated2020#8351]
[Round ID]: long ass time ago
[Reproduction]: get emag, emag two potted plants, hold the two newly emagged potted plants in both hands, drop both the emagged potted plants and haza you are now a potted plant for life.

**Comment by DaydreamPuppeh** [comment]
This bug has been around since potted plants were first able to be emagged.

**Comment by AnthonyJNgo** [comment]
This should be an easy fix, not sure why it's been sitting for four months.

**Comment by DaydreamPuppeh** [comment]
Longer. Its been around since January.

**Comment by Jujumatic** [comment]
I believe this issue is still around, should be an easy $1 fix

**Comment by AnthonyJNgo** [comment]
This has been here forever please fix it, $2 bounty.

**Comment by ghost** [comment]
also happens when holding two packaged plants and unpacking them one after the other

**Comment by AnthonyJNgo** [comment]
Did @k-k-karma fix this?
