### ISSUE TITLE
space lube when frozen, will not produce a bar and will delete the chem if removed from the container

### ISSUE THREAD

**Issue by Eagle-Eyess** [HippieStation/HippieStationdeprecated2020#8354]
[Round ID]: # 30210
[Reproduction]: freeze space lube in a beaker, try to remove it. since it cannot be removed it cannot be used for the forge for any lube weapons.

**Comment by WarRage333** [comment]
Something with how water and lube don't leave chem piles but put a ''status'' effect on the tile probably

**Comment by Eagle-Eyess** [comment]
No it’s something recent because you were previously able to freeze it and make weapons and walls out of it.

**Comment by Eagle-Eyess** [comment]
There’s actually a lot of other chems that do this same thing but I left them out because if we can fix this one then the rest should be easy

**Comment by DaydreamPuppeh** [comment]
Yeah, you also can't make solidified ausium for ausium weapons

**Comment by Jujumatic** [comment]
Needs reproducing and if confirmed will likely be a complicated fix. I would estimate a $5 fix if set

**Comment by yoyobatty** [comment]
It is confirmed. Also lube is in the reagent state change blacklist so it and any other Chem will do the same.

**Comment by yoyobatty** [comment]
Also, this is not so much an issue but was added to stop lube from going into a gas form which was an easy solution to stop lube spam, that being said, frozen lube is needed for the forge, so I think this is more of an oversight.

**Comment by AnthonyJNgo** [comment]
This should have been fixed, $2 bounty.

**Comment by yoyobatty** [comment]
Easy, will update the reagents blacklist
