### ISSUE TITLE
Shooting a potted plant with honk mother staff has disastrous results

### ISSUE THREAD

**Issue by Carbonhell** [HippieStation/HippieStationdeprecated2020#8362]
Issue reported from  Round ID: 30222 (Hippie Station)

Reporting client version: 512
Using the staff of the honk mother on a potted plant apparently causes enormous lag due to the banana hitting the potted plant over and over.

**Comment by praisenarsie** [comment]
How does this cause lag? It's literally intended in fact?

**Comment by Eagle-Eyess** [comment]
Cause the banana sprite bounces so fast it crashes your game

**Comment by praisenarsie** [comment]
Then explain to me why I have witnessed it multiple times and it doesn't lag me at all?

**Comment by Eagle-Eyess** [comment]
Idk I haven’t had the problem either but people were complaining. Maybe go rest it on a Potted plant just to be safe

**Comment by Eagle-Eyess** [comment]
I tested this myself and received no lag so idk

**Comment by praisenarsie** [comment]
it's probably goonchat lagging them?

**Comment by AnthonyJNgo** [comment]
This is a client side error not due to the game. People need to get better internet.

Edit: okay I'm big dumb then this should be fixed

**Comment by k-k-karma** [comment]
it's goonchat and a known issue

**Comment by Jujumatic** [comment]
Ah the chat gets spammed by the banana, no? This should be a relatively easy fix though, I expect $1 on this

**Comment by AnthonyJNgo** [comment]
HONK. $2 please fix.

**Comment by yoyobatty** [comment]
Seems like this got fixed a while ago, just confirmed it.
