### ISSUE TITLE
improved shotgun broke

### ISSUE THREAD

**Issue by frozen-is-a-fag** [HippieStation/HippieStationdeprecated2020#8378]
![screenshot 8](https://user-images.githubusercontent.com/41840124/43360056-99fd58bc-927c-11e8-8b45-337a2a8c0cba.png)

Issue reported from  Round ID: 30254 (Hippie Station)

Reporting client version: 512

I have all the shit it asks for but I cant craft it please fix
xoxoxoxoxo

**Comment by praisenarsie** [comment]
![](https://i.imgur.com/RYhoNKQ.png)

you need a pipe instead of metal rods you FOOL
