### ISSUE TITLE
Absorb another changeling objective does not work

### ISSUE THREAD

**Issue by WarRage333** [HippieStation/HippieStationdeprecated2020#8408]
Issue reported from  Round ID: 30275 (Hippie Station)

Reporting client version: 512

As a changeling i absorbed another changeling and it didn't count
I was a mid-round ligger just like him so maybe thats part of the problem

**Comment by Carbonhell** [comment]
Was fixed in my absorb dna fix most likely. Code seemed to be outdated. Remake it if still happens.
