### ISSUE TITLE
Spread infestation changeling ability does not unlock

### ISSUE THREAD

**Issue by WarRage333** [HippieStation/HippieStationdeprecated2020#8409]
Issue reported from  Round ID: 30276 (Hippie Station)

Reporting client version: 512

You're supposed to absorb 3 people and it would unlock.

I absorbed 5 players and 3 monkey humans and it never unlocked

**Comment by AnthonyJNgo** [comment]
I can test this tonight, I remember being able to buy the ability a month ago but could be wrong.

**Comment by Jujumatic** [comment]
Lings are dead
