### ISSUE TITLE
Locker mech recipe might not be working

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStation/HippieStationdeprecated2020#8432]
Issue reported from  Round ID: 30299 (Hippie Station)

Reporting client version: 512

User having issue trying to create one, tried myself using his RPG-ified parts and still couldn't get it work, but I did create one over the weekend so need to test this

**Comment by Carbonhell** [comment]
It works. You probably missed some requirement,it requires a lot of objects. And the path is checked, not the item name,so RPGified items don't matter
