### ISSUE TITLE
Department protolathe taking whole stack of materials instead of asking for a number

### ISSUE THREAD

**Issue by WarRage333** [HippieStation/HippieStationdeprecated2020#8433]
Issue reported from  Round ID: 30300 (Hippie Station)

Reporting client version: 512

Not really a game breaking issue but it was broken before and got fixed

**Comment by JohnGinnane** [comment]
Is this possibly upstream?

**Comment by WarRage333** [comment]
I noticed it goes into the silo in the vault directly, but still i'd like it not to take the whole stack

**Comment by JohnGinnane** [comment]
Should be easy enough to fix, maybe use code from exosuit fab or soemthing

**Comment by JohnGinnane** [comment]
This is confirmed. I think it's because someone (either us or /tg/) changed it so the machines have infinite (remote) space for materials, so you can enter as much as you want

**Comment by WarRage333** [comment]
Feature kinda close this

**Comment by AnthonyJNgo** [comment]
+1 if this is even an issue still

**Comment by ghost** [comment]
this is actually not even an issue,  its more intuitive to split the stack in your hand than to have a gross pop up appear

**Comment by Jujumatic** [comment]
I don't think this is an issue anymore can someone confirm

**Comment by k-k-karma** [comment]
no
