### ISSUE TITLE
Rod crossbow permastuck

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#8447]
Round ID: 30318

If you shoot a rod crossbow at someone adjacent to a wall while handcuffed, they are completely unable to uncuff themselves. Also if the rod happens to fall out, you are still unable to move unless you deconstruct the wall you were rodded on.

**Comment by AnthonyJNgo** [comment]
They should be able to resist out.

**Comment by BlueNothing** [comment]
How do you even get one of these?

**Comment by Jujumatic** [comment]
Seems like this might be a complex issue to resolve but am unsure

**Comment by AnthonyJNgo** [comment]
Shouldn't be too big of a deal, $2 though.

**Comment by yoyobatty** [comment]
Still a bug, will fix this.
