### ISSUE TITLE
Chaplain doesn't have access to Chaple Maintenance beside mass driver

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStation/HippieStationdeprecated2020#8471]
Issue reported from  Round ID: 30342 (Hippie Station)

Reporting client version: 512

**Comment by Eagle-Eyess** [comment]
pretty sure its made so the chaplain doesnt have access so that assistants and such can have access.

**Comment by Eagle-Eyess** [comment]
chaplain already does have maint access in the crem room so i see no reason to give both

**Comment by praisenarsie** [comment]
it's literally a number/word change on some var on the door

**Comment by Eagle-Eyess** [comment]
yes that would then allow chaplain to have access but then it would not allow assistants to have access

**Comment by yoyobatty** [comment]
Incorrect, doors have required access and one required access, the former allows one with both the access requirements in, and the latter will grant access to either one of the access requirements. It's exactly like an and gate and or gate
