### ISSUE TITLE
Trying to place a space cleaner in a full backpack causes it to activate

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStation/HippieStationdeprecated2020#8472]
I thought I fixed this..

**Comment by JohnGinnane** [comment]
I suspect this is upstream but I need to test this to confirm

**Comment by Jujumatic** [comment]
I believe this is still an issue, easy fix would be $1

**Comment by AnthonyJNgo** [comment]
Easy fix, $1.

**Comment by yoyobatty** [comment]
Has to do with this line here: https://github.com/HippieStation/HippieStation/blob/f36040b814f46c69ecb66b06cdd8af59e47f3f69/code/datums/components/storage/storage.dm#L504

Will try to make an exception for storage containers or see if this line can get overriden.
