### ISSUE TITLE
Make admin heals more obvious for who witnesses them

### ISSUE THREAD

**Issue by Carbonhell** [HippieStation/HippieStationdeprecated2020#8490]
Issue reported from  Round ID: 30368 (Hippie Station)

Reporting client version: 512

It can be mistaken for a ling healing themself or such, why was this never fixed

**Comment by JohnGinnane** [comment]
haha I can already see this play out

**Comment by Higitus1** [comment]
This happend to be once, some guy died and I was dragging the body to medbay for cloning. He then got up so I killed him and cremated him. Turns out a Admin did it
