### ISSUE TITLE
space law book wont show the page

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#8511]
Issue reported from  Round ID: 30422 (Hippie Station)

Reporting client version: 512

how about making it 100% ingame so it doesnt lag like 4 minutes then anyway not show anything? i need it as sec

**Comment by JohnGinnane** [comment]
can confirm it's broke

**Comment by Carbonhell** [comment]
The problem is with the wiki itself, not with manuals ingame, I have tried contacting mso but never got an answer, gonna retry i guess but maybe downloading the text and applying it directly would be better instead of iframing

**Comment by AnthonyJNgo** [comment]
This isn't a code issue. Also wiki is fixed now.
