### ISSUE TITLE
Chair buckled icon still using tg's shuttle seat

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStation/HippieStationdeprecated2020#8535]
Buckled:
![image](https://user-images.githubusercontent.com/3355198/43722893-42ed4744-998e-11e8-9879-5a69dc89d5c5.png)
Unbucklked:
![image](https://user-images.githubusercontent.com/3355198/43722908-4fd7a102-998e-11e8-863b-5525c64908b3.png)

**Comment by Carbonhell** [comment]
Confirmed. Should be easy to fix.

**Comment by AnthonyJNgo** [comment]
99% sure this is no longer an issue, displays the correct icon when buckled.
