### ISSUE TITLE
romerol zombies don't have an objective telling them to act as a zombie

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#8542]
Issue reported from  Round ID: 30503 (Hippie Station)

Reporting client version: 512

they just go friendly and may even request to be cured. it's a very expensive traitor item wasted

**Comment by Carbonhell** [comment]
it's an admin matter which got resolved,they're considered team antags,i don't think this is a code issue

**Comment by ghost** [comment]
could just define a zombie antagonist datum to give on zombification and removed on cure if it's a big enough issue
shouldn't be much work

**Comment by ghost** [comment]
its mostly to prevent fights between zombies,  zombies defending humans, zombies requesting to be cured,  etc

**Comment by ghost** [comment]
would be better an upstream thing

**Comment by AnthonyJNgo** [comment]
Is this still an issue? Just give them the custom antagonist role and add the objective to spread the infection at all costs. Will look at it tonight.

**Comment by Jujumatic** [comment]
upstream issue tbh
