### ISSUE TITLE
Can of Cheap Cuisine doesn't put item in free hand

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStation/HippieStationdeprecated2020#8558]
Minor quality of life thing

**Comment by AnthonyJNgo** [comment]
This should be simple fix

**Comment by Jujumatic** [comment]
cheap cuisine is useless now but yeah is this still an issue, i would think so. easy fix would be $1

**Comment by AnthonyJNgo** [comment]
Of course Carbons item is bugged. $1 bounty.
