### ISSUE TITLE
Roundend Won't Occur if Mulligan Occurs

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#8559]
Issue reported from  Round ID: 30534 (Hippie Station)

If the main antagonist dies, say, wizard, and the roundtype is converted through mulligan, then the round won't end unless its done manually by an admin.

Reporting client version: 512

**Comment by Carbonhell** [comment]
Has this happened again?

**Comment by Carbonhell** [comment]
Happened again just now. Setting force_ending to 1 in ticker ended the round correctly, but trying to join from the lobby also seemed to work,there was no warning about the shuttle having docked on centcom. Something is really fucked up and should be checked. @HippieStation/maintainers this is CRITICAL priority, get working dammit

**Comment by Carbonhell** [comment]
Fixed by #8825
