### ISSUE TITLE
You can put a changeling tesla calw on your belt and its stuck there forever.

### ISSUE THREAD

**Issue by GuyonBroadway** [HippieStation/HippieStationdeprecated2020#8599]
Issue reported from  Round ID: 30630 (Hippie Station)

Reporting client version: 512

Title, grow a claw and put it in yer belt slot, you can't get rid of it ever, using the power again just grows a new one.

**Comment by yoyobatty** [comment]
christ, whoever programmed that forgot to do some sanity checks, i'll investigate this
