### ISSUE TITLE
Welder doesn't fix robotic limbs

### ISSUE THREAD

**Issue by ExpAntique** [HippieStation/HippieStationdeprecated2020#8620]
Issue reported from  Round ID: 30684 (Hippie Station)

Reporting client version: 512
it just burns you instead of repairing your robotic limb

**Comment by Carbonhell** [comment]
I think it works with actual prosthetic limbs, doesn't work if you just augment the limbs.

**Comment by ExpAntique** [comment]
Well i remember before you used to be repair augmented limbs, since when you augment a limb you become part android

**Comment by JohnGinnane** [comment]
I had to repair my cyborg arm last night using a welder and there was no problems?

**Comment by WarRage333** [comment]
Fixed
