### ISSUE TITLE
crayons color the tile under the drawing

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#8628]
Issue reported from  Round ID: 30727 (Hippie Station)

Reporting client version: 512

makes the drawing hard to see in some colors, may make paint cans redundant. its annoying, also it makes people who walk on the drawing colored, too

**Comment by Jujumatic** [comment]
puts a reagent colour chempile which turns anything that gets in contact into the same colour. not really an issue anyway
