### ISSUE TITLE
Changelings are stuck on perma "We are already absorbing!"

### ISSUE THREAD

**Issue by Tranquill6** [HippieStation/HippieStationdeprecated2020#8639]
[Round ID]: # 30756

[Reproduction]: Unsure, I was absorbing a mime in the medbay when I had to stop midway and go kill a few people, then after that, I was unable to absorb any more people because when I tried it always said, "We are already absorbing!", even if I tried to with no one in my grip.

[For Admins]: I was no var-edited, I was a round-start changeling, and my absorb dna bugged out.

**Comment by ghost** [comment]
I've run my own server and interrupted all 3 stages, and even let it run to completion. I could still absorb correctly.
The only way I can see it failing is if you disconnect and get interrupted, which is harder to self test.

**Comment by Tranquill6** [comment]
Well, it certainly did happen, I can try to replicate it myself. I remember standing below the chemistry area in the medbay, hiding where the uranium now is when someone walked in on me absorbing so I had to quickly cancel it and take care of two people trying to stop me.

**Comment by Tranquill6** [comment]
Hm, I've had trouble replicating it too. It could be a very rare thing that occurs when you interrupt your absorbing at the right time and the server lag kicks in, because I remember trying to click Aborsb DNA when I was walking around the round, and it still gave me that. I was unable to absorb anyone for most of the round.

**Comment by JohnGinnane** [comment]
Do you recall getting the message saying you were interupted?

**Comment by Tranquill6** [comment]
I don't remember, I didn't have time to look at the time nor did I remember to scroll up. I'm assuming not because if it said I was interrupted, then it wouldn't have perma looped me. My guess is that the game didn't recognize me getting interrupted and I just thought I was trying to absorb someone, so it kept looping me.
