### ISSUE TITLE
CDDA style martials

### ISSUE THREAD

**Issue by JessHorserage** [HippieStation/HippieStationdeprecated2020#8697]
[Title]: # CDDA based martials

[Implementation]: # Levelable martial arts that provide buffs on dodging, attacking and doing cool moves

[Why]: # It would add a bonus fun mechanic onto the quite boring stun system that ss13 combat is

[Resources]: # Some stock attacking noises would have to be made, or not, it's just to add spice to melee combat, which in a lot of circumstances, is a disarm spam or a fucking trainwreck as the other person gets monked on.

@HippieStation/maintainers

**Comment by JessHorserage** [comment]
http://cddawiki.chezzo.com/cdda_wiki/index.php?title=Martial_arts for the list and what they do.

**Comment by JohnGinnane** [comment]
Would this be like the martial arts that chappie can get?

**Comment by JessHorserage** [comment]
My personal plan is that either it could be a nice block of martials that could be a job, or a chappy thing.

Or its dotted around in the game, spess ninja has ninjitsu, traitors could buy dragon style, ops could get newer ones.

I prefer the former.

**Comment by JohnGinnane** [comment]
Cool, but how do people acquire it? Do people level up? Is it gonna be based on RNG?

**Comment by Carbonhell** [comment]
Would be good to have a level up system general to all martial arts and new ones that use it, +1
But i dont want nonantags to have this. Or atleast not easily. Maybe it could be lavaland rewards or such?

**Comment by JessHorserage** [comment]
It would be leveled up, like in CDDA. Acquiring could be split up into differing departments, maybe like cargo ordering in some manuals gaining up to a few levels, or a chaplain turning their rod into a manual or maybe being able to order only one manual from the vendor they have. RNG wise I think CDDA does not make it based on rng, but CDDA's leveling is very slow, so it would have to be sped up mildly.

**Comment by JessHorserage** [comment]
Lavaland rewards could be perfect, like ruins or something.

**Comment by JessHorserage** [comment]
Maybe ordering in them from cargo would be the less powerful ones, and would still be in the extremely expensive range.

I'm talking like, 10000 for one book that only goes up to a mild level due to rarity.

**Comment by JessHorserage** [comment]
Tots and possibly ops could get the more powerful ones, it depends on the martial really. Sec already has a new thing so a tot item that gives REAL krav maga ala hitting fast and knocking out people it two hits kinda thing

**Comment by JessHorserage** [comment]
I'd reccomend playing the game with cheats on to get a bit of exp on how they feel, its not very combo based, mainly getting dodge on some of them.

Note: CDDA has a subreddit, https://www.reddit.com/r/cataclysmdda/ where we could get some info on how it feels and plays.

**Comment by JessHorserage** [comment]
Another idea is to make it so that if you wear bulky armour you have a higher chance to miss, hardsuits, riot  wear, sling and ling stuff ect.

**Comment by ghost** [comment]
It's getting to the point where there is slowly a gain of an overabundance of martial arts.
I've played around with CDDA for quite a while and quite a bit, I don't think they'll add much to SS13.
At most, I'll +1 it if it's just lavaland rewards for some crazy shit so that it's nicely rare, otherwise it's a -1, especially if it becomes orderable through cargo, no matter how low the power level.

**Comment by JessHorserage** [comment]
https://i.redd.it/e4lc37hcafpz.jpg

**Comment by JessHorserage** [comment]
wait shit nvm

**Comment by Eagle-Eyess** [comment]
I feel like melee combat is fine. Non antags don’t need martial arts and while disarm spam is cancer that’s how it should be these are cilvilans. Sec has their martial arts and traitors can get their own. At most maybe give to heads? They already get stun guns tho... -1

**Comment by Carbonhell** [comment]
On a second thought yeah. I agree with eagle, -1.
Denied
