### ISSUE TITLE
[SUGG] weeb portal

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#8703]
[Title]: weeb gateway 

[Implementation]: # cat themed portal that qdels you and redirects you to tgstation bagyl or sybil or terry,  random chance.  alternately just redirects you and closes the hippie screen.  possibly as am anomaly or supermatter detonation spawn,  maybe cult anomaly event

[Why]: # its fun

[Resources]: # slightly reskinned wormhole?  also largened up and has cat ears? 

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by Carbonhell** [comment]
why the hell would we send our players to tg,we aren't pro-torture

**Comment by Carbonhell** [comment]
-1

**Comment by ghost** [comment]
lol no -1

**Comment by ghost** [comment]
wtf ?

-1

**Comment by Carbonhell** [comment]
Denied.
