### ISSUE TITLE
[SUGG] add back saxophones

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#8705]
[Title]: saxophones 

[Implementation]: # bring back prerebase saxophones that would play the epic sax solo,  the robbie rotten theme (rip), etc.  it was really cool,  played a predefined song no midi bullshit

[Why]: greatly improves audio atmosphere

[Resources]: # both graphics and audio exist in older versions.

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by JohnGinnane** [comment]
Was it from old code? Should be very easy to bring back

**Comment by ghost** [comment]
yes

**Comment by Carbonhell** [comment]
hell yes +1

**Comment by ghost** [comment]
+1 pls

**Comment by Carbonhell** [comment]
Accepted!

**Comment by ghost** [comment]
working on this right now

**Comment by JohnGinnane** [comment]
Added in #8710
