### ISSUE TITLE
Ascended Slings cant gib, hypno or gore at all.

### ISSUE THREAD

**Issue by JessHorserage** [HippieStation/HippieStationdeprecated2020#8707]
Issue reported from  Round ID: 30852 (Hippie Station)

Reporting client version: 512

possibly the cqc hos bug

**Comment by Carbonhell** [comment]
Amari is dealing with this

**Comment by ghost** [comment]
If other click abilities work, like glare, this is confusing

**Comment by nalarmg** [comment]
Related PR - https://github.com/HippieStation/HippieStation/pull/8708

**Comment by ghost** [comment]
Close this

**Comment by praisenarsie** [comment]
no
