### ISSUE TITLE
Going in and out of bat form removes monk levels and also zombie

### ISSUE THREAD

**Issue by DaydreamPuppeh** [HippieStation/HippieStationdeprecated2020#8721]
Issue reported from  Round ID: 30866 (Hippie Station)

Reporting client version: 512

When you are a vampire and use bat form, you lose any monk levels you had. Also removes zombiefication.

**Comment by ghost** [comment]
This is due to batform using mind transfers. The fix would be to transfer monk levels on mind transfer, which would be better done upstream, but since i'm gitbanned upstream, I can't do.

Also I'm not entirely sure about zombification.

**Comment by ghost** [comment]
upstream doesn't have monk

**Comment by ghost** [comment]
Whoops

**Comment by ghost** [comment]
but yeah, this is more of a monk-code thing, than a vamp-code thing

**Comment by Jujumatic** [comment]
monk is dead
