### ISSUE TITLE
[SUGG] Dwarf expedition

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#8740]
[Title]: # Lava dwarves as seen in https://github.com/tgstation/tgstation/pull/29833

[Implementation]: Already coded in https://github.com/tgstation/tgstation/pull/29833 but might need tweaking. **Discuss.**
can see more about it here https://tgstation13.org/wiki/Lava_Dwarf

[Why]: # How does your feature improve the game anyhow? Why should it be added?
are you kidding, it's lavaland dwarves

[Resources]: # Eventual assets such as icons and sounds which you have and want to suggest related to this feature.
present in https://github.com/tgstation/tgstation/pull/29833 

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by ghost** [comment]
+1 also make it playable selectable race

**Comment by ExpAntique** [comment]
Meaningless Mentor +1

**Comment by Razorblaza** [comment]
+1 it was compleyely autistic but i loved it so i want it back

**Comment by Carbonhell** [comment]
Sure. Accepted.

**Comment by Jujumatic** [comment]
can't recommend a bounty value on this as too vague on exactly what would be added

**Comment by AnthonyJNgo** [comment]
KBB has a PR open for this, closing.
