### ISSUE TITLE
AI static dissappearing

### ISSUE THREAD

**Issue by MiniMeatwad** [HippieStation/HippieStationdeprecated2020#8742]
Issue reported from  Round ID: 30889 (Hippie Station)

Reporting client version: 512

i was tracking a person, then they went into maintenance and i noticed that the static wasn't blocking maintenance from being looked at, so i could still watch where they're going, but then i flew away for a bit and came back, and then the static came back.

**Comment by Carbonhell** [comment]
What byond minor version are you using? 1440?

**Comment by MiniMeatwad** [comment]
possibly 426, i cannot confirm.
