### ISSUE TITLE
Add waddling quirk

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStation/HippieStationdeprecated2020#8745]
[Title]: Add waddling quirk

[Implementation]: Should be easy to add the new component on quirk gain

[Why]: Would be funny to see people waddle about the place

[Resources]: None

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by ghost** [comment]
i really want to tie it behind being drunk

**Comment by JohnGinnane** [comment]
I wonder if we could do a modifying for waddle distance, so the quirk is just a little waddle while drunk makes you waddle violently and perhaps randomly?

**Comment by ghost** [comment]
thats probably trivial

**Comment by Carbonhell** [comment]
don't forget to label stuff with feature smh
also yeah sure +1

**Comment by ghost** [comment]
yes +1 cute

**Comment by ghost** [comment]
absolutely +1

**Comment by JohnGinnane** [comment]
I'm working on this, it's almost ready
