### ISSUE TITLE
Vr does not work

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#8759]
Issue reported from  Round ID: 30912 (Hippie Station)

Reporting client version: 512

**Comment by Carbonhell** [comment]
Possibly upstream?

**Comment by Carbonhell** [comment]
Nevermind, it was our issue. Most likely fixed,need to wait for the round to restart to check.

**Comment by Carbonhell** [comment]
I fixed the configs and tried loading one,but the code is so unspeakably shitty everything started runtiming, and this is an upstream problem. I had to disable it for the moment being, it's just unplayable right now.
