### ISSUE TITLE
Antag token system

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#8760]
[Title]: # Antag token system

[Implementation]: # Basically, instead of admins needing to use notes to give antag tokens, and admins needing to be ahelped to redeem them, how about we make them their own system? Eagle suggested on discord that you could select between, say, revenant, round antag, etc.

[Resources]: # Possibly a selection GUI?

@HippieStation/maintainers

**Comment by Carbonhell** [comment]
Yeah +1

**Comment by ghost** [comment]
Make it record the current round ID during when the token was given out for transparency and to make it easy to verify any potential situations/and or abuse.

+1

Greetings, Fluxcapacitor1337
Headmin

**Comment by Eagle-Eyess** [comment]
+1 aswell it have to be done well though. It cannot for any reason, show what the antag of the round is without them using the token or it will just give everyone meta info. But as it’s stated I feel it should give different antags. Revenant and swarmer maybe as staples as they usually spice up rounds without messing them 100% up. Also it should only be accessible roundstart. maybe revenant and swarmer could be allowed to people in the lobby after round starts but not the antag of that round.

**Comment by ghost** [comment]
Swarmers can mess up rounds easily if done right.

**Comment by Eagle-Eyess** [comment]
Not that fast though. Plus it brings other people into the round. Might be more good there than bad.

**Comment by Carbonhell** [comment]
Accepted as long as it doesn't cause any meta info to leak
