### ISSUE TITLE
[SUGG] Admin-independent antag token system + crew objective rewards

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#8761]
[Title]: # Admin-independent antag token system + crew objective rewards

[Implementation]: # How should the feature work out? What exactly is it supposed to do, in your initial idea? If an item, can it be crafted/found/bought and for what?

It works out like this: By doing crew objectives, you get a small percentage of either antag coin (satoshi's) or antag chance ala the system tg dded, which can be used by the player by clicking and toggling a Be Antag option in the main lobby menu, to spawn as antag (if more people use it it chooses randomly between them for who gets it, the unlucky losing nothing). (this could also work by crew objectives adding antag token satoshi AND loadout points for a double economy a la mobile game)

[Why]: # How does your feature improve the game anyhow? Why should it be added?
adds a cool OOC objective other than getting as much frags as possible. It's cool, been spoken in coderbus.

[Resources]: # Eventual assets such as icons and sounds which you have and want to suggest related to this feature.
Don't think there's any need for icons or sounds for this, just a new lobby button/char preferences button (the latter would be clunkier imo)

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by Carbonhell** [comment]
Interesting idea but maybe it should be split in two separate issues, one for antag tokens and one for crew objs. That said, raising antag chance would be better than just giving a token directly.
I like the idea overall, improves good play but objectives need to be carefully discussed cause the past ones were not liked.
+1

**Comment by Carbonhell** [comment]
Actually duplicate of #8760 and #8715 , expand on those two instead
Closing
