### ISSUE TITLE
Chem tiles missing icon

### ISSUE THREAD

**Issue by Eagle-Eyess** [HippieStation/HippieStationdeprecated2020#8765]
[Round ID]: #30928
Chem tiles did not have an icon when placed. This was on the first test of MetaLake so not sure if it was for that reason or because they actually broke. guessing the second option there tho.
![image](https://user-images.githubusercontent.com/36767768/44614490-9b591c00-a7f3-11e8-9f06-4896054071b3.png)
[Reproduction]: go on a round and place chem tiles

**Comment by ghost** [comment]
they're actually broke, it happens on box too.

**Comment by ghost** [comment]
i'll have a go at this
