### ISSUE TITLE
Shadowlings and Shadowpeople take perma oxy dmg

### ISSUE THREAD

**Issue by Eagle-Eyess** [HippieStation/HippieStationdeprecated2020#8766]
[Round ID]: #30929
[Reproduction]: take oxy dmg as sling. never goes away even in room full of oxygen
guess they cant breath idk.

**Comment by ghost** [comment]
my guess is you took oxy damage before you became a sling. it won't go up or down once you turn into a sling. Not really a bug, just a weird thing but with no side effects, I think?

**Comment by Eagle-Eyess** [comment]
na was taken when was a sling

**Comment by ghost** [comment]
how

**Comment by Eagle-Eyess** [comment]
well the person who first had the problem somehow got 10 oxy dmg (not sure how maybe went into space by accident, who knows.) and that wouldnt go away. so then i reproduced it by turning myself into a sling and admin giving me 50 oxy damage to see if it would go away which it did not.

**Comment by ghost** [comment]
first person might've had it before they turned into sling. and ofc you're gonna have it if an admin gives it to you

**Comment by Eagle-Eyess** [comment]
yes but if you give it to a normal human as admin it goes away as does normal oxygen dmg. it heals overtime when in the presence of o2.

**Comment by ghost** [comment]
slings don't take O2 damage. of course, as a side effect, this means they won't heal it either, since in the code, healing is just done by damaging with a negative value

**Comment by Eagle-Eyess** [comment]
and theres no way to fix this? even if they took it before they changed kinda weird that now they are going to be a lower maximum health for the rest of the round...

**Comment by ghost** [comment]
no it's a weird side effect of mobcode. can be manually fixed by admeme

**Comment by Eagle-Eyess** [comment]
can they take o2 dmg from chems? like say if i inject one with cyanide.

**Comment by ghost** [comment]
```inherent_traits = list(TRAIT_NOGUNS, TRAIT_RESISTCOLD, TRAIT_RESISTHIGHPRESSURE,TRAIT_RESISTLOWPRESSURE, TRAIT_NOBREATH, TRAIT_RADIMMUNE, TRAIT_VIRUSIMMUNE, TRAIT_PIERCEIMMUNE)```

Not sure, actually
