### ISSUE TITLE
Z-levels

### ISSUE THREAD

**Issue by xTrainx** [HippieStation/HippieStationdeprecated2020#8773]
[Title]: Multi Z-levels

[Implementation]: #should be like aurora z-levels, allowing you to make new floors or holes leading up and down, maybe build stairs and elevators, most importantly tho, it should allow people to play with gravity, make pitfalls and should give mappers a bit more of freedom when adding shit

[Why]:  i think it's high time hippie stole something from someone other than tgstation, i always though z levels were neat, and gives a lot more possibilities to the players to fun things, specially if we are allowed to make traps and pools with it. if this is made, i suggest giving the cats moths and the liggers their own room so they can be degenerates elsewhere

[Resources]: https://github.com/Baystation12/Baystation12

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by ghost** [comment]
this is an awful lot of work, and i don't even know if it's feasible without rewriting a lot of code
bay and tg split up quite a while ago and i have no idea how different they are now

**Comment by Carbonhell** [comment]
What mcbaw said. I doubt it's easily doable and i don't know if it's worth the effort honestly.
-1

**Comment by Eagle-Eyess** [comment]
Also don’t like this idea for the fact that if we add different z levels where people can go up or down it will give a lot less interaction between them and on our server where we still trying to increase the pop back to glory days does t seem like a good idea right now. -1

**Comment by ghost** [comment]
I am agreeing with Eagle-Eyess on this one.

Greetings,
Fluxcapacitor1337
Head Administration Team

**Comment by Carbonhell** [comment]
Denied.
