### ISSUE TITLE
Re-add old changeling Revival Features

### ISSUE THREAD

**Issue by Razorblaza** [HippieStation/HippieStationdeprecated2020#8789]
[Implementation]: Just Re-add the old TG method of revival where even in death you can slowly revive after you die

[Why]: Because it adds a lot more spice to the game and the fact that changeling cannot revive kinda makes them boring as you either have to wait for a crew member to revive you (who doesn't know your a ling) or just hope you have auto cloned yourself. When we had the old revival feature there was always a mad rush to find the ling before he escaped and ran away reforming but now you don't even have to worry and can just throw him in the morgue and job done.
I'm basically saying it was more tense and fun when the changelings had the chance to come back into the round and cause more chaos which makes funnier.

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by ghost** [comment]
have my completely meaningless +1

**Comment by Razorblaza** [comment]
+1 very good definetly had weight behind this +1 oh wow this is a plus 2 now

**Comment by Carbonhell** [comment]
I swear i thought i made a issue about this already weird. But yeah, this has my +1 even tho i wluld prefer if crystalwarrior lings were readded with tiered stings.

**Comment by ghost** [comment]
crystalwarrior lings? is that /vg/ lings?

**Comment by Carbonhell** [comment]
dunno,it was a tiered system where you could buy shitstings at tier 1, get more points/grow up in tier by absorbing people,eventually leading to tier 4 which unlocked horrorform(an actual,OP one)

**Comment by ghost** [comment]
i might actually bother to do this

**Comment by Carbonhell** [comment]
See https://github.com/HippieStation/HippieStation/issues/8830
I would prefer that to be done instead of this. -1ing this in favor of the other version.

**Comment by Eagle-Eyess** [comment]
As carbon said I would like a different kind of ling cause old ling (while better than new ling) wasn’t much better than what we have now. I haven’t played too much with the tiered ling but better than nothing so also going to -1 this in favor of that.

**Comment by ghost** [comment]
Either #8830 or this, both good with me...

+1

Greetings,
Fluxcapacitor1337
Head Administration

**Comment by Carbonhell** [comment]
Denied in favor of the full rework,which includes this
