### ISSUE TITLE
Liquids Redux

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#8791]
[Title]: # Liquid

[Implementation]: # Ya know, how liquids used to work. Except less laggy. And using that drawbox thing some redditor made. Also, maybe we could have certain types of clothing be liquid proof (hardsuits, biosuits, riot suits, radsuits)

[Why]: # shits and giggles

[Resources]: # https://pastebin.com/raw/m5dWySxP

@HippieStation/maintainers

**Comment by Carbonhell** [comment]
Last liquid implementation went really, really bad. Unless an experienced coder does this and it gets extensively tested, I don't want it.
For now, abstaining/leaning towards a -1

**Comment by Eagle-Eyess** [comment]
I agree with carbon I can’t see how liquids could be implemented after the horendous code we had last time but anything is possible so I’ll stay neutral for now

**Comment by ghost** [comment]
-1

Greetings, Fluxcapacitor1337
Head Administration

**Comment by Carbonhell** [comment]
Denied.
