### ISSUE TITLE
Robbie Rotten gamemode

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#8795]
[Title]: # WE ARE NUMBER ONE - the gamemode!

[Implementation]: # Basically, a single person spawns in maint, with the name Number One. Their objective is to commit petty crimes and cause as much chaos without physically hurting anyone.

[Why]: # In honor of Number One!

[Resources]: # Number one's jumpsuit and mustache!

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by JohnGinnane** [comment]
\>meme gamemode
no thanks

let me clarify what i mean though:

\>a single person spawns in maint
so only one person out of everyone on the station
\>objective is to commit petty crimes and cause as much chaos
aka general shittery
\>... without physically hurting anyone
🤔 

this would be perfect for a bus event or something, where an admin can watch over the player to make sure they don't cause actually physically hurt anyone (including indirectly like flooding plasma or something), and it means that other players still have a chance of getting real tator

**Comment by Carbonhell** [comment]
basically what assistants do every round
i don't think this needs a dedicated gamemode honestly, -1
