### ISSUE TITLE
[SUGG] F4 is whisper hotkey

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#8812]
[Title]: #  F4 is whisper hotkey
[Implementation]:  F4 is whisper hotkey

[Why]: #  F4 is whisper hotkey

[Resources]: # like the say hotkey but for whisper
Eventual assets such as icons and sounds which you have and want to suggest related to this feature.
# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by GuyonBroadway** [comment]
F4 is currently bound to adminchat.

You can whisper at any time by putting a # before anything you say.

**Comment by Carbonhell** [comment]
^
-1
