### ISSUE TITLE
Chem Dispensers icons turn invisible and become unusable

### ISSUE THREAD

**Issue by Jsau7** [HippieStation/HippieStationdeprecated2020#8832]
[Round ID]: #31018

When I joined the round the Chem dispensers were all normal, only until later on that I noticed that the chem dispensers' icons were invisible, I checked the ones in Chemistry and Science and they all seemed to have the same issue, I also tried to make a new chem dispenser with the board from tech storage and as soon as I finished adding the parts and screwdrivered the machine frame it came out invisible like the rest.

**Comment by JohnGinnane** [comment]
This is due to power going out and there's no unpowered dispenser icon so it just goes invisible

**Comment by Carbonhell** [comment]
Did #8849  fix this? @yoyobatty

**Comment by Carbonhell** [comment]
Nvm not fixed yet
