### ISSUE TITLE
Public nanite chambers are sometimes un-interactable

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#8837]
Issue reported from  Round ID: 31029 (Hippie Station)

Reporting client version: 512

Title says it all. Sometimes you build a public nanite chamber, and despite the APC being on, you can't click it or do anything with it. Alt+Click menu doesn't even show the nanite chamber.

**Comment by WarRage333** [comment]
Removed from the map

**Comment by ghost** [comment]
Bug has been fixed for a while. It was upstream.

Also wtf are you talking about, @WarRage333
