### ISSUE TITLE
[SUGG] Roguelike style melee

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#8838]
[Title]: # Roguelike style melee

[Implementation]: # 
Walking "into" someone with harm intent will attack them.

Not only it accomplishes the same thing as this (somewhat, it's not the same) it allows for two more things:
-Charges:
There's spears in-the game, but I can't mount the clown and charge at someone after running the whole hallway. Think about it: Jousts in space.

-Toreador:
Someone walks into you, he atacks. Side-step. Yakety-sax still works as a defensive maneuver, but won't help you if you're trying to atack the guy, compared to sidestepping and atacking.

[Why]: # Way more visceral combat

[Resources]: none needed

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by ghost** [comment]
do not like this...

-1

**Comment by Carbonhell** [comment]
I don't think this would improve the server anyhow, it'd just make people run around as autists and attack everyone even more than the current setup allows. Sorry, -1.
