### ISSUE TITLE
Remove dirty vars on our maps

### ISSUE THREAD

**Issue by praisenarsie** [HippieStation/HippieStationdeprecated2020#8839]
_maps/map_files/HippieStation/hippiestation.dmm:	pixel_x = 0;
_maps/map_files/HippieStation/hippiestation.dmm:	pixel_y = 0;
_maps/map_files/HippieStation/hippiestation.dmm:	pixel_y = 0
_maps/map_files/HippieStation/hippiestation.dmm:	pixel_y = 0
_maps/map_files/HippieStation/hippiestation.dmm:	pixel_x = 0;
_maps/map_files/MetaLake/MetaLake.dmm:	pixel_y = 0
pixel_[xy] = 0 detected in maps, please review to ensure they are not dirty varedits.

just do CTRL + F for pixel_x = 0 and pixel_y = 0, and you can remove them manually, watch for those ;

**Comment by Carbonhell** [comment]
@steamp0rt

**Comment by ghost** [comment]
>TFW webeditor won't let you edit one line of a 1.83 MB file
