### ISSUE TITLE
[SUGG] Xenobiology start-up buff

### ISSUE THREAD

**Issue by WarRage333** [HippieStation/HippieStationdeprecated2020#8854]
[Title]: Xenobiology start-up buff

[Implementation]: # Instead of the two gray slimes xenobio starts with it should start with ALPHA / OMEGA slimes (temp names or come up with something better). Alpha would split into a orange, purple and two gray slime, while Omega would split into blue, metal and two gray slimes. Giving you one tier 1 slime after the first split.

[Why]: # So many times i have tried to do xenobiology and i spent twenty minutes before i got tier 3 slimes, sometimes not even that high. As a traitor this is big gamble and not really worth doing nearly ever since the time you spend there you could killed the station over 5 times. Rounds don't last long as here as on /tg/ so to remove the start RNG it would speed it up and bring it up to par to hippie round speeds.

[Resources]: # Could use just the normal gray slime sprites for them

@HippieStation/maintainers

**Comment by ghost** [comment]
+1 this would be big

**Comment by JohnGinnane** [comment]
Cool idea but it would a buff to science so perhaps some kind of nerf to the rarer slimes to balance it? i.e. stop kiefer from getting his gold slimes even faster

**Comment by WarRage333** [comment]
Make the reaction cost 5 plasma instead of 1 if it becomes too much of a problem

**Comment by Carbonhell** [comment]
Dunno about this. Rather just buff the mutation chances,idk.

**Comment by WarRage333** [comment]
May be a bit overkill to make them all have higher mutation chance

**Comment by ghost** [comment]
As I am unfamiliar with the field of xenobiology I will have to be neutral on this.

Greetings, Fluxcapacitor1337
Headmin

**Comment by Eagle-Eyess** [comment]
I think maybe a better idea would be just making them eat the monkies faster. Still gives the rng that xenobioglogy needs so it isn’t op but also makes it not take forever.

**Comment by WarRage333** [comment]
Slime pr merged can close this
