### ISSUE TITLE
Backup crew event

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStation/HippieStationdeprecated2020#8855]
[Implementation]: At a certain point during the round all ghosts are prompted if they want to be part of backup crew (similar to how ERT is prompted), all those who hit "yes" will be given a new human with assistant job and will arrive via arrivals shuttle. 

[Why]: For all intents and purposes this would be a "lore friendly" free respawn at random. This might give people who have been out of the round for a while a chance to come back on. **The new human would technically be a new mind as such the whole 'new life rules' would apply** but I think this should be discussed to stop someone who was killed by an antag to respawn and just go straight for antag

[Resources]: Not much, would be pure code

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by JohnGinnane** [comment]
Just to expand on this, this would be a simple proc that could be called via Admin tab so if admins want to call this themselves they can

**Comment by ghost** [comment]
yeah this would be cool
also maybe a version that spawns them on lavaland randomly with a pickaxe/ka and internals

**Comment by Carbonhell** [comment]
No need for an admin button,admins can force random events.
Anyway i'm scared it could end up in cunts trying to look for revenge. Doubtful +1.

**Comment by JohnGinnane** [comment]
\>force random events
eh can they choose the event or is it always random because the point is to let them call this event specifically

**Comment by ghost** [comment]
I do not like this at all, better for this to be delegated to admins instead to make it a rare and controlled event with oversight in case people use ghost knowledge (which they frequently do even while under admin supervision) and for this to be potentially triggered when no admin is online sounds like a recipe for disaster. Too many variables that can go wrong. I do not like this.

-1

Greetings, Fluxcapacitor1337
Head Administration

**Comment by ghost** [comment]
or how about making this spawn the players on the far end of lavaland but fully equipped to come back to the station,  along with IDs.  
"marooned arrivals shuttle"

**Comment by Eagle-Eyess** [comment]
Yea don’t like this event even as an admin butting honestly. People will already know about the round (most times) so even if they try to not meta it’s very hard when you see the traitor coming at you. Not to mention as carbon stated grudeful people.

**Comment by Carbonhell** [comment]
On a second thought, this could help against murderboners and keeping people in the round. I'd prefer if this got in, atleast as a normal random event.

**Comment by JohnGinnane** [comment]
It would start off as a normal random event but admins could also call it via Fun if they're doing some bus

**Comment by Carbonhell** [comment]
We need opinions, lads. Comment.

**Comment by HippieBartels** [comment]
Would be good to keep people in the round but I'd rather it'd be an admin triggerable event only

**Comment by Carbonhell** [comment]
Needs more comments from Gms and Has

**Comment by AnthonyJNgo** [comment]
-1 for whatever it's worth people will metagame and or metagrudge. You're telling me they'll all spawn in arrivals together and when the traitor runs up to them they won't all mob on him? Big oof. We have spawner menus already, maybe make new spawn locations and increase the amount of people that can be at those locations. Revamping Charlie station would be very cool.

**Comment by Jujumatic** [comment]
i like this but drones already show there's a huge metagaming and metagrudging issue. i would like this however and it wouldn't be difficult to implement. $1-$2 bounty. also this needs more headmin and gm votes

**Comment by AnthonyJNgo** [comment]
Closing this because when dwarves is implemented this will not be used. We also already have ghost roles in the meantime.
