### ISSUE TITLE
Swapping hands with middle mouse

### ISSUE THREAD

**Issue by MiniMeatwad** [HippieStation/HippieStationdeprecated2020#8873]
it has a lag and it seems like if you press middle mouse too fast it doesn't swap hands, and sometimes it just doesn't swap hands, making it really hard to do quick swapping between hands with middle mouse

**Comment by ghost** [comment]
pressing x is way faster anyways

**Comment by MiniMeatwad** [comment]
not if you don't use hotkeys

**Comment by AnthonyJNgo** [comment]
-1. This isn't really something we can take care of. Honestly it could be your client, or your connection that is lagging. I haven't been able to replicate this issue, works fine for me.
