### ISSUE TITLE
Allow revolver to be swung in hand

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStation/HippieStationdeprecated2020#8874]
[Title]: *swoosh*

[Implementation]: Perhaps alt click on revolver to swing it

[Why]: See title

[Resources]: All code

https://www.youtube.com/watch?v=H6cDTVKHsek

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by ghost** [comment]
so we can pistol whip fools? I like this.

+1

Greetings,
Fluxcapacitor1337
Head Administration

**Comment by Eagle-Eyess** [comment]
+1 why not

**Comment by Carbonhell** [comment]
Sure, accepted
