### ISSUE TITLE
im cant make Hexamine 

### ISSUE THREAD

**Issue by lolmemelord123** [HippieStation/HippieStationdeprecated2020#8876]
Issue reported from  Round ID: 31076 (Hippie Station)

Reporting client version: 512

**Comment by lolmemelord123** [comment]
yeah i followed the recipe on the wiki and it didint make it

**Comment by JohnGinnane** [comment]
From what I can see, it's a cold recipe that must be cooled to 230K and have a pressure of 35Bar before reacting

**Comment by lolmemelord123** [comment]
well it dosent say that on the wiki

**Comment by JohnGinnane** [comment]
Yeah I noticed that, perhaps we should bug someone to look at it...

**Comment by JohnGinnane** [comment]
Can you try making it next round just to confirm it works?

**Comment by lolmemelord123** [comment]
idk isent carbon the wiki admin?

**Comment by lolmemelord123** [comment]
hold il try it again

**Comment by lolmemelord123** [comment]
well i can make but the wiki needs to be updated
