### ISSUE TITLE
TTS changes

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStation/HippieStationdeprecated2020#8884]
* Start with preference enabled (not sure why it isn't on by default)
* Allow admins to choose voice
* Admin TTS should show admin
* Voice ban
* Sanitize the text by removing "[" and "]" with everthing in between, but only the display text, not value
* Erik made some suggestions on how to process it but will need to do a lot of work as it's a complete rewrite, need to investigate further

**Comment by ghost** [comment]
please make whoever is TTSing voice get cut off instantly when the person gets critted or dies

+1

Greetings,
Fluxcapacitor1337
Head Administration

**Comment by JohnGinnane** [comment]
Very good idea, will see how it can be done

**Comment by Carbonhell** [comment]
Carbonhell: you should be using get_turf 
anything that actually has a loc to begin with can just snap to the turf layer of the contents tree with get_turf

**Comment by JohnGinnane** [comment]
Gonna use https://github.com/HippieStation/HippieStation/projects/9 for this work
