### ISSUE TITLE
[SUGGESTION] Heavily nerfed version of clown car spawning inside / within close proximity to clowns office by default

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#8885]
[Title]:  Heavily nerfed version of clown car spawning inside / within close proximity to clowns office by default

[Implementation]: # We take the existing clown car traitor item, nerf it down heavily and make it look distinct from the traitor clown car and have it spawn near clowns office.

[Why]: # Would be a fun addition to the game, I believe goon has this, I've seen it there and I think it would fit great here as well.

[Resources]: # Existing clown car, maybe a new shade of color

**Comment by ghost** [comment]
by "nerf it down heavily", you mean "get rid of the ability to suck up people, and spray lube", right?

wait no lube is a normal clown thing

**Comment by ghost** [comment]
that sounds good

**Comment by HippieBartels** [comment]
+1 would make playing as clown more interesting

**Comment by Eagle-Eyess** [comment]
+1 but maybe find a way for the clown to only be able to access it. Don’t want no greytiders to be able to steal it easily at least. Maybe keys in his locker.

**Comment by HippieBartels** [comment]
We can make it like the traitor clowncar, only the clown is able to steer it.

**Comment by ghost** [comment]
I believe @HippieBartels has already coded this. We just need the sprite to make it look distinct from the existing traitor clown car so they don't get mixed up.

**Comment by ghost** [comment]
bump

**Comment by Carbonhell** [comment]
Sure, accepted

**Comment by GuyonBroadway** [comment]
I'll try and get this done soonish.

**Comment by ghost** [comment]
Thanks
