### ISSUE TITLE
in game ambience does not stay turned off if disabled when you rejoin

### ISSUE THREAD

**Issue by Eagle-Eyess** [HippieStation/HippieStationdeprecated2020#8888]
![image](https://user-images.githubusercontent.com/36767768/44942605-86483400-ad83-11e8-9941-119f0880d980.png)

guessing the tts might have changed something as he says?

**Comment by Eagle-Eyess** [comment]
why does the bot auto make stuff new shit?

**Comment by Carbonhell** [comment]
So that if is it a feature, it can be moved accordingly
