### ISSUE TITLE
Cows don't moo

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStation/HippieStationdeprecated2020#8889]
Issue reported from  Round ID: 31096 (Hippie Station)

Reporting client version: 512

Screaming coos should moo

**Comment by ghost** [comment]
Extremely crucial for this to be resolved immediately.

Greetings,
Fluxcapacitor1337
Head Administration

**Comment by AnthonyJNgo** [comment]
Cows should moo. $1 bounty.

**Comment by AnthonyJNgo** [comment]
The cow asks, "Moo?"

You're welcome.
