### ISSUE TITLE
Using duct tape on damaged windows should repair them

### ISSUE THREAD

**Issue by JohnGinnane** [HippieStation/HippieStationdeprecated2020#8899]
Issue reported from  Round ID: 31103 (Hippie Station)

Reporting client version: 512

**Comment by Eagle-Eyess** [comment]
why duct tape? Not sure if it be the best idea to tape glass together... wait is it suppose to fix them?

**Comment by Carbonhell** [comment]
This is not an issue, it is a suggestion at most.

**Comment by Eagle-Eyess** [comment]
That’s what I thought but it has the issue round is and all. Anyway I don’t think duct tape would be the best for glass repair. -1

**Comment by JohnGinnane** [comment]
I reported it from in game so I couldn't choose suggestion but that's what its

It isn't meant as a robust solution, more of a "this will hold for now", so it won't make them full strength but it will slow/remove leaking air

**Comment by ghost** [comment]
how about using duct tape on GRILLES would make them opaque and ad-hoc airtight, but a simple hit will make them revert to grilles. thus, if a window is broken it can be quickly taped over until an engineer comes by

**Comment by Carbonhell** [comment]
Dunno, I don't see a lot of use cases. -1

**Comment by Carbonhell** [comment]
Needs more opinion

**Comment by AnthonyJNgo** [comment]
-1 duct taping glass fixing windows is weird and doesnt make sense.

**Comment by AnthonyJNgo** [comment]
Use a welder.
