### ISSUE TITLE
Infiltration mode port

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#8902]
[Title]: # Infiltration Gamemode

[Implementation]: # https://wiki.oraclestation.com/wiki/Syndicate_Infiltrator  Basically 3-5 syndicate infiltrators get anywhere from 4 to 6 objectives, and have to sneak onboard to complete them. They don't get murderbone weapons or huge bombs. They do, however, get tons of stealth shit, like e-pistols, manifest spoofs, etc

[Why]: # It's a gamemode that you LOSE if you murderbone! Certainly a good shakeup. Was fun on oracle (and the /tg/ testmerges earlier this year)

[Resources]: # I have everything I need

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by ghost** [comment]
I like the sound of this.

+1

Greetings,
Fluxcapacitor1337
Head Administration

**Comment by Eagle-Eyess** [comment]
So they get a bunch of stealth shit I like that but what stops them from murderboning besides being alerted to the crew? That’s not enough of an insentive to not murderbone. The gamemode sounds good nonetheless +1

**Comment by ghost** [comment]
They don't get murderbone shit. They can't buy e-swords, or e-bows, or syndie bombs.

**Comment by bubberduckydducker** [comment]
1+ from murderboner bubberducky

**Comment by ghost** [comment]
+1 also hi bubbersucky the edgeman
