### ISSUE TITLE
Chemist no longer has access to Cloning 

### ISSUE THREAD

**Issue by G-erma** [HippieStation/HippieStationdeprecated2020#8906]
Issue reported from  Round ID: 31109 (Hippie Station)

Reporting client version: 512

pretty fucking bad when chemist is the only med personnel on the station

**Comment by Eagle-Eyess** [comment]
Chemist never did have access to cloning but instead recieved extra access when there was no other medical staff. You sure there was no other medical staff that shift?

**Comment by G-erma** [comment]
OH FUCK IM STUPID

**Comment by Carbonhell** [comment]
np
