### ISSUE TITLE
PROTAGONISTS, SAVE US!! Spitballing on 'protagonist' roles.

### ISSUE THREAD

**Issue by LingeringProfanity** [HippieStation/HippieStationdeprecated2020#8907]
[Title]: Or how I learned to stop worrying and love the Batman.

The idea is simple. Antagonists are given a plethora of resources and built-in abilites. Syndies have their uplink, wizards have their spells, changelings have their stealth... I mean, their arm cannon that they use to kill everyone and everything because it's OP.  So, why not have "Protagonist" roles? Now, of course, on a normal server the protagonists are the crew themselves, yes? But on Hippie, a majority of the crew are absolute pieces of shit, total fucking assholes who would happily sabotague the station, security, the command staff, medbay, etcetera. Basically, the people who are supposed to be the protagonists are actually just shitty wanna-be antags who are upset that they didn't actually roll antag. The number of crew who actually PLAY AS PROTAGS, who actually want to help their crew mates and crush antag balls is INCREDIBLY SLIM. Incredibly slim. So, you cannot trust your fellow crew members, you cannot trust the inept AI or the borgs who happily let themselves get emagged... Who can you trust? The Captain? Well, the Captain, if he's good, doesn't fucking trust you. So you're basically fucked. The idea of a "Protag role" is to have a role that is held to a higher standard than the crew, than the antags, than anyone. They are held to a higher standard in this one regard: They must reside somewhere on the spectrum of 'good'. And make no mistake, they should be held to an EXTREMELY HIGH STANDARD OF PLAY. Because these roles, like their antag counterparts, are absolutely OP compared to normal crew, and some should be considered OP even compared to other antags. Not Wizards though... There's very little that's more OP than a wizard.

Every round should have atleast one protag, if not multiple. Their goals will all be different than antags in that instead of being told "Do this, get that, kill him." They will be told, depending on what protag they roll, how they should act in any given situation. Basically like Laws for the AI. An example

"Always render aid to those in need, even if an antag you are chasing is able to escape."

"You are the Captain's body guard. Guard him at all times." 

"Seek out evildoers and bring them to justice."

Things of that nature.

Now... not all protags need be "Goody Goody". Some protags can work 'against the station' and be given goals such as disarming the nuke, thereby rendering it useless. Or securing the disc and spare ID for themselves (If no Captain is at round start), to be hidden or destroyed at their leisure. 

Or perhaps even a total vigilante, doling out justice as they see fit, SO LONG AS IT IS INDEED JUSTICE, and not just "Hurr I r man with gun hurr". 

There could even be midround protags. Let's say the Captain joins up midround: Bam, throw a professional body guard right ontop of him at the shuttle, armed to the teeth, with almost as much access as the captain has. Captain secured.

Here is a list of possible Protag roles:
---------------------------------------------------
Batman/Owlman: This is one that is already in the game (I think). Anyhow, Owlman can spawn in at any population, I'd say. He'd work just as well with 50 players as he would with 10. He specializes in non-lethal knockouts. That means CQC/Martials arts. His punch should pack a whallop with a 10 percent chance of one hit KOing you, his grabs should basically be like the Chef's: If he grabs you, you're fucked. He is also able to break out of any hold with absolute ease. He is also given boomerangs which can be fired from a wrist gun which is unable to be dropped or removed from his persons, but he can unequip it, of course. ( the reason for it being a gun is because throwing shit is a fucking pain in the ass. It really is. Sometimes it throws, sometimes it doesnt, sometimes it fucking wants you to stop moving to throw the thing. Fuck throwing.) The boomerangs would be absolutely devilish, with a 20-30 percent chance of either disarming the target, disabling a random limb, or knocking them down, and doing a moderate bit of stun dmg and a very small amount of real dmg. He should have about ten of them loaded up at round start.

That was his offensive capability, his defensive is much better. Equipped with incredibly sturdy armor capable of withstanding any source of damage, from acid, to toxin to explosion, the man should be a walking tank. Also, very quick on his feet. He should never be able to be slipped, because that's just fucking retarded, but if he is knocked down at any time, he will get back onto his feet almost instantly due to being an agile mother fucker. He would also have very good stealth capability in darkness, able to vanish entirely when in darkness, and stay invisible for about 3-6 seconds even if a light source does pass over him. He should also be given a "pounce" ability. Allowing him to lunge forward every, say, 10 seconds. Allowing him to close the distance or flee with ease. When he has taken a moderate amount of damage, this ability should be disabled. Because, of course, he is just a man.

His utilities would be as follows: An incredibly high tech forensic scanner which tells you EXACTLY who's print you're looking at. No need to search medical records. It'll tell you who's blood you've just scanned. Now... as for fibers... well, I don't think it should be an instant identification. That'd be a bit OP, yes? There should still be a fair bit of detective work involved. But basically, this man would be a hellhound of Justice. You know how the crew fear certain antags? Like, dear god, Changelings give me the willies. Mute toxin is powerful. Well, antags should fear this man like crew fear them.  He'd also have a fair few cuffs which go on in a fraction of a second. Special cuffs that only respond to his DNA. (To be very, very clear... I think a majority of the equipment given to the Protags should have safeguards preventing their use by anyone else.) Also, a built in health scanner so he can know when to stop knocking the shit out of the guy he's apprehending. 

What this role would basically do is make antags much, much more careful. Any slip up, any fuck up, any wrong move and this man will be on their ass, beating their god damned brains in and dropping them off at security to be summarily executed by the captain. Only in the ABSOLUTE MOST DIRE OF SITUATIONS should the Owlman take it upon himself to deliver ultimate justice upon his enemies. 

He would be vigilante class, which means that he is outside of the law, and is not expected to cooperate with security, and vice versa. His motives/goals would most likely just be "Stop evil doers, kick ass, try not to just fucking murder the guy who's ass you're kicking." 
--------------------------------------
Solido Snaku

This role would primarily be concerned with the nuclear disc and either disarming the nuke or securing it somehow. He would be a true neutral protag. He is not expected to actively seek out antags, nor is he expected to render aid to anyone. His own survival is his number one priority. Once again, this man would be a master of CQC, able to break limbs like celery sticks, break out of holds almost instantly (Even other CQC holds, which should be a special attribute only of his. If Snake restrained Batman, Batman would have a hard time breaking out of the hold.) He would come equipped with  2 guns: A very powerful m1911 and a multi shot tranq gun. He would also have a decent supply of ammunition for both of them. The tranq gun should be quite strong, and should be a two shot KO with mediocre fire rate. Let's say 1 shot every 1.2 seconds and with 7 tranqs in the clip. His m1911 should function exactly the same as the current in-game version, but maybe with slightly better damage and a chance to stagger or something like that.. also, armor piercing bullets wouldn't hurt at all, I'd say, especially against Nukies.  This would make him want to favor his tranq, as it's more ammo efficient. But he should then be given the stipulation that he cannot kill anyone he has KO'd via CQC or tranq gun. Further more, he shouldn't be allowed to loop hole it... Like waiting for the guy to wake up then killing him. 

His defensive capabilities would be as followed: Where as Batman has supremely good armor, Snake should have supremely good regen. His stealth suit automatically applies pressure to any wounds he takes, almost instantly stopping all but the most severe of bleeding. Further more, due to his supreme willpower, very little slows him down. Even when he's right on the cusp of crit, he should still be moving at almost full speed. And when he is in crit, he doesn't go down. He's still god damned fighting you. A true American hero.... Invented by a Japanese man. Figure that. Anyhow, his suit would also provide him with camo. The AI cannot lock onto his location, borgs have a hard time seeing him (If he stands still for a 2 seconds, bam he's gone from borg eyes). He can also crawl under tables and instantly enter lockers just by moving onto them. He can PHASE through lockers. Ontop of that, when he's standing still he cannot be seen by human personnel unless they are within a certain range of him... Let's say a 2x2 square around him. When he's moving, he cannot be seen except by people in a 4x4 square of him. Now, I'm just pulling those numbers out of my ass, they can be changed as seen fit, but that should be his stealth mechanic. Of course, when in darkness, these numbers are lowered. If he's standing still in darkness, you need to be just about right ontop of him to see him... and by then it's probably too late. Also, he has a natural resistance to any type of tranq. Even if he does get knocked out via chemical or otherwise, it lasts for about 4 seconds, then he's immediately up. The drug will still make him a bit groggy and slow him down, but he'll still be combat capable.

Utilities: Decoys: He can set decoys that look just like him, and have the same stealth qualities as he has (Proximity, etc). These decoys will have a variety of functions: One may explode into a cloud of smoke if attacked or disarmed, one may explode into a sleeping gas cloud (Not an instant KO, but if you're quick on your feet and jump out of the cloud ASAP you'll still have taken pretty bad stamina dmg. Good for crowd control.), one that just fucking shocks the shit out of you (in a small radius. Let's say 2x2 shock explosion) and KOs everyone except the most healthy of individual. I'm talkin' eating your greens and drinking your milk every day sorta healthy. He will also have cardboard boxes which serve, basically, as portable lockers. When set, they will look like a normal locker or crate, but unlike lockers or crates they will be able to move when someone is "buckled" to them. Also, a set of binocs. Always bring your fucking binocs. Where are your binocs? Why don't you have your binocs? He also comes with, let's say, 3 grenades and 2 c4. 

His motives and playstyle would be: Never be seen, tranq anyone who sees you and tries to pursue you. Yes, this will put crew at harm, but when you see a man in a skin tight stealth suit, you oughta turn around and go the other way. If you chase after this man, you deserve whatever may happen to you if he tranqs you, cause he's not gonna babysit your body. He's gonna leave you there, asleep.  The only antags he is ABSOLUTELY OBLIGATED TO FIGHT... are Nuke Operatives. If Nuke Operatives are on the station and he hasn't already done his primary objective of disarming the nuke, well now he's in a bit of a pickle and he'd better just kill the fuck out of the nukies, or die trying.

His protag class would be "specialist". Not related to law and order, not expected to  dole out justice... He has one VERY specific thing that he does, and it involves the nuke and killing nukies. Now, that's not ALL he has to do. He can do whatever he wants, but unlike some of the other protags he isn't EXPECTED to anything other than that. And he only REALLY, ABSOLUTELY -NEEDS- to disarm the nuke if the Captain does something stupid like request nuke codes for no good reason or if he hears rumors of nukies.

(A quick aside: To elaborate on the standards involved in these roles, none of them should ever act shitty. Their one liners should never be "LOL GET FUCKED NOOB". Even the way they talk should be put under scrutiny. A certain level of humilty and humbleness should be expected. If a protag ever says "Lol u so salty, get wrecked." INSTANT FUCKING JOB BAN FROM THE WHOLE PROTAG SPECTRUM, RIGHT THEN AND THERE.)

--------------------------

The Vigilante: Based on the popular and very gorey comic book of the same name, this man is... literally... nothing more than a man in a skimask with a gun, BUT WITH A BURNING, RAGING DESIRE TO DELIVER INSTANT, BLOODY JUSTICE ON THOSE DEEMED UNFIT TO FUNCTION IN SOCIETY... Judge, Jury and Executioner. Here is a supplementary image to give you an idea of what this role would be like: https://static.comicvine.com/uploads/scale_small/0/4/26008-3208-28892-1-vigilante-the.jpg

This role would probably be given the most leeway of any of the protag roles. (Oh, most of these protag roles should have some sort of "base". Snake wouldn't have one. But the Owlman, when he spawns, a trap door should appear SOMEWHERE in maint... There could be, like, 20 or so different locations that it COULD appear, so people don't just go "I'm gonna go fuck up Batman's house." Anyway, the trapdoor would appear, and it would lead to a different z-level, and he would be inside his base already. He could suit up, drink some coffee, whatever, then leave his base, take note of where it is... perhaps put a small object somewhere nearby so he could remember easily where it is, then get to justice. The base would have some commodities... very good food that makes him super healthy, security monitoring... I dunno... A giant Penny or something? You know, just some fun sorta easter egg type shit but some of it would have functionality.) His base would just be a shitty little room in the maintenance somewhere. It would have basically nothing of real interest... The only plus it would have is that only HE can open that door. He could take people there, interrogate them, knock them around, a bit of light torture... all that good stuff. Anyway, the leeway he would have is that.. while he should try his best to make certain that the man he's working over in his secret base with a blowtorch and a set of pliers really is a bad guy, he can never be totally certain. So when he pulls the trigger and blows them away, if he just killed an innocent... well, that's just how it is. He made a mistake... Now, if he piles up too many of these mistakes, either during a single round or in general, he should be given a warning. But let's face it... he could probably fire his gun into a crowd of Hippie crew and hit atleast 5 different 'criminals'. Generally, most of the crew are out committing crimes rampantly. So, really if he kills a random guy that he just grabs at random and drags into maint, he's got, like, an 80 percent chance of killing a criminal. Something like that. And that's what he's all about. Real fucking justice. The Vigilante should be a very special protag in that he has a dual personality. Where as the Owlman should PROBABLY -just- be Owlman, and Snake should ABSOLUTELY just be Snake, the Vigilante should be a normal member of the crew. The Lawyer, The Chef, The Curator, The Chaplain, etc, etc. The only difference is that his ID is automatically given maint access, and he doesn't spawn in his workplace, but instead in his shitty little base. Anyway, enough of that preamble. ONTO THE GUNS. 

The Vigilante will spawn with a small stockpile of guns. 1 assault rifle, a big fucking magnum, a silenced handgun and something less lethal like a really fucking heavy telescopic baton, or a god damned... I dunno, a hammer to smash people's kneecaps with. Pfft. Something like that.  He also comes with a mask with goggles (It'd be an accessory, the goggles. The mask would just be a normal balaclava. The goggles are what matters. They'd stop flashes and pepper spray.) He wouldn't have CQC, surprising, I know. But his punches would do slightly more damage, with a slightly higher chance at knocking down. Oh, OH!! Great idea... Give him a pair of special gloves that increase his melee damage. That'd work, yeah. 

Anyway, other than his goggles and his guns, he literally has nothing else but his wits to keep him alive. 

His goals would be something along the line of: "You absolutely hate criminals. Distribute justice as you see fit." 

This means that if he sees a man breaking into Eva, he could, absolutely, 100 percent just gun the man down right then and there. Bang, bang, dead. That's honestly up to him. But once he becomes a criminal, he's in a pickle. He's not allowed to just murder sec. That's his only big 'no-no'. He can return fire if sec are chasing after him, but any shots fired at ACTUAL SEC (not just someone who has taken a sec ID) will always do minimal dmg, and will always be aimed at non-vital points. That should be a thing coded in. He has no choice but to disengage from sec... It doesn't matter if the security is crooked, shitty or not. Security is security to him. He should never kill them. But they can definitely kill him... Which is why he'll try to keep a low profile. Will he just gun down the man breaking into Eva? He could... he definitely could.. But is it worth it? 

-----------------------------------

So far we've seen all stealthy characters, haven't we? These people should mostly be out of the spotlight, hrm? Batman would most likely be navigating the maintenance (Ah, small note about Batman protag... full access. The antags have no where to hide. -WINK-), and that should probably be a stipulation of his... It'd be a bit stupid to run into Batman multiple times in the halls, so his preferred mode of travel should be maint.  Snake would be constantly hiding, observing... The Vigilante would be in the same sorta thing as Batman. When he's not doing his normal job, he's in the maint, lurking, looking for wrong doers, occasionally stalking the halls with his mask off, ready to pop it on, take off his ID and plug some lead into people. All of them are stealthy sort of indivdiuals, I would say..

Now let's see one that would be less so stealthy:
--------------------------
The Wandering Samurai:

The Samurai would follow a bastardized version of the Bushido code... now, I have no idea what that code entails. I just googled it and read a bit, but I'm on a bit of a roll with this so I'm not gonna stop and comprehend what it's all about. Anyway, we'll grab the Bushido code, take what we need from it and bam, that's the Samurai's goals. 

The Samurai would be a master of martial arts, completely unable to be disarmed or pushed down, with a NINETY PERCENT MELEE PARRY CHANCE, OH MY FUCKING GODDDDDDDDDDDDDDDDDDDDD. Further more, everytime he blocks a melee attack (which is EVERY FUCKING TIME), he immediately counter attacks for half his normal unarmed damaged... And his unarmed strikes would be fucking devastating, able to cripple a man, armored or no, with ease. Let's say inbetween 7 and 10 brute, but do extra damage to limbs. So 15 damage to limbs. Further more, his disarms aren't 'disarms', they're fucking 'breakarms'. If he disarms someone while targetting a limb, he'll do absurd amounts of damage to that limb... most likely snapping it clean in half with 3 or 4 disarms in a row. Wham, bam, thank you ma'am. His regular attacks, however, while doing tons of damage, will also have a chance to proc a special move... Now, the moves could be totally random, or he could have an option in his preferences which would allow him to pick which moves he would prefer to occur. The moves would be a legsweep, an eye gouge (temporary blindness... permanent if it procs multiple times), a throat punch (absurd oxy damage) and some other shit... maybe putting whoever he's hitting into an aggressive grab. 

And that's not even getting to his sword...   His sword is honed to a razor's sharpness, capable of slicing through flesh and bone cleanly and easily. He can lop an arm off in a single attack... Not to mention a head. And that's about it. He's a total badass but his Bushido code should be somewhat rigorous..

Such as never attacking an unarmed man with your sword... Things of that nature.

Ah, also, no-slip.

He has no reason to lurk in the maintenance. He'd most likely be hanging out in the Chapel and trying to get the Chaplain to let him convert it into his dojo... 

Now, there could be a whole system for what happens if he is able to get a dojo... Like, if he's in his dojo he has a good chance to block ranged attacks, thing of that nature. But that's a whole 'nother kettle of fish. I'm basically done detailing the Samurai.
---------------------------------------------------------------------------
Whew, I think I've been at this for about an hour... or more... I didn't even get to my "Power Rangers" idea, but that's basically just ERT anyway.

SO... I honestly and truly do believe this would give something new and fresh to the server, as well as giving people who honestly want to protect and serve the station a way to do so. Cause let's face it, half the fucking time security is just getting totally and absolutely fucked in the ass by butterdogs. (Ah shit, just thought of a security specific protag: Robocop.)

It would make antags play a little more carefully, it would make greytiders a little more afraid of being total fucking assholes... It would allow the Captain to breathe a little bit easier... (Speaking of which, I didn't get to my Captain's Bodyguard idea either.)

It's fine if you wish to have a server filled with chaos, where-in the crew rip each other apart for the sport of it... but for the love of God, balance that Chaos... I truly believe these protag roles are a necessity to balance out the amount of chaos inherent in the server. 

People would still greytide, shitty people would still be shitty to other people, etc, etc, etc, but now there would be a bit of Super-Human repercussion... And make no mistake, these protags (excluding the Vigilante) are basically Super-Humans. And I really do believe we need a Super-Human presence to properly function in the depths of chaos known as Hippie Station.

Thank you for taking the time to read this through to the end, if you have done so, and I truly hope to be working with you in the future to create a variety of interesting and fun protagonist roles.

--------Amiable Ferinian

@HippieStation/maintainers

**Comment by Eagle-Eyess** [comment]
I don’t like this idea. The point of the civilians is that... well they are civilians. If we add in protagonists with that plus any security personnel that might happen to be on how will antagonists accomplish anything? The point of making antags strong with their items is that it will allow them to get some kills here and there but if the crew team up there’s no possible way any antag could kill them all at the same time. antags already die too fast to all of the crew (most times) and adding these will make it even easier. -1

**Comment by ghost** [comment]
i think this idea is shit tbh -1, antagonists barely do shit anyways, this will only serve to have a few people play god mode around. people already behave as protagonists ingame

**Comment by ghost** [comment]
I like the idea of owl man spawning once every 50th round or so.

**Comment by LingeringProfanity** [comment]
Eagle-Eyesss, I have addressed the reason why protag roles are necessary in the text above.

Zamolxius, that's a bold faced lie. Hardly anyone acts as 'protagonists'. The amount of people who act that way are the minority. Further more.... God mode? Isn't that what antags are in the first place? You're telling me that playing wizard isn't playing 'god mode'?

You have absolutely no argument except that you're afraid of change.

**Comment by DaydreamPuppeh** [comment]
I like owlman, but I don't think the other protags should exist.

**Comment by LingeringProfanity** [comment]
Daydream, what about a "Captain's Bodyguard" protag? Someone's whos sole job is protecting the Captain?

**Comment by praisenarsie** [comment]
i need to write a copypasta explaining to stomp down anyone who suggests protagonists.

also captain's bodyguard is not a "protagonist" that's a literal job, nothing about that screams main character or whatever.

**Comment by ghost** [comment]
yeah...  this kind of idea belongs more on naruto byond games than space station 13. lol uber mega strong protagonist role guys!  so strong. 
also,  keep in mind that if its protagonists and crew vs antags,  antags need to be buffed

**Comment by LingeringProfanity** [comment]
"Protag roles" aren't "main characters". That's not what it's all about.

Further more, antags are already plenty buffed. Dear God, Changelings basically have an infinite ammo gun. Wizards can one hit ko anyone they want, and teleport through time and space. Syndies have access to more equipment than anyone on the station. Cultists are... well, I've seen people literally just lay down on runes and be converted. 

This rounds back to the whole premise of the text: The crew doesn't act like protagonists. They're generally disorganized and chaotic and killing each other.. Thus having these roles would actually work. It wouldn't work on other stations, where the crew works together to defeat antags. But on Hippie it'd be fine.

**Comment by ghost** [comment]
-1, autistic idea that wouldnt do any good

**Comment by LingeringProfanity** [comment]
Thank you for the constructive criticism, Zamolxius.  You're welcome to stop commenting now if you have nothing of actual value to add.

**Comment by ghost** [comment]
oh thanks for underlining an obvious fact out of defensiveness,  I'll be sure to take your feedback to heart and include it in my next opinion. 
its a shit idea which would only serve to make 1 maybe 2 spergs way better than every single man on the station willing to protect home and country from the antag scum.  people do try to get antags but its also fun to do other shit,  be it chaotic or not.  what would incentivise getting antags would be some OOC benefit or just add crew objectives for extra shit to do as nonantag.  -1 shit idea

**Comment by LingeringProfanity** [comment]
You keep repeating yourself. You keep bitching about how it'll make "maybe one or two people better than everyone else on station durrrrr"... Well, we already have that, it's called the fucking antags.

I honestly do not understand why you are so opposed to it other than you must have a deep seated discontentment with -something-.

Either make an actual argument against it or move on. The argument you pose now is flawed and not very good. Perhaps it is you who is filled with 'shit ideas', and not myself.

**Comment by ghost** [comment]
For "captain's bodyguard", that's pretty much the Blueshield on Oracle/Paradise, often called the Blueshit IC for obvious reasons.

**Comment by ghost** [comment]
"But on Hippie, a majority of the crew are absolute pieces of shit, total fucking assholes who would happily sabotague the station, security, the command staff, medbay, etcetera"
this is false,  you are disconnected from the common man if you think that is a problem.  the hippie station has different objectives from a tg station or a yog station,  just them behaving differently and being more abrasive and challenging is not being a piece of shit.  you should try playing as one of the plebeians,  an assistant there,  a clown there. i only see you as detective or head of personnel,  so it's a pretty solid reason for you to seek to gain new roles which help you boss over people without being challenged by the masses as is usual on the hippie station. 

"The number of crew who actually PLAY AS PROTAGS, who actually want to help their crew mates and crush antag balls is INCREDIBLY SLIM. Incredibly slim."
you know,  being a protagonist doesn't mean just fighting the antags all the time.  this is not DOTA or some other game,  there's supposed to be some mystery,  the "who's the alien" thing.  just because people don't prioritize what you do doesn't mean they aren't protags.  

I'd honestly say the whole cause of this idea would be solved by there being more security players, as they're the designated antag hunters.  Or HoS/captain I guess.  if you play one of these and don't do your duty,  don't expect people not starting to take justice into their own hands. 

"This rounds back to the whole premise of the text: The crew doesn't act like protagonists. They're generally disorganized and chaotic and killing each other.. Thus having these roles would actually work. It wouldn't work on other stations, where the crew works together to defeat antags. But on Hippie it'd be fine"
again,  the crew is a heterogene mass with wildly varying desires, they'll only band together if there's a clear threat.  now,  there must be some kind of security force that's supposed to work in teams and run down the antags... 

as flux said,  this may work with a small chance of appearance, but not every single round.  all in all,  buffing, shilling  or incentivising security would have better results for all of us,  as this one would just be one lone protag fighting the antag and, if he wins,  shuttle gets called.  that's it,  round over. meanwhile,  a sizeable security team polarizes that aforementioned heterogene mass of grayshits that populate the hallways,  against them,  and add a purpose to the game  sticking it to the man.  haven't seen that since when we were regularly highpop though.  not to say that security forces the antags to be furtive and play along the scope of the game.  changelings are stunnable like anybody else,  and recent nerfs made them not able to regenerate.  they're pansies compared to before,  even with the flesh cannon (which costs an amazing 4 points and which takes more than 5 bullets to crit IIRC).

**Comment by JohnGinnane** [comment]
@zamolxius hit the nail on the head

I'd also like to highlight that the crew isn't the "protagonist", they're the crew. It's security's job to maintain peace, which includes finding and fighting antags

Also, the station has often banded together again antags, most obvious being when nukies declare war and someone decides to order guns or open armoury

**Comment by LingeringProfanity** [comment]
Zamol, I dunno what Hippie Station you're playing on, but saying that people are just 'abrasive' is total rot. I just died because some faggot shit named Johnathan Clemens decided it would be funny to drug me and cuff me and then try to grief me. He wasn't even antag. Supposedly he was healing me while he was strangling me to death in a maint, so says admin. I ended up being dragged to safety when a paramedic ran in and hit him with a brick in response to my yelling. Unfortunately I was so drugged I couldn't move, was cuffed so I couldn't do anything, was muted from the drugs, and left laying in the medbay entrance. Then a ling decided to drag me into maint and kill me. 

Johnathan then went on to kidnap another person during the round and keep them in a locker in chemistry.

You say 'abrasive', but I have to wonder how disconnected YOU are from what is actually happening in the game.

Once again, no one plays security because of power gamers like Johnathan. And I don't blame them. 

Once again I ask you, why are you so opposed to protagonist roles.

Also, let me ask you this, do you prefer to play antagonist? I bet you do.

**Comment by ghost** [comment]
"zamolxius, I dunno what Hippie Station you're playing on, but saying that people are just 'abrasive' is total rot. I just died because some faggot shit named Johnathan Clemens decided it would be funny to drug me and cuff me and then try to grief me. He wasn't even antag. Supposedly he was healing me while he was strangling me to death in a maint, so says admin. I ended up being dragged to safety when a paramedic ran in and hit him with a brick in response to my yelling. Unfortunately I was so drugged I couldn't move, was cuffed so I couldn't do anything, was muted from the drugs, and left laying in the medbay entrance. Then a ling decided to drag me into maint and kill me."

so you're saying the protagonist will act as some kind of superpowered security that will let you not be beaten by those mean bullies who've drugged you and cuffed you in maint? 
 
is this a ban request or an issue?  sounds like classic happening on a space junk death trap,  deal with it.  learn from your mistakes to evade them next time. 

if a nonantag do shit just ahelp,  no need to seek to compensate by begging coders to make a special strong boy role just for you

"Johnathan then went on to kidnap another person during the round and keep them in a locker in chemistry."

again,  ahelp.  you send them to god,  he sorts them out


"You say 'abrasive', but I have to wonder how disconnected YOU are from what is actually happening in the game." =(no u) 

i mostly play as the lower folk,  the masses.  assistants,  janitors, clowns, bartenders.  i know how they tick,  im not some newbie who immediately plays exclusively head of personnel and detective to seize power hint hint

"Once again, no one plays security because of power gamers like Johnathan. And I don't blame them."

power gamers like that tend to act as security if there's none.  if you join roundstart and prevent them from arming up as usual you can win over them.  it's about teamwork.  if on an individual level he's stronger and more prepared than you,  on a team level it doesn't matter that much. 
also,  nobody plays security because you get major lip from admins if you arrest shitters,  IIRC,  and its pretty stressful. 


"Once again I ask you, why are you so opposed to protagonist roles."
they are just redundant in the current game,  and your motives for suggesting it seem to be highly based on your subjective feelings rather than thinking on the long term

"Also, let me ask you this, do you prefer to play antagonist? I bet you do."
i actually prefer to do shitty gimmicks such as spraying bright green muck on all the windows of the station then get valided for it



if we really needed security and the command chain really being present,  we could add a minimum personnel requirement for the round to start,  something like the captain,  the head of security,  and chief engineer. no need for snowflakey "protagonists" so big bad johnny clements won't cuff you and drug you in maint.  next time ahelp, or seize your fate in your own hands and actually work for something

**Comment by LingeringProfanity** [comment]
So, you're saying you literally are just a grey tider... So the actual reason you're so opposed to this is because it would hinder your ability to grey tide. Very curious.

**Comment by Kierany9** [comment]
this is literally why i made jesus a thing minus the powergay that these guys have

**Comment by ghost** [comment]
yeah,  jesus is a good kind of protagonist,  not a superpowered validhunter

"So, you're saying you literally are just a grey tider... So the actual reason you're so opposed to this is because it would hinder your ability to grey tide. Very curious."

no,  you can read up there what I'm saying. dont try to strawman my opinion,  man,  i actually support security more than greytidery,  just not the kind of security i often see you play,  joining up as head roles and expecting authority on a silver platter,  then you come here to demand protagonists as an equalizer


weak attempt to strawman,  no argument left,  I see. 


"So, you're saying you literally are just a pleb with a boner for authority and protagonism... So the actual reason you're so inclined to this suggestion is because it would improve your ability to dunk people and not get dunked by a guy with a bottle of water. Very curious."
