### ISSUE TITLE
Stuck on round start screen

### ISSUE THREAD

**Issue by robloxgothgf** [HippieStation/HippieStationdeprecated2020#8914]
Issue reported from  Round ID: 31133 (Hippie Station)

Reporting client version: 512
already tried relogging restarted byond all that fun stuff and still cant see anything and cannot play. 
https://gyazo.com/878d68c8fb256f81f0e7ae4acfb9bf5c

**Comment by AnthonyJNgo** [comment]
I've seen you in-game since this time, assuming it was a client issue.
