### ISSUE TITLE
[SUGG] Re-add omnilathe to RnD

### ISSUE THREAD

**Issue by WarRage333** [HippieStation/HippieStationdeprecated2020#8919]
[Title]: # Re-add omnilathe to RnD

[Implementation]: # Add the omnilathe back to reserach

[Why]: # Okay so now that RD's locker removed firing pins, can we have omnilathe back in science. Biggest fear of it was people were gonna print guns in science!!!, but now that's gone and you need to break into armory for those or order in cargo and break open crates. Anyone want to to say nay to and explain why a place that researchs things does not get to create them

[Resources]: # I'm not sure if any of the old computers remain in the code but the board for it should still be in the code, if the computers are removed just make the omnilathe craftable / spawned in RD's locker

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by ghost** [comment]
yeah man

**Comment by ghost** [comment]
+1

**Comment by Carbonhell** [comment]
Accepted, #8925
