### ISSUE TITLE
The Nanite Cloud Controller "Upload Program From Disk" button does nothing.

### ISSUE THREAD

**Issue by maxphillipsdev** [HippieStation/HippieStationdeprecated2020#8932]
Issue reported from  Round ID: 31153 (Hippie Station)

Reporting client version: 512

When clicking the button, it plays a selection sound and that's it. Doesn't add the program disk to the backup making the cloud sync aspect of nanites basically useless sadly.

**Comment by GuyonBroadway** [comment]
fixed allready
