### ISSUE TITLE
Throwing sounds

### ISSUE THREAD

**Issue by Carbonhell** [HippieStation/HippieStationdeprecated2020#8945]
[Title]: # Your feature needs to have a good title. If you want an object added, the object's name would be a good title, and such. Use common sense.

[Implementation]: Play some sound when you throw items. Pretty easy to do.

[Why]: More sounds is always better.

[Resources]: Attached to the feature request
[oggs.zip](https://github.com/HippieStation/HippieStation/files/2348419/oggs.zip)
Shit,i forgot to say the sounds are from Admiral Hippie. Sorry.

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by JohnGinnane** [comment]
\>more sounds
yes pls

**Comment by GuyonBroadway** [comment]
Look into specthrowsound added by items with throwforce multipliers like the kanada hockey stick (may or may not be broken)

**Comment by ghost** [comment]
+1

**Comment by Eagle-Eyess** [comment]
+1 good issue

**Comment by HippieBartels** [comment]
+1

**Comment by Carbonhell** [comment]
Accepted

**Comment by Jujumatic** [comment]
implemented
