### ISSUE TITLE
Can wear forge created weapons as gloves

### ISSUE THREAD

**Issue by Eagle-Eyess** [HippieStation/HippieStationdeprecated2020#8957]
[Round ID]: 31175
[Reproduction]: make a forge weapon. put it in glove slot.

**Comment by WarRage333** [comment]
Weapons to surpass metal gear

**Comment by ghost** [comment]
i mean, i can also put a holotool there

**Comment by ProtozoaPrime** [comment]
Just confirmed the bug in game, looks like you can also wear them on the suit slot, although the icon sprite vanishes when worn on the suit slot, although is magically still there - seems **very** buggy, will have a gheeze at this code asap.
