### ISSUE TITLE
Cant put holotool on belt or backpack after switching to tool

### ISSUE THREAD

**Issue by Eagle-Eyess** [HippieStation/HippieStationdeprecated2020#8960]
[Round ID]: 31182
[Reproduction]: use the holotool as a tool. try and put it in belt or back pack. will say that its stuck to your hand even tho you can drop it and such

**Comment by ghost** [comment]
I really need to refactor the holotool to use `screwdriver_act` and related procs

Remind me this weekend.

**Comment by Carbonhell** [comment]
@steamp0rt are you doing this?

**Comment by ghost** [comment]
Fixed by #9027
