### ISSUE TITLE
Can't make mummification bandages with cloth and egyptian staff in hand or on ground

### ISSUE THREAD

**Issue by challade** [HippieStation/HippieStationdeprecated2020#8961]
I attempted to make mummification bandages, but I get (Construction failed, missing tool.). The option is there, blue, and my immersion is ruined.

**Comment by Eagle-Eyess** [comment]
You have to place both items on a table. I know for a fact this works (unless it broke like the past 3 days) since someone had the same problem was able to craft them after they did just that.

**Comment by HippieBartels** [comment]
I fixed this yesterday. Had to do with nullrods being modularized and the recipe tools not being updated

**Comment by Carbonhell** [comment]
Ay thx, next time you can just add
Fixes #issuenum 
to fix the issue automatically when the PR is merged
