### ISSUE TITLE
Using tts while drunk means you slur the phoneme commands so you can't use em.

### ISSUE THREAD

**Issue by GuyonBroadway** [HippieStation/HippieStationdeprecated2020#8995]
title.

[:dv br 4000 pr 10 ap 10 as 2000] Benis 

becomes

[':dvv...huuuhhh...brr 4000 pr 111000 ap 10 ahs 222000] Benis

**Comment by ghost** [comment]
+1

**Comment by GuyonBroadway** [comment]
Its not a suggestion you boat-for-a-brain! Its a legit bug report.

**Comment by Manly-Dwarf** [comment]
yes please
that way my ears don't get raped

**Comment by Carbonhell** [comment]
i'd sat that you do not have good control of your speech while smashed drunk tbh

**Comment by JohnGinnane** [comment]
nah carbon, people can sing when they're drunk. Might be tricky to correct/replace phonemes after message has been treated

**Comment by AnthonyJNgo** [comment]
TTS is broken right now so this is no longer an issue.
