### ISSUE TITLE
[SUGG] Rework the RD's energy holotool to use the nifty new radial menu system

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#9003]
[Title]: # Rework the RD's energy holotool to use the nifty new radial menu system

[Implementation]:  Rework the RD's energy holotool to use the nifty new radial menu system

[Why]: Would make it way more worth it to use the holotool

[Resources]: none needed

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers 
@steamp0rt

**Comment by Eagle-Eyess** [comment]
It will still suck but +1

**Comment by ghost** [comment]
yeah sure whatever i'll do it when i refactor it tomorrow

**Comment by ghost** [comment]
+1

**Comment by HippieBartels** [comment]
+1

**Comment by GuyonBroadway** [comment]
this actually got added.
