### ISSUE TITLE
Firetrucks

### ISSUE THREAD

**Issue by Carbonhell** [HippieStation/HippieStationdeprecated2020#9031]
[Implementation]: A firetruck vehicle for atmos techs to spray reagents easily, could start loaded up with water. Maybe use minigun mechanics to keep spraying liquids. For balance purposes, make a reagent whitelist(water,nanofrost?)

[Why]: memes
could also give atmos tech more toys and love

[Resources]: No resource sadly

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by Carbonhell** [comment]
i'm sorry i cannot wait for this to be accepted,must do it now

**Comment by HippieBartels** [comment]
Hell yes but definitely needs a whitelist, first thing people would do is fill it with lube

**Comment by Eagle-Eyess** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by bardofrage** [comment]
+1 firetrucks NOW

**Comment by bubberducky2** [comment]
SPEEDMERGE :+1:

**Comment by ghost** [comment]
inb4 citadel ports but its cumtrucks
