### ISSUE TITLE
Forge floor tiles are broken textures

### ISSUE THREAD

**Issue by WarRage333** [HippieStation/HippieStationdeprecated2020#9034]
Issue reported from  Round ID: 31287 (Hippie Station)

https://i.imgur.com/tgMQhgO.png

oof

Reporting client version: 512

**Comment by Eagle-Eyess** [comment]
There’s already the same issue open I believe

**Comment by WarRage333** [comment]
Probably 

#8974

**Comment by Carbonhell** [comment]
8974 is unrelated to this
