### ISSUE TITLE
Vampire Bugs

### ISSUE THREAD

**Issue by fluffe9911** [HippieStation/HippieStationdeprecated2020#9036]
Here are two bugs with vampires that I know of at the moment

1. If you are forced out of vampire bat form you become immortal
To reproduce: become a vampire bat then have someone kill the bat (or smite the bat) when you pop out you will be immune to all damage

2. Vampire Objectives Dont Appear in the Traitor Panel
To reproduce: Pretty straight forward go to the player/traitor panel and make someone a vampire you will be unable to see or modify any vampire objectives they may or may not have

**Comment by Carbonhell** [comment]
@steamp0rt

**Comment by Carbonhell** [comment]
1 is fixed in #8996 
2 needs to be fixed i believe

**Comment by AnthonyJNgo** [comment]
This is not an issue anymore, 1 is fixed in #8996, and 2 is fixed.
