### ISSUE TITLE
Make it so colors dont fuck up antag signs

### ISSUE THREAD

**Issue by Eagle-Eyess** [HippieStation/HippieStationdeprecated2020#9039]
[Title]: different colors shouldnt recolor antag symbols

[Why]: make it easier to see who is on your team and stuff
![image](https://user-images.githubusercontent.com/36767768/45267502-b3f44380-b43b-11e8-8a1d-0e77ed2434ec.png)

**Comment by Eagle-Eyess** [comment]
I guess this is a feature?

**Comment by Carbonhell** [comment]
Might be hard to fix due to how coloring works.

**Comment by AnthonyJNgo** [comment]
Blood in and blood out, blood.
