### ISSUE TITLE
Conveyor Belt next to cargo for the garbage compactor

### ISSUE THREAD

**Issue by CarlCarbon** [HippieStation/HippieStationdeprecated2020#9041]
Issue reported from  Round ID: 31293 (Hippie Station)

Reporting client version: 512

The conveyorbelt in the garbage compactor has its corner pieces inverted preventing material from going down the belt. It is the two corners immediately after the recycler.

**Comment by AnthonyJNgo** [comment]
This is a ridiculously easy fix if it is not done already
