### ISSUE TITLE
Lasers instantly travelling

### ISSUE THREAD

**Issue by MiniMeatwad** [HippieStation/HippieStationdeprecated2020#9058]
[Implementation]: emitters would be a constant stream of laser instead of a laser projectile burst that fires periodically, lasers and pulse lasers and other laser stuff would travel instantly instead of being a projectile that can be dodged

[Why]: i don't think in a game that's trying to be realistic that people can dodge LASERS. it's literally light, so unless spacemen are actually gods or some sort of horrible bluespace experiments, i don't see them realistically dodging lasers. other than that, it'd make combat way less spray and pray with lasers, because you can't dodge lasers unlike projectiles. ( also why can people dodge projectiles so easily anyways? bullets should travel faster too )

[Resources]: /VG/ station has it, their laser guns and emitters and other stuff like that fire lasers instead of projectiles

@HippieStation/maintainers

**Comment by GuyonBroadway** [comment]
>Hitscan weapons.

What the fuck is this? Baystation or something?

**Comment by MiniMeatwad** [comment]
don't know a good way to respond to that, it doesn't seem to have good implications towards the feature request though.

**Comment by Carbonhell** [comment]
I'm really unsure about this.

**Comment by GuyonBroadway** [comment]
Bay has hitscan lasers and its cancer. Sec are impossible to fight.

**Comment by ghost** [comment]
seems like shit,  maybe add a special laser that has hitscan?  maybe.  or screwdriver a laser to shoot a hitscan and 255 tile range laser with 25 damage,  for all the charge?

**Comment by MiniMeatwad** [comment]
can i get some examples, guyonbroadway?

**Comment by GuyonBroadway** [comment]
Literally baystations laser guns. I'd dig up a video but I have none to hand but needless to say unless baysec misses via rng hit detection you lose good day sir.

**Comment by Eagle-Eyess** [comment]
-1 seems waaaayyu too over powered

**Comment by HippieBartels** [comment]
-1 I don't like this at all..

**Comment by ghost** [comment]
-1

**Comment by MiniMeatwad** [comment]
i played on /vg/ quite a bit and i never had any issues with the laser guns, it may be bay code but it isn't bay station automatically, meaning it can be modified to choosing and it could be turned into a special weapon of its own kind that's far weaker than normal but is hitscan, and the laser doesn't exactly have to be super strong, don't know why you guys all don't like change like this, mind explaining?

**Comment by Carbonhell** [comment]
@fluxcapacitor1337 @HippieBartels explain

**Comment by AnthonyJNgo** [comment]
-1, instant hit stuns are the last thing we need

**Comment by danhibiki** [comment]
Realism doesn’t coincide with balance

**Comment by AnthonyJNgo** [comment]
"unless spacemen are actually gods or some sort of horrible bluespace experiments"

Our spacemen are godly bluespace experiments :smug:
