### ISSUE TITLE
Remove fireball auto-aim

### ISSUE THREAD

**Issue by MiniMeatwad** [HippieStation/HippieStationdeprecated2020#9059]
[Implementation]: make it so that the wizard spell fireball doesn't automatically hit people adjacent to it, preventing the wizard from shooting down a 3 tile wide hallway and killing anyone in it, or killing them self because of auto-aim blowing the wizard up even though the wizard aimed for someone else, this should also prevent the fireball blowing up people on the ground the wizard didn't even aim at.

[Why]: why would you want wizard auto-aim fireballs?

@HippieStation/maintainers

**Comment by ghost** [comment]
i ded pls nerf
this hasn't any significant beneficial effect to the game tbh

**Comment by Carbonhell** [comment]
Fuck this shit, remove
+1

**Comment by Eagle-Eyess** [comment]
Yea fireball needs a nerf... not that it’s too op but it’s just not fun and has no skill to it. +1

**Comment by ghost** [comment]
+1

**Comment by WarRage333** [comment]
yes

getting hit by a fireball means death, its bullshit when its not going into the same tile and hits you 

+1

**Comment by AnthonyJNgo** [comment]
+1 fireball should be removed

**Comment by AnthonyJNgo** [comment]
This really failed to gain any meaningful votes, and has had no comments for half a year. Closing.
