### ISSUE TITLE
The wizard’s “mutate” spell doesn’t work

### ISSUE THREAD

**Issue by ExpAntique** [HippieStation/HippieStationdeprecated2020#9072]
When you use the spell, nothing happens.

 How to reproduce: become a wizard, learn mutate, and try to cast it.

**Comment by Manly-Dwarf** [comment]
Tested this bug. As a human, Mutate works just fine.
If you were playing as a golem or some other alien race, they aren't compatible with Hulk and its effects and therefore it won't work.
Golemwizards are cancer any way.
