### ISSUE TITLE
Assistant only traitor item for 20 TC [Feature]

### ISSUE THREAD

**Issue by bubberducky2** [HippieStation/HippieStationdeprecated2020#9085]
[Title]: Assistant only traitor item for 20 TC

[Implementation]: It's a traitor item that benefits the assistant only, My idea is that the item costs 20 TC and is revealed to be some extremely insulated gloves that store the power from wires and APC's and uses it as electricity to combat against other people.

[Why]: The greytider shirt is boring and i feel like the assistant should have an item that allows him to rip wires apart for power and drain out APC's, more on his abillities later.

[Resources]: coding and respriting the original insuls to have an electric glow and arc around them for the assistant one

More on the Why and Implementation section, The assistant could use the gloves to store either a small or medium amount of power and use it against people when it's full, it's like the Ninja Gloves but more combat/sabotage focused and has the greytiding spirit in it, Halves the damage when the victim is wearing insuls and completly stops it when he's wearing a hardsuit along with insuls.

He could also use it to charge weapons, stunbatons and other dubious items that use electricity to charge, at the cost of a cooldown and unabillity to use his gloves.

**Comment by bubberducky2** [comment]
i forgot to mention to make it unremovable aswell without insul protection because that shit will shock you due to the immense power it holds

**Comment by ghost** [comment]
make it work at range and shoot tesla bolts. multiple functions,  maximum power stuns more and burns,  ashes you if you already have maximum burn damage/are husked?  medium power stuns a bit,  tesla bolts applies the nice skeleton shock overlay and burns you,  lowest power is just a ranged frying bolt of tesla.  can absorb batteries for power?  1 highcap= 2 uses,  1 battery=0.5 uses,  anything more can be overcharged to function as a temporary energy field projector and either make a forcefield thing or shoot lighting bolts at people in range like a trap (your call)?  costs like 5 power or something

**Comment by bubberducky2** [comment]
ye fam sounds good, like a nanosuit power ability selection yes? just use shocking modes to vary between either small zaps or Mike Pence Mode

**Comment by ghost** [comment]
also make it automatically drains any weapon that uses electricity which you hold  in your hand because it works like that,  if it seems tot OP

**Comment by bubberducky2** [comment]
user could either make it so he drains the weapons or he charges them at will, but if you want remove the charging part and just zucc the weapons's power off of the sec

**Comment by ghost** [comment]
yeah it could work off a Suck or Fill setting,  fill works as said earlier,  suck EMPs shit and takes their power,  works on people.  changing mode requires taking the gloves off and fiddling with a screwdriver

**Comment by bubberducky2** [comment]
just fiddle with the gloves with a screw inhand instead, it should be nodrop to prevent clowns snatching it and zapping themselves to death due to their sillyness

**Comment by Eagle-Eyess** [comment]
+1 but only if the charging ability of weapons is removed. That’s way too powerful to have all it one item.

**Comment by ghost** [comment]
i meant it syphons the weapons cell to empty it whenever you hold a weapon,  as a disadvantage and it maybe also gains power usage

**Comment by fen0s** [comment]
one suggestion - on full charge, you can release emp which will disable all electricity around, including borgs, sec energy weapons, and other electric things

**Comment by ExpAntique** [comment]
I will only +1 if it looks like this:
![image](https://user-images.githubusercontent.com/37980640/45653865-72047680-baa7-11e8-949c-9b6d6791793b.png)

**Comment by Eagle-Eyess** [comment]
isnt there already like the powerglove that can use wires to shock people? if so -1 too similar. if not +1 but should really be for engineers not assistants...

**Comment by AnthonyJNgo** [comment]
Stale.
