### ISSUE TITLE
you can superfart in a clown car

### ISSUE THREAD

**Issue by praisenarsie** [HippieStation/HippieStationdeprecated2020#9131]
![https://i.imgur.com/Dyze0CW.png](https://i.imgur.com/Dyze0CW.png)

3 superfarts is enough to crit/kill people

fun fact this also kills the driver

**Comment by Koffheatalt** [comment]
this makes the clown car almost fucking useless if people just know they can all superfart to kill the driver

**Comment by GuyonBroadway** [comment]
This goes for lockers, disposal loops and so on...

**Comment by ghost** [comment]
we have to remove this immediately, maybe make it so if you superfart you get thrown the fuck out without causing damage to anyone but yourself

**Comment by ExpAntique** [comment]
+1 to what flux said

"holy shit, your ass blast sends you flying out of the trunk!"

make them get thrown out at max speed and only stop flying when they hit a wall, that way people can't just abuse to try and escape the clown car

**Comment by GuyonBroadway** [comment]
Do you have any idea the kind of snowflakey shitcode we would need to make a special check just for specifically superfarting in the clown car?

**Comment by Carbonhell** [comment]
...?
if(isturf(loc)) return

**Comment by GuyonBroadway** [comment]
Not to do what flux wanted it to do it won't.

**Comment by Eagle-Eyess** [comment]
why is this labeled feature? isnt it a bug +1 tho

**Comment by praisenarsie** [comment]
((joke))

**Comment by AnthonyJNgo** [comment]
This is a hilarious feature.
