### ISSUE TITLE
Head roles have to be randomized characters every round

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#9135]
[Implementation]: # Randomize the characters of head roles every round.

[Why]: # Will enhance gameplay.

[Resources]: # N/A

**Comment by yobob591** [comment]
+1000

**Comment by Carbonhell** [comment]
-1

**Comment by Manly-Dwarf** [comment]
+1
Personally I'm more against snowflake Captains. Random bodies are pretty strange, but I don't see any reason as to allow snowflake players their glory as Captain. No more Camilles or Lisa Greens, please. Neon-haired female nerd heads need to piss off. I'd prefer a gender ban over a total identity ban though.

**Comment by ExpAntique** [comment]
+1 if you include captain

**Comment by ghost** [comment]
captains,  security personnel and engineers must only be human males as only they have the grit,  respectively intelligence (male and human) to be efficient in their roles

**Comment by Eagle-Eyess** [comment]
-1 rather not deny people the they character that they like over killing off snowflake characters.

**Comment by lolmemelord123** [comment]
-1
