### ISSUE TITLE
Removal of the moth race

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#9136]
[Implementation]: # We remove the moth race.

[Why]: # Will improve gameplay/atmosphere.

**Comment by JohnGinnane** [comment]
why

**Comment by Manly-Dwarf** [comment]
+1

**Comment by Eagle-Eyess** [comment]
why

**Comment by biggiOS** [comment]
no -1 we need more races that we can alienate gas and burn on a stake

**Comment by ExpAntique** [comment]
+1

**Comment by AnthonyJNgo** [comment]
-1 need to know who I should kill first as antag, moths are usually unrobust

**Comment by ghost** [comment]
-1 until you give a better reason

**Comment by TrickyDickRichard** [comment]
+1488 killem all

**Comment by ghost** [comment]
nah just make them dizzy around lamps or lights

**Comment by AnthonyJNgo** [comment]
Stale and not approved.
