### ISSUE TITLE
Randomize ERT Appearances

### ISSUE THREAD

**Issue by craigbean** [HippieStation/HippieStationdeprecated2020#9169]
Make it so whoever spawns in as ERT has a randomized appearance. There was a ling round, ERT was sent in after 11 minutes, and one ERT member decided to run around without a hard suit, despite their station character being called out as a ling. They never spoke up about it until after it was figured out, so it'd be great not to repeat that meta bullshit.

**Comment by Eagle-Eyess** [comment]
-1 doesnt seem like a huge problem. cant ert see who other members are anyway with hud glasses?

**Comment by ghost** [comment]
+1
