### ISSUE TITLE
Feature request: New traitor uplink item

### ISSUE THREAD

**Issue by lolmemelord123** [HippieStation/HippieStationdeprecated2020#9182]
[Title]: new traitor uplink item 

[Implementation]: xeno egg, i think its fair to set the price to idk  25tc?

[Why]: because alien rounds only happen if a miner/admin get/spawn a egg and anyways i think the constant action of a xeno infection is fun,when its low pop it could get annoying so i think it will be a good  idea to set this item to 20+ people

[Resources]: use the ingame xeno egg sprite

**Comment by WarRage333** [comment]
25 tc same as romerol tbh

**Comment by bubberducky2** [comment]
make it 25 TC requring traitor cooperation or extreme surplus crate luck

**Comment by lolmemelord123** [comment]
eh sounds good?

**Comment by Eagle-Eyess** [comment]
until xenons get a rework and are more balanced i cannot say i like this. -1

**Comment by Carbonhell** [comment]
I remember the queen being stupidly op, if it was not fixed then -1 for the time being.

**Comment by ghost** [comment]
-1

**Comment by GuyonBroadway** [comment]
The queen isn't "Op" they are slow but have powerful defensive abilities like the AoE tail swipe that throws people away from them.

Not OP compared to other xenos anyway, xenos in general are balanced around being a once a moth adminbus special.
