### ISSUE TITLE
Ass penguins

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#9184]
_The ass penguin, or Aptenodytes forsteri rectum, is quite a strange creature, mainly due to it's infamous reproductive method, which many say is even worse than that of the xenomorph. The only similarity of the ass penguin's reproductive cycle to any other penguin is that it hatches from an egg. Even the egg is strange, however. It is first vomited into the rectum of a human (or primate) after being attacked and incapacitated by an ass penguin that has reached sexual maturity. After the egg is inserted, the penguin spits up a rapidly hardening resin, which keeps the egg in place, and prevents large bouts of flatulence from possibly detaching the rectum from the body, or the egg from the rectum. Once the egg hatches, the newly born ass penguin feeds on nutrients from the intestines of the host, before causing extremely severe pain, often described as "living hell" and "AGGHGHHHH I WANNA DIE" by victims, causing incapacitation in 99.99% of victims, and unconsciousness in 45.73% of them. After this occurs, the ass penguin chick uses built up gases in the rectum and large intestine in order to explosively launch itself out of the anus, where it will quickly flee, grow up, and repeat the cycle._

@HippieStation/maintainers

**Comment by Manly-Dwarf** [comment]
This is some fucked up shit.

I can't tell if I'm disturbed on every possible level of humanity, or if I love it.

**Comment by ghost** [comment]
This is actually based on an event I did as trialmin once.

**Comment by Carbonhell** [comment]
What the fuck
Suggestions were a mistake

**Comment by Shdorsh** [comment]
*Trialmins. Yes, indeed.

**Comment by ghost** [comment]
inappropriate

**Comment by lolmemelord123** [comment]
-1

**Comment by ghost** [comment]
`This is actually based on an event I did as trialmin once.`
making me gag here

**Comment by Eagle-Eyess** [comment]
-1. if you want to try and get this feature accepted try paradise

**Comment by Shdorsh** [comment]
-1 After dildo PRs this, what's next? Are you folks going to turn it into a summoning ritual or something?

**Comment by ghost** [comment]
+1

**Comment by GuyonBroadway** [comment]
Ok two points.

1: You are not of any rank that your +1 means anything.
2: You cannot +1 your own suggestion.

**Comment by Carbonhell** [comment]
-1, denied

**Comment by ghost** [comment]
+10

**Comment by ghost** [comment]
plz reopen

**Comment by DaydreamPuppeh** [comment]
Amari what the fuck

**Comment by ghost** [comment]
can we reopen this

**Comment by WarRage333** [comment]
Yes please

**Comment by ghost** [comment]
How do I delete PRs
