### ISSUE TITLE
Fix Clown Car Eject

### ISSUE THREAD

**Issue by craigbean** [HippieStation/HippieStationdeprecated2020#9193]
Issue reported from  Round ID: 31582 (Hippie Station)

Reporting client version: 512

The clown car eject button, at least for me, doesn't work. Gravity, no gravity, floor or no floor, nothing happens. I usually have to crash to get out. If it was designed like this as a joke, it's more frustrating than anything else. The passengers (aka everyone I abduct) can eject just fine. Resisting also doesn't seem to do anything.

**Comment by GuyonBroadway** [comment]
Fix is here.

https://github.com/HippieStation/HippieStation/pull/9306
