### ISSUE TITLE
Security Officers can roll Gang Boss

### ISSUE THREAD

**Issue by Manly-Dwarf** [HippieStation/HippieStationdeprecated2020#9195]
[Round ID]: # 31583

[Testmerges]: # We have testmerges?

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)
It seems like the bug was caused by the Gang Boss selecting someone who was currently still in the Lobby. Checking antags before he had spawned showed the leader of the Zero G gang having no name, no body, and listed as (DEAD). The moment he joined in as a Security Officer, he was made into a gang boss.
![rip](https://user-images.githubusercontent.com/33744849/45910936-6a144180-bddb-11e8-8f95-e9ce984413af.png)
If that's not the case, then I have no idea what caused it.

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)
Don't be a tool and remove their gangboss status. Encourage them to meme it up.

**Comment by Carbonhell** [comment]
https://github.com/HippieStation/HippieStation/blob/master/hippiestation/code/game/gamemodes/gangs/gangs.dm#L46
Try to add in this line a special role for the user, this could be causing the bug. Also might be wise to remove the set waitfor from post setup, just check other gamemodes
