### ISSUE TITLE
Thanos car.

### ISSUE THREAD

**Issue by GuyonBroadway** [HippieStation/HippieStationdeprecated2020#9199]
![image](https://user-images.githubusercontent.com/22083966/45919536-bbc9d400-be8e-11e8-8969-3ca153adedae.png)

Modified clown car but instead of trapping people on bump is has a %50 chance to teleport them somewhere safe (like swarmer teleport) or disintegrate them.

Probably adminbus only.

**Comment by Manly-Dwarf** [comment]
We could toss this in with the Infinity Gauntlet if someone wants to sprite it.

**Comment by ghost** [comment]
traitor item +1

**Comment by Eagle-Eyess** [comment]
+1

**Comment by ghost** [comment]
make it the thanoscopter and i'm in

![](https://assets.change.org/photos/2/uy/ip/YIUYiPuKbnihszx-1600x900-noPad.jpg?1525736592)

**Comment by AnthonyJNgo** [comment]
Stale.
