### ISSUE TITLE
[SUGG] port fat sprites

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#9259]
[Title]: add back fat sprites

[Implementation]: # distended belly only visible when topless

[Why]: # How does your feature improve the game anyhow? its fat sprites

[Resources]: # Eventual assets such as icons and sounds which you have and want to suggest related to this feature.
 should be in old hippie, but it'd be trivial to make a larger torso appear when the player is fat and has his jumpsuit unbuttoned and left hanging ala engineer or assistant jumpsuit,  or just naked 
# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by Eagle-Eyess** [comment]
+1
