### ISSUE TITLE
Tesla needs to be removed for a bit

### ISSUE THREAD

**Issue by Zyzarda** [HippieStation/HippieStationdeprecated2020#9275]
Every time the Tesla goes loose, it ends up hanging a bunch of stuff and generally needs to be deleted as quickly as possible before it breaks the server entirely. Can we replace it with the singularity until this can be diagnosed and fixed?

**Comment by bubberducky2** [comment]
sorry no anime

**Comment by Dinopeaks** [comment]
how is it breaking the server entirely?

**Comment by WarRage333** [comment]
You can feel the lag as soon lord thor escapes captivity much like the old lord singuloth would slow the server to a crawl

**Comment by Zyzarda** [comment]
Things blow up and then hang, resulting in a permanent explosion that doesn't ever move or go away. Bits of the tesla stop moving and instagib anything that go near them. The server lags heavily to the point where its unplayable.

**Comment by Manly-Dwarf** [comment]
The Tesla can fucking clone its self.
Why?

**Comment by Eagle-Eyess** [comment]
I don’t want to straight up remove it though

**Comment by bubberducky2** [comment]
probably because of the 50 explosions every second it teleports

**Comment by Iamgoofball** [comment]
In specific, its the lights from explosions.

Just revert the PR that added lighting to explosions, we figured this out at /tg/.

**Comment by Carbonhell** [comment]
There is already a PR up to fix this, it was caused by the orbit component pr most likely
