### ISSUE TITLE
["SUGGESTION"] [DONGCODE] Holy Flamethrower: Remove Changeling, Vampires and Shadowling from rotation until they are overhauled

### ISSUE THREAD

**Issue by Manly-Dwarf** [HippieStation/HippieStationdeprecated2020#9277]
[Title]: # Your feature needs to have a good title. If you want an object added, the object's name would be a good title, and such. Use common sense.
Holy Flamethrower (a witty name for what is otherwise just removing features)
Here you go, Yoyobatty.

[Implementation]: # How should the feature work out? What exactly is it supposed to do, in your initial idea? If an item, can it be crafted/found/bought and for what?
Go to config
Changeling 0% chance to happen
Vampire 0% chance to happen
Shadowling 0% chance to happen
Also add Chaos Mode later on where they can pop up again I guess

[Why]: # How does your feature improve the game anyhow? Why should it be added?
These three gamemodes are all widely agreed to be terrible.
If you aren't in the know, here's why. Changeling is obviously going to be much bigger and more in depth as some people here are against removing it, for whatever reason.
# Vampire
[Video 1](https://youtu.be/yE5alNvrkYM)
[Video 2](https://youtu.be/ofYeaDkAneM)

It's literally just Changelings but without the tools that make you overpowered and a thousand times longer. It would be more excusable as a fucking mid-round antagonist, which is what it used to be.

# Shadowling
![rekt](https://i.imgur.com/tvuBXkv.png)

Shadowling suffers from similar problems to Vampire and Changeling, it's insanely annoying, not very fun to play as or against, has a lot of sitting around and doing nothing, shuttle recalls, and so on. I don't think there's a single player who really enjoys Shadowling in its current state besides Toof. Thankfully, steamport said he had plans on remaking both Vampire and Shadowling, which could result in them becoming much better gamemodes. But for now, they both suck, and have no reason to be in rotation as nobody wants to develop for them in their current state.

# Changeling
Possibly the most controversial antagonist currently on Hippiestation, there's a pretty strong divide on those who like Changeling and those who despise it. I'm going to try to run down four arguments people make in favor of Changeling and explain why Changeling doesn't work and needs removal.

### Argument #1: Stealth is great if executed well! We just need Tiers back to stop the murderbone!
Actually, no. Tiers didn't do much to stop the murderbone in original Changeling, and Changeling was never stealthy - even with tiers. You still charged at people in the open and stunned, cuffed, and mutestung. Tiers only delayed the process until you could get adrenals and all the other overpowered shit that make Changeling a nightmare to deal with. Stealth is a meme on hippiestation as of now due to zero roleplay, no vision cones, no Security, barely anyone caring about screams for help over the radio, and so on. If anything,
### Counterargument: Changeling's design right now only encourages murderbone.
Everyone on the current staff and coder team has come to hate murderbone. It makes our population decline, it makes rounds drag out, people get salty, and murderboners usually are the type of people who make admin complaints when you spawn ERT to kill their asses in one go. Which is strange, because Changeling is literally murderbone: the antag. Right now, Arm Blade and other weapons are way too powerful and are better than Traitor's variant of the weapon due to Changeling being undetectable, Changeling's objectives encourage killing an arbitrary number of people instead of other kinds of objectives - further encouraging murderbone, and Changeling has really easy methods of getting around the only means to kill it (before it was nerfed, at least). As a result, you're some hyper overpowered antagonist who has the ability to run around killing everyone with utmost ease, and your objectives blatantly tell you to do so.
The nerfs I made to Changeling, i.e removing regenerate, did a little bit to fix the murderbone since some players are now a bit more cautious before charging into battle. But as a whole it still encourages killing the entire server, and you can still do it very easily.

### Argument #2: Changeling is an interesting antagonist that's been around since our old days! Removing it would be erasing SS13 history!
That didn't stop us from making huge changes to Cult, Wizard, hell even Traitor in some regards, removing Malf AI and making it simply Traitor AI, and so on. Changeling has weirdly been stuck in the past where its original design has barely been updated and has only gotten worse thanks to the feature creep, and lack of roleplay.
Also, what exactly is interesting about changeling besides...
### Counterargument: The only interesting thing about Changeling is that it's traitor-but-better
Think of every single ability Changeling has.
Revive from Death: better cloning.
Stings: better syringes/parapen
Transform: Better camo suit
Armblade: Better esword
Hivemind Commune: better syndicate radio
Absorption: Better means of taking people out of the round
Last Resort: Better microbomb implant
Acid Vomit Thing: Better Freedom Implant
Etc. Literally all Changeling boils down to right now is "Traitor but better" hence why murderbone is so easy to do with it.

### Argument #3: You're just mad!
![smug_high-res](https://user-images.githubusercontent.com/33744849/46114485-dec2f380-c1c0-11e8-96c0-340925b558d9.png)
### Counterargument: The nerfs I made to changeling barely did anything
I'll admit that it was a shitty PR. It didn't actually fix the core issues with Changeling, it just made Changeling worse and therefore boring. It went from being unfun to fight against and killing the whole server every time to being unfun to fight against and to play as. I would have no issues reverting the PR, but that would require keeping changeling around.

### Argument #4: Just add hivemind!
A common thing people want to do with ling is adding hivemind. It's as if Changeling, in its current state right now, will be massively improved if Hivemind was added. Outside of the fact that this would do nothing but make changeling even better, it brings up that
### Counterargument: Nobody wants to develop for Changeling
Changeling gets barely any new content added to it at all. In fact barely anyone wants to develop anything for Changeling besides Xhuis' nerfs over on /tg/, which I think says a lot. If nobody wants to develop the gamemode, and it's controversial due to its quality, then why do we still have it in rotation? There's no point in keeping it here until we get that whole rework idea done, which evidently a lot of people seem to like.
[Resources]: # Eventual assets such as icons and sounds which you have and want to suggest related to this feature.
Just use the config.

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by Eagle-Eyess** [comment]
-1 this removes three rounds from the 8/9 (is clockcult actually back?) rounds there are. That’s about a third of the game modes. Idc if they shitty right now leave them in to fix them no reason to remove them...

**Comment by Manly-Dwarf** [comment]
@Eagle-Eyess That's an understandable position, but Steamport is already making another gamemode right now. It wouldn't be long before we had more.

**Comment by ghost** [comment]
agreeing with eagle-eyes here...

**Comment by DaydreamPuppeh** [comment]
-1. We need the variety badly

**Comment by Manly-Dwarf** [comment]
angery
aight fine let's give it a shot. But shitty gamemodes need fixing!
