### ISSUE TITLE
Gateway missions

### ISSUE THREAD

**Issue by Caxxo1** [HippieStation/HippieStationdeprecated2020#9324]
Bring back gate way missions you ffffffffffffffffffffffffffffffffffffucks

**Comment by Eagle-Eyess** [comment]
pretty sure we got rid of them because everyone would just leave the station and it be annoying for the antags of that round and stuff. basically the whole crew would be miners

**Comment by yobob591** [comment]
we got rid of them also due to the immense lag

**Comment by AnthonyJNgo** [comment]
Stale, and being done already iirc.
