### ISSUE TITLE
Remove the foam vent event thing because it lags the hell out of everything and also delaminates the supermatter really not cool guys

### ISSUE THREAD

**Issue by Zyzarda** [HippieStation/HippieStationdeprecated2020#9326]
[Round ID]: # (If you discovered this issue from playing HippieStation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**)
[Round ID]: # (It can be found in the Status panel or retrieved from https://tools.hippiestation.com/stats/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by Manly-Dwarf** [comment]
GOOFCODE

**Comment by GuyonBroadway** [comment]
I get there is a bug but please write a proper fucking error report, this helps nobody.

**Comment by praisenarsie** [comment]
it's pretty descriptive if you ask me.

goof didn't factor in chemicals spewing in the SME room and some of those chemicals can turn into gases (assuming) or it will damage the SME in some form or another.

**Comment by GuyonBroadway** [comment]
See nobody explained that the foam shit can flood the supermatter chamber.

**Comment by bubberducky2** [comment]
nobody bothered to know that this can but rarerly flood the SM room full of plasma or C02 thanks to chemistry, and the cockroaches slamming into it isn't helping either
