### ISSUE TITLE
Make food cost money again,  but less.  

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#9340]
[Title]: #Make Junk food cost money again 

[Implementation]: Make junk food cost money again,  not 25 like before,  but from 2 to 10$ varying by healthiness.  cheesie honkers are cheap,  fourno raisins are five/7 bucks?  give money a purpose. the more tactfully integrated the money system is,  the better it is and more well balanced,  not the tg way

[Why]: # How does your feature improve the game anyhow? Why should it be added?

[Resources]: # Eventual assets such as icons and sounds which you have and want to suggest related to this feature.

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by Eagle-Eyess** [comment]
my only problem with this is that the snack foods arent very good. i feel if we gate them behind money they should get a buff as well. only a small one

**Comment by ghost** [comment]
add like one tick worth of bicaridine to them, or kelotane and leave the price decently expensive.  carbonhells cheap cuisine is like 2 bucks,  of course.  and add more trashy but cheap food that's got bad shit inside

**Comment by MrWankman** [comment]
That is overdoing it i think. Just set useless junk food to 2 bucks or something as said. Nothing that is only for aesthetic fun out to be that expensive really if you don't want the money to just be another thing people want gone after a time.

**Comment by AnthonyJNgo** [comment]
Economy revamp fixes this.
