### ISSUE TITLE
botany is completely bugged from the economics update

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#9379]
Issue reported from  Round ID: 31874 (Hippie Station)

Reporting client version: 512

seeds cost money and the vendor doesnt detect ID

**Comment by GuyonBroadway** [comment]
The botany vendor has been bugged for a while. Imma just revert it later.

**Comment by Carbonhell** [comment]
I merged a fix today, can anyone confirm if this still happens?

**Comment by Iamgoofball** [comment]
Did you guys properly set the department on the botany job to be Service? That'd be the cause of this.

**Comment by Manly-Dwarf** [comment]
It's not "bugged", you just need an ID in hand.

**Comment by Iamgoofball** [comment]
Oh, yeah, I see. ID cards are supposed to work from the ID slot.

This is the ID card thing, there's a bug upstream and a fix PR already made.

**Comment by MrWankman** [comment]
For a bit of clarity I'll add that while playing with my download of the game I found that only ID's that come with legitimately spawned players can access venders as only spawning like that will give that ID card an associated account for money. Even the Captain's spare doesn't have an associated account so it can't even access venders. Also yes, the ID must be in your ID slot and not in your hand.

**Comment by MrWankman** [comment]
Actually I'm finding sometimes you have to have it in your hand or the machine won't read the card so this is just confused now. Oh well.

**Comment by Iamgoofball** [comment]
Yeah, there's a bug with where the game checks for your ID. We tried to expand it to check ID/PDA/Hand/Offhand in that order, but for some reason it only checks active hand and gives up. There's a bugfix upstream.

**Comment by WarRage333** [comment]
Fixed
