### ISSUE TITLE
You can warp in turf/wall via pool ladders and z-level travel [Bug]

### ISSUE THREAD

**Issue by bubberducky2** [HippieStation/HippieStationdeprecated2020#9390]
This is a bug that i've found while fucking around on my own hippiecode server, it's a mild one but hey, can't hurt to fix shit right?

[Round ID]: Not on a Hippiestation round, but on a server with 2018 up to date Hippiestation code

[Testmerges]: None

[Reproduction]: Spawn a pool ladder and then any wall of your choosing, then click on the pool ladder to warp to the inside of the wall.

Same for z-levels, you just suddenly warp into another z-level regardless if there's any obstructions, such as a wall or other things.

[For Admins]: No var editing was done.

**Comment by Supermichael777** [comment]
can players move or construct pool ladders?

**Comment by bubberducky2** [comment]
no but they can fortify around the pool and make it so it's a 1 way only door in a sense
