### ISSUE TITLE
Enable Halloween races. 

### ISSUE THREAD

**Issue by robloxgothgf** [HippieStation/HippieStationdeprecated2020#9394]
[Implementation]: # Enable them for a good October vibe. 

[Why]: # It is the month where things become spooky. 

[Resources]: # species_types, everything is there.

**Comment by MrWankman** [comment]
Maybe either for the month, week or even just the day of Halloween, make our spookyskeletons have all the traits of the normal /tg/ skeletons so it encourages the niggers to be skeletons for Halloween. Make Hippie Spooky Again?

**Comment by robloxgothgf** [comment]
bump

**Comment by Eagle-Eyess** [comment]
i feel like it should be for a week so ill +1

**Comment by Carbonhell** [comment]
Outdated
