### ISSUE TITLE
Suggestion: Make admin heal more obvious

### ISSUE THREAD

**Issue by ExpAntique** [HippieStation/HippieStationdeprecated2020#9432]
[Title]: # Make admin-heal more obvious

[Implementation]: # When someone gets healed by an admin through the player panel, make a holy sound play (like the sound effect when someone's prayer is answered) and make a message show up for everyone nearby (something like: "[name] was healed by divine intervention!") and maybe like a beam of light on them or something. 

[Why]: # because there's a huge problem that's been around giving admins panic attacks where someone is healed after a situation is resolved, and they are immediately beaten down because passersby think they're a changeling or some shit.

[Resources]: # The sound effect that plays when you receive the best cookie could be used for this.

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by ghost** [comment]
very good

**Comment by bubberducky2** [comment]
very good

**Comment by ghost** [comment]
ok done

**Comment by Eagle-Eyess** [comment]
+1
