### ISSUE TITLE
More Access to Facehuggers for Xenobiology

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#9442]
[Title]: # More Access to Facehuggers for Xenobiology

[Implementation]: # There are several ways to accomplish this. I will list the two that come to mind.

### Add facehuggers to the gold slime's creature pool (which would involve first making facehuggers a creature, or just writing some bootleg workaround to get them to spawn).

This would mean that facehuggers can't be made at roundstart, so if shit goes south at least the station will be somewhat prepared. It would also require a modicum of effort on the part of the xenobiologist, since those alien organs *are* pretty strong and *need* to get worked for.

### Create an item to sterilize and desterilize facehuggers.

The item should probably be near the end of the research trees (and/or unlocked with alien technology) so, again, Mr. Xenobio can't make an alien breakout or give himself superpowers within 10 minutes of round start. This will also mean that xenos can only be scienced upon (legally) with the RD's permission, thus in turn meaning that there's some sort of safety check in place.

An alternative is to add some sort of functionality to high-tier slime serums to de/sterilise the critters in addition to their other stuff. Again, the 'time and effort' costs would make this balanced and the part with the RD still stands.

### What next?

Add slime serum functionality to make intelligent pet xenos, give more functions for xeno organs, and just about anything else that can be thought of and coded in. # The possibilities are endless!

[Why]: # Xenobiology needs more ways to get *true* xenobiology going in order to farm those sweet alien organs, as well as to give traitor scientists a few more options. Currently facehuggers almost never come up on lavaland and are most often just killed on sight by miners, and xeno rounds are far and few between, so a xenobiologist looking for some 'spicier' stuff to do is shit out of luck. Also, bio hoods stop facehuggers so a xenobio who remembers his biosuit shouldn't be that much of a threat.

[Resources]: # The sterilisation item probably need a sprite or something, shouldn't be too hard to make.

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by MrWankman** [comment]
I like anything that makes xenobio more fun but I wonder since we no longer have restricted science ID accesses and only just Scientist/Roboticist/RD then how would the RD keep a scientist from moving the tech tree to where he wants? Unless there's some ID access to certain tech tree stuff I'm not aware of I think the thing with RD is hopeful at best and anyone who's willing to go through the effort can get most anything on hippiestation anyways and I don't see that as an issue anyways myself.

**Comment by ghost** [comment]
@MrWankman The only sterilized facehugger on the station is in the RD's office, and he'll generally try to get back at anyone who breaks in and steals his shit. In addition to that, if it's a late tech tree unlock (or an advanced slime potion effect) it'll take at least 20-30 mins to get, not counting other resource costs. This will a) give the station time to prepare in case shit does go south and b) the RD will have more time to hunt down the heathen who stole Lamarr. That's what I meant by 'safety check'

Also the other scientists will probably notice the xenobio building towards the facehugger tools if it is implemented through the tech tree and thus will be able to act accordingly. That is just my line of reasoning for why it'd be relatively difficult to stealthily powergame your way into a xeno outbreak.

**Comment by MrWankman** [comment]
From what I have seen with the tech tree, it don't seem to take long to get anything that you don't have to wait on mining for resources for. Also in how you described the system, you wouldn't need Lamarr. As for the tech tree thing I'll have to check again myself but I was pretty sure that we don't have to worry about farming research points to get to the ends of branches.

**Comment by MrWankman** [comment]
Yeah, it looks like from what I'm seeing in the science tree that only a few minutes on hippie and you can rush any single branch to the end really.

**Comment by ghost** [comment]
In order to desterilise a facehugger, you need a facehugger to desterilise. The only one there is in the RD's office, which makes it relatively difficult to get, keep, sterilize, 'implement' and get xenos without raising any alarms.

The research tree thing can always be countered by locking it off behind Ayy Tech, while the potion option requires you to do quite a bit of xenobio in order to get the potion you need. Imo, it sounds pretty balanced at first glance to me.

**Comment by MrWankman** [comment]
I am saying this taking your system into account, not as things currently are. Like if you add the ability to get a headcrab with slimes then like I said Lamarr is pointless. I'm not saying this system shouldn't be in I'm just saying safety protocols like "The RD will guard it" is optimistic on hippie is all.

**Comment by ghost** [comment]
The slimes thing is probably never going to happen, since that would require insane amounts of workarounds or reworks. The reason? Facehuggers are technically 'items', not mobs. This makes it *really hard* to actually get them to spawn with the gold slime without, again, layers upon layers of reworks. So yeah, probably never going to happen.

About Lamarr - this part is there more to give a certain clue to the rest of the station that maybe Mr. Xenobio is up to something. I'm not saying the RD will guard Lamarr, but they will at least notice a broken (or opened) display case. This also goes for any scientists who decide to walk past the hallway - a broken window into the RD office, a missing Lamarr and (possibly) a walled-off and welded shut Xenobiology wing would be dead giveaways that Mr. Xenobio maybe isn't a model citizen. In short: there needs to be a way for at least someone to know that xenos are being made without needing to enter xenobio, and making Lamarr a necessary step of the process helps that

**Comment by MrWankman** [comment]
Suppose the only clue there really is xeno being walled off. Beyond that detail it could just be a memer who wants to make people annoyed or salty by stepping on Lamarr unwillingly or even just a more amuzing way to stun and do naughty things to them.

**Comment by ghost** [comment]
Fair enough. 

On the other hand, it's an issue which is something along the lines of "the guy breaking into the vault probably just wanted the credits and not the core", and scientists will probably still check out possible hideouts for signs of 'advanced' xenobiology just in case it *wasn't* some random chucklefuck.

Also gives Lamarr a use, and uses for unconventional objects are always lovely.

**Comment by MrWankman** [comment]
Funnily enough I think most non nuke ops who do break into vault only just meme cargo's budget or want the few goodies in the vault that are not lethal to the station.

**Comment by MrWankman** [comment]
Or they want the banhammer toy lol
