### ISSUE TITLE
Add packaged survival meals

### ISSUE THREAD

**Issue by ExpAntique** [HippieStation/HippieStationdeprecated2020#9463]
[Title]: # Add packaged survival meals

[Implementation]: # A new food that can't be cooked, and can only be acquired by buying it from cargo, admin spawn, or the survival storage of those lavaland shelters. It will have a shitload of nutrition, like a super bite burger, and a little bit of omnizine like donk pockets

[Why]: # would be a good item to have for events and they would be useful for a station that has no cook and is in a state of disaster, as the only foods that are already available on the station are donuts and donk-pockets, which provide almost no nutrition.

[Resources]: # they could look like this: https://rimworldwiki.com/wiki/Packaged_survival_meal

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by ghost** [comment]
make it a box like donuts containing disgusting/bland tasting waxy blocks of foam/dope

**Comment by Eagle-Eyess** [comment]
i dont know about adding omnizine to it. the nutrition is fine though

**Comment by Maroonenahmoron** [comment]
I mean it’s not hard to buy some pizzas from cargo and put them into a blender, even find a chemmaster and cram it into pills/patches.

**Comment by AnthonyJNgo** [comment]
We should give miners more food options but -1 this as it would quickly be a powergame item.
