### ISSUE TITLE
Elite Hardsuit Sprite freaks out on the End Round screen?

### ISSUE THREAD

**Issue by Manly-Dwarf** [HippieStation/HippieStationdeprecated2020#9466]
[Round ID]: # 31985

[Testmerges]: # Not sure. It worked when I first merged it.

[Reproduction]: # Buy an elite hardsuit and end the round.
The result is... this.
![broken hardsuit](https://user-images.githubusercontent.com/33744849/46638150-8202f980-cb2d-11e8-92e6-f0dcd2e9d7a3.png)
[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by yoyobatty** [comment]
Rip
