### ISSUE TITLE
Decent admin list

### ISSUE THREAD

**Issue by Carbonhell** [HippieStation/HippieStationdeprecated2020#9468]
Move the admin list out of the changelog header to a dedicated button or something that fetches admin and rank from the database, so it is always up to date. Maybe the changelog header list can be kept for maintainers, and new ones have to make the new entry for themself.

**Comment by Carbonhell** [comment]
Tag with feature please

**Comment by Eagle-Eyess** [comment]
sure +1

**Comment by AnthonyJNgo** [comment]
It is ridiculously easy to update changelog as is.
