### ISSUE TITLE
Mining Ticket in QM's and HoP's lockers

### ISSUE THREAD

**Issue by Caxxo1** [HippieStation/HippieStationdeprecated2020#9518]
When I stopped playing, there used be two extra mining tickets in the QM's and the HoP's lockers. Now they're gone.
It's a shame, I really don't think there's anything to gain by removing them.

**Comment by MrWankman** [comment]
If you mean the mining vouchers, that could be good. At the very least on lowpop if there are no miners, then whoever decides to be an impromptu one aut to be able to get a voucher somehow for a decent start.

**Comment by Eagle-Eyess** [comment]
dont think the HoP should have one but im for the QM getting it back +1

**Comment by AnthonyJNgo** [comment]
Doesn't Cargo report to HoP also? He has an energy gun and flash already, not sure why a mining voucher wouldn't be warranted.

**Comment by AnthonyJNgo** [comment]
Has it been a month already? This still isn't in? +1
