### ISSUE TITLE
Remove economy from vending machines

### ISSUE THREAD

**Issue by Jujumatic** [HippieStation/HippieStationdeprecated2020#9549]
[Title]: Removal of vending machine economy

[Implementation]: Removing the prices from vending machines and all that other shit

[Why]: There's seemingly no way to actually earn money other than wait, essentially meaning that someone with a low income job AKA greytide cannot even get random clothing from a machine or anything. What the actual fuck??

[Resources]: Err I mean I'll probably code it myself if it's simple enough so yeah

**Comment by Iamgoofball** [comment]
lmao get fucking good

if you want money go steal it from someone and their ID or do a job or you know go to the HOP and get a real job with a real paycheck

**Comment by bubberducky2** [comment]
i too enjoy those nice moments where i get paid 10$ every 15 minutes and the heads of staff are either absent or validhunting

**Comment by Iamgoofball** [comment]
Go steal money from people then

**Comment by Jujumatic** [comment]
Nobody even does their job on the station  ?????????? And by saying that you are literally encouraging people to self antag just so they can use a vending machine???

**Comment by Iamgoofball** [comment]
What is this, Bay? Go shake someone down for their cash, gives Security a job.

**Comment by Dinopeaks** [comment]
when there is sec :(

**Comment by Maroonenahmoron** [comment]
Go grab a handle at a slot machine and spin it for a while, or as said before, put some effort into the station with a REAL job to get a REAL paycheck!

Pretty sure there’s a few locations in maintenance where coins always spawn, including the diamond one, so don’t go saying the pickings are slim as Jim.

**Comment by Carbonhell** [comment]
no,-1

**Comment by Jujumatic** [comment]
i can't actually use the coins in vending machines anymore and i couldn't find any reliable way to get the money into my pda therefore poor :( besides that I'll just get a random high paying job and not do it like 90% of the people who play to then afford vending machine stuff. logic = 100%

**Comment by ghost** [comment]
steal, rob, be a nigra

**Comment by ghost** [comment]
we need a public sale machine which sends the stuff to be sold to cargo
possibly giving the payout from cargo departmental funds, or just disappear the items and gives you a subpar price for it comparatively to cargo

**Comment by ghost** [comment]
so you can steal anything not bolted down and sell it as a poor grayshit

**Comment by Pyko1** [comment]
make assistants start with welfare check /food stamps that can be used to buy 1 item

**Comment by Pyko1** [comment]
inb4 validhunting since someone tabled you at roundstart and took your food stamp.

**Comment by Iamgoofball** [comment]
@Pyko1 they already get five free paychecks($25) roundstart, this is literally the case

**Comment by Jujumatic** [comment]
$25 cant even buy you shit when even shoes cost like $50 dollars you oaf

**Comment by ghost** [comment]
do ya'll not realize @Iamgoofball half-assed economy just so he'd get paid, then fucked off because, well, he got paid. didn't even bother bugtesting or fixing bugs.

**Comment by Iamgoofball** [comment]
Fuck off mrty

**Comment by Iamgoofball** [comment]
Your slander is somehow stupider than normal

**Comment by Jujumatic** [comment]
mfw all he can say is fuck off :smirk: your ideas are.... ok... sometimes, but your code is always absolute ass, this is why we call it goofcode. if you're going to implement something as big as economy it needs to be made as a reward system, not as a clutch for getting bare essentials from machines (food, tools?) when the only way to get more money is to wait or essentially antagonise people by mugging them for their pda's, you clearly haven't thought of any ways the players can earn money so they can actually afford stuff if they're not captain or hop. being such a defensive insecure shit will get you nowhere because it changes absolutely nothing - your code is still shit and half assed and it's ruined vending machines completely, and doesn't even give people what they wanted

**Comment by DesolateG** [comment]
Or, you could... get a job!

Tough concept I know

**Comment by Iamgoofball** [comment]
@Jujumatic If you're an engineer, you have access to tools. Have you considered becoming an engineer or asking one to help you?

**Comment by GuyonBroadway** [comment]
If you are struggling to earn cash as assistant you are a lazy fuck who isn't trying hard enough.

https://i.redd.it/5tozv7uq4ms11.png

**Comment by Jujumatic** [comment]
my point is that nobody even does their job to begin with so now I'm just going to go with the highest paid job on the station, go validhunting for a few minutes and then get whatever the fuck i want for still doing absolutely nothing. you think that's a well thought out system, where you get paid for doing your job, and you still get paid exactly the same amount for doing nothing? he said it himself that the only ways to earn money are to wait it out or mug people. nice one.

**Comment by ghost** [comment]
make it work based not a salary based on time,  add more money sinks

**Comment by Jujumatic** [comment]
if there was actually rewards based on working I'd be fine with the economy but right now it makes absolutely no fucking sense, there is 0 incentive to work just steal a high paying job and do nothing and voila rich because lol

**Comment by ghost** [comment]
actually goofball in this case it would be libel, not slander

**Comment by Iamgoofball** [comment]
fair

**Comment by Eagle-Eyess** [comment]
-1 also cant you just hack a machine? i mean you greytide

**Comment by danhibiki** [comment]
Tbh the limited play I got, the economy wasn’t nearly as bad as people make it out. I think @iamgoofball did good and at best we could scale some things back if it seems too expensive

**Comment by Iamgoofball** [comment]
Did you idiots actually revert it

**Comment by danhibiki** [comment]
No it’s very much live, at least last night

**Comment by Manly-Dwarf** [comment]
No, it's a good feature that should not be reverted, but instead expanded upon.

**Comment by ghost** [comment]
better solution: we never let goof make such a big feature again.

**Comment by Iamgoofball** [comment]
better solution, mrty should learn to code first

**Comment by Lxtoofonea** [comment]
-1, but the money from them should go to cargo.

**Comment by yobob591** [comment]
-1, but we should have a better way to get money other than waiting
