### ISSUE TITLE
Make greytide great again (remove extra security on command doors)

### ISSUE THREAD

**Issue by Jujumatic** [HippieStation/HippieStationdeprecated2020#9550]
[Title]: Removal of extra security on command doors

[Implementation]: Put all command doors as they used to be AKA it wouldn't take 5 million years to unweld all that goddamn plasteel from the doors before being able to hack them.

[Why]: Spending 5 years on every single command door to actually do anything with them is terrible, it's already difficult enough trying to get into the AI upload for example. Besides that actively curbing greytide like this will destroy the greytide playerbase = less players = rippie hippie
[Resources]: The actual PR that did the change should be around here somewhere, it should actually be very easy to revert

**Comment by Iamgoofball** [comment]
no, get good

**Comment by bubberducky2** [comment]
just use thermite instead idiot

**Comment by yoyobatty** [comment]
We should be required to make iron and aluminum oxide first, by burning the aluminum and reacting iron with water

**Comment by ghost** [comment]
yeah,  aluminum over 800kelvin and mix with iron and water
maybe have mixing it with water and iron at high temperatures instantly make it explode with searing hot temperature to restrict it to chemistry?  if needed....  needs to be cooled

**Comment by Dinopeaks** [comment]
i like it it makes you that little bit safer when you are a sec boy 🛌

**Comment by yoyobatty** [comment]
Also juju, as we discussed, we should reduce the airlock sec stats from 6 to 1 
`Reflect damage: 30 > 21
Integrity still stays 50% higher than most doors
Metal cover that just requires a welder to expose wires`
Still decent security, but doesn't require gloves and fireaxes work.
or we could use Sec level 3 which requires welder then crowbar, but maintains door reflection damage stat.

**Comment by GuyonBroadway** [comment]
Build a locker mech and drill down the door!

**Comment by Jujumatic** [comment]
lol shut up @Iamgoofball you are living saltcode who makes shit prs like this https://github.com/tgstation/tgstation/pull/40941

**Comment by Iamgoofball** [comment]
I don't see how cracking down on ERPers is salt

**Comment by Carbonhell** [comment]
I dislike the idea of giving greytiders their power again. If you want to cause issues, you are gonna have a hard day doing so. -1

**Comment by Caxxo1** [comment]
It's not even hard to go around it.
Just break into EVA and steal the RCD

**Comment by Maroonenahmoron** [comment]
-1, high access areas should be designed to stay that way and not open to someone who spends 30 seconds grabbing gloves and a toolbox

**Comment by Eagle-Eyess** [comment]
-1 just get good
