### ISSUE TITLE
More projectile weapons for security

### ISSUE THREAD

**Issue by Caxxo1** [HippieStation/HippieStationdeprecated2020#9553]
I think Security deserves more projectile weapons with upgrades from R&D
Something like a /vg/ glock at round start(a shitty gun)
After that it's all stuff that has to be researched
A proper pistol(still not a .357)
Then the NT automatic rifle
And finally a sort of machine gun that can only be fired from stationary
With bullet upgrades ala the ones for exosuits

**Comment by ghost** [comment]
give the lawyer shined shoes that can AoE flash because of their shinyness

add random chance for different weaponry for sec,  50 percent taser,  25 percent ballistic pistol with rubber bullets?  10 percent disabler shotgun and like 1 percent  pulse destroyer (or dragnet)

**Comment by Maroonenahmoron** [comment]
Security could use some pistols... but I doubt how would they be intergrated since their kit is mostly about subduing and restraining. Dart pistols perhaps?

**Comment by Caxxo1** [comment]
It's not standard equipment to be used against greytiders and shit. Although it could be made that the only bullets available are rubber bullets.
Anyway, these are weapons against situations of real crisis, like nukies with their pesky shields, mass revs and cultists where everyone non implanted is to be granted a quick death, even maybe lavaland fauna.
Things like bullets that have a 90% bleeding effect would be extremely effective against a large mob of antagonists.

**Comment by ghost** [comment]
outsourced automatically charging bullets that cost money to shoot as you pay China to fabricate the ammo
ahem space China

**Comment by Eagle-Eyess** [comment]
+1 for more bullet guns. always thought it was weird that sec never had any besides shotguns and the dets one pistol. would make sense if rnd could get more though.

**Comment by yobob591** [comment]
sec having more lethal weapons in general is probably a good idea, though it may end up causing more "sec killed me 4 no raisin"

+1

**Comment by Lxtoofonea** [comment]
sec should start with a lethal gun, not laser, but a gun, +1

**Comment by AnthonyJNgo** [comment]
KBB is working on a PR now that revamps sec and does this, closing this issue.
