### ISSUE TITLE
Special Abilities for Lawyers

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#9557]
[Title]: # Lawyers and their special abilities

[Implementation]: # All of the below will be locked to lawyers only with special lawyer implants (ordered from cargo, gotten from warden or in lawyers at roundstart)

### OBJECTION
First and foremost, the objection. Activating this ability causes everyone to be interrupted (similar to getting hit while speaking) and unable to speak for 3-5 seconds. This is so the lawyer can state the objection and elaborate upon it, thus taking the spotlight. If the lawyer just spams it no-one will take him seriously. Should have a cooldown of 5-10 seconds.

### Power move
The lawyer starts out (and gets more of, probably from a special lawyer cargo crate or something) a random item which can then be equipped to unlock this power move. This can be several things: finger-snapping gloves, adjustable glasses, table-slamming implant and so forth. This creates a notification in the chat (e.g. *Lawyer McLawyerface adjusts his glasses!*) and interrupts everyone else. Again, spamming this means no-one will take you seriously. Cooldown of 2-3 seconds.

### Theme song
Using the lawyer implant, the lawyer can put on their theme song (specifically, they choose one of the 'cornered' themes from the Phoenix Wright games) to play for at most 30 seconds. Cooldown of 1-2 minutes. The lawyer can also activate the ability one more time during cooldown to play a short version of the theme without the intro.

[Why]: # Lawyers should get some special abilities to make people play them more. They can have great potential as banes of shitcurity, if only they are done right.

[Resources]: # A bunch of voicelines and music can be yoinked from the Phoenix Wright games and the items would be pretty easy to skin up.

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by biggiOS** [comment]
make it usable only in space court
o h w a i t
nobody uses space court omegalul

**Comment by Eagle-Eyess** [comment]
Woops. Anyway I see no reason why this job should get special abilities for no reason... -1

**Comment by danhibiki** [comment]
This would be badass if lawyer can roll antag. Free mute sting from changelings

**Comment by DaydreamPuppeh** [comment]
Only if you can also choose the pursuit themes from the investigations games. Also the theme of the lawyer is their objection theme, not their cornered/pursuit theme. For example, Athena Cykes has Courtroom Revolutionaire and Apollo Justice has A New Chapter of Trials.

**Comment by DaydreamPuppeh** [comment]
Also we need to have the option to chose the sound effect of the lawyer's objection.

**Comment by Dinopeaks** [comment]
it is interesting idea but it seems like it can be a bit OP

**Comment by ghost** [comment]
@DaydreamPuppeh I don't see why not. This is just a concept I have, after all.

@danhibiki @Dinopeaks except everyone would hear the interrupted sentences over the radio and the lawyer sounds coming from maint, and instantly know who the antagonist is. Also you have to constantly spam the abilities in order to get them to mute, unlike a single changeling mutesting.

**Comment by ghost** [comment]
@Eagle-Eyes just like sec shouldn't get donut buffs and krav maga, chaplain shouldn't get holy effects, chef shouldn't have god-tier grabs, bartender shouldn't be able to throw shit without it spilling, etc.? Right now, the lawyer is glorified greytide with some sec and no maint access. These abilities would actually make the job interesting, and if the player is entertaining enough, an IC bane of shitcurity.

**Comment by Eagle-Eyess** [comment]
All of those effects that you just said make sense or are minor besides the chef one (which i believe is either gone or on its way out). Security should know martial arts, the donut thing is whatever. The chaplain holy affects are mostly in place for cult and stuff. The bartender one is again whatever.

 I agree lawyer is glorified greytide, but these abilities are either annoying, powerful, able to be abused easily or a combination of both. You think of better balanced/less annoying abilities and maybe ill change my opinion.

**Comment by ghost** [comment]
@Eagle-Eyess I can suggest making the OBJECTION paralyse the lawyer for its entire muting duration. This will ensure that the lawyer can only use the item-based ability offensively, and cannot just spam one and then the other for infinite interruption and silence. Also increase the cooldown of the Power Move. If you find any other ways to make it more appropriate, please tell me.
