### ISSUE TITLE
port this PR from paradise adding a safe refactor

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#9558]
[Title]: # Your feature needs to have a good title. If you want an object added, the object's name would be a good title, and such. Use common sense.

[Implementation]: # How should the feature work out? What exactly is it supposed to do, in your initial idea? If an item, can it be crafted/found/bought and for what?

[Why]: # How does your feature improve the game anyhow? Why should it be added?

[Resources]: # Eventual assets such as icons and sounds which you have and want to suggest related to this feature.
https://github.com/ParadiseSS13/Paradise/pull/9843
# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by ExpAntique** [comment]
holy shit

**Comment by Shdorsh** [comment]
Oy this looks good. Is it in yet?
