### ISSUE TITLE
[sugg] This Sugg Will Fix Combat; Click Now

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#9565]
[Title]: # Your feature needs to have a good title. If you want an object added, the object's name would be a good title, and such. Use common sense.

[Implementation]: #add velocity so you can't go from 0 to 100 km/h in 0.5 second and weight determines acceleration

[Why]: # 

[Resources]: # 
@HippieStation/maintainers

**Comment by danhibiki** [comment]
Gross

**Comment by Eagle-Eyess** [comment]
-1

**Comment by Kierany9** [comment]
add it for jetpacks only
