### ISSUE TITLE
surgery dun got goofed

### ISSUE THREAD

**Issue by xTrainx** [HippieStation/HippieStationdeprecated2020#9567]
Issue reported from  Round ID: 32139 (Hippie Station)

Reporting client version: 512

self surgery and surgery wont work, surgery drape seems to be useless now

**Comment by ghost** [comment]
I also had this issue come up. I thought that maybe I was doing something wrong, but this is what my 'assistant' and I tried:
1. Self surgery while standing up
2. Self surgery while resting
3. Assisted surgery while standing up
4. Assisted surgery while resting
5. All of the above with clothes and without.
In 0 of those cases did drapes work.

**Comment by Kevak** [comment]
Still fucked.

**Comment by yoyobatty** [comment]
https://github.com/HippieStation/HippieStation/pull/9577 Fixed
