### ISSUE TITLE
port https://github.com/tgstation/tgstation/pull/40223

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#9568]
[Title]: # port https://github.com/tgstation/tgstation/pull/40223

[Implementation]: # How should the feature work out? What exactly is it supposed to do, in your initial idea? If an item, can it be crafted/found/bought and for what?

[Why]: # How does your feature improve the game anyhow? Why should it be added?

[Resources]: # Eventual assets such as icons and sounds which you have and want to suggest related to this feature.

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by ghost** [comment]
For those who want an explanation:
Circuits can now be objects; e.g. pen assemblies make pens, drone assemblies make drones, belt buckle assemblies make items which you can chuck on your belt buckle, etc.
Also I'm hitting that +1 button

**Comment by BlueNothing** [comment]
Same here!

**Comment by Eagle-Eyess** [comment]
This seems like a cool idea so I’ll +1. Though I don’t know enough about circuits to know if this will have bad consequences
