### ISSUE TITLE
Igniters aren't working properly

### ISSUE THREAD

**Issue by TheSpartyn** [HippieStation/HippieStationdeprecated2020#9569]
The wall mounted igniters in the toxins lab aren't igniting plasma in the chamber, thought it might've been a change but 2 people are telling me they're glitched, and it used to successfully ignite the exact same mixture I'm using now.

Issue reported from  Round ID: 32158 (Hippie Station)

Reporting client version: 512

**Comment by TheSpartyn** [comment]
I don't know shit about coding but I looked through the igniter updates and this is the only thing I could find, it didn't get changed after the sparks rework.

![ye](https://cdn.discordapp.com/attachments/473741466611613697/504424560943300618/unknown.png)

**Comment by TheSpartyn** [comment]
epic gamer bump because its still broken

**Comment by BlueNothing** [comment]
Bump, I'm also having trouble with it.

**Comment by BlueNothing** [comment]
To those reading this and in need of a workaround: Throw a lit welding tool into the airlock chamber for toxins from the outside, then, when the gas is all ready to be collected, cycle the airlock. Hacky, but it does at least sort of work.

**Comment by TheSpartyn** [comment]
Yeah I've been doing this but it usually causes the inner airlock to break and is kinda fucky.

They should really just put the floor igniter in instead of the wall ones, the floor one in the Turbine works great.

**Comment by TheSpartyn** [comment]
ok

this is epic

**Comment by AnthonyJNgo** [comment]
Swap wall igniter in toxins for the floor igniter, ok

**Comment by yoyobatty** [comment]
Already fixed.
