### ISSUE TITLE
poopee

### ISSUE THREAD

**Issue by Yobih** [HippieStation/HippieStationdeprecated2020#9579]
[Implementation]: # add poop and pee. they are with the chem system so you can spray them all around.
[Why]: it's hilarious. adds reason to play janitor.

[Resources]: i got nothin.

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by danhibiki** [comment]
Die

**Comment by Shdorsh** [comment]
How about: no.

**Comment by Manly-Dwarf** [comment]
I tried it once as a joke PR.
Safe to say, no it's not gonna happen.

**Comment by Eagle-Eyess** [comment]
I really want to plus one this but to be safe -1
