### ISSUE TITLE
Human mutation toxin should affect slimes

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#9584]
[Title]: # Human mutation toxin should affect slimes

[Implementation]: # Add some sort of blood system for slimes, then let human mutation toxin turn slimes into humans

[Why]: # Black slime toxin is wayyy to broken as it stands. It takes about 20 minutes to get, and then it's a matter of loading a syringe gun and shooting it at people (or foam grenades, I could see those being a massive problem). There is one way to stop the transformation which is quite difficult to find on its own (frost oil), but once the slime is slimed there is no way back - that is why I think this change is required.

[Resources]: # None

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by Eagle-Eyess** [comment]
+1  the only problem with this is it be a pain to do

**Comment by ghost** [comment]
Yeah, but it's also a pain to get shot and turn into a slime. Mind you, I was doing the shooting and I still felt like it was fucked up.
