### ISSUE TITLE
gulag food is disgusting and makes you puke continously, cant even feed

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#9591]
[Round ID]: # (If you discovered this issue from playing HippieStation hosted servers:)
[Round ID]: # (**INCLUDE THE ROUND ID**) 32548
[Round ID]: # (It can be found in the Status panel or retrieved from https://tools.hippiestation.com/stats/round.php ! The round id let's us look up valuable information and logs for the round the bug happened.)

[Testmerges]: # (If you believe the issue to be caused by a test merge [OOC tab -> Show Server Revision], report it in the pull request's comment section instead.)

[Reproduction]: # (Explain your issue in detail, including the steps to reproduce it. Issues without proper reproduction steps or explanation are open to being ignored/closed by maintainers.)

[For Admins]: # (Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them.)

**Comment by GuyonBroadway** [comment]
Prison food is supposed to be disgusting. You want decent food, don't get brigged.

**Comment by ghost** [comment]
problem is,  this stunlocks you and doesn't let you mine since you vomit continously after like 2 or 3 soy

**Comment by GuyonBroadway** [comment]
Solution: don't eat soy.

**Comment by bubberducky2** [comment]
yay for making gulag food useless, Epic!

**Comment by danhibiki** [comment]
Just eat your ass for nutrition or ask a sec officer. If your in gulag it’s not like you shouldn’t expect a shitty situation. Does gulag have NPCa you have to fight?

**Comment by k-k-karma** [comment]
cook goliath steaks

**Comment by ghost** [comment]
havent really seen Goliaths on gulag

**Comment by AnthonyJNgo** [comment]
Prisoners should have real food.

**Comment by AnthonyJNgo** [comment]
PR opened.
