### ISSUE TITLE
[Suggestion] Prosecutors Badge

### ISSUE THREAD

**Issue by DaydreamPuppeh** [HippieStation/HippieStationdeprecated2020#9605]
For making all of the criminals who want rp to lose hope.

Make the badge look similar to the prosecutors badge in investigations.

**Comment by bardofrage** [comment]
Yeah sure, +1

**Comment by earthmoonjune** [comment]
+1

**Comment by AnthonyJNgo** [comment]
I did this, but my icon sucks. Closing since a PR exists.
