### ISSUE TITLE
Mime cant use ventriloquist dummy to communicate

### ISSUE THREAD

**Issue by press-mark** [HippieStation/HippieStationdeprecated2020#9647]
[Round ID]: #33032

[Testmerges]: # N/A

[Reproduction]: # Be a mime, hold your ventriloquist dummy in either hand, try and speak through it with :r or :l and be presented with "You find yourself unable to speak!". It works if you break your vow of silence however, but that defeats the point.

From a roundstart tip:
"As the Mime, you can use :r and :l to speak through your ventriloquist dummy."

**Comment by ghost** [comment]
mimes cant talk and the whole point of ventriloquism is talking and making it appear that the doll is. retard bitch

**Comment by DaydreamPuppeh** [comment]
Zamol. There is a roundstart tip that specifically says this is possible

**Comment by Eagle-Eyess** [comment]
I think it be cool if the mime could do this
