### ISSUE TITLE
Javier Costello

### ISSUE THREAD

**Issue by CarolinaBeck** [HippieStation/HippieStationdeprecated2020#9661]
Issue reported from  Round ID: 33066 (Hippie Station)

Reporting client version: 512

So this is a counter report for the report Javier made,

As follows, round starts I'm playing as HOS and i start by locking off armory for security reasons then i go to check my office and i see somebody i don't recognize in my office so i go to arrest and the gun was set to kill(which idk why). anyways they arrest me and guess what Javier leaves my HOS ID on the fucking floor and the fucking clown just picks it up and runs off with it, which shows a blatant disregard for keeping the station safe

**Comment by ghost** [comment]
brother,  i am very sorry but github reports are only for code issues
this is a good suggestion though, they should add a new github report template for reporting administration issues to admins

**Comment by Manly-Dwarf** [comment]
Okay, will make sure to code Javier out of the game.

**Comment by DaydreamPuppeh** [comment]
Lmao. You make ban request on the forums, not github
