### ISSUE TITLE
scout mode holopara is damaged in ash storms

### ISSUE THREAD

**Issue by Yobih** [HippieStation/HippieStationdeprecated2020#9666]
Issue reported from  Round ID: 33110 (Hippie Station)

Reporting client version: 512

guy;s ranged holopara was exploring an ash storm with its scout mode ability, and apparently was transferring damage back to his owner even though he saw himself at 100% health. Bug killed his owner.

**Comment by k-k-karma** [comment]
not a bug; intentional. scout holoparas are damageable in general and can even bait megafauna to the owner

**Comment by Eagle-Eyess** [comment]
Yea seems intended. Any dmg done to the holo is transferred to the owner and since ash storms do dmg.... you get the point
