### ISSUE TITLE
Pirates don't have money to buy drinks from the Pirate Shuttle Booze-o-Mat

### ISSUE THREAD

**Issue by buildmaster668** [HippieStation/HippieStationdeprecated2020#9682]
Round ID: 33278

Quite simple, if you're a pirate, you're ID isn't hooked up to a bank account, so you have no money to use the Booze-O-Mat, nor can you add money since you have no account.

To reproduce: Be a pirate, head to the bar section of the shuttle and attempt to buy a drink from the Booze-o-Mat.

EDIT: The items became free when moving the ship. Prices may be based on z-level.

**Comment by ghost** [comment]
we need a way to pay cash in general

**Comment by Tranquill6** [comment]
Fixed as of recently.
