### ISSUE TITLE
Shadowling thralling vs. split personality

### ISSUE THREAD

**Issue by Maroonenahmoron** [HippieStation/HippieStationdeprecated2020#9687]
[Round ID]: 33329

Shouldn't it make sense when someone gets converted by a shadowling, them along with their split personality brain trauma should be converted as well? Because there's an organ that signifies their current thrall status and should affect them as a whole being.

**Comment by k-k-karma** [comment]
this is just a continuity error with lore. split personalities are seperate minds, i can edit the organ description to be on just a single hemisphere

**Comment by k-k-karma** [comment]
not only that but split personalities are so much of their own mind that if the first mind is cloned, the second mind can re-enter the first mind's brain and also be cloned.

**Comment by danhibiki** [comment]
This was some horseshit, had someone that was thralled that just went around killing people., but he kept his thrall antag icon. Super grudge but split should just be removed, dumb gimmick that totally ruined the round for me.

**Comment by AnthonyJNgo** [comment]
We should just remove split personality to be honest.
