### ISSUE TITLE
merge https://github.com/tgstation/tgstation/pull/40907 birdboat station

### ISSUE THREAD

**Issue by ghost** [HippieStation/HippieStationdeprecated2020#9719]
[Title]: # merge https://github.com/tgstation/tgstation/pull/40907

[Implementation]: # add https://github.com/tgstation/tgstation/pull/40907

[Why]: # How does your feature improve the game anyhow? Why should it be added?

[Resources]: # Eventual assets such as icons and sounds which you have and want to suggest related to this feature.

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by k-k-karma** [comment]
finally i can show off give me a second

**Comment by k-k-karma** [comment]
#9720
