### ISSUE TITLE
More variants of pipes. (Bluespace, layering, new. ect.) and new gases ideas [FEATURE]

### ISSUE THREAD

**Issue by bubberducky2** [HippieStation/HippieStationdeprecated2020#9773]
**This feature request proposes new variants of pipes, post in the comments down below if you disagree with some certain pipes, or request other pipes to be added in.**

**[PIPE1]:** BLUESPACE PIPES!!!

Oh yeah, baby, they're going to be back, better than ever, and maybe a little nerfed...
I propose that these bluespace pipes are restricted to RPD upgrade cartridges made from RND after bluespace research, not expensive either to make these.

The bluespace pipes will do as the same before, but their sprites will be changed a little bit cuz they look ugly as FUCK.
(will post in comments below my sprite idea in mspaint :thinking: )

Bluespace manifolds and many other pipes will be included, at the end of them they will teleport gases into another ID of the same variant, AKA
Pipe ID 1 teleports gas into another pipe with the same ID, Some of them will have a toggleable option that has *Receiving* or *Sending*, there cannot be 3 pipes with the same ID or else the link will be broken and will not work and notify you, if a funny assclown decides to fuck you over with this, just change the ids of both the pipes into something random.

The ID's will be 2 digit to prevent complications, 3 digits maybe.
**OPTIONAL**
**SUBPIPE: BLUESPACE MANIFOLDS**
Bluespace manifolds will have nodes at the end of them when you click on them and each node will have an ID to teleport to, basically a 3x gas sucker that goes into 3x more pipes, what will you do with 3 pipes? Who knows? - (idea can be skipped)
**OPTIONAL**
Layers will be certaintly interesting for these bluespace pipes, they will teleport layer 1 to layer 3, to layer 3 to layer 2, and thus so on!

**[PIPE2]:** ROTATING PIPES, VOLUME FILTERERS-MIXERS. [time to get slightly complicated on the 1st one]

There will be an option to feature rotating pipes, this will feature way less pipes, but they will have a special function, to be able to rotate with the items plukked into them (timer-receiver, timer-igniter... thus so on)

Rotating pipes will require no upgrades, but they will need items from the toolstorage area or robotics tools to make them work.

Basically what these pipes will do is rotate to another interconnected path when triggered to redirect gas, this will not get rid of the gas that was previously traveling, but im sure that's fixed by connecting a filter for these gases anyway...

Useful for creating automated cooling systems when it reaches a certain temperature (for this you will use analyzer attachment, if you have any other ideas ie. bikehorn making funny sound each rotation then code them in or make a feature)
and it rotates back when cooled enough (cooldown for rotating is 5 seconds to prevent laggy glitch pipes)

Volume filters and mixers are basically the same version as the previous ones, but they pump more gas and they won't be as much of a burden as the kPa versions, I wanted these ones to be seperate from the kPa for those kPa lovers so they won't bitch and cry i guess

there should be some versions of these that have a 2nd node that redirects another gas of your choosing, basically filtering 2 gases at once! epic!!! 4-way here we come baby

**[PIPE3]:** HEAT EXCHANGER CHANGES
Heat exchangers should exchange their heat with space and other nearby tiles or space tiles, aswell as any nearby other HE's on the same layer.

HE's should also interconnect with each other (ie. like this ╦╦╦ ) to provide more HEAT EXCHANGING POWER!!!!!!!!!!!!!!

_SUBIDEA:_ Make gases be even COLDER, add in hypernobilium at the end of thereshold or new gas that is made (cold fusion) 
+++++++++++++++++++++++++++
https://en.wikipedia.org/wiki/Cold_fusion
https://en.wikipedia.org/wiki/Bose%E2%80%93Einstein_condensate
+++++++++++++++++++++++++++
Ok boys, this shit's gettin serious, we are playing with the COLD now:
Gases reaching a certain threshold under the cold (not attainable by space or lazy cold generators, find another way to cool these gases below threshold. hint: chemistry or cold fusion could help you)
are to react violently and create a warped version of the canister, the air around it is so cold it penetrates space suits and instantly cools down any air to -273.15 C and below.

(To prevent people from powergaming these gases they will have to work with it or expirement with it, many finicky gases shall be made here! Glory to Einstein!)

This new reaction shall create either:
Maxcap explosion or weaker. Can be stopped and defused or transformed into a canbomb. (very low chance) - **(OPTIONAL)**

Bluespace portal in a random Z-level or bluespace glitch tile. (low chance)

Instead of neutrons, it shall create photons, harvest the LIGHT!!! or light up entire ROOMS - calculated by fusion (mid-high chance) Basically BIG LAMP.

Cold room, hypernobilium is made, moles calculated by level of fusion (mid-high)
*New gas called Supergas He-4 (not a fluid, now a gas), a superatom. calculated moles by power of fusion, very special gimmicky gas. (mid-high)

*Supergas He-4 will not warm up at all circumstances, it will instantly cool down any gas it touches to the lowest point possible without toggling the cold fusion again, then keep it there, basically hyper nobilium 2.0., but very low in mole creation, interactions with the air will cool it down instantly wherever it travels, freezes water vapour and crystalizes it. cracks windows and weak walls slowly until they break open due to the intense atom attraction it has, (see excitons, polaritons and magnons, basically a weaker singularity and a stronger grav anomaly, should be expected to be antag only when releasing this gas for it is very powerful.)
Gas will only be able to occupy 1 tile at a time, but will be very noticable
Color of the gas will be a deep blue and purple shifting fog that is extremely visible, even when low in moles.

Attraction of the atoms in this gas can knockdown spacemen, destroy their lungs when inhaled, push them around in no-grav enviroments, push around pushable items or throw them even.

**MORE NEW GASES**
- ARGON: A weak gas that glows faintly in a deep purple when near any kind of power/machinery/ that's on, has the discription of a very bright(when on) fat plasma thicket gas in a deep purple , also very HEAVY, heavier that water vapor infact. so it's deadly to breathe.
Argon is made by cooling down oxygen, nitrogen and c02 together in an enlarge abundance of water vapour, oxygen, C02 and nitrogen, this should be hard to make because it will also make the next gas:

- NEON:

Neon is an extremely bright gas, non-flammable and non-toxic (in low doses) that can be used to light up entire rooms within seconds in a red/orange glow.
Neon is made by combining Argon, c02 and oxygen at a high temperature

Neon at a high temperature will reach a critical point and cause shocks to people due to it being a very conductive noble gas, but increase in glow when the temperature increases.

This gas is extremely rare and will cost alot of money if you sell it, 1000 points per mole, quick buck for a sick fuck!

END OF POST.
Like i said above, go suggest some more shit or point out any problems in the comment section, no gay pls

**Comment by k-k-karma** [comment]
i'll work on neon and argon first

**Comment by bubberducky2** [comment]
![bluespacepipe](https://user-images.githubusercontent.com/43244417/48571190-f3914d00-e90e-11e8-9921-17516f2983ca.png)
Here is an example of the bluespace pipe reskin... in mspaint... :tada:

**Comment by cris5311** [comment]
+1

**Comment by AnthonyJNgo** [comment]
Stale.
