### ISSUE TITLE
Poser Tags do not work unless your a gang member

### ISSUE THREAD

**Issue by fluffe9911** [HippieStation/HippieStationdeprecated2020#9778]
TO REPRODUCE:
1. Grab a crayon or a spray can
2. Attempt to spray a poser tag
3. Be sad at the fact the tag is invisible

**Comment by k-k-karma** [comment]
you sure this isnt a downstream issue

**Comment by fluffe9911** [comment]
On actual server testing it may actually just be a down stream issue which is strange considering it was also a bug on the local hippie file weird going to close this I guess sorry

**Comment by fluffe9911** [comment]
Ok did some more server testing and it seems if your a gang member poser tags work but do not work if your not a gang member tested on the actual server this time

**Comment by k-k-karma** [comment]
interesting
