### ISSUE TITLE
Gateway game mode

### ISSUE THREAD

**Issue by Caxxo1** [HippieStation/HippieStationdeprecated2020#9794]
[Title]: Gateway game mode

[Implementation]: It's an extended round with a clear, co operative target. A game mode outside of normal rotation, that needs to be forced. Random Gateway missions used. At round start a message like this appears: "Attention crew! The Syndicate are planning to use their own Bluespace Artillery on the station. The only way to stop them is to travel to place X to disable it. Our intern is working right now to find  it and connect it to your Gateway! Top priority!
We'd send a specialized team but we've already used the budget on extra paper clips. Oh well, don't screw it up!" 
The gateway wouldn't open for 15 minutes, and then a 30 minute countdown would start. If nobody deactivates the BSA, it's game ogre for everyone.

[Why]: It'd be nice to have a straight man round every now and then, where spessmen of all jobs work together to prepare themselves for God knows what. Miners mining, nerds researching, cargo ordering stuff, shitcurity gearing up etc.

[Resources]: We already got the gateway missions, but I think they need to be buffed, to be a decent challenge for a well prepared crew, not just random greyshirts accidentally running into them.

**Comment by k-k-karma** [comment]
reverse war ops? sounds nice +1

**Comment by yobob591** [comment]
I like it, more PVE stuff would be nice and would hopefully encourage less validhunty stuff

**Comment by danhibiki** [comment]
I understand the novelty but I think it detracts from the appeal of hippie personally. Anything off station becomes a hassle for antags, and modes like this lend itself to hour long rounds because you _want_ to finish them. just some food for thought

**Comment by AnthonyJNgo** [comment]
@danhibiki Well, not really. Did you read the OP post fully? There wouldn't be any antags in this round, strictly PVE. The gateway is the antag. He also mentioned that the gateway would remain closed for fifteen minutes, and then a thirty minute timer would start that would end the round once finished. Max time of 45 minutes? Personally I think it's great, maybe knock the prep time to five minutes instead of fifteen, and then start the thirty minute timer for a total round time of thirty five minutes.

**Comment by Caxxo1** [comment]
I think it goes against the spirit of the game and especially that of Hippie, but there's nothing wrong with eating ice cream between lunch and dinner. As long as it's kept to an "every now and then" basis, I think it would be beneficial

**Comment by Caxxo1** [comment]
The reason I chose 15 minutes of prep time is for prep time. I'd like the miners to mine, maybe science can get nanites and shit, maybe they get AI shell going, maybe someone gets borged etc. With 5 minutes I think most will just rob the armory, get a hardsuit and then die. Forcing the gateway to be nerfed

**Comment by WarRage333** [comment]
Out of rotation for admeme events +1

**Comment by AnthonyJNgo** [comment]
Stale.
