### ISSUE TITLE
Make the exosuit extinguisher able to take reagents from chemical tanks

### ISSUE THREAD

**Issue by WarRage333** [HippieStation/HippieStationdeprecated2020#9848]
[Title]: # Make the exosuit extinguisher able to take reagents from chemical tanks

[Implementation]: # 

	if(istype(target, /obj/structure/reagent_dispensers/watertank) && get_dist(chassis,target) <= 1)
		var/obj/structure/reagent_dispensers/watertank/WT = target
		WT.reagents.trans_to(src, 1000)
		occupant_message("<span class='notice'>Extinguisher refilled.</span>")
		playsound(chassis, 'sound/effects/refill.ogg', 50, 1, -6)

think just adding the chem tank ( /obj/structure/reagent_dispensers/chemical ) somewhere there somehow will do just fine

[Why]: # I think you were able to do this before they changed so you can unscrew water tanks anymore to add chemicals to them, now that i think about maybe just make it so you can add chemicals again to water tanks fuk tg no fun allowed

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by yoyobatty** [comment]
The original idea of adding chems to fire extinguishers was a mistake to begin with

**Comment by danhibiki** [comment]
I mean I said this before

**Comment by AnthonyJNgo** [comment]
Chems in fire extinguishers was a mistake.
