### ISSUE TITLE
Wizard Time stop spell does not always stop people

### ISSUE THREAD

**Issue by Eagle-Eyess** [HippieStation/HippieStationdeprecated2020#9849]
Issue reported from  Round ID: 34021 (Hippie Station)

Reporting client version: 512

Wizard used time stop on person. Person became color of time stop, but did not get frozen. Happened two times in a row in two rounds. Both resulted in wiz death.

**Comment by k-k-karma** [comment]
BOTH TIMES were me i had the nul lrod which negates all wizard spells

**Comment by Eagle-Eyess** [comment]
guess it aint a bug then
