### ISSUE TITLE
flightsuits

### ISSUE THREAD

**Issue by geylard** [HippieStation/HippieStationdeprecated2020#9868]
[Title]: # Your feature needs to have a good title. If you want an object added, the object's name would be a good title, and such. Use common sense.

[Implementation]: # How should the feature work out? What exactly is it supposed to do, in your initial idea? If an item, can it be crafted/found/bought and for what?
readd flightsuits
[Why]: # How does your feature improve the game anyhow? Why should it be added?
i like flightsuits
[Resources]: # Eventual assets such as icons and sounds which you have and want to suggest related to this feature.
the old flightsuit things
# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers 
no

**Comment by Manly-Dwarf** [comment]
I'd be willing to give this a shot if it removed RTA, or any reactive armors for this matter. But the idea of giving the Research Director an item that's pretty much only useful for combat instead of his job is disgusting, and that's pretty much what both the RTA and Flightsuits are.

**Comment by geylard** [comment]
a flightsuit is the thing that requires tons of all types of minerals to make and R&D to be maxed out.

**Comment by ghost** [comment]
As long as RnD can also research Prototype Hardsuits (a non-combat alternative), I'm fine with this. The fact that it's impossible for science to get this bad boy until like 2 hours into the round kind of balances it out.

**Comment by ghost** [comment]
for the max RND item just add an item that analyzes things on the spot and depending on their tech values,  creates a random special item or smth

**Comment by TheSpartyn** [comment]
for max RND just let them get traitor/abductor tech nodes for like 100k points

**Comment by AnthonyJNgo** [comment]
This and RTA are cancer.
