### ISSUE TITLE
As Sentient Disease, if your host or the person you're trying to infect has internals, then you cannot infect anyone.

### ISSUE THREAD

**Issue by coolguymcman** [HippieStation/HippieStationdeprecated2020#9877]
Issue reported from  Round ID: 34283 (Hippie Station)

Reporting client version: 512

**Comment by ghost** [comment]
That's a feature, not a bug

**Comment by coolguymcman** [comment]
dang, really? my entire round got ruined because i chose a dude with internals on but alright.
