### ISSUE TITLE
Re-Nerf-Buff? Cost of getting to femto manipulators 

### ISSUE THREAD

**Issue by WarRage333** [HippieStation/HippieStationdeprecated2020#9895]
https://github.com/HippieStation/HippieStation/pull/6985

This was changed to lower the price from 10k

But a few weeks ago they added an extra node and renamed the femto node on the tech webs, please lower both to 2.5k instead of 5k and 10k

Why: So much trash node have been added with the nanite tech trees its already a pain to wait this shit out

**Comment by ghost** [comment]
you have some ways to increase research point generation, like making complex gases or creating nukes. I'd be up for bringing the cost down a bit though, 15,000 for items which aren't just science powergamey shenanigan crap but what instead help literally the entire station is a bit much.

**Comment by WarRage333** [comment]
BUMPPPPPPPPPP

**Comment by WarRage333** [comment]
I DID THIS
