### ISSUE TITLE
Removal of the extraction limit of every Stat but potency from botany dna machine

### ISSUE THREAD

**Issue by RafRoq** [HippieStation/HippieStationdeprecated2020#9906]
[Implementation]:  # it's exactly how dna machine work on yogstation, you can transfer the code from there or just change a couple numbers that even I can do it 

1- Experienced botanists can go over this limit using wheat for anything, wheat has the highest natural growth speed among all fruits if you want to do something, just stick to the wheat, so it's a boring and useless limitation, it's just for disrupt the production and variety of foods and fruits, why would you plant apples if wheat grows faster? Hippie rounds are almost always short

2- machines never get upgrades because most rounds last little and scientists never work
And dna machine is only worth  to transfer stats  if maxed since you have wheat 

3- potency is the trait that really matters to limit, because it control the amount of chemicals and power of intrinsically traits, what botany is based around 

-hey mutt what is the edible wheat? I'm hungry
-I do not know man, pick one and hope not to die
* blows up because he ate the nitroglycerin one

**Comment by danhibiki** [comment]
No way, potency is the easiest trait to manipulate and the others are up to RNG unless your friendly scientist upgrades it. All you have to do to raise potency is spam saltpetre

**Comment by RafRoq** [comment]
My intention is to remove extraction cap from yield, production speed, lifespan, and endurance because they are not needed

**Comment by ghost** [comment]
this is good

**Comment by ghost** [comment]
if botany too op just add weeds that take the pest/weed level and spawn mobs to attack the botanist

**Comment by Jujumatic** [comment]
does this mean we can get 5 million potency bananas

banana takes up THE WHOLE SCREEN AND STUNS FOR 5 MINUTES

**Comment by RafRoq** [comment]
No, this mean you don't need to upgrade dna machine to extract yield 10 and production speed 1

**Comment by RafRoq** [comment]
Closing since I made a pr
