### ISSUE TITLE
Look at my DAB

### ISSUE THREAD

**Issue by AnthonyJNgo** [HippieStation/HippieStationdeprecated2020#9909]
Dabbing Emote.

There should be a "dab" button that allows players to dab in-game, but has a chance to give brain damage every time you do it.

It would take literally ten seconds to code a verb and implement it, and I think it would be hilarious.

**Comment by gumbythegreen** [comment]
Seconded. This will be a fine addition to our emote collection

**Comment by k-k-karma** [comment]
what does this button do

**Comment by Carbonhell** [comment]
why is this issue PINNED

**Comment by k-k-karma** [comment]
dunno

**Comment by AnthonyJNgo** [comment]
Because it's a great idea, now give me your +1's.

**Comment by AnthonyJNgo** [comment]
I am making a pr for this today, pinning.

**Comment by AnthonyJNgo** [comment]
I really need to do this.

**Comment by AnthonyJNgo** [comment]
PR opened
