### ISSUE TITLE
Suggestion: Stone Mask from JoJo

### ISSUE THREAD

**Issue by ExpAntique** [HippieStation/HippieStationdeprecated2020#9953]
[Title]: #Adds the Stone Mask

[Implementation]: # Could be a rare lavaland or space ruin spawn, and then be wearable on the mask slot of anyone that equips it. Does nothing until it becomes blood-stained, which causes it to then latch onto the person and be temporarily unremovable, and turning them into a  vampire. Could also be sold for huge amounts of money.

[Why]: # Would definitely make rounds more interesting if someone decides to put it on or force it on someone else during an otherwise peaceful round.

[Resources]: #
![image](https://user-images.githubusercontent.com/37980640/49331549-ad71f580-f56c-11e8-8797-a7371a60306d.png)

On a side note, Our vampires should definitely be more jojo-y. Current vamps are kinda cool because they have a Castlevania vibe, but could be better.

# Be sure to ask some maintainer to label this issue as a feature. Either ping them on our discord or PM them on our forum. Thank you for sharing your ideas!
@HippieStation/maintainers

**Comment by DaydreamPuppeh** [comment]
Only if we add the redstone of aja and make a stand that can stop time

**Comment by ghost** [comment]
stand that can stop time would be kinda easy,  also make it hit faster but less damage for balance (and owner still has time stopped for him) also red stone of ajah gay

**Comment by ghost** [comment]
also tbh the previous kind of vampire that you became by drinking out of the random goblet that appeared in your hand was cooler as it was a choice and you also needed to keep the goblet if you wanted to convert others

**Comment by ExpAntique** [comment]
I mean, this is also a choice as you don't have to put the mask on, and you also force the mask onto other people. Also ZA WARUDO is a wizard spell IIRC

**Comment by BlueNothing** [comment]
It is, Exp, but can also be generated from sepia slimes. The idea of making a holoparasite that can use it is... maybe not ridiculous. Don't forget cooldowns, though.

**Comment by k-k-karma** [comment]
no more mining self-antag

**Comment by Manly-Dwarf** [comment]
> Could be a rare lavaland or space ruin spawn

-1

**Comment by ghost** [comment]
could also have a 0.001% chance to drop from mining a rock tile

**Comment by AnthonyJNgo** [comment]
This is being included in Pillarmen, so approved.
