### ISSUE TITLE
RD cant use his ID to unlock borg covers.

### ISSUE THREAD

**Issue by WarRage333** [HippieStation/HippieStationdeprecated2020#9987]
Issue reported from  Round ID: 34755 (Hippie Station)

Roboticists can. 

Reporting client version: 512

**Comment by yoyobatty** [comment]
Checked the access defines for science roles, RD has robotics_access on it, so somehow it got removed during this round. I checked the access on silicons too, it needs `robotics_access`, the RD spawns with it on skeleton and full crew.
