### ISSUE TITLE
Telescience Doesn't Work

### ISSUE THREAD

**Issue by BlueNothing** [HippieStation/HippieStationdeprecated2020#9994]
[Round ID]: #34770

[Reproduction]: # Research prerequisites, and you'll see that Advanced Bluespace Travel appears to unlock nothing. Checking the circuit imprinter doesn't show the new circuits available for printing.

**Comment by WarRage333** [comment]
Check in the omni circuit printer in robotics

**Comment by BlueNothing** [comment]
Can that one print it?

**Comment by BlueNothing** [comment]
Let me put it this way: The node researches, but doesn't show any items when you look at it in list view, so it looks like it doesn't unlock anything when you grab it.

**Comment by BlueNothing** [comment]
Nope, that one can't print it either, @WarRage333 .

**Comment by BlueNothing** [comment]
/datum/techweb_node/adv_bluetravel
	id = "advanced_bluetravel"
	display_name = "Advanced Bluespace Travel"
	description = "Using superior knowledge of bluespace, you can develop more finely-controlled teleportation equipment."
	prereq_ids = list("micro_bluespace", "bluespace_travel")
	design_ids = list("telepad", "telesci_console")
	research_costs = list(TECHWEB_POINT_TYPE_GENERIC = 5000)
	export_price = 5000 

Working with:

/datum/design/board/telepad
	name = "Machine Design (Telepad Board)"
	desc = "The circuit board for a telescience telepad."
	id = "telepad"
	build_path = /obj/item/circuitboard/machine/telesci_pad
	category = list ("Teleportation Machinery")
	departmental_flags = DEPARTMENTAL_FLAG_ENGINEERING | DEPARTMENTAL_FLAG_SCIENCE
/datum/design/board/telesci_console
	name = "Computer Design (Telepad Control Console Board)"
	desc = "Allows for the construction of circuit boards used to build a telescience console."
	id = "telesci_console"
	build_path = /obj/item/circuitboard/computer/telesci_console
	category = list("Teleportation Machinery")
	departmental_flags = DEPARTMENTAL_FLAG_ENGINEERING | DEPARTMENTAL_FLAG_SCIENCE 

Any idea why these two wouldn't synergize?

**Comment by k-k-karma** [comment]
https://github.com/HippieStation/HippieStation/blob/master/hippiestation/code/modules/research/designs/machine_designs.dm is not included in hippiestation.dme.

**Comment by yoyobatty** [comment]
![untitled](https://user-images.githubusercontent.com/32651551/49454165-99b7d080-f7b2-11e8-88b7-f1f9848c57c0.png)

uh

**Comment by k-k-karma** [comment]
it's invalid because it can't find it
